### PR TITLE
feat(serve): allow setting ssl certificate in angular-cli.json

### PR DESCRIPTION
**Pull request by itslenny**
Currently users must use the --ssl, -ssl-cert, -ssl-key flags to run the
server using an ssl certificate. This update allows users to set
those options in default.serve so they can just run `ng serve` without any
flags.

### CODE REVIEW

**Comment by filipesilva** [comment]
I should mention that there is some time pressure to get this in due to RC0. I'm not sure we can add it afterwards since it does change the config api.

**Comment by filipesilva** [comment]
@itslenny I added my approval but it's contingent on CI passing, per usual.

**Comment by itslenny** [comment]
@filipesilva I got a failure on Travis that doesn't seem to be related to my change. Is this a known flaky test? It only failed in one of the environments.

```
[37m  [34mRunning `ng "e2e" "--watch" "--live-reload"` [silent, matching(/Spec started/)]...[37m[39m
[37m  [34mCWD: /tmp/angular-cli-e2e-117122-3895-lldysh.vkfp5sif6r/test-project[37m[39m
[37mtravis_fold:end:tests.misc.live-reload[39m
[37m[32mLast step took [37m[1m[34m24.38[37m[22m[32ms...[37m[39m

[31mError: Expected API to have been called 2 times but it was called 1 times.[39m
[37m
[39m
[31m[31mTest "tests/misc/live-reload" failed...[31m[39m
[31m[31mExpected API to have been called 2 times but it was called 1 times.[31m[39m
[31m[31mError: Expected API to have been called 2 times but it was called 1 times.
    at Promise.resolve.then.then.then.then.then.then.then._ (/home/travis/build/angular/angular-cli/tests/e2e/tests/misc/live-reload.ts:62:19)[31m[39m

```

**Comment by filipesilva** [comment]
Yes that test is flaky sometimes. I have ran into it today as well. I'll restart that job.

**Comment by filipesilva** [comment]
@itslenny thanks for your work getting this in!

**Pull request merged**
