### PR TITLE
fix(@angular/cli): not use buildOptimizer for JIT in prod

### LINKED ISSUE #8345: ng build --no-aot --prod does not work in angular-cli 1.5
### Problem.

Аfter the upgrade to angular-cli 1.5 does not work JIT-mode.
https://github.com/splincode/angular5-demo

AOT: 

```bash
ng build --aot --prod
cd dist/
http-server
# open in browser http://127.0.0.1:8081
```
It's work

JIT: 

```bash
ng build --no-aot --prod
cd dist/
http-server
# open in browser http://127.0.0.1:8081
```

```text
main.c90f048daaa26da75376.bundle.js:1 Uncaught Error: Unexpected value 't' imported by the module 't'. Please add a @NgModule annotation.
    at p (main.c90f048daaa26da75376.bundle.js:1)
    at main.c90f048daaa26da75376.bundle.js:1
    at Array.forEach (<anonymous>)
    at t.getNgModuleMetadata (main.c90f048daaa26da75376.bundle.js:1)
    at t._loadModules (main.c90f048daaa26da75376.bundle.js:1)
    at t._compileModuleAndComponents (main.c90f048daaa26da75376.bundle.js:1)
    at t.compileModuleAsync (main.c90f048daaa26da75376.bundle.js:1)
    at t.compileModuleAsync (main.c90f048daaa26da75376.bundle.js:1)
    at t.LMZF.t.bootstrapModule (main.c90f048daaa26da75376.bundle.js:1)
    at Object.cDNt (main.c90f048daaa26da75376.bundle.js:1)
```

### Versions.
```text
Angular CLI: 1.5.0
Node: 9.0.0
OS: win32 x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.0
typescript: 2.4.2
webpack: 3.8.1
```

What am I doing wrong?

### PR DESCRIPTION
**Pull request by trotyl**
fixes #8345

### CODE REVIEW

**Comment by hansl** [comment]
Is this still work in progress?

**Comment by hansl** [comment]
If you fix the lint issue, we can merge this.

**Comment by trotyl** [comment]
@hansl It’s too late yesterday, just made a placeholder, will work on it soon.

**Comment by trotyl** [comment]
@hansl Do you want me to add some tests against it? Not sure if this one is urgent.
If tests not required, should be ready to merge now.

**Comment by clydin** [comment]
Is decorator removal the only problematic pass within the build optimizer?  Would it be useful to add an option to the build optimizer loader to disable the pass?

**Comment by trotyl** [comment]
@clydin Without AOT there can be no tree-shaking or other kinds of dead-code elimination, all types would be referenced in metadata, the only optimization remains is `tslib` import.

**Comment by clydin** [comment]
The build optimizer passes facilitate dead code removal via UglifyJS for a variety of TypeScript output code structures.  There is most definitely a benefit even without AOT enabled.

**Comment by trotyl** [comment]
> The build optimizer passes facilitate dead code removal via UglifyJS for a variety of TypeScript output code structures.

The code-wrapping will only help when the identifier itself is removable, so it's only true for non-Angular related TypeScript libraries, but for all Angular libraries there can be little help as nothing can be removed.

**Comment by clydin** [comment]
Which would demonstrate a benefit to leaving it in place.  A significantly reduced benefit currently, but a benefit nonetheless.

**Comment by clydin** [comment]
Also of note is the following result of a simple application in JIT mode with decorator removal disabled:
```
0.bundle.js: 814 -> 19762 bytes (2327.76%), 474 -> 5803 bytes gzipped (1124.26%)
1.bundle.js: 20367 -> 499 bytes (-97.55%), 6057 -> 314 bytes gzipped (-94.82%)
main.bundle.js: 663919 -> 614389 bytes (-7.46%), 161742 -> 150118 bytes gzipped (-7.19%)
polyfills.bundle.js: 55243 -> 55243 bytes (0%), 17953 -> 17953 bytes gzipped (0%)
Total: 740343 -> 689893 bytes (-6.81%), 186226 -> 174188 bytes gzipped (-6.46%)
```
And an AIO test application with the same setup:
```
0.bundle.js: 14879 -> 14879 bytes (0%), 6633 -> 6633 bytes gzipped (0%)
main.bundle.js: 1230957 -> 1047748 bytes (-14.88%), 278220 -> 242911 bytes gzipped (-12.69%)
polyfills.bundle.js: 55243 -> 55243 bytes (0%), 17953 -> 17953 bytes gzipped (0%)
Total: 1301079 -> 1117870 bytes (-14.08%), 302806 -> 267497 bytes gzipped (-11.66%)
```

**Comment by trotyl** [comment]
Thanks for the data for aio, after inspecting the stats.json, the reason why `getPrefixClassesTransformer` can save most size leads to the generated `NgFactory` which contributes to the most unused codes, haven't consider that.

**Comment by trotyl** [comment]
You're right, indeed what `getPrefixClassesTransformer` saves is a little higher than `getScrubFileTransformer`.

**Pull request merged**
