### PR TITLE
Merge Webpack Feature branch into Master

### LINKED ISSUE #1356: Webpack build system upgrade tracker
Remaining action items:
- [x] environment config https://github.com/angular/angular-cli/pull/1364
- [x] path mapping https://github.com/angular/angular-cli/pull/1359
- [x] sass/less/stylus (tests) https://github.com/angular/angular-cli/pull/1363
- [x] ng test errors https://github.com/angular/angular-cli/pull/1359
- [x] remove `require` from test shim https://github.com/angular/angular-cli/pull/1359
- [x] remove SystemJS dependency https://github.com/angular/angular-cli/pull/1376
- [x] ~~figure out lazy loading~~
- [x] remove vendor.ts https://github.com/angular/angular-cli/pull/1383
- [x] remove material2 specific options https://github.com/angular/angular-cli/pull/1385
- [x] `--source-dir` support https://github.com/angular/angular-cli/pull/1378
- [x] clean up broccoli remnants https://github.com/angular/angular-cli/pull/1386
- [x] remove windows elevation check https://github.com/angular/angular-cli/pull/1384
- [x] fix prod builds https://github.com/angular/angular-cli/pull/1395
- [x] add `ng e2e` test using prod builds https://github.com/angular/angular-cli/pull/1394
- [x] overall cleanup https://github.com/angular/angular-cli/pull/1388
- [x] disable HMR https://github.com/angular/angular-cli/pull/1402
- [x] review documentation https://github.com/angular/angular-cli/pull/1407
- [x] support arbitrary environments in runtime config https://github.com/angular/angular-cli/pull/1404
- [x] squiggly lines on editor with decorator errors https://github.com/angular/angular-cli/pull/1420
- [x] fix `libs` option in `tsconfig.json` https://github.com/angular/angular-cli/pull/1425
- [x] remove `module.id` https://github.com/angular/angular-cli/pull/1426
- [x] use karma config and remove reporters https://github.com/angular/angular-cli/pull/1437
- [x] re-add outDir to an ignored folder https://github.com/angular/angular-cli/pull/1428
- [x] add host options to `ng serve` https://github.com/angular/angular-cli/pull/1442
- [x] add @types support https://github.com/angular/angular-cli/pull/1449
- [x] sourcemaps in unit tests don't work https://github.com/angular/angular-cli/pull/1447

Things to investigate:
- [ ] using fonts https://github.com/angular/angular-cli/issues/1356#issuecomment-235020027
- [ ] problems building ngrx/angularfire2 https://github.com/angular/angular-cli/issues/1356#issuecomment-234930265

### PR DESCRIPTION
**Pull request by hansl**
This is the official WebPack support feature being added to the Angular CLI.

Because there is no changes between `beta.10` and `beta.11`, there is no need for a release. A `webpack.1` release will be done shortly after this is merged.

Fixes #1356.

### CODE REVIEW

**Comment by filipesilva** [comment]
@googlebot I signed it.

**Comment by TheLarkInn** [comment]
Hey Google CLI bot, I have signed it

**Comment by nfantone** [comment]
Hey, awesome! (Some) Faith in Javascript-writing humans have been restored!

Congratulations on this decision.

**Comment by scottwio** [comment]
Happy days, great work guys

**Comment by nagchanda** [comment]
@filipesilva 

I am currently on beta 5 and having an issue when doing ng serve -prod 
ng build -prod: Error: ENOTEMPTY: directory not empty, rmdir dist/vendor/rxjs/  i.e. mentioned in 
https://github.com/angular/angular-cli/issues/1409. 

I see it is closed now with the release of new version 'webpack'. 

But as the new webpack is not released yet for upgrading my project,( mentioned in https://github.com/angular/angular-cli/pull/1456) 
can you please suggest if there is any way to resolve the issue.

**Comment by filipesilva** [comment]
@nagchanda there are a couple solutions suggested in #1409, but there's the very real possibility that your bug might be fixed in a newer beta as well since beta.5 is rather old.

**Comment by nagchanda** [comment]
@filipesilva 

thank you for the quick reply. I have tried the options listed but wasnt successful. I will try to upgrade to latest version i.e. beta 10 and see if the issue is resolved.

**Comment by nagchanda** [comment]
@filipesilva - I have upgraded to beta 10. I had the same issue again. So now manually deleted the dist folder and was able to do ng build --prod successfully. Additionally, I have also tested adding a new environment file for qa and did ng build --environment=qa, it worked :) . I was happy seeing that. 

Thank you so much again.

**Comment by filipesilva** [comment]
Glad to hear it worked :D

**Comment by RodrigoMattosoSilveira** [comment]
Auto Reload when CSS files change still does not work!

**Comment by LukeStonehm** [comment]
Indeed, LiveReload for Sass changes not coming through :(

**Comment by zakdances** [comment]
Using `1.0.0-beta.11-webpack.2`, how do I get a command such as `ng g component home` to generate a `home.component.pug` instead of `home.component.html`?

**Comment by filipesilva** [comment]
@zakdances there is no jade/pug support in yet.

**Comment by santoshsas** [comment]
@filipesilva can you give steps for VsCode chrome extension for debugging with angular-cli@webpack

**Comment by hansl** [comment]
@santoshsas if you have questions this PR is not the right place. Gitter would probably be better.

**Pull request merged**
