### PR TITLE
CI build-bazel-e2e fix

### PR DESCRIPTION
**Pull request by alan-agius4**
See each commit.

### CODE REVIEW

**Review by devversion — APPROVED** [review]

**Comment by devversion** [comment]
One thing I noticed: Usually Bazel has problems determining the memory/CPU ceilings and we explicitly set them in the .circleci/bazelrc but here the CI bazelrc config is not wired up in all Bazel jobs (as it seems): https://github.com/angular/angular-cli/blob/main/.circleci/dynamic_config.yml#L298

**Comment by alan-agius4** [comment]
Good point, although the values there are for an xlarge class
https://github.com/angular/angular-cli/blob/308e3a017f876bfc727e68803bfbce11e9d3396e/.circleci/bazel.rc#L10-L15

**Comment by devversion** [comment]
Yes, but Bazel might incorrectly compute the ceiling for the classes currently used (e.g. medium)

**Comment by alan-agius4** [comment]
Yes you right.

**Pull request merged**
