### PR TITLE
fix(@angular/cli): use inline sourcemaps in test

### LINKED ISSUE #6640: Angular cli 1.1.1 doesn't allow in-browser debugging
### Bug Report
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.1.1
node: 8.0.0
os: darwin x64

### Repro steps.

ng new debugtest
cd debugtest
ng test
in the browser -> Debug -> developer tools / sources -> cmd+p ->
cannot find app.component.ts!

### LINKED ISSUE #6737: Test source maps are not working
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.1.2
node: 6.9.1
os: win32 x64

### Repro steps.
1. ng new source-maps
2. Make a test failing (e.g. app.component.spec.ts expect a wrong title)
3. npm test
 

### The log given by the failure.
```
Chrome 58.0.3029 (Windows 10 0.0.0) AppComponent should have as title 'app' FAILED
        Expected 'app' to equal 'app2'.
            at Object.<anonymous> (http://localhost:9876/_karma_webpack_/main.bundle.js:89:27)
            at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:2800:26)
            at AsyncTestZoneSpec.webpackJsonp.../../../../zone.js/dist/async-test.js.AsyncTestZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/vendor.bundle.js:2643:39)
            at ProxyZoneSpec.webpackJsonp.../../../../zone.js/dist/proxy.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/vendor.bundle.js:3406:39)
Chrome 58.0.3029 (Windows 10 0.0.0): Executed 2 of 3 (1 FAILED) (0 secs / 0.154 secs)
Chrome 58.0.3029 (Windows 10 0.0.0) AppComponent should have as title 'app' FAILED
        Expected 'app' to equal 'app2'.
            at Object.<anonymous> (http://localhost:9876/_karma_webpack_/main.bundle.js:89:27)
            at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:2800:26)
            at AsyncTestZoneSpec.webpackJsonp.../../../../zone.js/dist/async-test.js.AsyncTestZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/vendor.bundle.js:2643:39)
            at ProxyZoneSpec.webpackJsonp.../../../../zone.js/dist/proxy.js.ProxyZoneSpec.onInvoke (http://localhost:987Chrome 58.0.3029 (Windows 10 0.0.0): Executed 3 of 3 (1 FAILED) (0.204 secs / 0.191 secs)
```

### Desired functionality.
The output should show the line number of the typescript file instead of the bundle.

### LINKED ISSUE #6785: ng test - no source files in Chrome
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.1.3
node: 6.9.4
os: win32 x64
@angular/animations: 4.2.4
@angular/common: 4.2.4
@angular/compiler: 4.2.4
@angular/core: 4.2.4
@angular/forms: 4.2.4
@angular/http: 4.2.4
@angular/platform-browser: 4.2.4
@angular/platform-browser-dynamic: 4.2.4
@angular/router: 4.2.4
@angular/cli: 1.1.3
@angular/compiler-cli: 4.2.4
@angular/language-service: 4.2.4

### Repro steps.
run `ng test`

### Desired functionality.
step through test code in chrome tools using the Karma DEBUG button

### Mention any other details that might be useful.
There are no longer any source files, previously we had a webpack folder with all the source files.

This no longer exists.

### PR DESCRIPTION
**Pull request by filipesilva**
Fix #6737 
Fix #6785 
Fix #6640

### CODE REVIEW

**Comment by FalloutPL** [comment]
can we expect to release this before 1.3.0 ? i.e. 1.2.1 ?

**Comment by filipesilva** [comment]
@FalloutPL it should be out in 1.2.x, since it's a fix.

**Comment by AlexLnz** [comment]
I updated to 1.2.1 and still can't debug karma tests. I get no source files.

**Comment by filipesilva** [comment]
@AlexLnz @FalloutPL it seems this wasn't released as part of 1.2.1 after all, but it is in `1.3.0-beta.1`.

**Comment by AlexLnz** [comment]
Ok, thanks for clarifying.

**Pull request merged**
