### PR TITLE
added section on difference between building with or without prod flag

### PR DESCRIPTION
**Pull request by stiasta**
My team spent a long time figuring out why our code broke when building our project with the `--prod` flag compared to when we did not.

Since we don't know much about the build process in angular-cli we did not know what the real difference was when using the flag.

We finally found out that `constructor.name` did not work when building prod.

Therefore this pull request contains a warning with example and a "difference" section.
I know that tree shaking is done and uglifying. Is there more that could be added?

### CODE REVIEW

**Comment by stiasta** [comment]
I used a different email when submiting the commits. I did sign the CLA using my gmail account. how can i add the rest of the emails?

**Comment by stiasta** [comment]
I have added the email i used with the commit to my gmail as an alternate account. hopefully it will accept the cla now.

**Comment by stiasta** [comment]
perhaps a lint warning should be added aswell ?

**Comment by vfedoriv** [comment]
BTW, maybe need add something like this:

> -- aot flag is enabled by default with a production build

**Comment by filipesilva** [comment]
I agree that these differences should be documented, and maybe a new flag to opt-in minification.

We can't add this flag now however, and the documentation shouldn't focus so much on the effects of minification however.

I'll track this in https://github.com/angular/angular-cli/issues/5315.

**Pull request closed without merging**
