### PR TITLE
feat: swap out raw-loader for html-loader for html files

### LINKED ISSUE #2231: Webpack skips images referenced in html templates (img src)
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
```
OS X El Capitan
```

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
```
angular-cli: 1.0.0-beta.14
node: 6.3.0
os: darwin x64
```
3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

Create new project with `ng new test-project`
Add images folder to src (and you can add to src/app, doesn't matter).
Reference image in app.component.html
`test`
Build project with `ng build -prod`

4. The log given by the failure. Normally this include a stack trace and some
   more information.
Image is not being bundled into dist folder and is not loading producing 404 error.

5. Mention any other details that might be useful.
Problem is reproduced with `ng build -prod` and is not reproduced with `ng serve -prod`.
github repo showing problem: https://github.com/alexsorokoletov/angular-cli-image-loader-problem

I am not sure if this is a problem of webpack html loader plugin or issue related to it's configuration or I am doing something wrong.
For a workaround I am using `assets` folder and put all images there. 
However, it is strange to me keeping some images in assets and some (that are mentioned in the css files) inside the webpack bundle
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

### PR DESCRIPTION
**Pull request by TheLarkInn**
#* angular html components as well as index.html now have the benefits of [html-loader](https://github.com/webpack/html-loader)
* Fixes #2231

### CODE REVIEW

**Comment by hansl** [comment]
LGTM. I'll wait for tests to pass.

**Comment by TheLarkInn** [comment]
Looks like tests failed on basehref, I'll give this another whirl

**Comment by alexsorokoletov** [comment]
Almost there, would be great to have this fixed in the coming update! 
Thank you, @TheLarkInn

**Comment by filipesilva** [comment]
TBH if you wanna replace our custom base href plugin by base functionality of HTMLPlugin, I can't say I mind. Might be the sort of stuff that would happen in a different commit/pr.

**Comment by rolandoldengarm** [comment]
Will this PR be merged soon? :)

**Comment by hansl** [comment]
@TheLarkInn Have you tried running `ng build --base-href /url` in a new project and look if the base is there? To me it seems like this breakage is legit.

**Comment by TheLarkInn** [comment]
@hansl I noticed that in your PR you had html-loader (the AOT one), so I hadn't revisited it.

**Comment by TheLarkInn** [comment]
I'll take a look at this next and see what errors are being caused.

**Comment by filipesilva** [comment]
Closed since we removed this in https://github.com/angular/angular-cli/pull/2537

**Pull request closed without merging**
