### PR TITLE
fix(@angular/cli): allow TS 2.5 for Angular >= 5.1

### PR DESCRIPTION
**Pull request by cyrilletuzi**
@filipesilva @Brocco @hansl

### CODE REVIEW

**Comment by cexbrayat** [comment]
Fixes #8768

**Comment by filipesilva** [comment]
LGTM, was just putting up a PR for this right now. Unsure what's happening with CI, looking into it.

**Comment by cyrilletuzi** [comment]
The PR was done before #8765 was fixed, maybe the source of CI error ?

**Comment by Brocco** [comment]
@cyrilletuzi Can you please rebase this PR? There have been a few fixes since you created your PR. Thanks!

**Comment by cyrilletuzi** [comment]
Sorry, I had to redo this in #8792 

Don't even know how the last operation has been possible, so I've started from start to clean my git history.

**Comment by JinsPeter** [comment]
When can npm install @angular/compiler-cli@5.1.0 reflect this?

**Pull request closed without merging**
