### PR TITLE
Add @angular-devkit/build-karma

### PR DESCRIPTION
**Pull request by filipesilva**

### CODE REVIEW

**Comment by filipesilva** [comment]
Supersedes https://github.com/angular/devkit/pull/965

**Comment by filipesilva** [comment]
Blocking for now.

**Comment by alexeagle** [comment]
@filipesilva what's it blocked on?

**Comment by filipesilva** [comment]
@alexeagle last I spoke with @hansl about this package he preferred to not publish more architect builders until the API stabilized.

**Comment by hansl** [comment]
Closing this as it's been moved.

**Pull request closed without merging**
