### PR TITLE
build: update dependencies of 11.0.x

### PR DESCRIPTION
**Pull request by matheo**
This PR contains the following updates:

latest `@babel` packages
latest `@angular` 11.0.x packages and hashes

Last night I updated my websites and `@babel/templates` was fixed to an old version
so this synces the 11.0.x branch with `@angular/*` 11.0.x too,
as there's a little void updating these when `master` gets the `next` version.

### CODE REVIEW

**Comment by matheo** [comment]
@filipesilva can we have a patch release with updated deps?

**Comment by alan-agius4** [comment]
Hi @matheo, thanks for this.

The latest Babel packages are consumed in version 11.1. Typically dependencies updates only happen in minors because of the risk of unexpected breakages.

Is there any reason why we need to update `@babel/` packages in a patch version? Does it fix an outstanding issue?

**Comment by matheo** [comment]
@alan-agius4 nope, it just syncs the package-lock versions in the Angular Apps, no known issues tho

**Comment by alan-agius4** [comment]
In such case it’s best not to update Babel packages in a patch version.

**Comment by matheo** [comment]
ok, closing this

**Pull request closed without merging**
