### PR TITLE
feat: Use JSON file to create a NEW project and to GENERATE components, routes, directives, etc.

### PR DESCRIPTION
**Pull request by kenhansen01**
I created a new command in the ng2 commands folder. It looks for a file named ng-project.json, then sychronously goes through and creates the project and as many routes, components, directives, etc as are set up in the json file. 

These are executed through child_process.execSync,

To use the command. Save a JSON file and run:
```
ng newfromjson
```
There is also a model for the json file (a Typescript interface) that shows all the options. It should be set up like this (options with '?' are optional):
```lang-javascript
{
  package: {
    name: string,
    blueprint?: string,
    dryRun?: boolean,
    verbose?: boolean,
    skipNpm?: boolean,
    skipGit?: boolean,
    directory?: string
  },
  routes?: {
    name: string,
    flat?: boolean,
    default?: boolean,
    lazy?: boolean,
    skipRouterGeneration?: boolean,
    route?: string
  }[],
  components?: {
    name: string,
    flat?: boolean,
    route?: string
  }[],
  pipes?: {
    name: string,
    flat?: boolean
  }[],
  services?: {
    name: string,
    flat?: boolean
  }[],
  directives?: {
    name: string,
    flat?: boolean
  }[],
  classes?: {
    name: string,
    flat?: boolean
  }[],
  enums?: {
    name: string,
    flat?: boolean
  }[]
}
```

I am working on a way to skip existing items and only add new ones if the json is changed.

### CODE REVIEW

**Comment by filipesilva** [comment]
Heya, we've made some massive changes in the build system in #1455, you might want to rebase to make sure your PR still works!

**Comment by esinek** [comment]
@kenhansen01 - any plans to rebase and continue this?

**Comment by Brocco** [comment]
@kenhansen01 I appreciate your efforts with the work you have put into this, but I feel like this is outside the current scope of the CLI. The current approach for this would be to create an external script to automate the CLI.

The idea itself is sound and will be considered in the future.

Thanks again for your efforts.

**Comment by kenhansen01** [comment]
Fair enough. I was having trouble finding the time to rework and rebase with all of the changes since I started work on this was started.

**Pull request closed without merging**
