### PR TITLE
fix(@angular/cli): fix webdriver deep import on yarn

### LINKED ISSUE #4596: [beta.31] ng e2e does not work anymore
### OS?
Archlinux

```
@angular/cli: 1.0.0-beta.31
node: 7.5.0
os: linux x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/flex-layout: 2.0.0-beta.4
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.6
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.6
```

### Repro steps.

Created with ng init and always updated

Running `ng e2e --progress=false -e=prod-e2e` gives:
```

➜  frontend git:(master) ✗ ng e2e --progress=false -e=prod-e2e                               
** NG Live Development Server is running on http://localhost:4200. **
(node:24803) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Hash: af5145659c048450397c
Time: 16784ms
chunk    {0} 0.chunk.js, 0.bundle.map 190 kB {1} {2} {3} {4} {5} {6} {7} {8} {10} [rendered]
chunk    {1} 1.chunk.js, 1.bundle.map 157 kB {0} {2} {3} {4} {5} {6} {7} {8} {10} [rendered]
chunk    {2} 2.chunk.js, 2.bundle.map 111 kB {0} {1} {3} {4} {5} {6} {7} {8} {10} [rendered]
chunk    {3} 3.chunk.js, 3.bundle.map 18.3 kB {0} {1} {2} {4} {5} {6} {7} {8} {10} [rendered]
chunk    {4} 4.chunk.js, 4.bundle.map 19.8 kB {0} {1} {2} {3} {5} {6} {7} {8} {10} [rendered]
chunk    {5} 5.chunk.js, 5.bundle.map 18.9 kB {0} {1} {2} {3} {4} {6} {7} {8} {10} [rendered]
chunk    {6} 6.chunk.js, 6.bundle.map 17 kB {0} {1} {2} {3} {4} {5} {7} {8} {10} [rendered]
chunk    {7} 7.chunk.js, 7.bundle.map 26.6 kB {0} {1} {2} {3} {4} {5} {6} {8} {10} [rendered]
chunk    {8} 8.chunk.js, 8.bundle.map 11.5 kB {0} {1} {2} {3} {4} {5} {6} {7} {10} [rendered]
chunk    {9} polyfills.bundle.js, polyfills.bundle.map (polyfills) 222 kB {14} [initial] [rendered]
chunk   {10} main.bundle.js, main.bundle.map (main) 202 kB {13} [initial] [rendered]
chunk   {11} styles.bundle.js, styles.bundle.map (styles) 203 kB {14} [initial] [rendered]
chunk   {12} scripts.bundle.js, scripts.bundle.map (scripts) 15.3 kB {14} [initial] [rendered]
chunk   {13} vendor.bundle.js, vendor.bundle.map (vendor) 4.14 MB [initial] [rendered]
chunk   {14} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]

WARNING in ./src/app/features/cockpit/workspaces/petals-content/petals-component-view/petals-component-overview/petals-component-overview.component.ts
35:55-68 "export 'IComponentRow' was not found in '../../../state/components/component.interface'

WARNING in ./src/app/features/cockpit/workspaces/petals-content/petals-component-view/petals-component-overview/petals-component-overview.component.ts
35:88-101 "export 'IComponentRow' was not found in '../../../state/components/component.interface'

WARNING in ./src/app/features/cockpit/workspaces/petals-content/petals-service-unit-view/petals-service-unit-overview/petals-service-unit-overview.component.ts
35:55-70 "export 'IServiceUnitRow' was not found in '../../../state/service-units/service-unit.interface'

WARNING in ./src/app/features/cockpit/workspaces/petals-content/petals-service-unit-view/petals-service-unit-overview/petals-service-unit-overview.component.ts
35:90-105 "export 'IServiceUnitRow' was not found in '../../../state/service-units/service-unit.interface'
webpack: Compiled with warnings.
(node:24803) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module 'protractor/node_modules/webdriver-manager/built/lib/cmds/update' from '/home/vnoel/Linagora/Petals/dev/git/petals-cockpit-new/frontend'
(node:24803) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

And stay blocked.

### PR DESCRIPTION
**Pull request by filipesilva**
Followup from https://github.com/angular/angular-cli/pull/4597

Following @Meligy suggestion in https://github.com/angular/angular-cli/pull/4597#issuecomment-282561038

Fix #4596

### CODE REVIEW

**Comment by Meligy** [comment]
Would a simple `fs.existsSync` (or similar) be faster than try / catch here?

**Comment by filipesilva** [comment]
It would. But I kinda don't trust the require logic here very much... 

The webdriver package behaves oddly in requires. Doing just `require('webdriver-manager/built/lib/cmds/update')` should really just work in all scenario since the package exists. But it doesn't work in npm.

So I kinda prefer to have the try-catch around them.

**Comment by rolandjitsu** [comment]
Are you sure this works? I just upgraded and installed packages via `yarn install` and I still get:
```text
 angular-lab@0.0.0 e2e /Users/rolandjitsu/Projects/angular-lab
> ng e2e --no-watch ---no-live-reload

** NG Live Development Server is running on http://localhost:49152 **
(node:90082) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.     
Hash: 700e7624bdecc6694c7c
Time: 14534ms
chunk    {0} 0.chunk.js, 0.chunk.js.map 43 kB {1} [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 28.1 kB {4} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 39 kB {5} [initial] [rendered]
chunk    {3} scripts.bundle.js, scripts.bundle.js.map (scripts) 77 kB {5} [initial] [rendered]
chunk    {4} vendor.bundle.js, vendor.bundle.js.map (vendor) 4.12 MB [initial] [rendered]
chunk    {5} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]
webpack: Compiled successfully.
Cannot find module 'protractor/node_modules/webdriver-manager/built/lib/cmds/update' from '/Users/rolandjitsu/Projects/angular-lab'
Error: Cannot find module 'protractor/node_modules/webdriver-manager/built/lib/cmds/update' from '/Users/rolandjitsu/Projects/angular-lab'
    at Function.module.exports [as sync] (/Users/rolandjitsu/Projects/angular-lab/node_modules/resolve/lib/sync.js:37:15)
    at Object.requireProjectModule (/Users/rolandjitsu/Projects/angular-lab/node_modules/@angular/cli/utilities/require-project-module.js:6:28)
    at /Users/rolandjitsu/Projects/angular-lab/node_modules/@angular/cli/tasks/e2e.js:35:66
    at Class.run (/Users/rolandjitsu/Projects/angular-lab/node_modules/@angular/cli/tasks/e2e.js:16:16)
    at Compiler.rebuildCb (/Users/rolandjitsu/Projects/angular-lab/node_modules/@angular/cli/commands/e2e.js:99:48)
    at Compiler.applyPlugins (/Users/rolandjitsu/Projects/angular-lab/node_modules/tapable/lib/Tapable.js:61:14)
    at Watching._done (/Users/rolandjitsu/Projects/angular-lab/node_modules/webpack/lib/Compiler.js:91:17)
    at /Users/rolandjitsu/Projects/angular-lab/node_modules/webpack/lib/Compiler.js:74:18
    at Compiler.emitRecords (/Users/rolandjitsu/Projects/angular-lab/node_modules/webpack/lib/Compiler.js:351:37)
    at /Users/rolandjitsu/Projects/angular-lab/node_modules/webpack/lib/Compiler.js:57:19
    at /Users/rolandjitsu/Projects/angular-lab/node_modules/webpack/lib/Compiler.js:344:11
    at next (/Users/rolandjitsu/Projects/angular-lab/node_modules/tapable/lib/Tapable.js:154:11)
    at Compiler.compiler.plugin (/Users/rolandjitsu/Projects/angular-lab/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at next (/Users/rolandjitsu/Projects/angular-lab/node_modules/tapable/lib/Tapable.js:156:14)
    at Compiler.compiler.plugin (/Users/rolandjitsu/Projects/angular-lab/node_modules/@ngtools/webpack/src/plugin.js:236:13)
    at Compiler.applyPluginsAsyncSeries1 (/Users/rolandjitsu/Projects/angular-lab/node_modules/tapable/lib/Tapable.js:158:13)
    at Compiler.afterEmit (/Users/rolandjitsu/Projects/angular-lab/node_modules/webpack/lib/Compiler.js:341:8)
    at Compiler.<anonymous> (/Users/rolandjitsu/Projects/angular-lab/node_modules/webpack/lib/Compiler.js:336:14)
    at /Users/rolandjitsu/Projects/angular-lab/node_modules/webpack/node_modules/async/dist/async.js:359:16
    at iteratorCallback (/Users/rolandjitsu/Projects/angular-lab/node_modules/webpack/node_modules/async/dist/async.js:935:13)
    at /Users/rolandjitsu/Projects/angular-lab/node_modules/webpack/node_modules/async/dist/async.js:843:16
    at MemoryFileSystem.writeFile (/Users/rolandjitsu/Projects/angular-lab/node_modules/memory-fs/lib/MemoryFileSystem.js:328:9)
    at Compiler.writeOut (/Users/rolandjitsu/Projects/angular-lab/node_modules/webpack/lib/Compiler.js:330:27)
    at Compiler.<anonymous> (/Users/rolandjitsu/Projects/angular-lab/node_modules/webpack/lib/Compiler.js:312:20)
    at /Users/rolandjitsu/Projects/angular-lab/node_modules/webpack/node_modules/async/dist/async.js:3025:16
    at eachOfArrayLike (/Users/rolandjitsu/Projects/angular-lab/node_modules/webpack/node_modules/async/dist/async.js:940:9)
    at eachOf (/Users/rolandjitsu/Projects/angular-lab/node_modules/webpack/node_modules/async/dist/async.js:990:5)
    at Object.eachLimit (/Users/rolandjitsu/Projects/angular-lab/node_modules/webpack/node_modules/async/dist/async.js:3089:3)
    at Compiler.emitFiles (/Users/rolandjitsu/Projects/angular-lab/node_modules/webpack/lib/Compiler.js:301:20)
    at Immediate.<anonymous> (/Users/rolandjitsu/Projects/angular-lab/node_modules/memory-fs/lib/MemoryFileSystem.js:288:4)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

**Comment by filipesilva** [comment]
@rolandjitsu this fix isn't published yet. It will be in the next released version.

**Comment by rolandjitsu** [comment]
Ahhh ... ok. I thought it was published with the RC0 release. I just saw the timestamp on the merge 😄  Looking forward to the fix.

**Pull request merged**
