### PR TITLE
chore: update broccoli

### PR DESCRIPTION
**Pull request by cebor**
This removes a spurious global dependency installed by `multidep`.

https://github.com/broccolijs/broccoli/commit/d00a07448624bd41c4a4065197d71dad73b68609

Fixes: https://github.com/angular/angular-cli/issues/536

### CODE REVIEW

**Comment by jkuri** [comment]
@cebor thanks for that update! It removes the annoying `multidep`. 

Can you please amend your commit message to something like `chore: bump broccoli version`?

**Comment by cebor** [comment]
@jkuri done

**Comment by jkuri** [comment]
@cebor thanks! Let the tests pass and we'll get this one merged.

**Comment by filipesilva** [comment]
*Very* welcome. Cheers!

**Pull request merged**
