### PR TITLE
Update compiler_host.ts (Fix for #3847)

### PR DESCRIPTION
**Pull request by jdavidls**
The problem: duplication of symlinked source files (npm linked sources) in CompilerHost's stats.
The solution: resolve these paths before of all

It's my gift of kings :)

Fix https://github.com/angular/angular-cli/issues/3847

### CODE REVIEW

**Comment by timofeysie** [comment]
What is the status of this PR?  I am getting this error when trying to use an npm link lib in my Ionic 2 project:
```
undefined is not a constructor (evaluating 'new __WEBPACK_IMPORTED_MODULE_8_shared_lib__
```
Will this PR fix the issue?

**Comment by jdavidls** [comment]
Hi @timofeysie.

This PR fix the building errors described in #3847 (I made a mistake by labeling #3875),
Where npm linked libraries with same dependencies are duplicated, It's solves the «Type 'XXX' is not assignable to type 'XXX» compilation errors, where XXX are the same type declares in the same source file, but resolved by different symlink.

The only thing that does this PR is to resolve all the symlinked source files before to passing them to the compiler. 

The issue you are describing seems to be something different. 

Sorry, i'm a disinterested contributor, i think that I can not help you much.

**Comment by filipesilva** [comment]
@hansl can you review?

**Comment by sterfpaul** [comment]
Any update on this? Is there any way I could help to fix the failing checks?

**Comment by BernhardRode** [comment]
@sterfpaul the whole file got refactored/moved ... i tried to find the place, where this could fit, too... but had no luck....

**Comment by sterfpaul** [comment]
@BernhardRode Seems about the same to me on current master.

**Comment by filipesilva** [comment]
Closing as something similar has already been added.

**Pull request closed without merging**
