### PR TITLE
fix(710): Missing http module dependency

### PR DESCRIPTION
**Pull request by guillaumeleone**
Fixes https://github.com/angular/angular-cli/issues/710.

### CODE REVIEW

**Comment by guillaumeleone** [comment]
I signed it!

**Comment by tapas4java** [comment]
@guillaumeleone There is already a open PR for this change.

**Comment by guillaumeleone** [comment]
@tapas4java Oh right, but the commit log about this PR is not explicit :)

**Comment by guillaumeleone** [comment]
I signed it!

**Comment by hansl** [comment]
I'm going to merge this one, as it's the oldest and it's in alphabetical order. Thanks.

**Comment by hansl** [comment]
Merged with https://github.com/angular/angular-cli/commit/c0aadae49826f11b949a184e2bc15e36ec6d0daf

**Pull request closed without merging**
