### PR TITLE
docs: update test case description

### PR DESCRIPTION
**Pull request by santoshyadav198613**

### CODE REVIEW

**Comment by santoshyadav198613** [comment]
I am not sure about commit message, let me know which scope to use.

**Comment by alan-agius4** [comment]
Thanks for this! Can you change the scope to `test` please?

**Comment by alan-agius4** [comment]
@santoshyadav198613 `@schematics/update` is not a valid message package scope, can you change it to `@schematics/angular` please? Thanks

**Comment by santoshyadav198613** [comment]
> @santoshyadav198613 `@schematics/update` is not a valid message package scope for this change because the changes are in a different package.
> 
> Can you change it to `@schematics/angular` please? Thanks

Done.

**Comment by alan-agius4** [comment]
Thanks

**Pull request merged**
