### PR TITLE
fix(@schematics/angular): remove module test

### LINKED ISSUE #11277: [schematics/angular] No need to generate a module spec
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Repro steps

When generating a module, a spec file is created.
This file has no real interest and was not generated before CLI v6 if I'm not mistaken.
It's possible to skip the generation with the `spec` option,
but as the test is not really useful, the test should never be created and the option removed?

```
module-spec git:master ❯ ng g m shared
CREATE src/app/shared/shared.module.spec.ts (275 bytes)
CREATE src/app/shared/shared.module.ts (190 bytes)
```

### Desired functionality

It should not generate a spec file.

### PR DESCRIPTION
**Pull request by cexbrayat**
The `module` schematic was generating a useless `module.spec.ts` file.
This commit removes such test.

Fixes #11277

### CODE REVIEW

**Comment by clydin** [comment]
Unfortunately, this would be a breaking change and would need to wait for 7.0.

**Comment by cexbrayat** [comment]
Now that we have 7.0 beta, can this get merged?

**Comment by clydin** [comment]
Can you fix the conflict?  The schema type definitions are auto-generated at build time now.

**Comment by cexbrayat** [comment]
@clydin Ha yes sorry! I fixed the conflicts.

**Comment by vikerman** [comment]
We will discuss in the triage meeting to understand what happened here and make sure we are more intentional this time around.

**Comment by vikerman** [comment]
Decided this makes sense.

**Pull request merged**
