### PR TITLE
Eliminate duplication of reporters in karma.conf.js #4658

### PR DESCRIPTION
**Pull request by rkrisztian**
Advantage is more flexible configuration for non-conditional reporters.

### CODE REVIEW

**Comment by rkrisztian** [comment]
I signed it!

**Comment by rkrisztian** [comment]
I signed it!

**Comment by filipesilva** [comment]
It's a smarter way of doing it, but it's much less readable imho.

**Comment by rkrisztian** [comment]
I don't really understand this argument. It may be less readable, but "much" is an overstatement; and not scalable for additions of reporters:

* you would have to add unconditional reporters more than once;
* you would have to duplicate every array for every conditional reporter.

Every project in such situations ends up refactoring that code.

Would you prefer a syntax like this instead?

```
reporters: ['progress', '...']
	.concat(config.angularCli && config.angularCli.codeCoverage ? ['coverage-istanbul'] : []),
	.concat(...),
```

**Comment by filipesilva** [comment]
This is mostly a matter of style and thus subjective. I understand you don't agree and think it would look better another way but... I think it's fine as is and it doesn't make much different at all. So it would take a more objective reason to be worth the change.

Maybe a better change would be to have the code coverage reporter be specified in the `angularCli` option and added automatically. I think that would be a better solution overall. But it's not a very important thing so I don't see me doing it soon.

**Pull request closed without merging**
