### PR TITLE
fix(find-lazy-modules): JSON parse error for loadChildren

### LINKED ISSUE #1891: Angular Cli 1.0.0-beta.11-webpack.8: ng build failed if route 'loadChildren'
https://github.com/angular/angular-cli/blob/master/addon/ng2/models/find-lazy-modules.ts#L38

```
.map((node: ts.PropertyAssignment) => {
        return JSON.parse(node.initializer.getText(source)); // tslint:disable-line
      });
```

JSON.parse failed with ：
```
loadChildren:'app/+workspace/+settings/settings.module#SettingsModule'
```

### PR DESCRIPTION
**Pull request by chalin**
Fixes #1891, #1960.

cc @filipesilva @ericjim - was failing for ng2.io, but this fixes the issue.

### CODE REVIEW

**Comment by ericjim** [comment]
lol, I guess it LGTM.

**Comment by ericjim** [comment]
Nice find

**Comment by filipesilva** [comment]
LGTM but @hansl can you weigh in?

**Comment by hansl** [comment]
This fix is faulty though since it replaces quotes regardless of context. 

I think I know what's going on, might take a look at it tomorrow. Might just need to evaluate the code (or even better don't parse JSON since we shouldn't need to).

**Comment by hansl** [comment]
I already made a function to get the string value of the key of an object, the more I think about that line the clearer the fix is. Typescript gives us the string value of a string literal, I just need to use that. My bad for this horrible code in the first place.

 I was young, and that was folly.

**Comment by filipesilva** [comment]
Closed in favor of https://github.com/angular/angular-cli/pull/1987

**Pull request closed without merging**
