### PR TITLE
Remove typescript dep

### PR DESCRIPTION
**Pull request by filipesilva**

### CODE REVIEW

**Comment by devoto13** [comment]
Should this also close https://github.com/angular/angular-cli/issues/5053? Original report is the same problem. There are lots of discussions on unrelated topics, so maybe it's better to suggest users to open new issues with clear description instead.

**Comment by picosam** [comment]
Hello, is it normal that I'm still getting this error message then:

```
→ npm install
npm WARN @angular/compiler-cli@5.0.2 requires a peer of typescript@>=2.4.2 <2.5 but none is installed. You must install peer dependencies yourself.
npm WARN tsickle@0.24.1 requires a peer of typescript@2.4.2 but none is installed. You must install peer dependencies yourself.
```

Using `@angular/cli@1.5.2` and `@angular/*@5.0.2`...

**Comment by filipesilva** [comment]
@picosam what version of TS are you using?

**Comment by picosam** [comment]
@filipesilva So I now after updating I'm getting this:
`npm WARN @angular/compiler-cli@5.1.0 requires a peer of typescript@>=2.4.2 <2.6 but none is installed. You must install peer dependencies yourself.`

In my `packages.json` file I have this: `"typescript": "^2.6.2"`

**Pull request merged**
