### PR TITLE
chore: `implicityAny` by default and update blueprints

### LINKED ISSUE #107: consider turning on noImplicitAny by default
currently our blueprints don't pass the noImplicitAny check - we should fix that.

- [ ] understand the impact
- [ ] change the [config](https://github.com/angular/angular-cli/blob/d89d717358cbecdd74244189234eb8740f12faa2/addon/ng2/blueprints/ng2/files/src/tsconfig.json#L10)
- [ ] update blueprints that fail the check

Current failures for an empty project:

```
[DiffingTSCompiler]: Typescript found the following errors:
  app/sample-45.spec.ts (7, 71): Parameter 'app' implicitly has an 'any' type.
  app/sample-45.spec.ts (12, 65): Parameter 'app' implicitly has an 'any' type.
  app/sample-45.ts (14, 17): Parameter 'meaning' implicitly has an 'any' type.
```

@rkirov @alexeagle - what's your guidance on this?

### PR DESCRIPTION
**Pull request by cironunes**
Closes #107

### CODE REVIEW

**Comment by filipesilva** [comment]
I think you forgot to change `tsconfig.json` to have `"noImplicitAny": true,`.

Other than that, it looks good.

**Comment by Brocco** [comment]
@filipesilva We don't want to enable `noImplicityAny`, only have the blueprints support it being turned on without causing any issue. If we were to turn it on then it would force anyone using the CLI to write code to comply with that setting, which is something we don't want to do.

**Comment by filipesilva** [comment]
Got it. Then this one looks ready to merge for me.

**Comment by hansl** [comment]
In order to close #107, we need to consider having noImplicitAny for our e2e tests. It seems like you're not enabling it anywhere (might have missed it).

**Comment by cironunes** [comment]
@hansl this is just updating the blueprints, we can address having the config for our e2e tests in a separated PR. BTW, closing this in favor of #150

**Pull request closed without merging**
