### PR TITLE
fix(@angular/cli): update copy-webpack-plugin to 4.1.1

### PR DESCRIPTION
**Pull request by d3viant0ne**
- This release picks up a ReDoS security patch in minimatch: https://nodesecurity.io/advisories/minimatch_regular-expression-denial-of-service

### CODE REVIEW

**Comment by filipesilva** [comment]
LGTM, thanks for updating this 👍

**Comment by d3viant0ne** [comment]
I'll make sure that at an absolute minimum, all the releases in contrib that relate to security get a pull request here as well.

**Comment by filipesilva** [comment]
That's much appreciated, honestly. You can ping me as well and I'll add make one. Is there a place where you list these contrib security releases, twitter maybe?

**Comment by d3viant0ne** [comment]
https://twitter.com/WebpackContrib

**Pull request merged**
