### PR TITLE
fix(@angular/cli): fix routing blueprint

### PR DESCRIPTION
**Pull request by sumitarora**

### CODE REVIEW

**Comment by johnpapa** [comment]
This is the app root routing module. We should do this in the child routing modules. for example when we run `ng g m villains --routing`

**Comment by sumitarora** [comment]
@johnpapa It's already array there. https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/blueprints/module/files/__path__/__name__-routing.module.ts#L4

**Comment by johnpapa** [comment]
The current one is invalid code .... it is an empty path that goes nowhere.

I was just suggesting that it generate something valid. Whatever option that is

**Comment by gioragutt** [comment]
@hansl @johnpapa when the array is empty, what happens with the `router-outlet`? I assume you can't just route to `AppComponent`, as I guess it would either throw an error, or crash the site in a recursive route if that's allowed. Perheps a dummy component can be used as an initial route.

**Comment by filipesilva** [comment]
@hansl can you re-review?

**Comment by hansl** [comment]
Closing every Blueprints related issue and PR.

**Pull request closed without merging**
