### PR TITLE
Added check for dry run component generation

### LINKED ISSUE #753: `ng generate route --dry-run` modifies system-config.ts
1. OS X El Capitan
2. `ng --version`:
  
  ```
  angular-cli: 1.0.0-beta.1
  node: 6.1.0
  os: darwin x64
  ```
3. Run `ng generate route login --dry-run`. After the command completes `system-config.ts` is modified - `'app/+login'`entry is added to the `barrels` array "App specific barrels" section. Expected behavior - in the `--dry-run` mode none of the files should be modified.

### PR DESCRIPTION
**Pull request by delasteve**
This fixes #753.

There is probably a better way to do this, but in my limited knowledge of the codebase, this is how I would fix it.

If there is a better way, let me know and I will change it!

### CODE REVIEW

**Comment by Brocco** [comment]
@delasteve there are additional files modified within the `afterInstall` method in the route blueprint, please update that function to not modify the parent route. You can find that function [here](https://github.com/angular/angular-cli/blob/f7ae81f164c6ce010800c9bbe051bd48ebb3247c/addon/ng2/blueprints/route/index.js#L120)

Also, please rebase this branch on top of master before re-pushing.

**Comment by delasteve** [comment]
@Brocco, I believe everything you asked for is complete. Let me know if there is another thing you find that relates to this. I would be glad to fix it.

**Comment by Brocco** [comment]
@delasteve that does look good, especially adding tests. One last thing, can you please revise your PR to be a single commit? Once done & CI runs it can be merged in.

THANKS!

**Comment by delasteve** [comment]
@Brocco, looks like the main project is failing due to a Broccoli issue. I will rebase this (again) when the project is back to green.

**Comment by Brocco** [comment]
Merged

**Pull request closed without merging**
