### PR TITLE
fix(@angular-devkit/build-angular): support inline javascript in less for browser-esbuild

### LINKED ISSUE #25572: Angular 16 esbuild: inline JavaScript is not enabled of less
### Command

serve

### Description

Hope to keep `javascriptEnabled` enabled in esbuild, currently ng-zorro-antd still needs support for inline scripts.

Config differences between [esbuild](https://github.com/angular/angular-cli/blob/main/packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/less-language.ts#L90) and [webpack](https://github.com/angular/angular-cli/blob/main/packages/angular_devkit/build_angular/src/tools/webpack/configs/styles.ts#L272).

A simple step to reproduce:

```
# Angular 16.1.x
ng new demo
ng add ng-zorro-antd
ng s --force-esbuild
```

Error:

```
✘ [ERROR] Inline JavaScript is not enabled. Is it set in your options? [plugin angular-less]

    node_modules/ng-zorro-antd/src/style/color/bezierEasing.less:110:0:
      110 │ .bezierEasingMixin();
          ╵ ^


✘ [ERROR] Inline JavaScript is not enabled. Is it set in your options? [plugin angular-less]

    node_modules/ng-zorro-antd/src/style/color/bezierEasing.less:110:0:
      110 │ .bezierEasingMixin();
          ╵ ^


✘ [ERROR] Inline JavaScript is not enabled. Is it set in your options? [plugin angular-less]

    node_modules/ng-zorro-antd/src/style/color/bezierEasing.less:110:0:
      110 │ .bezierEasingMixin();
          ╵ ^


✘ [ERROR] Inline JavaScript is not enabled. Is it set in your options? [plugin angular-less]

    node_modules/ng-zorro-antd/src/style/color/bezierEasing.less:110:0:
      110 │ .bezierEasingMixin();
          ╵ ^


✘ [ERROR] Inline JavaScript is not enabled. Is it set in your options? [plugin angular-less]

    node_modules/ng-zorro-antd/src/style/color/bezierEasing.less:110:0:
      110 │ .bezierEasingMixin();
          ╵ ^


✘ [ERROR] Inline JavaScript is not enabled. Is it set in your options? [plugin angular-less]

    node_modules/ng-zorro-antd/src/style/color/bezierEasing.less:110:0:
      110 │ .bezierEasingMixin();
          ╵ ^


✘ [ERROR] Inline JavaScript is not enabled. Is it set in your options? [plugin angular-less]

    node_modules/ng-zorro-antd/src/style/color/bezierEasing.less:110:0:
      110 │ .bezierEasingMixin();
          ╵ ^


✘ [ERROR] Inline JavaScript is not enabled. Is it set in your options? [plugin angular-less]

    node_modules/ng-zorro-antd/src/style/color/bezierEasing.less:110:0:
      110 │ .bezierEasingMixin();
          ╵ ^


✘ [ERROR] Inline JavaScript is not enabled. Is it set in your options? [plugin angular-less]

    node_modules/ng-zorro-antd/src/style/color/bezierEasing.less:110:0:
      110 │ .bezierEasingMixin();
          ╵ ^


✘ [ERROR] Inline JavaScript is not enabled. Is it set in your options? [plugin angular-less]

    node_modules/ng-zorro-antd/src/style/color/bezierEasing.less:110:0:
      110 │ .bezierEasingMixin();
          ╵ ^


✘ [ERROR] Inline JavaScript is not enabled. Is it set in your options? [plugin angular-less]

    node_modules/ng-zorro-antd/src/style/color/bezierEasing.less:110:0:
      110 │ .bezierEasingMixin();
          ╵ ^


✘ [ERROR] Inline JavaScript is not enabled. Is it set in your options? [plugin angular-less]

    node_modules/ng-zorro-antd/src/style/color/bezierEasing.less:110:0:
      110 │ .bezierEasingMixin();
          ╵ ^


✘ [ERROR] Inline JavaScript is not enabled. Is it set in your options? [plugin angular-less]

    node_modules/ng-zorro-antd/src/style/color/bezierEasing.less:110:0:
      110 │ .bezierEasingMixin();
          ╵ ^


✘ [ERROR] Inline JavaScript is not enabled. Is it set in your options? [plugin angular-less]

    node_modules/ng-zorro-antd/src/style/color/bezierEasing.less:110:0:
      110 │ .bezierEasingMixin();
          ╵ ^


✘ [ERROR] Inline JavaScript is not enabled. Is it set in your options? [plugin angular-less]

    node_modules/ng-zorro-antd/style/color/bezierEasing.less:110:0:
      110 │ .bezierEasingMixin();
          ╵ ^

  The plugin "angular-less" was triggered by this import

    angular:styles/global:styles:1:8:
      1 │ @import 'src/styles.less';
        ╵         ~~~~~~~~~~~~~~~~~


  ➜  Local:   http://127.0.0.1:4200/
Watch mode enabled. Watching for file changes...
```

### Describe the solution you'd like

_No response_

### Describe alternatives you've considered

_No response_

### PR DESCRIPTION
**Pull request by cipchk**
Fix #25572

## PR Checklist

Please check to confirm your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular-cli/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #25572

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by dylanvdmerwe** [comment]
Note that this appears to be needed for esbuild to support `ng-zorro-antd`.

**Comment by qyjs** [comment]
cool, when can I use the esbuild.

**Comment by JoaoPauloLousada** [comment]
look forward to having this fix!

**Comment by JoaoPauloLousada** [comment]
@cipchk it seems there is a problem with the format of a commit message. I see the CI/lint pipeline is complaining about that.

**Comment by qyjs** [comment]
@alan-agius4 it seems there is a problem with the format of a commit message. I see the CI/lint pipeline is complaining about that.

Thank you very much. We urgently need this feature

**Comment by alan-agius4** [comment]
Thanks for your contribution. However, let's close this in favor of https://github.com/angular/angular-cli/pull/25639 which enables JavaScript support conditionally.

**Pull request closed without merging**
