### PR TITLE
refactor: removes `@angular/ssr/tokens` and imports the symbols from `@angular/core`

### PR DESCRIPTION
**Pull request by dgp1130**
Since the symbols are exposed from `@angular/core`, there is no need for a separate export in `@angular/ssr/tokens` anymore.

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
LGTM, thanks @dgp1130 👍

**Review by AndrewKushnir — APPROVED** [review]

**Comment by jkrems** [comment]
Sorry for that, looks like my merge of the angular bot generated version bumps created a conflict here. `main` should already contain rc3 of the framework packages now.

**Comment by dgp1130** [comment]
No problem, just rebased and dropped the version bump.

**Review by jkrems — APPROVED** [review]

**Comment by jkrems** [comment]
Switched `action: merge` and plan to land in a few minutes. Feel free to object if I shouldn't. :)

**Pull request merged**
