### PR TITLE
fix(@angular/cli): fix webdriver deep import on yarn

### LINKED ISSUE #4596: [beta.31] ng e2e does not work anymore
### OS?
Archlinux

```
@angular/cli: 1.0.0-beta.31
node: 7.5.0
os: linux x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/flex-layout: 2.0.0-beta.4
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.6
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.6
```

### Repro steps.

Created with ng init and always updated

Running `ng e2e --progress=false -e=prod-e2e` gives:
```

➜  frontend git:(master) ✗ ng e2e --progress=false -e=prod-e2e                               
** NG Live Development Server is running on http://localhost:4200. **
(node:24803) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Hash: af5145659c048450397c
Time: 16784ms
chunk    {0} 0.chunk.js, 0.bundle.map 190 kB {1} {2} {3} {4} {5} {6} {7} {8} {10} [rendered]
chunk    {1} 1.chunk.js, 1.bundle.map 157 kB {0} {2} {3} {4} {5} {6} {7} {8} {10} [rendered]
chunk    {2} 2.chunk.js, 2.bundle.map 111 kB {0} {1} {3} {4} {5} {6} {7} {8} {10} [rendered]
chunk    {3} 3.chunk.js, 3.bundle.map 18.3 kB {0} {1} {2} {4} {5} {6} {7} {8} {10} [rendered]
chunk    {4} 4.chunk.js, 4.bundle.map 19.8 kB {0} {1} {2} {3} {5} {6} {7} {8} {10} [rendered]
chunk    {5} 5.chunk.js, 5.bundle.map 18.9 kB {0} {1} {2} {3} {4} {6} {7} {8} {10} [rendered]
chunk    {6} 6.chunk.js, 6.bundle.map 17 kB {0} {1} {2} {3} {4} {5} {7} {8} {10} [rendered]
chunk    {7} 7.chunk.js, 7.bundle.map 26.6 kB {0} {1} {2} {3} {4} {5} {6} {8} {10} [rendered]
chunk    {8} 8.chunk.js, 8.bundle.map 11.5 kB {0} {1} {2} {3} {4} {5} {6} {7} {10} [rendered]
chunk    {9} polyfills.bundle.js, polyfills.bundle.map (polyfills) 222 kB {14} [initial] [rendered]
chunk   {10} main.bundle.js, main.bundle.map (main) 202 kB {13} [initial] [rendered]
chunk   {11} styles.bundle.js, styles.bundle.map (styles) 203 kB {14} [initial] [rendered]
chunk   {12} scripts.bundle.js, scripts.bundle.map (scripts) 15.3 kB {14} [initial] [rendered]
chunk   {13} vendor.bundle.js, vendor.bundle.map (vendor) 4.14 MB [initial] [rendered]
chunk   {14} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]

WARNING in ./src/app/features/cockpit/workspaces/petals-content/petals-component-view/petals-component-overview/petals-component-overview.component.ts
35:55-68 "export 'IComponentRow' was not found in '../../../state/components/component.interface'

WARNING in ./src/app/features/cockpit/workspaces/petals-content/petals-component-view/petals-component-overview/petals-component-overview.component.ts
35:88-101 "export 'IComponentRow' was not found in '../../../state/components/component.interface'

WARNING in ./src/app/features/cockpit/workspaces/petals-content/petals-service-unit-view/petals-service-unit-overview/petals-service-unit-overview.component.ts
35:55-70 "export 'IServiceUnitRow' was not found in '../../../state/service-units/service-unit.interface'

WARNING in ./src/app/features/cockpit/workspaces/petals-content/petals-service-unit-view/petals-service-unit-overview/petals-service-unit-overview.component.ts
35:90-105 "export 'IServiceUnitRow' was not found in '../../../state/service-units/service-unit.interface'
webpack: Compiled with warnings.
(node:24803) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module 'protractor/node_modules/webdriver-manager/built/lib/cmds/update' from '/home/vnoel/Linagora/Petals/dev/git/petals-cockpit-new/frontend'
(node:24803) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

And stay blocked.

### PR DESCRIPTION
**Pull request by filipesilva**
Fix #4596

### CODE REVIEW

**Comment by filipesilva** [comment]
Doesn't seem like this fix is enough.

**Comment by Meligy** [comment]
How about adding `webdriver-manager` directly instead of via `protractor`?

**Comment by cexbrayat** [comment]
@filipesilva As you were wondering if this was enough, your PR fixes the issue for my project (cli `beta.31` + yarn)

**Comment by victornoel** [comment]
@cexbrayat I guess it doesn't work with npm anymore and that's why it is not enough?

**Comment by filipesilva** [comment]
Yeah it doesn't work npm with this fix. Not sure what the solution is for now, but the workaround is to update webdriver manually (`($npm bin) webdriver-manager update`) and to run the e2e command without webdriver (`ng e2e --no-webdriver-update`).

**Comment by Meligy** [comment]
Would it make sense to run `node_modules/.bin/webdriver-manager` as a child process with the project as a working directory for the process?

**Comment by Meligy** [comment]
That's essentially the CLI doing it the same way as the workaround.

**Comment by filipesilva** [comment]
That's what we were trying to move away from, running npm scripts in separate processes.

**Comment by Meligy** [comment]
I think there are potential 2 options:

1 - Add `webdriver-manager` to `devDependencies` so that it's hopefully always directly under `node_modules`. The con is having to sync its version to `protractor` manually

2 - Add a file check for one of the cases (say NPM, under `protractor`), and if it doesn't exist, revert back to looking in `node_modules`. The con is that it's just silly, and might not serve well in the future, but you can worry about this when there are many more cases.

I just going with option 2, as this is a basic failing scenario at the moment.

**Comment by filipesilva** [comment]
@Meligy I think something like 2 is a pretty good solution for now. Trying both and failing only if neither is there.

**Pull request closed without merging**
