### PR TITLE
fix(@angular-devkit/build-angular): do not break with Jasmine's mock clock

### LINKED ISSUE #11164: Regression: upgrading from 6.0.7 to 6.0.8 makes test fail
A test that has been passing for months, with many different versions of Angular and Angular CLI, fails every time it's run afer an upgrade from cli 6.0.7 and devkit 0.6.7 to cli 6.0.8 and devkit 0.6.8, for a reason that I can't explain.

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions

Node v8.11.1
NPM 6.0.0
Yarn 1.6.0
macOS High Sierra 10.13.4 (17E202)

### Repro steps

Here's a link to our repo where the problem happens: https://github.com/Ninja-Squad/globe42.git

Repro steps:
 - `git clone https://github.com/Ninja-Squad/globe42.git`
 - `cd globe42/frontend`
 - `git checkout cli-test-regression-before`
 - `yarn`
 - `ng test` --> all tests pass
 - `git checkout cli-test-regression-after`: the only difference with the before branch is the versions of the CLI and the devkit, in package.json and yarn.lock
 - `yarn`
 - `ng test` --> one test fails, for a reason that I can't explain

### The log given by the failure

```
HeadlessChrome 0.0.0 (Mac OS X 10.13.4) TasksPageComponent should navigate to other page when clicking page FAILED
	Expected spy navigate to have been called with [ [ '.' ], Object({ relativeTo: Object({ data: Observable({ _isScalar: true, _subscribe: Function, value: Object({ taskListType: 'todo', tasks: Object({ content: [ Object({ id: 0, description: 'Some description', title: 'Some title', category: Object, dueDate: '2017-08-01', status: 'DONE', totalSpentTimeInMinutes: 0, assignee: null, creator: Object, concernedPerson: null }), Object({ id: 1, description: 'Some description', title: 'Some title', category: Object, dueDate: '2017-08-01', status: 'DONE', totalSpentTimeInMinutes: 0, assignee: null, creator: Object, concernedPerson: null }), Object({ id: 2, description: 'Some description', title: 'Some title', category: Object, dueDate: '2017-08-01', status: 'DONE', totalSpentTimeInMinutes: 0, assignee: null, creator: Object, concernedPerson: null }) ], number: 0, size: 3, totalElements: 8, totalPages: 3 }) }) }), parent: Object({ snapshot: Object({ data: Object({  }) }) }) }), queryParams: Object({ page: '1' }) }) ] but it was never called.
	    at http://localhost:9876/_karma_webpack_/webpack:/src/app/tasks-page/tasks-page.component.spec.ts:143:31
	    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke node_modules/zone.js/dist/zone.js:388:1)
	    at AsyncTestZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.AsyncTestZoneSpec.onInvoke node_modules/zone.js/dist/zone-testing.js:713:1)
	    at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke node_modules/zone.js/distHeadlessChrome 0.0.0 (Mac OS X 10.13.4) TasksPageComponent should navigate to other page when clicking page FAILED
	Expected spy navigate to have been called with [ [ '.' ], Object({ relativeTo: Object({ data: Observable({ _isScalar: true, _subscribe: Function, value: Object({ taskListType: 'todo', tasks: Object({ content: [ Object({ id: 0, description: 'Some description', title: 'Some title', category: Object, dueDate: '2017-08-01', status: 'DONE', totalSpentTimeInMinutes: 0, assignee: null, creator: Object, concernedPerson: null }), Object({ id: 1, description: 'Some description', title: 'Some title', category: Object, dueDate: '2017-08-01', status: 'DONE', totalSpentTimeInMinutes: 0, assignee: null, creator: Object, concernedPerson: null }), Object({ id: 2, description: 'Some description', title: 'Some title', category: Object, dueDate: '2017-08-01', status: 'DONE', totalSpentTimeInMinutes: 0, assignee: null, creator: Object, concernedPerson: null }) ], number: 0, size: 3, totalElements: 8, totalPages: 3 }) }) }), parent: Object({ snapshot: Object({ data: Object({  }) }) }) }), queryParams: Object({ page: '1' }) }) ] but it was never called.
	    at http://localhost:9876/_karma_webpack_/webpack:/src/app/tasks-page/tasks-page.component.spec.ts:143:31
	    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke node_modules/zone.js/dist/zone.js:388:1)
	    at AsyncTestZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.AsyncTestZoneSpec.onInvoke node_modules/zone.js/dist/zone-testing.js:713:1)
	    at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke node_modules/zone.js/dist/zone-testing.js:285:1)
HeadlessChrome 0.0.0 (Mac OS X 10.13.4): Executed 394 of 465 (1 FAILED) (0 secs / 28.893 secs)
HeadlessChrome 0.0.0 (Mac OS X 10.13.4) TasksPageComponent should navigate to other page when clicking page FAILED
	Expected spy navigate to have been called with [ [ '.' ], Object({ relativeTo: Object({ data: Observable({ _isScalar: true, _subscribe: Function, value: Object({ taskListType: 'todo', tasks: Object({ content: [ Object({ id: 0, description: 'Some description', title: 'Some title', category: Object, dueDate: '2017-08-01', status: 'DONE', totalSpentTimeInMinutes: 0, assignee: null, creator: Object, concernedPerson: null }), Object({ id: 1, description: 'Some description', title: 'Some title', category: Object, dueDate: '2017-08-01', status: 'DONE', totalSpentTimeInMinutes: 0, assignee: null, creator: Object, concernedPerson: null }), Object({ id: 2, description: 'Some description', title: 'Some title', category: Object, dueDate: '2017-08-01', status: 'DONE', totalSpentTimeInMinutes: 0, assignee: null, creator: Object, concernedPerson: null }) ], number: 0, size: 3, totalElements: 8, totalPages: 3 }) }) }), parent: Object({ snapshot: Object({ data: Object({  }) }) }) }), queryParams: Object({ page: '1' }) }) ] but it was never called.
	    at http://localhost:9876/_karma_webpack_/webpack:/src/app/tasks-page/tasks-page.component.spec.ts:143:31
	    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke node_modules/zone.js/dist/zone.js:388:1)
	    at AsyncTestZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.AsyncTestZoneSpec.onInvoke node_modules/zone.js/dist/zone-testing.js:713:1)
	    at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke node_modules/zone.js/distHeadlessChrome 0.0.0 (Mac OS X 10.13.4): Executed 465 of 465 (1 FAILED) (35.172 secs / 34.964 secs)
```

### Desired functionality

The test seems correct, and has always passed with previous versions. Upgrading the CLI shouldn't make it fail.

### LINKED ISSUE #11626: `@angular-devkit/build-angular` breaks Jasmine's mock clock
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x] test
```

### Versions
```
> node --version
v8.11.3

> npm --version
5.6.0

> ng --version
Angular CLI: 6.1.0-rc.3
Node: 8.11.3
OS: win32 x64
Angular: 6.0.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.0-rc.3
@angular-devkit/build-angular     0.7.0-rc.3
@angular-devkit/build-optimizer   0.7.0-rc.3
@angular-devkit/build-webpack     0.7.0-rc.3
@angular-devkit/core              0.7.0-rc.3
@angular-devkit/schematics        0.7.0-rc.3
@angular/cli                      6.1.0-rc.3
@ngtools/webpack                  6.1.0-rc.3
@schematics/angular               0.7.0-rc.3
@schematics/update                0.7.0-rc.3
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.9.2
```
OS: Windows 10

### Repro steps
1. `npm install --global @angular/cli`.
2. `ng new test-app && cd test-app`.
3. `npm test` --> Passed ✔️
4. Add a test in `src/app/app.component.spec.ts` that uses `jasmine.clock().install()`. E.g.:
    ```ts
    it('should pass', () => {
      jasmine.clock().install();
      expect(true).toBe(true);
      jasmine.clock().uninstall();
    });
    ```
5. `npm test` --> Fails ❌
    > Error: Jasmine Clock was unable to install over custom global timer functions. Is the clock already installed?

### The log given by the failure
```
Chrome 67.0.3396 (Windows 10.0.0) AppComponent should pass FAILED
        Error: Jasmine Clock was unable to install over custom global timer functions. Is the clock already installed?
            at UserContext.eval (webpack:///./src/app/app.component.spec.ts?:31:25)
            at ZoneDelegate.invoke (webpack:///./node_modules/zone.js/dist/zone.js?:387:26)
            at ProxyZoneSpec.onInvoke (webpack:///./node_modules/zone.js/dist/zone-testing.js?:287:39)
            at ZoneDelegate.invoke (webpack:///./node_modules/zone.js/dist/zone.js?:386:32)
            at Zone.run (webpack:///./node_modules/zone.js/dist/zone.js?:137:43)
            at runInTestZone (webpack:///./node_modules/zone.js/dist/zone-testing.js?:508:34)
Chrome 67.0.3396 (Windows 10.0.0) AppComponent should pass FAILED
        Error: Jasmine Clock was unable to install over custom global timer functions. Is the clock already installed?
            at UserContext.eval (webpack:///./src/app/app.component.spec.ts?:31:25)
            at ZoneDelegate.invoke (webpack:///./node_modules/zone.js/dist/zone.js?:387:26)
            at ProxyZoneSpec.onInvoke (webpack:///./node_modules/zone.js/dist/zone-testing.js?:287:39)
            at ZoneDelegate.invoke (webpack:///./node_modules/zone.js/dist/zone.js?:386:32)
            at Zone.run (webpack:///./node_modules/zone.js/dist/zone.js?:137:43)
            at runInTestZone (webpack:///./node_modules/zone.js/dist/zone-testing.js?:508:34)
            at UserContext.eval (webpack:///./node_modules/zone.js/dist/zone-testing.js?:523:20)
Chrome 67.0.3396 (Windows 10.0.0): Executed 4 of 4 (1 FAILED) (0 secs / 0.433 secs)
Chrome 67.0.3396 (Windows 10.0.0) AppComponent should pass FAILED
        Error: Jasmine Clock was unable to install over custom global timer functions. Is the clock already installed?
            at UserContext.eval (webpack:///./src/app/app.component.spec.ts?:31:25)
            at ZoneDelegate.invoke (webpack:///./node_modules/zone.js/dist/zone.js?:387:26)
            at ProxyZoneSpec.onInvoke (webpack:///./node_modules/zone.js/dist/zone-testing.js?:287:39)
            at ZoneDelegate.invoke (webpack:///./node_modules/zone.js/dist/zone.js?:386:32)
            at Zone.run (webpack:///./node_modules/zone.js/dist/zone.js?:137:43)
            at runInTestZone (webpack:///./node_modules/zone.js/dist/zone-testing.js?:508:34)
Chrome 67.0.3396 (Windows 10.0.0): Executed 4 of 4 (1 FAILED) (0.462 secs / 0.433 secs)
```

### Desired functionality
No errors :grin:

### Mention any other details that might be useful
AFAICT, the problem is caused by incorrect order of code execution. More specifically:
- Jasmine stores the global timing functions (such as `setTimeout`).
- When calling `jasmine.clock().install()`, it overwrites the timing functions with mocks.
- Before doign so, it checks whether the currently global timing functions are different than what it has stored in step 1. If so, it assumes the clock is already installed (i.e. the functions are overwritten) and throws.
- Zone.js also overwrites the global timing functions to make them zone-aware.

In order for this to work, Zone.js must patch the global functions before Jasmine stores the "original" global functions (to later compare them and determine if the clock is already installed). For some reason, it seems that Jasmine is storing the global functions before Zone.js has patched them. Then, once we call `jasmine.clock().install()`, Jasmine compares the orignal, unpatched global functions with the current global functions (which have since been patched  by Zone.js) and finds that they are not the same (and throws).

I have no idea why this is happening, but by trying out several versions I have found out this is broken in `@angular-devkit/build-angular` v0.6.8 (and all the way through v0.7.0-rc.3). The commit that broke it is 0b126f6d3 and more specifically [this change][1].

Reverting the `test` property back to also check `!chunks.some(({ name }) => name === 'polyfills')` fixes the issue.

[1]: https://github.com/angular/angular-cli/commit/0b126f6d34ac5d94a5fb96d38f23b2b690afd56d#diff-8311f86ef0adf0533613f54692cbd2abR80

### PR DESCRIPTION
**Pull request by gkalpak**
Fixes #11164.
Fixes #11626.

### CODE REVIEW

**Comment by gkalpak** [comment]
@filipesilva, shouldn't this also be merged into the 6.1.x branch?
It is not included in the recent `@angular-devkit/build-angular@0.7.0` 😢

**Comment by filipesilva** [comment]
It will be merged into 6.1.1, but 6.1.0 was already frozen except for release blocking commits.

**Comment by Manduro** [comment]
@filipesilva This is not in 0.7.3/6.1.3 yet it seems, could you merge it for 6.1.x please?

**Comment by filipesilva** [comment]
@Manduro looking into why that happened, it should be there but isn't.

**Pull request merged**
