### PR TITLE
fix(lint): add default eslint file, fix cmd

### PR DESCRIPTION
**Pull request by filipesilva**
Project linting was setup in a weird way:
- there was a [deprecated](http://eslint.org/docs/user-guide/configuring#configuration-file-formats) `.eslintrc`file with minimal config
- there was a non-standard `eslint.json` file with loads of rules
- the npm script didn't find any errors when I tested by turning on the `semi` rule

I remember @zackarychapple had asked me for help some time ago and it was me that got back to him saying that we needed to use the npm script as `eslint -c eslint.json './**/*.js'`, but when testing today on the console and trying to integrate with my editor, I found out that doesn't do anything.

This PR the consolidates all config in a standard `.eslintrc.json` file and explicitly lists dirs to lint (I tried not doing that but it seemed to hang on windows... my bet is that `node_modules` isn't being ignored automatically).

### CODE REVIEW

**Comment by filipesilva** [comment]
Follow up to the `node_modules` issue: https://github.com/eslint/eslint/issues/5780

**Comment by filipesilva** [comment]
Added `.eslintignore` and updated npm script to use solution provided in https://github.com/eslint/eslint/issues/5780#issuecomment-205341956.

The lint command now correctly works for all `.js` files inside the project, and it ignores the templates because they are `.ts` anyway.

**Comment by hansl** [comment]
<3 it !  LGTM.

**Comment by hansl** [comment]
Is this going to fix https://github.com/angular/angular-cli/issues/371?

**Comment by filipesilva** [comment]
Removed the inaccurate comment from `.eslintignore`, otherwise everything is the same.

**Comment by filipesilva** [comment]
Also related to the initial problem https://github.com/eslint/eslint/issues/5796

**Comment by filipesilva** [comment]
@hansl this is unrelated to #371, but I'll have a look at it with what I've learned from this PR.

**Pull request merged**
