### PR TITLE
feat: add ability to output bundles in separate directory

### PR DESCRIPTION
**Pull request by ValeryVS**
Implements #4788 

Add `bundlesOutDir` option to `.angular-cli.json`

```
.
..
bundles/
    main.bundle.js
index.html
```

### CODE REVIEW

**Comment by ValeryVS** [comment]
There are errors with deploy test.
Can I run only my test with some command?
Manual testing is fine.

**Comment by ValeryVS** [comment]
@filipesilva could you see this `css-urls` fail? It is from #4803 
It seems, that EOT files really should named with hash.

**Comment by filipesilva** [comment]
Heya @ValeryVS, I'm not sure we want to add this option... It's very similar to the existing `--deploy-url` and I'm not sure how they should interact together. In fact, that's why the `css-urls` test is failing.

I think you raise a good point about EOT files. You can do it currently via `ng build --output-hashing=media`, but now that more stuff is being extracted then we should default to it.

**Comment by ValeryVS** [comment]
I will research about `deployUrl` options more, and, may be, recreate this PR later.

**Comment by ValeryVS** [comment]
I see...
For same purpose, I can use "deployUrl" setting and, then move bundle files and assets dir into "bundles/" dir.

**Comment by zakhenry** [comment]
@ValeryVS how were you able to use deployUrl with moving the bundle files? I'm attempting to achieve this with 

```bash
mkdir dist/static && find dist -type f -maxdepth 1 -mindepth 1 -not -name index.html -exec mv '{}' dist/static \;
```

which seems to mostly work, however some of the links are broken as I have a separate asset directory, but setting the `deployUrl` to `static` causes the path `/static` to be prepended to those asset urls

**Comment by ValeryVS** [comment]
@zakhenry 

.angular-cli.sjon
```json
{
  "deployUrl": "app/"
}
```

makefile or shell script
```bash
mv dist dist-tmp
mkdir dist
mv dist-tmp dist/app
mv dist/app/index.html dist/
```

Result
```
./
    dist/
        app/
            main.bundle.js
        index.html
    src/
```

**Comment by zakhenry** [comment]
@ValeryVS thanks, I was able to work it out, turns out I was having issue with the base root definitions in my scss files, eg I had to change `url(/assets/path/to/file)` to `url(~assets/path/to/file` so the webpack asset flattening still worked

**Comment by ValeryVS** [comment]
@zakhenry 
Thanks for hint with tilda.

**Pull request closed without merging**
