### PR TITLE
Correct forkChecker ats config option to speed up reloads

### PR DESCRIPTION
**Pull request by texel**
The option for awesome-typescript-loader to fork the type checker is `forkChecker`, not `useForkChecker`. This change forks the type checker, and drastically lowers reload times (from ~4sec to ~1.5sec on a new project on my machine).

### CODE REVIEW

**Comment by filipesilva** [comment]
@texel the CI errors are unrelated to your work, it's something we're fixing in another PR. The CLI is something we need though, and can't merge without.

**Comment by texel** [comment]
@googlebot I signed it!

**Comment by Meligy** [comment]
@texel the got doesn't seem to recognize the CLA. Did you use the same email as the one you have in your github profile when you signed it?

**Comment by texel** [comment]
@Meligy no, I'm gonna get that fixed ASAP.

**Comment by texel** [comment]
Oops, tried to update my email address in the relevant commits, that didn't go so well. Will close this PR and reopen.

**Comment by texel** [comment]
New PR: https://github.com/angular/angular-cli/pull/3011

**Pull request closed without merging**
