### PR TITLE
docs: move documentation from readme to wiki

### PR DESCRIPTION
**Pull request by Brocco**

### CODE REVIEW

**Comment by DennisSmolek** [comment]
This pulls out all documentation on 3d party and global libraries. Was this an intended omission?

**Comment by Brocco** [comment]
Yes, all of this documentation is now available via the wiki (which is still being worked on and improved). The purpose was to clean up the readme to be a brief intro with the actual documentation in the wiki (maintained in the `docs/documentaiton` folder in the repo).

**Comment by waiholiu** [comment]
Might be useful to at least have a link in the Readme somewhere to say that that is where the documentation is now living?

**Comment by filipesilva** [comment]
@waiholiu yeap, I'll be working on a better wiki landing page and directing people there.

**Pull request merged**
