### PR TITLE
SCSS 'WebP' image load

### PR DESCRIPTION
**Pull request by Gusachenko**
issue : https://github.com/angular/angular-cli/issues/6526

### CODE REVIEW

**Comment by filipesilva** [comment]
LGTM 👍

**Comment by filipesilva** [comment]
Heya, can you have a look at the CLA? We cannot merge without it.

**Comment by Gusachenko** [comment]
I signed it!

**Comment by Gusachenko** [comment]
@filipesilva i'm looking at the CLAs, thanks!

**Comment by Gusachenko** [comment]
new PR, with corresponding commit message: https://github.com/angular/angular-cli/pull/6594

**Comment by filipesilva** [comment]
Closing in favor of #6594

**Pull request closed without merging**
