### PR TITLE
fix(@angular/cli): expanded locale pattern in workspace schema for lo…

### PR DESCRIPTION
**Pull request by sacgrover**
…cales field

Fixes: angular#17032

### CODE REVIEW

**Comment by sacgrover** [comment]
Sure, Sorry, I just noticed you made the same changes on same time.

**Comment by clydin** [comment]
No problem.  Yours was quicker by 2 seconds so we can go with yours.

**Comment by sacgrover** [comment]
@clydin  I found two more instances. Do we need to update that as well?

https://github.com/angular/angular-cli/blob/c9a5f3ced6689feac9cc0ccbd15b0fed6f454d6e/packages/angular_devkit/build_angular/src/browser/schema.json#L214

https://github.com/angular/angular-cli/blob/c9a5f3ced6689feac9cc0ccbd15b0fed6f454d6e/packages/angular_devkit/build_angular/src/server/schema.json#L178

**Comment by clydin** [comment]
Yes. Please do.

**Comment by sacgrover** [comment]
Done

**Comment by dgp1130** [comment]
Also merged to patch branch (9.0.x).

**Pull request merged**
