### PR TITLE
fix(@angular/cli): Generating component considers default style ext

### LINKED ISSUE #7624: Generate(component): Does not default to SCSS when specified in `.angular-cli.json`
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.4.0
node: 8.4.0
os: darwin x64
@angular/animations: 4.4.0-RC.0
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.4.0-RC.0
@angular/compiler: 4.4.0-RC.0
@angular/core: 4.4.0-RC.0
@angular/flex-layout: 2.0.0-beta.9
@angular/forms: 4.4.0-RC.0
@angular/http: 4.4.0-RC.0
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.4.0-RC.0
@angular/platform-browser-dynamic: 4.4.0-RC.0
@angular/router: 4.4.0-RC.0
@angular/cli: 1.4.0
@angular/compiler-cli: 4.4.0-RC.0
@angular/language-service: 4.4.0-RC.0
@angular/service-worker: 1.0.0-beta.16
typescript: 2.5.2

### Repro steps.

Run `ng g c foo`

### The log given by the failure.

No failure

### Desired functionality.

Result: `foo.component.css`
Expected Result: `foo.component.scss`

### Mention any other details that might be useful.

.angular-cli.json Example:

```json
"defaults": {
  "styleExt": "scss",
},
```

### PR DESCRIPTION
**Pull request by AhsanAyaz**
Fixes #7624, #7644, #7647, #7708, #7715, #7719, #7721 & #7522

### CODE REVIEW

**Comment by AhsanAyaz** [comment]
@filipesilva , @Brocco  you please review this? I think I fixed #7522 too with this. 
This would probably avoid anyone else to fix the same stuff.

**Comment by avatsaev** [comment]
Are there any unit tests for this?

**Comment by AhsanAyaz** [comment]
@avatsaev Added unit test for the use case. Though I do need to discuss about use cases where we want to do the `setupProject` based on some extra parameters. 
For instance right now all tests have this setup `ng(['new', 'foo', '--skip-install']`.
What if I need project set up with `ng(['new', 'foo', '--skip-install', '--style', 'scss']` etc. 
Gonna create an issue probably for this.

**Comment by avatsaev** [comment]
@AhsanAyaz that's great! Just be aware there is a commit message format, "Added unit-test" probably won't pass, must be something like "test (generate): add unit tests"

**Comment by AhsanAyaz** [comment]
@avatsaev Yeah watched the build failing. Really hurts. lol
Fixing it :)

**Comment by AhsanAyaz** [comment]
@Brocco thanks for reviewing earlier. 
I added the unit test. You can re-review when you have some time. Thanks.

**Comment by iusmanadil** [comment]
Awesome!

**Comment by grapgrap** [comment]
Awesome! Can i meet this at next version release?

**Comment by ninrod** [comment]
Hi, in what version was this landed?

**Pull request merged**
