### PR TITLE
fix(@schematics/angular): migrate build-angular for 7.0 RC users

### LINKED ISSUE #12647: `ng update @angular/cli` from 7.0.0-rc.1 fails to update @angular-devkit/build-angular
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
@angular/cli@7.0.1

### Repro steps
Update shown in https://github.com/angular/angular/pull/26555 needed followup commit to fix devkit/build-angular version: https://github.com/angular/angular/pull/26555/commits/9631b3a7f6ca97e2dc87e80fb5e9db635f055b2e

### Mention any other details that might be useful
Reported by @IgorMinar

### PR DESCRIPTION
**Pull request by clydin**
Fixes #12647

### CODE REVIEW

**Comment by filipesilva** [comment]
We might get this into 7.0.2 though.

**Comment by clydin** [comment]
7.0.2 is already out (https://github.com/angular/angular-cli/releases/tag/v7.0.2).

**Comment by kyliau** [comment]
@clydin could you please fix the merge conflict?

**Comment by clydin** [comment]
Rebased.

**Pull request merged**
