### PR TITLE
build: run prettier on legacy-cli e2e files

### PR DESCRIPTION
**Pull request by jbedard**
I'm working on switching these to run via bazel and getting significant diffs when editing the files. Are we ok with a single commit formatting all these? For now it's just the legacy-cli which I hope is all the files I'll be editing when switching to bazel...

### CODE REVIEW

**Review by clydin — APPROVED** [review]

**Review by dgp1130 — APPROVED** [review]
LGTM. I'm fine with a one-time format like this, but @clydin should we start enforcing the formatter for legacy tests? It seems like we haven't been doing that so far.

I didn't realize we have so many tests which still use Promises, we should consider updating those to `async/await` next time we touch any of them.

**Comment by jbedard** [comment]
I think the pre-commit runs the formatter? I was assuming it was added at some point but never run on these files, because now when I commit any of them they get formatted...

Also note I've only formatted the e2e legacy-cli files which I hope is all #23085 touches, there's plenty more outside that directory.

**Comment by clydin** [comment]
As mentioned, the commit hooks will run the formatter on changed files.  CI will also verify the formatting for all changed files in the PR.  When `prettier` was introduced essentially all files except those in the `tests` directory were formatted.

**Comment by dgp1130** [comment]
Ok, so we just didn't do the one-time format when we first enabled in the formatter. As long as we're consistent moving forward, I have no concerns.

**Comment by jbedard** [comment]
Thanks!

**Pull request merged**
