### PR TITLE
feat(@angular/cli): add fallback for CSS variables

### LINKED ISSUE #7514: add fallback for css variables
```
- [ X ] feature request
```

### Desired functionality.

Css variables should degrade gracefully on older browsers by having a fallback. This [post css plugin ](https://github.com/postcss/postcss-custom-properties) does exactly that when started with the option `preserve: true`. More generally I believe the cli should support the css cutting edge with fallback thanks to `cssnext`. However variables is what this request is about.

### Why ?

If css variable is not supported by a browser it will simply be ignored, meaning that a bunch of css statements won't be applied. 

**Example**

This

```css
:root {
  --color: red;
}

div {
  color: var(--color);
}
```

should compile to this:

```css
:root {
  --color: red;
}

div {
  color: red;
  color: var(--color);
}
```

Here is an example that would do just that:

```javascript
// dependencies
var fs = require("fs")
var postcss = require("postcss")
var customProperties = require("postcss-custom-properties")

// css to be processed
var css = fs.readFileSync("s.css", "utf8")

// process css using postcss-custom-properties
var output = postcss()
  .use(customProperties({ preserve: true }))
  .process(css)
	.css
	
console.log(output)

```

### PR DESCRIPTION
**Pull request by garoyeri**
Aim to resolve #7514 by including postcss-custom-properties. This will generate extra rules in CSS when a `var()` is used to allow for compatibility with older IE browsers that do not support the feature.

### CODE REVIEW

**Comment by cyrilletuzi** [comment]
@garoyeri Is this supposed to work everywhere in the app ? Because currently it seems to work for CSS variables declared and used in the global styles (`src/styles.scss`) but not for CSS variables used in components' styles.

**Comment by garoyeri** [comment]
Reading through https://github.com/postcss/postcss-custom-properties/blob/master/README.md, there are some caveats on what works and what doesn't.  Primarily, it will only work on variables declared in the `:root` selector. This was a trade-off that I was okay with since I was using it to handle theming use cases.

**Comment by cyrilletuzi** [comment]
@garoyeri  Yes my variables are in `:root`, but they are only transformed for styles using them in `style.scss` but not in styles of components.

**Comment by garoyeri** [comment]
Ok, I did a little more digging, turns out that it is completely unsupported by postcss-custom-properties as per the issue here: https://github.com/postcss/postcss-custom-properties/issues/68.

Basically, the plugin only operates on a single file unless you use postcss-import to inline the other styles which will cause weird things to happen.  The only thing I can think of off the top of my head is to create a theme stylesheet globally that will be used by the component to map your theme variables onto the specific styles you want to override.  This definitely isn't ideal, and supporting IE11 is an uphill journey :(

**Comment by nicky-lenaers** [comment]
@cyrilletuzi I'm stubling upon the same issue where component styles are not using the values generated by postcss-custom-properties. Do you have a workaround for this?

**Comment by cyrilletuzi** [comment]
@nicky-lenaers This feature has been removed from the CLI, because the issue couldn't be solve. If you don't need support for IE11, just use CSS variables.

**Pull request merged**
