### PR TITLE
docs(@angular/cli): update command to generate component

### PR DESCRIPTION
**Pull request by shahrishabhptechnical**
`ng g component ../newer-cmp` was throwing error
so, use `ng g component ./newer-cmp` to generate component

### CODE REVIEW

**Comment by shahrishabhptechnical** [comment]
I signed it!

**Comment by shahrishabhptechnical** [comment]
Ok Thanks !

**Comment by shahrishabhptechnical** [comment]
Looks like commit message is longer. so, one check is failing

**Comment by shahrishabhptechnical** [comment]
Updated Commit message

**Comment by shahrishabhptechnical** [comment]
@Brocco Can you please give me feedback of my change.

**Comment by shahrishabhptechnical** [comment]
Is anything required from my side as Review is still in progress?

**Comment by shahrishabhptechnical** [comment]
When will this get merged?

**Comment by filipesilva** [comment]
@shahrishabhptechnical right about now :D

Thanks for fixing this!

**Pull request merged**
