### PR TITLE
fix(config): change css regex which causes error

### PR DESCRIPTION
**Pull request by sarunint**
Closes angular/angular#11445

### CODE REVIEW

**Comment by hansl** [comment]
LGTM. Thanks!

**Comment by hansl** [comment]
@sarunint could you please login in https://cla.developers.google.com/ and accept the CLA?  Then once you've done it please comment back here, thanks! I'll merge once that's done.

**Comment by sarunint** [comment]
I've already signed it. Not sure why @googlebot doesn't pick it up.

**Comment by sarunint** [comment]
Rebased, and @googlebot finally noticed the CLA.

**Comment by hansl** [comment]
Thanks. As soon as travis is done Il'l merge. LGTM

**Pull request merged**
