### PR TITLE
fix(build): don't ignore js in public

### LINKED ISSUE #540: Static JS assets not copying
Hello Angular-Cli Folks!

I am having trouble getting static JS files (like jquery components for a static page) to copy over the dist folder in version 0.0.34.

Placing the JS folder in the client, or app/assets does nothing, and they are just skipped. Other non JS files are not however in these areas.

Let me know what is the right approach to have static JS files.

### PR DESCRIPTION
**Pull request by filipesilva**
Fix #540

### CODE REVIEW

**Comment by Splaktar** [comment]
It would be great to get this into `master` ASAP. Can you please update the branch with the latest from master?

**Comment by Splaktar** [comment]
I tested this locally and confirm that this also solves https://github.com/vaadin/angular2-polymer/issues/28

**Comment by Splaktar** [comment]
Really would like to get this merged as I have to use a forked version of the CLI until then.

**Comment by hansl** [comment]
LGTM.

**Comment by efriandika** [comment]
LGTM

**Pull request merged**
