### PR TITLE
feat(@angular-devkit/build-angular): use terser instead of uglify-es

### LINKED ISSUE #9340: --prod does not work in Firefox ESR 45.9.0
Hi,

running ´ng serve --prod´ and opening the application in Firefox ESR 45.9.0 throws an exception.

> TypeError: this is undefined

### Versions
```
ng: 1.6.5
npm: 5.6.0
Node: 8.9.4
```

### Repro steps

* ng new foobar
* cd foobar
* ng serve --prod
* Open in Firefox ESR 45.9.0

### Observed behavior

Blank page, error in console

### Desired behavior

Everything works as expected

BR
Jakob

### PR DESCRIPTION
**Pull request by filipesilva**
Should help bring down prod build times, @SanderElias reported a ~60% reduction on his project.

Should fix #9340.

### CODE REVIEW

**Comment by filipesilva** [comment]
Thanks for the heads up @kzc, didn't remember that. Fix up at https://github.com/angular/angular-cli/pull/12033

**Comment by filipesilva** [comment]
@kubbafox this is now released in `@angular-devkit/build-angular@0.9.0-beta.2`.

**Comment by kqadem** [comment]
@filipesilva Is this an ng 7 only feature or can we expect to make use of it while remaining on ng 6.x? For. e. g. by just upgrading cli and/or the devkit packages?

**Comment by kqadem** [comment]
@filipesilva Wow, thx for the quick reply! Alright, let's see how it comes. Having a quite big enterprise product here going to be launched soon prohitibing us major version changes.

Since the change only involves switching a package, we might even consider kind of dirty mapping from uglify to terser... I mean, **~60% build time reduction** :scream:

**Comment by filipesilva** [comment]
Well that was for a specific project. I can't say that'll be the case for every project. Have you tried the beta on your app?

**Comment by kqadem** [comment]
I think I'm going to have a look at it by the end of the week.

> Well that was for a specific project. I can't say that'll be the case for every project

yep, could be even more 😜

**Comment by cquixada** [comment]
We had the same problem involving uglify-es. Changing the version from "angular-devkit/build-angular" to "0.9.0-rc.3", even with Angular CLI 6.2.5, our application is running again with older versions of FF without needing "build-optimizer=false". Thanks.

**Comment by kqadem** [comment]
@cquixada did you notice any improvements regarding build time?

**Pull request merged**
