### PR TITLE
add support for the ssl options of the ng serve task

### PR DESCRIPTION
**Pull request by sbaramov**
Added support for running the webpack dev server in ssl mode through 'ng serve' command. The command options --ssl, --ssl-key, and --ssl-cert are used to configure the server.

This is a second attempt to submit the pull request because the first one #2089 has a broken CLA. This fixes issue #1576

### CODE REVIEW

**Comment by sbaramov** [comment]
@Brocco this is the second pull request with correct CLA. I could not run locally `npm run e2e` because of this error: 

`The package webpack@2.1.0-beta.25 does not satisfy its siblings' peerDependencies requirements!`

This appear to be a local env issue which i will investigate later. Hope this works for you.

**Comment by Brocco** [comment]
Thanks for moving this to a new PR, merged!

**Comment by ranbuch** [comment]
I'm running ```ng serve options --ssl``` and I'm getting ```your connection is not private no unsafe option``` page. Usually when I'm getting this error message I can press on the ```Advanced``` button and click ```Proceed to localgost (unsafe)``` but not in that case.

Chrome error: ```NET::ERR_CERT_INVALID```

```You cannot visit localhost right now because the website sent scrambled credentials that Google Chrome cannot process. Network errors and attacks are usually temporary, so this page will probably work later```

Is there anyone else who's having the same problem?

**Comment by davidbilge** [comment]
Hi ranbuch, I had the same problem a while ago. You can use Chrome's [flags page](chrome://flags/#allow-insecure-localhost) to allow insecure ssl certificates for localhost which is very useful on a dev machine.

**Comment by ranbuch** [comment]
Thank you davidbilge,

I haven't found a useful flag in chrome://flags.

The only flag that I thought would help is:

```Allow invalid certificates for resources loaded from localhost```

It's on ```Enabled```

I'm running Chrome Version 55.0.2883.75 m on Windows 10.

**Comment by ranbuch** [comment]
Oh, I should have re-lunch chrome.

It's winking for me now.

Thanks!

**Comment by davidbilge** [comment]
Okay, great :)

**Comment by sumigoma** [comment]
@ranbuch @davidbilge what you're seeing is probably related to https://github.com/angular/angular-cli/issues/3645

**Pull request merged**
