### PR TITLE
feat(@angular/cli): add eject --config option

### PR DESCRIPTION
**Pull request by sinedied**
Fixes https://github.com/angular/angular-cli/issues/9878.

### CODE REVIEW

**Comment by hansl** [comment]
Hi @sinedied,

We do not support eject in 6.0 yet. When we do we'll have a proper eject workflow. If you rebase this PR on top of the 1.7.x branch I'm open to review and merge it (and release it with 1.7.5). Let me know.

**Comment by sinedied** [comment]
@hansl Sure, I'll do that ASAP, thanks for the feedback

**Comment by sinedied** [comment]
@hansl It's done, should be good but seems there's an issue with the command that checks the commit's message, is there anything I should do to fix it?

**Comment by clydin** [comment]
The `eject` feature is currently being reimplemented within the `angular/devkit` repository located here: https://github.com/angular/devkit

**Comment by sinedied** [comment]
@clydin Thanks for the heads up, I'll take a look to rebase the changes.

What about the 1.7.x . branch, isn't it worth merging as it's ready?

**Pull request closed without merging**
