### PR TITLE
Support proxy to backend

### PR DESCRIPTION
**Pull request by mmrath**
Issue #889 

@filipesilva @TheLarkInn Here is the implementation for further discussion. I don't think it is merge ready. Please let me know your feedback on the implementation. 

Also need your help on the testing side. How do I approach testing? Any existing test cases I can refer to?

### CODE REVIEW

**Comment by mmrath** [comment]
I signed it!

**Comment by mmrath** [comment]
I think we should remove proxy and insecure proxy options.

**Comment by filipesilva** [comment]
Can you include in the first comment a brief text description of your solution as well? It should help us review the code by giving it a overall summary.

In regards to testing I talked a bit with @TheLarkInn and one way that stood out was to have an additional server, proxy calls to it, and verify that we can get stuff from it. There might be better options but this one seemed sound.

**Comment by mmrath** [comment]
@filipesilva @TheLarkInn I have added two test cases, open for your review.

**Comment by TheLarkInn** [comment]
Need to update branch and tests will run again.

**Comment by mmrath** [comment]
@TheLarkInn Updated, all tests passed.

**Comment by allenshiels** [comment]
@mmrath Thanks. I'm using your enhancement and it is working a well. It is essential for me, so it would be great to get this merged into the official branch soon.

Presumably the CI build will succeed now because of 5a9941e4f32e3b02c3ca24a2833b94ec1bbe7d73

**Comment by allenshiels** [comment]
FWIW I agree about removing the proxy and insecure proxy options. They're pretty limited and are just adding to command line option overload.

**Comment by mmrath** [comment]
@filipesilva @TheLarkInn One of the travis CI run appears to be a flaky.

**Comment by filipesilva** [comment]
@TheLarkInn can you review?

**Comment by TheLarkInn** [comment]
LGTM pending tests.

**Comment by mmrath** [comment]
Thanks @TheLarkInn @filipesilva. All tests passed now.

**Comment by yesman85** [comment]
@mmrath could you supply a bit of documentation for the readme? I've never worked with this and it's a bit confusing.

**Comment by filipesilva** [comment]
@yesman85 there is some documentation in the wiki: https://github.com/angular/angular-cli/wiki/stories-proxy

**Comment by nikithaperuka89** [comment]
@filipesilva I am having issues with my proxy.config it works locally. However, when I deploy the application to dev environment the backend api call fails with a 404.

Here is my proxy.config.json:

 "/rest/*": {
    "target": "http://backend-api",
    "secure": false,
    "pathRewrite": {
      "^/rest/*": ""
    },
    "changeOrigin": true
  }
}

**package.json:**
 "scripts": {
    "ng": "ng",
    "start": "ng serve --proxy-config proxy.conf.json",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  }

Please advice

**Pull request merged**
