### PR TITLE
fix(vendor): Fix to add concatenated vendors in index.html

### PR DESCRIPTION
**Pull request by jkuri**
@cironunes, @filipesilva please check this soon as master still not working.

### CODE REVIEW

**Comment by filipesilva** [comment]
It looks ok but you and @cironunes are the ones working on it, I don't have as much information as you two.

**Comment by jkuri** [comment]
I now tested with "clean npm install", creating new project, linking, and I am pretty sure that this now works.

**Comment by jkuri** [comment]
If you check current master its not working, and @cironunes seems to be away at the moment.

**Comment by filipesilva** [comment]
Let's put it in then. Can't have master not working.

**Comment by jkuri** [comment]
I re-checked on master now, and it is working. Thank you.

**Comment by filipesilva** [comment]
:+1:

**Comment by cironunes** [comment]
thanks @jkuri

**Pull request merged**
