### PR TITLE
feature(@ngtools/webpack): add an option to skip code generation.

### LINKED ISSUE #3072: Feature request: option to disable AoT in @ngtools/webpack plugin
In order to use `@ngtools/webpack` in dev mode with fast reload time, it would be great to be able to disable AoT in the plugin.
This way, when activating lazy loading, we could use just one plugin and one route configuration for dev and prod modes.

/cc @hansl

### PR DESCRIPTION
**Pull request by hansl**
Fix #3072

### CODE REVIEW

**Comment by JamesHenry** [comment]
@hansl Forgive me, I am still trying to get my head around the intended usage of @ngtools/webpack for non-angular-cli projects - will this PR essentially make the loader from @ngtools/webpack a first class equivalent of ts-loader or awesome-typescript-loader? (Albeit those will having some additional features which are not necessarily required).

Essentially I got @ngtools/webpack working well with building my hybrid ng1 and ng2 app with AoT, but ran into a strange runtime issue with Injectable when attempting run the code in JIT mode via my dev server.

I was attempting to use @ngtools/webpack _without_ using the AoTPlugin. I tracked the issue with that down the decorator metadata not being emitted by the backup ts program you create in such cases where the plugin is not available. When attempting to research whether or not to submit that as an issue, I found this PR.

I was naturally hoping to use the same tooling across dev, testing and prod (i.e. not have to use awesome-typescript-loader only for dev), would you recommend I simply wait for this PR to land, or is the best way still to use awesome-typescript-loader?

Thanks for all your hard work!

**Comment by hansl** [comment]
@JamesHenry The Webpack AoT plugin already acts as a replacement for ATL and TS-Loader. With this PR it allows you to use JIT compiling for faster compile times. As such, inside the CLI it will replace ATL entirely.

This PR will allow you to use the same plugin and loader for both development (with JIT) and production (with AoT).

**Comment by JamesHenry** [comment]
Perfect! Thanks for getting back to me so quickly. Are there any outstanding tasks ahead of merging?

With this being a nested subdirectory, is there a way to easily npm install the WIP from this PR branch?

**Comment by hansl** [comment]
Not easily. Just wait for the release :) It will be soon after this lands.

**Comment by JamesHenry** [comment]
Ha fair enough! Thanks for the help

**Comment by hansl** [comment]
I'm going to submit this as I need to work on other things. As far as I can tell, this is ready and at least as feature complete as the current master. We'll address bugs before the next release.

Cheers!

**Comment by JamesHenry** [comment]
Thanks! As in the next release of the CLI, or @ngtools/webpack itself?

**Comment by hansl** [comment]
We release both at the same time, so yes. ;)

**Pull request merged**
