### PR TITLE
perf(@angular-devkit/build-angular): change webpack hashing function to `xxhash64`

### PR DESCRIPTION
**Pull request by alan-agius4**
`xxhash64` uses a faster WASM based hash mechanism.

### CODE REVIEW

**Comment by clydin** [comment]
Is there a referenced to what the options enables and/or changes that we can track?

**Comment by alan-agius4** [comment]
The docs don’t explicitly mention the options https://webpack.js.org/configuration/experiments/#experimentsfuturedefaults

**Comment by alan-agius4** [comment]
Maybe we set each option manually to the future default and add an inline commit that this is the future default?

**Comment by clydin** [comment]
I think that’s a good idea. For this PR I think just updating the hash function should be good since that’s pretty much the majority of the PR.
My concern is that the “futureDefaults” option appears to be fluid and may change in minors in potentially breaking ways.

**Comment by alan-agius4** [comment]
@clydin PTAL.

**Review by clydin — APPROVED** [review]

**Pull request merged**
