### PR TITLE
fix(karma): Enable test of global scripts

### PR DESCRIPTION
**Pull request by YonatanKra**
Fixes https://github.com/angular/angular-cli/issues/2897

### CODE REVIEW

**Comment by YonatanKra** [comment]
It is strange - I've done only minor linting fixes, and travis failed (and only for node 6.0).  There might be some error with the travis config.

**Comment by YonatanKra** [comment]
I've tried doing that, but it doesn't work when dealing with complex libraries (like Cesiumjs). That's why I've reverted to changing the `karma.conf` directly to include the whole node module.
Do you still want me to apply the change, even though it is less robust?

**Comment by filipesilva** [comment]
That's a tough cookie... especially because changes in https://github.com/angular/angular-cli/pull/3402 will break this approach. 

I think I need to find a more robust way of adding scripts to the test command, probably by compiling the test config via ts for both dev and release setups.

**Comment by filipesilva** [comment]
Superseded by https://github.com/angular/angular-cli/pull/3543

**Pull request closed without merging**
