### PR TITLE
feat(@angular/cli): optimize stylesheets after bundling

### LINKED ISSUE #8598: deprication notice while build: Node#moveTo was deprecated. Use Container#append.
#### Version

```

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.5.3
Node: 8.9.1
OS: linux x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.3
@angular/tsc-wrapped: 4.4.6
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.3
@schematics/angular: 0.1.0
typescript: 2.4.2
webpack: 3.8.1
```

### Observed behavior
```
30% building modules 167/168 modules 1 active ...nts/src/styles.scssNode#moveTo was deprecated. Use Container#append.
```
After updating to 1.5.3 I get this notice with `scss` while running `ng build --prod`

### LINKED ISSUE #8640: Unreliable build hashes when running `ng build --aot` and after using `ng eject`
### Versions
```
Angular CLI: 1.5.4 (e)
Node: 6.11.1
OS: darwin x64
Angular: 5.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.4
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.21
@angular-devkit/schematics: 0.0.37
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.4
@schematics/angular: 0.1.7
typescript: 2.4.2
webpack-concat-plugin: 1.4.0
webpack-dev-server: 2.9.4
webpack: 3.8.1
```

### Repro steps

The following are the exact commands I'm taking to reproduce. The items of note here are the "main" hashes (not the chunk or bundle hashes), which I'm marking with `<=====` to the right of each relevant hash.
```
➜  ng new testHash
...
➜  Desktop cd testHash
...
➜  testHash git:(master) ng build --prod
Date: 2017-11-26T08:56:50.130Z                                                          
Hash: 5a07dd3af5441b340e31 <=====
Time: 19908ms
chunk {0} polyfills.ad37cd45a71cb38eee76.bundle.js (polyfills) 60.8 kB [initial] [rendered]
chunk {1} main.ffbb21fa33d0e637d7cc.bundle.js (main) 152 kB [initial] [rendered]
chunk {2} styles.d41d8cd98f00b204e980.bundle.css (styles) 0 bytes [initial] [rendered]
chunk {3} inline.723114ead04c6055da6b.bundle.js (inline) 1.45 kB [entry] [rendered]
➜  testHash git:(master) ng build --prod
Date: 2017-11-26T08:57:14.938Z                                                          
Hash: 5a07dd3af5441b340e31 <=====
Time: 19708ms
chunk {0} polyfills.ad37cd45a71cb38eee76.bundle.js (polyfills) 60.8 kB [initial] [rendered]
chunk {1} main.ffbb21fa33d0e637d7cc.bundle.js (main) 152 kB [initial] [rendered]
chunk {2} styles.d41d8cd98f00b204e980.bundle.css (styles) 0 bytes [initial] [rendered]
chunk {3} inline.723114ead04c6055da6b.bundle.js (inline) 1.45 kB [entry] [rendered]
➜  testHash git:(master) ng eject --prod --aot
...
➜  testHash git:(master) npm i
...
➜  testHash git:(master)  npm run build
Hash: 061aac4c0e51c4c0ca29 <=====
Version: webpack 3.8.1
Time: 18669ms
                                   Asset       Size  Chunks             Chunk Names
polyfills.245d62a283551f04431d.bundle.js    60.8 kB       0  [emitted]  polyfills
     main.eabb13002b0ed154f44b.bundle.js     152 kB       1  [emitted]  main
   inline.c21ac12d3c43e4c7c0c1.bundle.js    1.45 kB       3  [emitted]  inline
  styles.d41d8cd98f00b204e980.bundle.css    0 bytes       2  [emitted]  styles
                             favicon.ico    5.43 kB          [emitted]  
                            ./index.html  591 bytes          [emitted]  
                    3rdpartylicenses.txt    3.29 kB          [emitted] 
...
➜  testHash git:(master) npm run build
Hash: 12e3523ac034f26a628d <=====
Version: webpack 3.8.1
Time: 19587ms
                                   Asset       Size  Chunks             Chunk Names
polyfills.245d62a283551f04431d.bundle.js    60.8 kB       0  [emitted]  polyfills
     main.eabb13002b0ed154f44b.bundle.js     152 kB       1  [emitted]  main
   inline.c21ac12d3c43e4c7c0c1.bundle.js    1.45 kB       3  [emitted]  inline
  styles.d41d8cd98f00b204e980.bundle.css    0 bytes       2  [emitted]  styles
                             favicon.ico    5.43 kB          [emitted]  
                            ./index.html  591 bytes          [emitted]  
                    3rdpartylicenses.txt    3.29 kB          [emitted]
```

### Observed behavior

After `ng eject` the main hash are not reliably the same, regardless of no change. Interestingly enough, the chunkhashes are the same, but the main hash changes.

### Desired behavior

Running the build task two times consecutively should render the same results. This may be related to a plugin order issue.

### LINKED ISSUE #8891: Corrupted image when using css-loader+file-loader+AngularCompilerPlugin
### Versions
```
Node: 9.3.0
Npm: 5.5.1
Angular: 5.1.0
@ngtools/webpack: 1.9.1
css-loader: 0.28.7
file-loader: 0.11.2
webpack: 3.6.0
```

### Repro steps
These steps are borrowed from here since share the same problem and my project is to complex to just do a plunker from: https://github.com/gdi2290/angular-starter/issues/1939

1.  Start with clean installation of angular-starter
Add declaration in the styles.scss:
```
body {
  background: url('./../assets/img/angular.png');
}
```
2. Create scss file in the directory src/app/+detail/+child-detail/child-detail.scss with this single declaration:
```
h1 {
  background: url('../../../assets/img/angular.png');
}
```
3. Add styles to the ChildDetailComponent:
```
@Component({
  selector: 'child-detail',
  template: `
    <h1>Hello from Child Detail</h1>
  `,
  styleUrls: ['./child-detail.scss'],
})
export class ChildDetailComponent implements OnInit {

  public ngOnInit() {
    console.log('hello `ChildDetail` component');
  }

}
```
4. Run npm run build:aot:prod

### Observed behavior

In the dist folder there will be two generated png files instead of one.  One file is slightly larger then the original file. It's also corrupted and can't be viewed (not even in PS). They have different hashes in the generated name, which I guess makes sense since it's the MD5 hash of the file if I'm not mistaken. 
When looking in are main.js file I can see that the images references in the background: url() is the corrupt image. This was not happening when running Angular 4 and JIT.

### Desired behavior
Only one image should be created and it should not be corrupt. 

### Mention any other details that might be useful (optional)
I've read through tons of tickets, documentation and tried more combinations in my Webpack config than I can count. The reason I'm writing this ticker here is because of the following quote in the issue tracker.

> 
url()'s in component stylesheets are now processed. This allows the CLI to hash the assets and supports long-term caching. However, the URL now needs to be build-time discoverable and the path must be relative to the component stylesheet for this to work. This also has the advantage that component based assets can be encapsulated within the component source location, if desired.

Forgive me if this is not an Angular CLI issue. But I can't find any related issue with css-loader and file-loader alone. And since the first image is generated fine I suspect something is happening after they are done. Unfortunately there's so much stuff happening behind the curtain, I don't even know who creates the second file.   

This is a log from my own project, not the sample one.
You can clearly see the correct image 'bf8...' being generated. 
```
Child src/app/login-view/login-view.component.scss:
                                   Asset    Size  Chunks             Chunk Names
    bf801dc8612d99ff6adbe37a8dca7877.jpg  103 kB          [emitted]
     + 1 hidden asset
    [10Fg] ./src/app/login-view/login-view.component.scss 363 bytes {0} [built]
            factory:812ms building:1ms = 813ms
    [PGCf] ./src/assets/images/hero-startpage-1920x1000.jpg 82 bytes {0} [built]
           [] -> factory:287ms building:371ms = 658ms
    [scMX] ./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js!./src/app/login-view/login-view.component.scss 827 bytes {0} [built]
           [] -> factory:492ms building:4458ms = 4950ms
        + 1 hidden module
```
But there is no references in the log to the corrupt file besides in the list of generated files.
It just magically appear in the list of resources. And as mentioned earlier it also ends up in the generated CSS instead of 'bf801dc8612d99ff6adbe37a8dca7877.jpg'.

```
f143e4b206e3c901697fe0aeca784d7b.jpg     188 kB          [emitted]
```

### LINKED ISSUE #8934: problematic assets generation with invalid url since 1.5.4
### Versions
```
$ ng version

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.6.1
Node: 8.9.3
OS: linux x64
Angular: 5.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.1
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.1
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps

* clone this branch of demo repo https://github.com/e-cloud/demo-repo-for-various-issues/tree/ng-cli-assets-problem
* install dependencies and run `npm run show/ yarn show`
* open the url shown and compare the image url of logo and the message below. like the image below
image

### Observed behavior
In dist folder, the image url referenced from JS/TS code(which is invalid image) is different from what is in html template, while it is the same image.

### Desired behavior
they should reference the same url and the valid image.

### PR DESCRIPTION
**Pull request by clydin**
Re-structuring the webpack resource loader allows the new stylesheet optimizing plugin to process component styles as well as global styles.  Global styles are now optimized as a whole rather than in isolated parts; allowing for more comprehensive optimizations.

Fixes #8598
Fixes #8640 (2nd commit)
Fixes #8934; Fixes #8891 (2nd & 3rd commit)

### CODE REVIEW

**Comment by rokerkony** [comment]
Hi guys,
after upgrade to CLI v1.6.3 (angular in v5.1.2) and removing node_modules and lock file I still have an error with `Node#moveTo was deprecated. Use Container#append.`

It seems that #8598 is not fixed yet :(

@clydin @filipesilva

**Comment by devoto13** [comment]
@rokerkony This PR is marked as `feat`, which means that it will be available only in CLI 1.7, not in patch releases of 1.6.

**Comment by rokerkony** [comment]
@devoto13 oh, I saw it in the release notes:
https://github.com/angular/angular-cli/releases

if it is as you say, I'll wait for that, thank you

**Comment by DzianisUkrainets** [comment]
@devoto13 @rokerkony could i use some angular/cli version with angular 5 without this issue?

**Comment by devoto13** [comment]
@DzianisUkrainets you can try [1.7.0-beta.2](https://github.com/angular/angular-cli/releases/tag/v1.7.0-beta.2).

**Pull request merged**
