### PR TITLE
feat(@schematics/angular): Allow generation of suffix-free files

### LINKED ISSUE #16811: Allow generation of suffix-free file and symbol names
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
 A clear and concise description of the problem or missing capability...

During style guide meetings we discussed that although recommended for most projects, suffixes in names of components, directives, and services in particular could be redundant for some projects.

We'd not change the official style guide recommendation, but we'd want to enable folks with advanced use cases to drop the suffixes when needed.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

This proposal is for a global CLI flag per project which disables the current default behavior. When this flag is enabled it'll not suffix any of the generated files, nor the declared symbols inside of them.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

Drop suffixes completely, which is bad for most projects.

### PR DESCRIPTION
**Pull request by sacgrover**
Allow generation of suffix-free file and symbol names.
Fix #16811

### CODE REVIEW

**Comment by sacgrover** [comment]
@alan-agius4 / @clydin  
Any advice on ci/circleci: build-bazel  FAIL?
ci/circleci: flake-jail is getting passed on local but not on github.

**Comment by dgp1130** [comment]
@mgechev, can you give this a quick look? We're not sure exactly what you were expecting from the design perspective here. Is this what you had in mind?

**Comment by mgechev** [comment]
We haven't discussed design yet. My suggestion would be to deprecate the `type` option (in v10) and replace it with a `suffix` one, which accepts an empty string. With @clydin we discussed few alternatives and this seems like the cleanest one.

If you see corner cases, we can draft a design document.

**Comment by sacgrover** [comment]
@mgechev / @dgp1130  Should I close this PR?

**Comment by clydin** [comment]
Something that can be fixed for the current version is the `type` option on several of the schematics.  When setting the `type` to an empty string the file names generated will contain an extra period (`.`).  Fixing this would act as an enabler for the proposed name change to `suffix` in a later version.

**Comment by dgp1130** [comment]
Spoke with @mgechev and @jelbourn, they both agree Minko's design of converting `type` to `suffix` and accepting an empty string is the way to go. So I think we have consensus on the design side.

I think we can follow @clydin's suggestion to allow an empty string `type` to and go from there.

**Comment by sacgrover** [comment]
@dgp1130 If nobody started working on it yet then I can do the mentioned changes for "type"

**Comment by dgp1130** [comment]
@sacgrover, I don't believe anyone else has started on this, so you're good to go!

**Comment by sacgrover** [comment]
@dgp1130  I have opened another PR for this. https://github.com/angular/angular-cli/pull/17040

**Comment by clydin** [comment]
Closing as the work for this is progressing in the above mentioned PR.

**Pull request closed without merging**
