### PR TITLE
docs: fix typo "jsob" to "json"

### PR DESCRIPTION
**Pull request by fredrik-lundin**
Fixes a typo in the documentation ("jsonb" to "json")

### CODE REVIEW

**Comment by fredrik-lundin** [comment]
I signed it!

**Comment by fredrik-lundin** [comment]
Travis is complaining on my commit message (i added the scope "stories" to the `docs` prefix, which it didn't like). How can I fix that now that I have already committed?

**Comment by Brocco** [comment]
Try this as your commit message:
>docs: fix typo "jsob" to "json"

**Comment by fredrik-lundin** [comment]
@brocco problem is how I change my already pushed commit message. Wouldn't it be enough if you just squash the commits in the or and keep the pr title as commit message?

**Comment by clydin** [comment]
To update you can do the following:
```
git commit --amend
git push --force
```

**Comment by fredrik-lundin** [comment]
@Brocco updated commit message!

**Pull request merged**
