### PR TITLE
bug(): Inject missing providers for routes

### PR DESCRIPTION
**Pull request by Brocco**
CORE_DIRECTIVES from angular2/core was missing when using ngIf & ngFor

### CODE REVIEW

**Comment by IgorMinar** [comment]
This is not necessary because CORE_DIRECTIVES are added to PLATFORM_DIRECTIVES which are available by default. am I missing anything?

**Comment by Brocco** [comment]
It was throwing an error when I was running ng-test locally on that branch, adding this fixed the tests running after adding routes

**Comment by filipesilva** [comment]
It's probably due to the need to configure default providers for tests according to platform. I believe the angular 2 changelog has some information about that in beta 2.

**Comment by Brocco** [comment]
@filipesilva I was able to find the docs you were referring to, but for now master is still @ beta 0

**Comment by filipesilva** [comment]
Perhaps we should recheck this after updating.

**Pull request closed without merging**
