### PR TITLE
support fingerprinting on builds

### PR DESCRIPTION
**Pull request by alejomendoza**

### CODE REVIEW

**Comment by grizzm0** [comment]
This is already overridden in prod using chunkhash instead of hash. What's the use case for hash in a dev build?

**Comment by alejomendoza** [comment]
We need to use fingerprinting for our `development` environment while not targeting production. Thanks.

**Comment by clydin** [comment]
ng build supports specifying different environment and target combinations.   Would this cover your use case?
Out of curiosity, what is the actual use case?

**Comment by filipesilva** [comment]
I won't merge this as is because it's a big breaking change. I understand you might need to add fingerprinting to dev though, and my suggestion is that you make it an option in the build/serve commands.

That way it can be passed down to the webpack config generator functions and you can choose for each env.

It should default to false for dev, and true for prod.

**Comment by hansl** [comment]
Closing this; there are already alternatives. You can do `ng serve --target=prod --env=dev` to get the same result. Also, you should not cache local files during development.

**Pull request closed without merging**
