### PR TITLE
feature(universal): add support for Angular Universal

### PR DESCRIPTION
**Pull request by devCrossNet**
add the possibility to scaffold a universal project with --universal.

This is the next attempt to bring in the --universal feature flag.
Related PR: https://github.com/angular/angular-cli/pull/2318

It is rebased onto the angular-cli/master branch and will update the angular-cli/universal branch.

### CODE REVIEW

**Comment by Brocco** [comment]
The CI build is failing for e2e tests.

**Comment by devCrossNet** [comment]
Can someone give me a hint why this is happening on appvayor:

> test-project@0.0.0 pree2e C:\Users\appveyor\AppData\Local\Temp\1\angular-cli-e2e-116918-1312-ufniqq\test-project
> webdriver-manager update
>
> C:\Users\appveyor\AppData\Local\Temp\1\angular-cli-e2e-116918-1312-ufniqq\test-project\node_modules\protractor\node_modules\webdriver-manager\built\lib\cmds\update.js:63
>     var gecko = options[Opt.GECKO].getBoolean();
>                                   ^

I tested this code on Windows 10 64-bit (Node 4/6), Linux Mint 17 (Node 4/6), OSX (Node 4/6) and it worked. 

Did I miss some dependency updates? I don't see it.

**Comment by Brocco** [comment]
You can ignore appveyor for now... there's a bug unrelated to our code... I believe when installing a web driver.

**Comment by filipesilva** [comment]
@devCrossNet context for that error: https://github.com/angular/webdriver-manager/issues/107. It's not something we can fix on our side, I think.

**Comment by devCrossNet** [comment]
So, the PR is ready then?

**Comment by chrillewoodz** [comment]
So the --univseral flag is available now in the CLI if I update?

**Comment by devCrossNet** [comment]
@chrillewoodz it has to be published to npm first. @Brocco do you know when it'll be available?

**Comment by webmutation** [comment]
Where is the seed of the universal project that gets generated?

**Comment by devCrossNet** [comment]
@webmutation here is the blueprint: https://github.com/angular/angular-cli/tree/universal/packages/angular-cli/blueprints/universal. It is based on https://github.com/angular/universal-starter

**Comment by kylecordes** [comment]
I realize that this optional support for universal is already merged; but I wonder if the project might consider an alternative model?

Maybe "all CLI projects are universal" instead of "there is a switch you can flip, but most people don't flip it, so will likely be issues that come up which are different for universal projects".

**Comment by devCrossNet** [comment]
@kylecordes there is a lot going on at the moment. this is the first try to figure out how people will use it and how it can be finally integrated to the CLI. We also have to figure out how to play well with the --mobile flag. Or if we should combine --mobile and --universal but with different build targets like `prerender`and `rerender`. But for now, the goal is to get the main CLI to have the 1.0.0 stable release.

**Comment by devCrossNet** [comment]
@webmutation this kind of mechanism would be part of the core functionality of the CLI. I don't know if the CLI team is planning something like this. My goal is, to integrate a possibility to use universal within the CLI, based on the best practices of the Universal team.

**Comment by goriunov** [comment]
Hello , thank you very much for your work , i found that angular universal 
     "angular2-platform-node": "~2.0.11",
    "angular2-universal": "~2.0.11",
    "angular2-universal-polyfills": "~2.0.11",
    "angular2-express-engine": "~2.0.11",
does not work well with 
    @angular/compiler": "^2.1.0", 

it show error 
  var SelectorMatcher = compiler_1.__compiler_private__.SelectorMatcher, CssSelector =   compiler_1.__compiler_private__.CssSelector;
TypeError: Cannot read property 'SelectorMatcher' of undefined

probably need to renew dependency

**Comment by devCrossNet** [comment]
@goriunov I disabled the aot support for now. But I want to update the dependencies anyways :-) maybe I can get it to work.

**Comment by elekzalan** [comment]
Hello. You have any idea, when the `--aot` flag is going to work? `angular2-universal` supports aot compilation since version **2.1.0-rc.1**. Thank you for your work on this awesome project.  :smiley:

**Comment by MarkPieszak** [comment]
@goriunov Please use 2.1.0 for Angular Core packages. 2.1.1 changed CssSelector & SelectorMatcher and I'm working on getting the fix in to Universal at the moment. You can follow https://github.com/angular/universal/pull/607 for when they'll be fixed so that we can use 2.1.1 with Universal.

**Comment by jaumard** [comment]
Is the `--universal` on the last npm version ? Because I didn't find anything on on docs about the flag and generate a new app with it doesn't embed universal :(

**Comment by kuldeepkeshwar** [comment]
@devCrossNet does it support AOT with universal `2.1.0-rc.1` ?

**Comment by devCrossNet** [comment]
@jaumard the universal-cli support is now a separate package on npm `universal-cli`

@kuldeepkeshwar no, it is still on universal version 2.0.11, waiting for version 2.1.1.

**Comment by chrillewoodz** [comment]
@devCrossNet Why is it a separate package?

**Comment by devCrossNet** [comment]
@chrillewoodz please read this comment: https://github.com/angular/angular-cli/issues/1050#issuecomment-259102059

**Comment by chrillewoodz** [comment]
@devCrossNet Ok makes sense. And you have to uninstall the angular-cli the same way as before, before installing the universal-cli?

**Comment by devCrossNet** [comment]
@chrillewoodz yes

**Comment by chrillewoodz** [comment]
Has the `universal-cli` been removed again? Can't seem to find it anymore.

**Comment by devCrossNet** [comment]
https://www.npmjs.com/package/universal-cli

https://github.com/devCrossNet/angular-cli

**Pull request merged**
