### PR TITLE
fix(loader): Temporarily stop removing decorators from source files

### LINKED ISSUE #2799: Custom decorators are stripped when using the AoT build flag
### OS?

Mac OSX Sierra
### Versions.

```
angular-cli: 1.0.0-beta.17
node: 6.2.1
os: darwin x64
```
### Repro steps.
1. Clone [@ngrx/example-app](https://github.com/ngrx/example-app)
2. Compile the project using the `--aot` flag
3. Check the compiled copy of [either effect service](https://github.com/ngrx/example-app/tree/master/src/app/effects)
4. Note that the `@Effect()` decorator from [@ngrx/effects](https://github.com/ngrx/effects) has been stripped from the classes
### The log given by the failure.

No errors are thrown

### PR DESCRIPTION
**Pull request by MikeRyan52**
Previous behavior was to remove all decorators from a source file when using the
@ngtools/webpack loader. This had the side effect of removing any third party
decorators, silently breaking apps when using the `aot` production flag. This skips 
the decorator removal process until a better way can be determined to remove 
Angular-specific decorators.

Closes #2799

### CODE REVIEW

**Comment by filipesilva** [comment]
@hansl can you weight in?

**Comment by hansl** [comment]
This is the wrong fix. The reason the decorators are removed is to allow for tree shaking. Otherwise you don't reduce the size by using AoT. The right fix is to use Tsickle (https://github.com/angular/tsickle), which moves decorators into a static property which can then be removed safely (without losing runtime information).

The right fix is to use Tsickle or the compiler-cli to remove the annotations (by moving them into static properties) and keep other decorators around.

This will not be merged in, but a fix for this issue is coming before final.

**Comment by SaltyDH** [comment]
Might not be the right approach long-term, but essentially I now have to go and learn what Tsickle is and how to add it to my existing pipeline just to get my existing build ecosystem back online. If a proper fix for this issue is coming before final, why can't we actually simplify this problem in the interim rather than introducing additional moving parts?

A configuration switch would really suffice here with a disclaimer warning of the impacts.

**Comment by rthewhite** [comment]
@hansl is there an ETA for the fix you are talking about? 

Because from what i understand everything will still work when not removing the decorators but tree shaking is less efficient? Then this temporarily solution at least gives people that are using decorators AOT, something which seems way more valuable then tree shaking to me? The size of the bundle will probably always be smaller with AOT then without? Not to mention the huge performance increase in runtime...

**Comment by hansl** [comment]
This is something we're talking about daily here on the team. It's part of a greater effort.

**Pull request closed without merging**
