### PR TITLE
Data path  must NOT have additional properties(skipTests)

### LINKED ISSUE #20811: Data path "" must NOT have additional properties(skipTests). Angular 12.0.0
# 🐞 Bug report

### Command (mark with an `x`)

- [x] generate

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 11 ....

### Description

 A clear and concise description of the problem...
I initiated a new angular project in which I had `--skip-tests` flag for the application on running the module generate command I got this error

## 🔬 Minimal Reproduction

generate new project `ng new appName --skip-tests`
generate new module `ng generate module shared`

## 🔥 Exception or Error
```
Schematic input does not validate against the Schema: {"skipTests":true,"name":"shared","project":"search"}
Errors:

  Data path "" must NOT have additional properties(skipTests).

```

</code></pre>

## 🌍 Your Environment

```
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.0
Node: 14.15.1
Package Manager: npm 6.14.8
OS: linux x64

Angular: 12.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0
@angular-devkit/build-angular   12.0.0
@angular-devkit/core            12.0.0
@angular-devkit/schematics      12.0.0
@schematics/angular             12.0.0
rxjs                            6.6.7
typescript                      4.2.4

```
</code></pre>

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by Patil2099**
Fixes #20811

### CODE REVIEW

**Review by alan-agius4 — CHANGES_REQUESTED** [review]
Thanks for this. 

Can you please amend the commit message as per our guidelines highlighted in https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-a-pull-request-pr

```
fix(@schematics/angular): don't add `skipTest` option to module schematic options

Closes ##20811
```

**Comment by Patil2099** [comment]
Sure @alan-agius4

**Comment by Patil2099** [comment]
The commit message has been changed now @alan-agius4 .

**Review by alan-agius4 — APPROVED** [review]
It looks like now CI is failing due to formating.

Kindly run 
```
  yarn ng-dev format files packages/schematics/angular/application/index.ts
```

Commit and squash and push again, thanks.

**Comment by Patil2099** [comment]
I think this is complete now @alan-agius4. Please let me know if you want any other changes Thanks.

**Review by alan-agius4 — APPROVED** [review]
Thanks for your contribution. LGTM

**Pull request merged**
