### PR TITLE
add 'include' option for tsconfig.json

### PR DESCRIPTION
**Pull request by jcde**

### CODE REVIEW

**Comment by jcde** [comment]
I signed it!

**Comment by filipesilva** [comment]
@jcde what is the problem you are trying to solve with this change?

**Comment by jcde** [comment]
my application has two versions with two different app.module.ts located in folders src/version1 and src/version2 

there is a shared NgModule that is common for both of them and is located in folder /src/app

tsconfig.json includes the shared folder
"include": [
    "src/app"
]

when I am compiling application by AotPlugin it would be nice to set 'include' option for tsconfig.json with values 'src/version1' or 'src/version2'

**Comment by hansl** [comment]
We don't support the old plugin anymore.

**Pull request closed without merging**
