### PR TITLE
fix(polyfills): move polyfills to own entry point

### LINKED ISSUE #2752: change detection behaving differently with cli build
### OS?

> Windows 7
> ### Versions.
> 
> angular-cli: 1.0.0-beta.17
> node: 6.2.1
> os: win32 x64

@angular/common: 2.1.0
@angular/compiler: 2.1.0
@angular/core: 2.1.0
@angular/forms: 2.1.0
@angular/http: 2.1.0
@angular/platform-browser: 2.1.0
@angular/platform-browser-dynamic: 2.1.0
@angular/router: 3.1.0
core-js: ^2.4.1
rxjs: 5.0.0-beta.12
ts-helpers: ^1.1.1
zone.js: ^0.6.25
### Repro steps.

> When running the app from the angular cli build, change detection does not function as expected. 

Unfortunately, our app and the situations in which this issue occurs are prohibitively complex to provide a simple way to reproduce the problem. Essentially, the change detector is not fired in all situations where we would expect it to. 

Detailed explanation of the issue can be found here http://stackoverflow.com/questions/40047415/angular-2-change-detection-behaves-differently-with-cli-webpack
### The log given by the failure.

No error is thrown, change detection simply fails to run when expected.

### LINKED ISSUE #3309: Getting 'Map' is undefined error.
### OS?
```
Windows 7 (running on a VM)
```

### Versions.
```
angular-cli: 1.0.0-beta.20-4
node: 6.6.0
os: darwin x64
```

### Repro steps.

I am trying to use the custom elements v1 polyfill (custom-elements.min.js) in the angular-cli.json by using the following pattern:

```
      "scripts": [
        "../node_modules/mutationobserver-shim/dist/mutationobserver.min.js",
        "../node_modules/@webcomponents/custom-elements/custom-elements.min.js",
      ],
```
This works across all browsers except IE10. In the console, it says:

```
SCRIPT5009: 'Map' is undefined 
```

### Mention any other details that might be useful.

The polyfill works fine when loaded through `script` tag in a non angular-cli static website. However, in angular-cli generated projects, it logs an error when I try to use it in the scripts section of angular-cli.json. The error will be gone and the polyfill will start working fine if I insert es6-shim in the script: 

```
      "scripts": [
        "../node_modules/es6-shim/es6-shim.min.js",
        "../node_modules/mutationobserver-shim/dist/mutationobserver.min.js",
        "../node_modules/@webcomponents/custom-elements/custom-elements.min.js"
      ],
```

However, I don't want to use `es6-shim` because there is `core-js/es6/map` imported in the `polyfills.ts` file. Also, it does work fine with no es6 shims so for the polyfill, I believe I don't need either of them. 

The log error was pointing at the polyfill (https://github.com/webcomponents/custom-elements/blob/master/custom-elements.min.js). 

screenshot 2016-11-28 23 56 57

I would like to know why it's getting this error on only IE10.

Thank you!

### LINKED ISSUE #4140: Tracking: Polyfills
Where do we put them?

### PR DESCRIPTION
**Pull request by filipesilva**
Polyfills found in `polyfills.ts` would not be available for scripts due to being loaded in the main bundle only. 

This PR loads polyfills as a separate entry point, before everything else.

Extra documentation also added to `polyfills.ts`.

Fix #2752
Fix #3309
Fix #4140

### CODE REVIEW

**Comment by cebor** [comment]
Webpack also accepts modules/package names as entry option.

```
entry: {
      polyfills: [
        'core-js/es6',
        'core-js/es7/reflect',
        'zone.js/dist/zone'
],
```

Would not this be a cleaner solution?

**Comment by filipesilva** [comment]
@cebor it's true that webpack accepts that, but the purpose of the `scripts` array is to provide feature parity with script tags. Script tags don't accept package names. I suppose the feature could be enhanced but it doesn't seem too important.

**Comment by hansl** [comment]
(cf. https://github.com/angular/angular-cli/pull/3999)

While you’re at refactoring the polyfills and how they’re included, could you include the `long stack trace` when using debug? Would fix #2233.

**Comment by filipesilva** [comment]
@hansl see https://github.com/angular/angular-cli/issues/2233#issuecomment-274149408, adding the long stack trace is not the solution to that issue.

**Comment by filipesilva** [comment]
Also need to add a lot of comments to polyfills to show opt-in ones for each browser.

**Comment by hansl** [comment]
LGTM, Thanks!

**Pull request merged**
