### PR TITLE
added @angular/forms in system-config.ts  #1199

### PR DESCRIPTION
**Pull request by maliq**
Fix angular/form nor found, issue #1199

### CODE REVIEW

**Comment by maliq** [comment]
I signed it!

**Comment by hansl** [comment]
Can you add an upgrade to forms `0.2.0` in this PR?

**Comment by maliq** [comment]
done.

**Comment by hansl** [comment]
Seems like the Windows tests are timeout and unrelated to this, and Travis is passing. So I'll merge this. LGTM. Thanks!

**Pull request merged**
