### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by metric152**
Added Http to package.json

### CODE REVIEW

**Comment by zackarychapple** [comment]
I don't believe adding HTTP is necessary. Is there a reason you feel it should be in there by default?

**Comment by metric152** [comment]
I think a lot of people will be using the command line tool to build webapps that make rest calls. Be default this tool can't do that and there is a lot to look through before you can understand what to put where before that works properly.

**Comment by Brocco** [comment]
@metric152 you mention

>there is a lot to look through before you can understand what to put where before that works properly

But based upon your PR, the only thing they'd have to do is `npm install @angular/http --save` so I am failing to see the savings this offers. While there are a lot of applications that will indeed use http (including most of mine) I don't see the value of just adding it to package.json (especially without injecting in the corresponding providers).

**Comment by intellix** [comment]
Could do a wizard which asks which packages you'd like to include which automatically adds the providers. generator-gulp-angular is brilliant in this regard as you get to pick CSS, HTML, JS preprocessors along with CSS framework etc

**Comment by metric152** [comment]
@Brocco 
If you're familiar with npm it's very easy to add it to the project. If you haven't it's another hurdle to overcome. I've mostly used bower for front end libraries. 

Having the http lib added would just be one less step someone new would have to deal with.

**Comment by aciccarello** [comment]
It sounds like a documentation problem to me

**Comment by metric152** [comment]
It feels like a weird addition to the front page readme to add "If you need to make REST requests then use the following npm command.." instead of it just working like angular 1 does.

**Comment by hansl** [comment]
I'm going to commit https://github.com/angular/angular-cli/pull/635 because it's older than this one and in alphabetical order.  I kinda agree with `http` being part of the base install, but it's a slippery slope; we're going to have a lot of those packages in the angular org and we don't want to include them all in the packages (since most people wouldn't care about them).

IMO http doesn't fit that description for now. We might revisit later on.

**Pull request closed without merging**
