### PR TITLE
docs: readme

### PR DESCRIPTION
**Pull request by sashaphmn**
Made some corrections in the documentation

## PR Checklist

Please check to confirm your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular-cli/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by alan-agius4** [comment]
@sashaphmn, as mentioned in the previous PR you need to generate the readme by using `yarn admin templates`

**Comment by sashaphmn** [comment]
Please tell me how to do it, I don't fully understand

**Comment by alan-agius4** [comment]
@sashaphmn I did it for you.

**Review by alan-agius4 — APPROVED** [review]
LGTM

**Comment by sashaphmn** [comment]
> as mentioned in the previous PR you need to generate the readme by using `yarn admin templates`

Thank you

**Comment by alan-agius4** [comment]
The changes were merged into the following branches: main, 19.0.x

**Pull request merged**
