### PR TITLE
chore(templates): update constructor in templates

### PR DESCRIPTION
**Pull request by neolwc**
[Try to match `ngOnInit`](https://github.com/angular/angular-cli/blob/master/packages/angular-cli/blueprints/component/files/__path__/__name__.component.ts#L20)
https://github.com/angular/angular-cli/pull/3481/files#diff-6ead890c6989056b273279a71cc65e28L20

### CODE REVIEW

**Comment by hansl** [comment]
Constructors are different than functions, and they're treated differently by the style guide.

**Comment by neolwc** [comment]
Maybe there shouldn't be a space between the braces?
Or is that intended as well? @hansl

**Comment by hansl** [comment]
Basically. We work with the official angular styleguide.

**Comment by neolwc** [comment]
Then could the `TSLint` reflect this guide?

**Comment by hansl** [comment]
It does up to what rules are available. We don't implement custom rules.

**Comment by neolwc** [comment]
Could you please send me a link showing this style guide rule specifically? Couldn't find one.

**Comment by hansl** [comment]
https://angular.io/styleguide#!#03-01

**Pull request closed without merging**
