### PR TITLE
refactor(@angular-devkit/build-angular): mute internal reporters

### PR DESCRIPTION
**Pull request by corinna000**
when other reporters are configured

internal Karma reporters should suppress output when user-defined
reporters are configured to prevent extrananeous error reporting for
failed tests (from ng test)

### CODE REVIEW

**Comment by corinna000** [comment]
Not sure how to fix the CLA issue since I used a different gmail account for the commit than I used to sign the CLA. Any tips?

**Comment by clydin** [comment]
If you drop the first commit and squash the other two, the CLA check should be fine.

**Comment by shairez** [comment]
Funny, that's the same PR as mine from the past - 
https://github.com/angular/angular-cli/pull/9529

I wonder what caused the regression there...

**Comment by corinna000** [comment]
Sorry, @shairez ! Good developers copy, great developers steal. =)

**Comment by shairez** [comment]
LOL 😄 

Pay attention though, that in these lines:
```
function muteDuplicateReporterLogging(context: any, config: any) {
  context.writeCommonMsg = function () { };
  const reporterName = '@angular/cli';
  const hasTrailingReporters = config.reporters.slice(-1).pop() !== reporterName;
   if (hasTrailingReporters) {
    context.writeCommonMsg = function () { };
  }
}
```

The first `context.writeCommonMsg = function () { };` makes the rest pretty much useless.

It was meant to be "if the last reporter is the angular CLI one, remove the duplication"

So @filipesilva  make sure you test it thoroughly and if it works with several different reporters, then you could remove the lines followed by `context.writeCommonMsg = function () { };`

If not, remove the first statement and change the reporter's name if it has changed.

**Pull request merged**
