### PR TITLE
add buffer-shims to dependencies: angular/angular-cli#3131

### PR DESCRIPTION
**Pull request by watashiSHUN**
simply run "npm install --save buffer-shims"

### CODE REVIEW

**Comment by watashiSHUN** [comment]
I signed it!

**Comment by hansl** [comment]
Why do we need this?

**Comment by hansl** [comment]
Closing this. Please come back with a reason this PR is needed (and ping me), and I'll reopen.

**Comment by Davy-F** [comment]
Isn't it required for AOT?

I'm trying to use angular-cli with aot compilation and getting `Error: Cannot find module 'buffer-shims'`

**Pull request closed without merging**
