### PR TITLE
docs(@schematics/angular): fix typo in web worker schematics ("service worker" --> "web worker")

### PR DESCRIPTION
**Pull request by gkalpak**
☝️

### CODE REVIEW

**Comment by gkalpak** [comment]
BTW, is this correct:

https://github.com/angular/angular-cli/blob/ab3dcdd04fa23b969bc0cef886cd17283bd5ce9f/packages/schematics/angular/web-worker/schema.json#L6

It feels wrong (at least I don't understand what it means), but I am not sure what would be the correct description.
Maybe replace `run` with `generate`?

**Comment by alan-agius4** [comment]
@gkalpak, I don’t think that is correct it should be something along `Creates a new generic web worker definition in the given or default project."`

**Comment by alan-agius4** [comment]
Feel free to fix that in this PR or a separate one 😊

**Comment by gkalpak** [comment]
Fixed.

**Comment by alan-agius4** [comment]
@gkalpak, can you please rebase to make this green? thanks

**Pull request merged**
