### PR TITLE
Fix a compilation error that occurs when the "paths" option is not set but "baseUrl" is

### LINKED ISSUE #9671: Module resolution fails in v1.7.0 when "baseUrl" is set in tsconfig
### Versions
```
Angular CLI: 1.7.0
Node: 8.9.4
OS: linux x64
Angular: 5.2.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.0
@angular-devkit/build-optimizer: 0.3.1
@angular-devkit/core: 0.3.1
@angular-devkit/schematics: 0.3.1
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.0
@schematics/angular: 0.3.1
@schematics/package-update: 0.3.1
typescript: 2.6.2
webpack: 3.11.0
```

### Repro steps
* Run `git clone https://github.com/mprahl/angular-cli-9671-reproducer.git`
* Run `cd angular-cli-9671-reproducer && npm install && ng serve`

### Observed behavior
```
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'reproducer/hello/hello.component' in '/path/to/angular-cli-9671-reproducer/src/app'
```

### Desired behavior
The imports should work as they did in v1.6.x.

### Mention any other details that might be useful (optional)
The following commit broke this functionality: https://github.com/angular/angular-cli/commit/29aa274b6721c1399ca2baca18565b21254fb3f0

Running angular-cli with commit https://github.com/angular/angular-cli/commit/29aa274b6721c1399ca2baca18565b21254fb3f0 reverted works as expected.

### PR DESCRIPTION
**Pull request by mprahl**
Fixes #9671

### CODE REVIEW

**Comment by mprahl** [comment]
I signed it!

**Comment by clydin** [comment]
Thank you for the contribution.  However, while this may fix the problem observed within the referenced issue, this will break module resolution in the general case.  The `ts.resolveModuleName` method is unfortunately too course-grained to fully support module resolution in all cases.

**Comment by mprahl** [comment]
@clydin what cases would cause this to break? This works on a new app generated from angular-cli and the app that wouldn't compile with v1.7.0.

**Comment by clydin** [comment]
For a package, `ts.resolveModuleName` will resolve to the `typings`/`types` field of the `package.json`.  While appropriate for transpiling typescript, this is not the case for bundling the actual code for the package.  The location of the actual code can potentially be found at multiple locations depending on the configuration (e.g., fields such as `main`, `browser, `module`, or `es2015`).  As the type definition file can be located at an arbitrary location within the package;  there's no clean method to determine the appropriate source code file from only the path of the type definition file returned.  Factor in deep imports, as well as the no-typings fallback case of using a root `index.ts`/`index.js`, and `ts.resolveModuleName` is not useable for general resolution.  If the intrinsics behind the method were publicly available, it would potentially possible.
Longer-term, the method's use will most likely be removed.

**Pull request closed without merging**
