### PR TITLE
feat(serve): add --hmr flag

### PR DESCRIPTION
**Pull request by jschwarty**
Add webpack-dev-server hot module replacement support when the --hmr flag is true.

### CODE REVIEW

**Comment by hansl** [comment]
Could you show a warning when this option is used with a link to some HMR documentation? The problem with HMR (and the reason this hasn't been done so far) is that not all angular applications are compatible, and there's no way to know. So we should at least warn the user that their app might break if they don't know what they're doing.

**Comment by hansl** [comment]
"Some documentation" in this case might be a wiki on our side and/or an external tutorial on HMR + ng2

**Comment by jschwarty** [comment]
Yes, I can add that.

**Comment by jschwarty** [comment]
I added a notice message to the console output when running `ng serve --hmr` that informs the user that HMR is on for the dev server but requires additional app code to take advantage of it. I included a link to the [webpack HMR docs](https://webpack.github.io/docs/hot-module-replacement.html) as that describes how the opt-in for HMR works, but I don't know which reliable resource to link to that shows how to do hmr with angular (probably best to have that on the cli wiki).

Although, it may be out of the scope of the cli to be responsible for guiding users into how to do hmr with angular since hmr for webpack dev server is opt-in (just enabling it does not activate your app code to use it). Could be looked at like using the `--host` or `--port` flags...cli is just providing the ability to leverage configuring the underlying dev server and what you do with it from there is up to you.

**Comment by beeman** [comment]
I'm happy to write some docs that help setting up HMR in a project built with the cli, it's just that I did not get it working yet.

I've looked at how [angular2-hmr](https://github.com/AngularClass/angular2-hmr) implements this, though their structure is quite different from what the cli generates.

@jschwarty if you could maybe provide a basic cli-generated project with HMR enabled, I'm happy to describe how to build it from a fresh `ng init` generated project.

**Comment by jschwarty** [comment]
I have a cli generated project that is using angular2-hmr and this new cli
update. I can put that together into a sample peoject that you can use for
that write up. Will let you know when I have that done...

**Comment by born2net** [comment]
would be sooooo awesome if we can have an example of ng-cli with HMR
TX

Sean

**Comment by jschwarty** [comment]
@beeman 
https://github.com/jschwarty/angularcli-hmr-example
Uses @angularclass/hmr package.
Has documentation in the readme.md about HMR stuff.

**Comment by hansl** [comment]
@jschwarty re
> cli is just providing the ability to leverage configuring the underlying dev server and what you do with it from there is up to you.

Agreed, but a lot of people will blame us if they use HMR wrongly in a CLI generated project. I want to avoid issues.

**Comment by born2net** [comment]
tx!!!!

**Comment by hansl** [comment]
LGTM. Thanks.

**Comment by born2net** [comment]
for me hmr was the killer app ng-cli needed... so now really no need for using webpack directly!!!!

**Comment by jschwarty** [comment]
@hansl re
> Agreed, but a lot of people will blame us if they use HMR wrongly in a CLI generated project. I want to avoid issues.

Cool, I agree with avoiding those issues! So where would be the best place to contribute some docs to the cli to help explain HMR and possible usages with a cli project?

**Comment by hansl** [comment]
The wiki would be the right place, but I’m not sure if you have access. A markdown file added to `docs/wiki/` would be nice. We have a plan somewhere to move the wiki to that directory and update it when that directory changes.

**Comment by beeman** [comment]
@jschwarty thanks for the project. I will write down the steps to get there from a fresh project.

**Comment by born2net** [comment]
@beeman tx please update here when done so I can checkout

**Comment by beeman** [comment]
I created a tutorial that covers setting up HMR with a new app scaffold with angular-cli.

https://github.com/beeman/angular-hmr/wiki/HMR-with-Angular-CLI

@born2net please let me know if you have any comments. Feel free to post them here, or create an issue on that repo.

@hansl please let me know if you like to see changes in order to get it in the wiki here.

**Comment by born2net** [comment]
will do, tx!!!

**Comment by born2net** [comment]
I recommend putting these docs on the HMR project page on the project front page on GitHub as this is essential.
here https://github.com/jschwarty/angularcli-hmr-example

**Comment by jwuliger** [comment]
Great stuff!!

**Comment by beeman** [comment]
@born2net decided to move the tutorial here: https://medium.com/@beeman/1b0d13b80130 , feel free to ping me for any comments.

**Comment by born2net** [comment]
great tx!

**Comment by born2net** [comment]
maybe add a link to https://github.com/jschwarty/angularcli-hmr-example
as well in blog

**Comment by beeman** [comment]
@born2net good tip. Though I've linked to the example built using this tutorials so I can keep it updated and reference the commits.

**Comment by born2net** [comment]
ok tx!

**Comment by born2net** [comment]
In latest angular-cli: 1.0.0-beta.22 getting exceptions....

```
** NG Live Development Server is running on http://localhost:4200. **
  0% compilingError encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in C:/msweb/msbarcode/src/app/app.module.ts, resolving symbol AppModule in C:/msweb/msbarcode/src/app/app.module.ts
Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in C:/msweb/msbarcode/src/app/app.module.ts, resolving symbol AppModule in C:/msweb/msbarcode/src/app/app.module.ts
    at simplifyInContext (C:\Users\root\AppData\Roaming\npm\node_modules\angular-cli\node_modules\@angular\compiler-cli\src\static_reflector.js:475:23)
    at StaticReflector.simplify (C:\Users\root\AppData\Roaming\npm\node_modules\angular-cli\node_modules\@angular\compiler-cli\src\static_reflector.js:478:22)
    at StaticReflector.annotations (C:\Users\root\AppData\Roaming\npm\node_modules\angular-cli\node_modules\@angular\compiler-cli\src\static_reflector.js:60:36)
    at NgModuleResolver.resolve (C:\Users\root\AppData\Roaming\npm\node_modules\angular-cli\node_modules\@angular\compiler\bundles\compiler.umd.js:14261:46)
    at CompileMetadataResolver._loadNgModuleMetadata (C:\Users\root\AppData\Roaming\npm\node_modules\angular-cli\node_modules\@angular\compiler\bundles\compiler.umd.js:14646:45)
```

The project is pretty simple, posted here:
https://github.com/born2net/msbarcode

any ideas?

tx

Sean

**Comment by mattdistefano** [comment]
@jschwarty Do you have an example of this working w/ lazy-loaded routes?

**Comment by fabien0102** [comment]
@jschwarty  I found this example https://github.com/jschwarty/angularcli-hmr-example but a little doc could be useful 😄

**Comment by beeman** [comment]
@fabien0102 there's some details in the post I put up on Medium: https://medium.com/@beeman/tutorial-enable-hrm-in-angular-cli-apps-1b0d13b80130 , please let me know if anything is unclear.

**Comment by fabien0102** [comment]
@beeman Great! I think you can add this link into angular-cli docs 😉 (It’s always better if all information are consolidate in one place)

**Comment by montella1507** [comment]
@beeman  are there any additional steps to "keep" HMR working? It worked like a charm in starter solution. 

But now it works correctly only for components from 1 module. For another it has to reload entire page with error:

https://github.com/AngularClass/angular2-hmr/issues/42#issue-195968966

The topic / documentation with  common pitfalls in usage of HMR would be very appreciated by the community. Good work anyway!

**Comment by rxjs-space** [comment]
@jschwarty , @hansl , Hi, could we have a blueprint for a hmr starter like in the [example](https://github.com/jschwarty/angularcli-hmr-example)? So, we can do `ng new xyz --hmr` and have the hmr setup already.

**Comment by landon-morin** [comment]
@beeman Is there a follow up tutorial on how to get HMR working with lazy loaded modules? I was able to follow your original tutorial and was able to get HMR working perfectly for anything that isn't lazy loaded. Unfortunately my project consists of a large amount of lazy loaded modules.

Is there anything I can do to fix this? Thanks!

**Comment by rob-balfre** [comment]
@rxjs-space I've opened a pull request with this new feature today.  https://github.com/angular/angular-cli/pull/5396

**Comment by beeman** [comment]
@landon-morin I have not tried it with lazy loaded modules yet. This is the issue to track it https://github.com/AngularClass/angular2-hmr/issues/42

**Comment by intellix** [comment]
I'm guessing since this was merged, we can create a separate entrypoint so we don't need HMR in production builds: https://github.com/angular/angular-cli/issues/3940

**Pull request merged**
