### PR TITLE
Make "app" point configurable in component generation

### PR DESCRIPTION
**Pull request by dhcdata**
angular-cli.json allows flexibility for how project structure is defined.  This PR allows for the "app" to be configurable. Consider the following tree structure:

```
├── .
├── angular-cli.json
├── src/ (default but configurable with "root" value)
│   ├── app/ (default)
│   ├── assets
│   ├── environments
│   ├── myCustomApp/ (configurable by added "app" value)
│   ├── index.html
│   ├── [...]
├── [...]
```

### CODE REVIEW

**Comment by dhcdata** [comment]
I signed it

**Comment by baruchvlz** [comment]
You're trying to make `src/app` be `src/{ngConfig.app[0].app` ?

**Comment by dhcdata** [comment]
Correct. This would make the "app" point configurable. When attempting to build a generic module in parallel with an specific application, this type of structure makes it easier to keep them separate.

**Comment by filipesilva** [comment]
Superseded by https://github.com/angular/angular-cli/pull/4610 I think.

**Comment by dopry** [comment]
@filipesilva I do not think it is infact superceded by #4610, I think they're the similar and parts of a whole.

**Comment by dhcdata** [comment]
`ng new` command creates the project with `src/app`.  Once that's done and #4610 is merged, identifying the "mount-ish" point is irrelevant.

Adding a flag for `ng new` might be beneficial but is outside the scope of where this PR went.

**Pull request closed without merging**
