### PR TITLE
feat(generate): add directives

### LINKED ISSUE #148: Ability to generate directives
The CLI currently doesn't have a way to generate directives, just components.

### PR DESCRIPTION
**Pull request by cironunes**
Closes #148

### CODE REVIEW

**Comment by hansl** [comment]
LGTM.

**Comment by Brocco** [comment]
I'd suggest adding some information about the new generation in the readme as part of this PR

**Comment by jkuri** [comment]
Yes, readme should be included.

**Comment by cironunes** [comment]
Thanks for the feedback guys. I took the opportunity to improve the whole scaffolding session on the README. Please take a look and let me know if we can merge this in.

**Comment by jkuri** [comment]
:+1: for aliases.

**Comment by filipesilva** [comment]
lgtm :+1:

**Pull request merged**
