### PR TITLE
feat(@angular/cli): adding skip e2e test option

### PR DESCRIPTION
**Pull request by sumitarora**
Adds another option to skip e2e tests
```
--skip-e2e (Boolean) (Default: false) Skip creating e2e files.
```
Fixes: https://github.com/angular/angular-cli/issues/5724

### CODE REVIEW

**Comment by ammar91** [comment]
This not seems be working in 1.2.0, I ran

`ng new my-app --skip-e2e --skip-tests -d`

It still generate e2e directory and protractor config

**Comment by LeLocTai** [comment]
> This not seems be working in 1.2.0, I ran
> `ng new my-app --skip-e2e --skip-tests -d`

For the record it should be `--skip-e2e true`.  Pretty weird if you ask me.

**Comment by kiewic** [comment]
I think this feature was reverted on 7a6cb215

**Comment by rreynier** [comment]
Why was this reverted? Not everyone needs this scaffolded :(

**Comment by sinanaltaii** [comment]
i dont want to scaffold e2e files, just want to scaffold the app, i dont want any test related files or frameworks scaffolded upon creation of new app

**Pull request merged**
