### PR TITLE
docs: update hmr documentation

### LINKED ISSUE #11028: HMR not working according to the documentation
### Versions

```
Angular CLI: 6.0.5
Node: 8.9.4
OS: win32 x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.5
@angular-devkit/build-angular     0.6.5
@angular-devkit/build-optimizer   0.6.5
@angular-devkit/core              0.6.5
@angular-devkit/schematics        0.6.5
@angular/cli                      6.0.5
@ngtools/webpack                  6.0.5
@schematics/angular               0.6.5
@schematics/update                0.6.5
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3

```

### Repro steps

* create new application with cli
* follow the steps on https://github.com/angular/angular-cli/wiki/stories-configure-hmr
* one of the steps instructs to edit `angular.json` `serve` section according to this:

       "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "hmrWarning": false,
            "browserTarget": "hmrtest:build"
          },
          "configurations": {
            "hmr": {
                "hmr": true,
                "fileReplacements": [
                  {
                    "replace": "src/environments/environment.ts",
                    "with": "src/environments/environment.hmr.ts"
                  }
                ]
              },
            "production": {
              "browserTarget": "hmrtest:build:production"
            }
          }
        },
* when I do that, there's a lint error telling me that the `fileReplacements` property is not allowed
* run the project with `ng serve --configuration hmr`

### Observed behavior
* project won't compile with the following error: 

> Schema validation failed with the following errors:
>   Data path "" should NOT have additional properties(fileReplacements).
> 

### Desired behavior
Project compiling and HMR working

### Mention any other details that might be useful (optional)
I managed to make it compile using the `angular.json` from #10668, this way the project runs, and the console prints:

> NOTICE: Hot Module Replacement (HMR) is enabled for the dev server.

Also, the in the  browser console I can see the message 

> [HMR] Waiting for update signal from WDS...

But when I make any change in the project, the page is fully reloaded like it does without HMR.

### PR DESCRIPTION
**Pull request by bniedermeyer**
Update documentation for the hmr story to show proper configurations
in angular.json and src/tsconfig.app.json.

Closes #11028, #10668, #10663, #11093, #11121

### CODE REVIEW

**Comment by bniedermeyer** [comment]
Looks like Travis ran into issues installing npm during a couple jobs. 
```
Updating nvm
nvm.install
3.54s$ nvm install 8
Downloading and installing node v8.11.2...
Downloading https://nodejs.org/dist/v8.11.2/node-v8.11.2-linux-x64.tar.xz...
Computing checksum with sha256sum
Checksums matched!
Now using node v8.11.2 (npm v5.6.0)
cache.1
Setting up build cache
$ export CASHER_DIR=$HOME/.casher
0.06s$ Installing caching utilities
0.00s
70.73sattempting to download cache archive
fetching PR.11029/cache-linux-trusty-7b1199fb7ff31509408e073597f37e53d115dda658128b74b8eb14a767d8cf9f--node-8.tgz
fetching PR.11029/cache--node-8.tgz
fetching master/cache-linux-trusty-7b1199fb7ff31509408e073597f37e53d115dda658128b74b8eb14a767d8cf9f--node-8.tgz
found cache
0.00s
7.44sadding /home/travis/build/angular/angular-cli/node_modules to cache
creating directory /home/travis/build/angular/angular-cli/node_modules
$ node --version
v8.11.2
$ npm --version
5.6.0
$ nvm --version
0.33.11
70.96s$ npm install -g npm@5.8.0
npm ERR! code E429
npm ERR! 429 Too Many Requests: npm@5.8.0
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-05-26T16_04_23_799Z-debug.log
The command "npm install -g npm@5.8.0" failed and exited with 1 during .
```

I'm not seeing a way for me to force the job to run again. What's the best course of action here?

**Comment by robert-claypool** [comment]
Also #11121 🤣

**Comment by bniedermeyer** [comment]
@clydin or @Brocco, can you please take a look at the failing test when you get a second? This PR is just doc updates - it shouldn't touch anything that would be impacting the e2e test that is failing.

**Comment by robertbaker** [comment]
@bniedermeyer this PR currently contains invalid json. I submitted a PR to your branch to fix it.

**Comment by bniedermeyer** [comment]
This is currently pending #11144

**Comment by robertbaker** [comment]
I'm ok with my commits being merged!

**Comment by filipesilva** [comment]
Heya, thank you for updating this guide! I'll merge it now and it should be published next time we publish the wiki (probably for 6.1 final).

**Comment by FinalDes** [comment]
how to fix 
[ts] Element implicitly has an 'any' type because type 'NodeModule' has no index signature. bug

**Pull request merged**
