### PR TITLE
style(@angular/cli): update ascii art to Angular CLI

### PR DESCRIPTION
**Pull request by beeman**
Updates the ASCII art from angular-cli to Angular CLI.

Used figlet `big` from this site http://www.askapache.com/online-tools/figlet-ascii/

```
❯ ng -v

                            _               _____ _      _____
    /\                     | |             / ____| |    |_   _|
   /  \   _ __   __ _ _   _| | __ _ _ __  | |    | |      | |
  / /\ \ | '_ \ / _` | | | | |/ _` | '__| | |    | |      | |
 / ____ \| | | | (_| | |_| | | (_| | |    | |____| |____ _| |_
/_/    \_\_| |_|\__, |\__,_|_|\__,_|_|     \_____|______|_____|
                 __/ |
                |___/
@angular/cli: local (v1.0.0-beta.32.3, branch: update-ascii-art)
```
```
commit 85804c88748b1815034f6f39d743b33eb7684167
Author: Bram Borggreve <borggreve@gmail.com>
Date:   Fri Feb 17 12:32:10 2017 -0500

    chore: initial commit from @angular/cli

                                _               _____ _      _____
        /\                     | |             / ____| |    |_   _|
       /  \   _ __   __ _ _   _| | __ _ _ __  | |    | |      | |
      / /\ \ | '_ \ / _` | | | | |/ _` | '__| | |    | |      | |
     / ____ \| | | | (_| | |_| | | (_| | |    | |____| |____ _| |_
    /_/    \_\_| |_|\__, |\__,_|_|\__,_|_|     \_____|______|_____|
                     __/ |
                    |___/
```

*Updated*

```
❯ ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / _ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: local (v1.0.0-beta.32.3, branch: update-ascii-art)
```

```
commit bed2e59f0333f3eae322685ed84f0cb330acdb97
Author: Bram Borggreve <borggreve@gmail.com>
Date:   Fri Feb 17 14:28:59 2017 -0500

    chore: initial commit from @angular/cli

        _                      _                 ____ _     ___
       / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
      / _ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
     / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
    /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                   |___/
```

### CODE REVIEW

**Comment by hansl** [comment]
Is it possible to add the spacing?  I'm also asking about this PR with our branding team.

**Comment by hansl** [comment]
Just got OK from branding, but would still like to see a space between `Angular` and `CLI`. Also, could we make the `ng version` one smaller? It's a lot of useless text to go in the issues :)

**Comment by beeman** [comment]
@hansl updated

**Comment by beeman** [comment]
This is the last version that's up in the branch. With a better `A` to please @delasteve 👍  
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
```

**Comment by delasteve** [comment]
Pleased indeed! 👍

**Pull request merged**
