### PR TITLE
fix(routes): fix providers for route unit tests

### PR DESCRIPTION
**Pull request by filipesilva**
Fix broken providers in unit tests for generated routes.

/cc @Brocco

### CODE REVIEW

**Comment by Brocco** [comment]
lgtm

**Comment by cexbrayat** [comment]
Wouldn't that be better to use `provide` instead of the deprecated `bind` method?

**Comment by filipesilva** [comment]
It definitely would, yes - were it not for my lack of knowledge in that field. I'll put up a PR to fix that.

**Comment by filipesilva** [comment]
@cexbrayat can you review if this is what you mean? https://github.com/angular/angular-cli/pull/201

**Pull request merged**
