### PR TITLE
Fix(config):Add MIME type to work around Chrome > 54 problem (#2125)

### PR DESCRIPTION
**Pull request by jtsom**
Added a mime type configuration to the karma.config.js file to work around an issue with beta releases of Chrome (versions greater than 54)

Fix https://github.com/angular/angular-cli/issues/2125

### CODE REVIEW

**Comment by filipesilva** [comment]
We're investigating https://github.com/angular/angular-cli/issues/2125, so putting this PR on hold until we can get some information from the Karma team.

**Comment by jtsom** [comment]
Ok cool. But I'll still use this fix until you figure it out...

**Comment by jtsom** [comment]
Now that this has been sitting for a month, and I've been bitten several times by this, any chance it will be fixed soon?

**Comment by filipesilva** [comment]
We were waiting on word from the karma team, but haven't gotten it yet. I'll merge it and we can remove later if it's fixable on their end. Thank you for putting this PR together.

**Pull request closed without merging**
