### PR TITLE
feat(@angular/cli): Add VsCode recommendation for Angular Console

### PR DESCRIPTION
**Pull request by mrmeku**

### CODE REVIEW

**Comment by mrmeku** [comment]
So what do we all think @alexeagle and @mgechev? Is Angular Console ready to be an official recommendation of Angular's VSCode experience?

**Comment by cyrilletuzi** [comment]
@mgechev @alexeagle @IgorMinar It may sounds personal and emotional, but I need to say it: I feel very sad about this move. Suggesting official extensions like Angular Language Service is nice. But I'm not sure it's very respectful for community work to promote a specific third part extension (potentially privileged only because their authors are close to the official team), while there are others extensions which are at least as much as good, and currently widely more adopted, like [Angular schematics](https://marketplace.visualstudio.com/items?itemName=cyrilletuzi.angular-schematics), which have nearly 100 000 users and 500 000 downloads.

I've put a lot of (free) work in this extension. I was already sad to never had a support tweet from the team about such a successful work. Now with this PR, basically you say: you can put all your work to the trash, as from now on people will be prompted to install another extension. 👎

**Comment by alexeagle** [comment]
Hi @cyrilletuzi 

This is totally an oversight on our part. We are just putting together the list of recommended extensions (see my later PR #13776 where I added some more that we heard about from John Papa).

I think we owe you:
- a README in that extensions directory indicating what criteria we are using for selecting the recommended extensions
- take all your work that meets the guidelines and promote it in the CLI recommended extensions

I know you have published `cyrilletuzi.typescript-angular-plugin` but as you know, this is harder for us to figure out because we probably will confuse users if we recommend two different language service plugins. @kyliau can you figure out which of the two language service plugins is better to recommend for most (non-ivy) users in Angular 8.0?

I looked for your extensions other than `cyrilletuzi.angular-schematics` and that one. Do you suggest other third-party extensions that should be recommended by the CLI?

**Comment by cyrilletuzi** [comment]
Hi @alexeagle, thanks for your quick answer.

I'm not sure about what you are saying about `cyrilletuzi.angular-schematics`: are you waiting some changes from me, so it can be in the suggestions?

You can forget `cyrilletuzi.typescript-angular-plugin`: it was an experimentation. Pro: more efficient. Con: it supposes there are no error in `@angular/language-service`, otherwise it breaks the whole TypeScript IntelliSense. And as the Language Service is not the more supported area in Angular currently, it would be a risky move. Additionnaly, it doesn't support external templates.

**Comment by IgorMinar** [comment]
I fully agree with @cyrilletuzi, this was a rushed and insufficiently-thought-through merge on our part. I suggest we roll it back and consider the whole community before we start making recommendations.

**Comment by IgorMinar** [comment]
@cyrilletuzi please accept our apology. Given our past conversations,  I also feel like we are running out of apology credits with you. Thanks for being extremely patient with us. I'll be following up with you via email today.

**Comment by alexeagle** [comment]
We reverted the commits that add recommended extensions and will roll forward with the guidelines in place.

**Comment by mgechev** [comment]
When we saw the PR by @mrmeku which introduced recommended VSCode extensions to the CLI we were very interested because we genuinely believe that this would help Angular developers improve their productivity.

Excited to help folks be productive we overlooked the PRs which introduced the recommendations and did not consider all the possible options. That's a mistake on our side, and we're really sorry. I've been in the exact same situation as an external contributor, and I know how disappointing this can feel.

As @alexeagle mentioned, we'll revert the recommendations from the current release. We'll take a step back and define criteria based on which we'll endorse an extension in our official list. Once we're confident in our rules are not biased, we'll make them publicly visible so anyone can share their opinion and help us polish them even further. After that, we'll define the top extensions that will help Angular developers to be productive and reintroduce them as official recommendations in the CLI.

**Comment by jeffbcross** [comment]
Hi @cyrilletuzi thanks for raising this, and on behalf of Nrwl, we're sorry this came across the way it did. I agree, only first-party extensions should be promoted by Angular CLI. We submitted this because we've been collaborating with the Angular team since the early prototypes of Angular Console to make it the official UI companion for Angular CLI, but we're still working with the Angular team on that transition.

**Comment by jeffbcross** [comment]
Hi @cyrilletuzi, I looked at your extension and how you promote it:
image
image

You're certainly free to promote your project however you see fit, but I'd encourage you to read the [Angular Communication Guidelines](https://docs.google.com/document/d/18cXfy3I94llOA7iDuTmW7yxEcPcjgFwCjgMamDCLi4I/edit) doc for recommendations on how to communicate about projects in relation to other projects.

**Comment by cyrilletuzi** [comment]
@jeffbcross My intention was not to be offensive to anyone or to anyone work. I know very well it's a lot of work and that's exactly why I try to promote mine. So please accept my apologies.

If the "competition" was fair, I would not have compared to any other tool: it's the role of users to do so. But, to my opinion, the "competition" was not fair: on my side, despite my tool was the first released and had some success, I never had any support. On your side, you can have a post about your work on the official Angular blog, among other things.

I'm not saying that as an excuse, just so you can understand in which mood I was (quite upset, I confess). I agree it was quite agressive promotion: I've updated the doc to remove what you mentionned.

**Comment by vishal423** [comment]
It would be fair competition if `Angular CLI` chooses not to recommend one community extension over other.

**Pull request merged**
