### PR TITLE
perf: move es6-shim to core-js (new stuff only)

### LINKED ISSUE #851: Switch from es6-shim to core-js/client/shim
## tl;dr
The `es6-shim` is fatally slow for IE10 and IE11. The alternative `core-js/client/shim.min.js` can be as much as 25x faster.

Switch to that library when generating the ES6 shim script for `index.html`:

    // package.json: "core-js": "^2.4.0",

    <script src="node_modules/client/shim.min.js"></script>

## Background
We (IdeaBlade) have a large A2 app that can display 1000s of table rows. Works fine in Chrome, Edge, FF.  Died miserably in IE11 and IE10.

Discovered that `core-js` is ​25x faster than the `es6-shim` library when processing arrays of data.  The app is now usable on IE11 (IE10 testing pending). 

See https://www.npmjs.com/package/core-js 
See also: http://stackoverflow.com/questions/36570532/angular-2-performance-ie11-ngfor

After discussion with @mhevery and PatrickJS, have decided to switch to `core-js`. Core-js is highly modular and one could build a custom bundle.

We want one file that covers the largest shimming needs and don't want to have to maintain our own fine-tuned bundle. We selected the `core-js/client/shim.min.js` (77k) as best fit for our needs.

Am in process of migrating all doc samples to use this `core-js` shim.

## Verification:

IdeaBlade reports success on IE11, Chrome, Edge, and FF with this library. 

Ward spot checked a few of the larger doc samples in IE11 as well as Chrome and Edge. 

No known tests on IE10 or Safari yet.

### PR DESCRIPTION
**Pull request by hansl**
Fixes #851.

### CODE REVIEW

**Comment by filipesilva** [comment]
@hansl core-js also includes reflect-metadata, I tested it myself. Can you remove it as well in this PR?

**Comment by Shyam-Chen** [comment]
Hello, I would like to help you for this.

**Comment by briananderson1222** [comment]
👍 This is essential for working with IE

**Comment by briananderson1222** [comment]
Any reason this is being held up?

For those who are having major slow-downs on IE9-11 I ended up removing es6-shim and reflect-metadata, adding core-js (including in the vendorNpmFiles array), and adding the following to the angular-cli-build.js file after the `vendorNpmFiles` array.
```js
polyfills: [
      'vendor/core-js/client/shim.min.js',
      'vendor/systemjs/dist/system.src.js',
      'vendor/zone.js/dist/zone.js'
    ]
```

been running this setup for almost a month now with no issues and extreme performance enhancements in IE9-11

**Comment by splintercode** [comment]
@filipesilva since core-js now includes reflect-metadata would it be appropriate for the docs to be updated and remove the reference in the live examples as well? I'm not to sure because under the core-js repo it sounded that it was experimental and wasn't guaranteed to stay. If so I'll get a pr going on the docs.

**Pull request closed without merging**
