### PR TITLE
Disable HMR

### PR DESCRIPTION
**Pull request by filipesilva**
See https://github.com/angular/angular-cli/issues/1356#issuecomment-234127769

### CODE REVIEW

**Comment by TheLarkInn** [comment]
LGTM pending tests!

**Comment by tapas4java** [comment]
Why we are disabling? Isn't HMR ready yet??

**Comment by TheLarkInn** [comment]
Live reload will work, HMR needs a couple more bits of config. And the HMR here is style hot reloading. Which is still awesome, not to be confused with the amazing (but needs more config and thought put into) react-hot-loader HMR.

**Comment by tapas4java** [comment]
Thanks @TheLarkInn

**Comment by TheLarkInn** [comment]
@tapas4java anytime, and feel free to test the new.patch. Im so so so excited for people to run this branch!!!!

**Comment by rexebin** [comment]
Could you please integrate [Angular2-hmr](https://github.com/AngularClass/angular2-hmr) and enable HMR if possible? We'd love to enjoy HMR with angular-cli.

**Pull request merged**
