### PR TITLE
feat(@angular/cli): add trailing slash to deployUrl when missing

### LINKED ISSUE #7295: deployUrl (ng build) doesn't seem to add a trailing slash
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.2.7
node: 7.10.0
os: darwin x64
@angular/animations: 4.3.3
@angular/cli: 1.2.7
@angular/common: 4.3.3
@angular/compiler: 4.3.3
@angular/core: 4.3.3
@angular/forms: 4.3.3
@angular/http: 4.3.3
@angular/platform-browser: 4.3.3
@angular/platform-browser-dynamic: 4.3.3
@angular/router: 4.3.3
@angular/compiler-cli: 4.3.3
@angular/language-service: 4.3.3

### Repro steps.

`$ ng build --deployUrl=some/path`

### The log given by the failure.

Some resources (like font awesome loaded via npm) do not load because they're missing a slash in the middle.
e.g.: `GET 404: http://localhost:8080/some/pathfontawesome-webfont.af7ae505a9eed503f8b8.woff2`

### Desired functionality.

Add a trailing slash to the deployUrl (if needed) when forming the path.
e.g.: `http://localhost:8080/some/path/fontawesome-webfont.af7ae505a9eed503f8b8.woff2`

### PR DESCRIPTION
**Pull request by tomastrajan**
Closes #7295

### CODE REVIEW

**Comment by filipesilva** [comment]
@clydin can you review please?

**Comment by clydin** [comment]
As currently implemented, the deploy URL option mimics the behavior of webpack's public path option which simply prepends the value provided to resource requests.  So technically this PR would be a breaking change.  However, I'm not sure anyone is currently using the option to prepend directly to the filename of the resource (as opposed to the common case of adjusting the path).

Also of note, the CLI's base href option also would typically require the user to use a trailing slash.  According to the specification, the trailing slash is actually significant to the meaning of the base href value (i.e., `/base/` and `/base` have different behavior within a web browser).

**Comment by tomastrajan** [comment]
@clydin I had similar worries and [asked Webpack guys directly](https://twitter.com/tomastrajan/status/937919027971629056) and got response that it is always safe to append trailing slash when missing on publicPath. Then again I the context in the question was lacking so it's possible that answer didn't account for all use cases.

**Comment by clydin** [comment]
This is something that webpack should probably fix directly but changing it here as well shouldn't cause a problem.

**Pull request merged**
