### PR TITLE
Add Error Handling to Bootstrapping Logic

### PR DESCRIPTION
**Pull request by sanspace**
This one is recommended in the style guide. https://angular.io/guide/styleguide#style-02-05 If it's part of the blueprint, it'd be better.

I am not sure if I've added it to the right file. Please review and merge if you think it's fine.

### CODE REVIEW

**Comment by sanspace** [comment]
I signed it!

**Comment by filipesilva** [comment]
@Brocco can you review?

@sanspace CI is failing because of the commit message. We require commit messages to follow a specific format to auto generate the change log. Can you change it to `fix(@angular/cli): Add Error Handling to Bootstrapping Logic` please?

**Comment by sanspace** [comment]
I think, I will have to send another PR with the correct commit msg format. Please reject/close this one. Thank you.

**Comment by sanspace** [comment]
Sent another PR https://github.com/angular/angular-cli/pull/7242

**Pull request closed without merging**
