### PR TITLE
multiple files: fix typos

### PR DESCRIPTION
**Pull request by schneiderl**
Please be aware that this pull request was automatically created using [gtf](https://github.com/schneiderl/gtf) - a typo fixing bot

You should be able to merge this with no other problems.
In case the proposed changes do not make sense, I would be glad to hear about it.

### CODE REVIEW

**Comment by alan-agius4** [comment]
@schneiderl can you please address the above comment?

**Comment by schneiderl** [comment]
I'm unsure this is the right way to do this.

**Comment by alan-agius4** [comment]
@schneiderl, I squashed the commits for you.

**Comment by dgp1130** [comment]
Also merged to patch branch (9.0.x).

**Pull request merged**
