### PR TITLE
fix(@angular/cli): add a flag to let assets outside of outDir

### LINKED ISSUE #8122: Allow ng build to put files in the outdir and levels higher than the outdir
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.4+
node: 6.11.4
os: darwin x64

### Repro steps.
See the project here  https://github.com/Azure-Samples/angular-cosmosdb/tree/develop in the `develop` branch.

Notice that I set the outdir and root like this 
```
      "root": "src/client",
      "outDir": "dist/publicweb",
```

Now notice I have assets that I want to end up in the folder one level higher than the `outdir`.

```
"assets": [
        {
          "glob": "**/*.*",
          "input": "../server/",
          "output": "../"
        },
      ],
```

When i run this I get an error saying I can't do this. This started in 1.4.4. It works in 1.4.3

### Desired functionality.
I would like this to work so I can deploy both an express server from `src/server/**` and the client app , ending up in the outdir, where the node/express server serves everything in a folder below it. See below:

```
/dist/index.js // my express server
/dist/publicweb // the folder with my angular client code
```

### Mention any other details that might be useful.
I had a chat with @Brocco about this at AngularMix ... I'm hoping we can find a way to do this where it is allowed to go up the outdir as long as it doesn't go past the project root.

### PR DESCRIPTION
**Pull request by hansl**
On top of #7778
Fixes #8122

### CODE REVIEW

**Comment by hansl** [comment]
@filipesilva PTAL.

**Comment by dzonatan** [comment]
So the whole project cannot be built outside anymore (using `../` in apps `outDir`)?
That's a breaking change. :/

**Comment by BnSmth** [comment]
@dzonatan, The change you are referring to occurred in #7778. This change adds a flag to `.angular-cli.json` to allow the original behavior (allowing assets to be output outside `outDir`).

**Comment by dzonatan** [comment]
@BnSmth, I'm not talking about assets. Instead about entire application. That change in #7778 only checks the asset paths against `outDir`. There is no limitation here to use `../` in `outDir`. 

Simple steps to reproduce:
1. `ng new example`
2. add `../` for `apps[0].outDir` in `.angular-cli.json`
3. `ng build`

Do that with both cli versions and you will see in `1.5.3` it builds and in `1.5.4` doesn't.

If this was not intentional then I'll create an issue.

**Comment by guilhermejcgois** [comment]
@dzonatan I have created one #8613, this change caught us by surprise 😢

**Comment by BnSmth** [comment]
@dzonatan Sorry, my bad. I misunderstood the issue and agree that a fix needs to be put in place. Also, as you said, given this is a breaking change, a note should have been added to the release.

**Pull request merged**
