### PR TITLE
Updates postcss-url to version 7

### PR DESCRIPTION
**Pull request by aeimer**
GITHUB warned us in our project, so here the fix:
```
We found a potential security vulnerability in one of your dependencies.

The handlebars dependency defined in package-lock.json has a known moderate severity security vulnerability in version range < 4.0.0 and should be updated.

Only users who have been granted access to vulnerability alerts for this repository can see this message.
Learn more about vulnerability alerts
```

### CODE REVIEW

**Comment by olivierlemasle** [comment]
As mentioned in the [Contributing guide](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md), could you please:
- sign the CLA and comment the PR,
- amend your commit to comply to the [Commit message guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#commit); I suppose that this would be correct:

```
build(@angular/cli): update postcss-url to version 7
```

Did you willingly omit to mention the particular vulnerability and the CVE link in order so as not to expose the vulnerability? If not, you could add more details in the commit message and/or the pull request.

Thank you!

**Comment by olivierlemasle** [comment]
Fixes #8521

**Comment by hansl** [comment]
@olivierlemasle actually this would be a `fix()`, not a `build`. `build` is for project management only, this affects created applications.

@aeimer I'll let you sign the CLA and reword your commit, but if nothing changes in the next 3 hours I'll make another PR (I was already in the process of upgrading those dependencies).

We'll release this fix next wednesday with 1.5.2.

**Comment by aeimer** [comment]
@hansl see #8528

**Comment by hansl** [comment]
@aeimer thanks.  FYI you don't need to create a new PR for this (I can change the commit message prior to merging). You could just open your branch, do `git commit --amend`, change the message then `git push -f` to update this PR. :)

**Pull request closed without merging**
