### PR TITLE
Automatic desktop notifications on build errors

### PR DESCRIPTION
**Pull request by jkuri**
I modified a TypeScript compiler to show notifications similar like [grunt-notify](https://github.com/dylang/grunt-notify). 
This can come handy when developing an application.
Note that notifications are disabled by default and can be enabled in `config/angular-cli.json` file.

### CODE REVIEW

**Comment by filipesilva** [comment]
I hadn't given much thought to this functionality but it seems to be useful and unobtrusive on the rest of the project. Plus since the cli is taking care of notifications, it's hard to sometimes know from within the editor wether or not the build is broken.

So lgtm. Could you rebase on top of master?

**Comment by jkuri** [comment]
@filipesilva sure, rebased.

**Comment by Brocco** [comment]
This also looks pretty good, although instead of having the configuration values stored in a new config file, please add an attribute in the root object in package.json to store this information.

I would suggest a name to match this repo/package `angular-cli` and pull the value from that file.

Also I do not think it makes sense to have the audio notification turned on by default and it that'd make a good value to be pulled from the configuration.

package.json
```
{
  "angular-cli": {
    "notifications": {
      "enabled": true,
      "playSound": false
    }
  }
}
```

**Comment by jkuri** [comment]
@Brocco yes, you are right, there's no need for additional config file. Will modify it later tonight and make a commit.

**Comment by filipesilva** [comment]
I hadn't even noticed the sound, but I'm totally with @Brocco on this one. It would drive me crazy.

**Comment by jkuri** [comment]
@filipesilva haha. I made a commit as @Brocco suggested btw.

**Comment by filipesilva** [comment]
@Brocco seems happy with it so I am happy to merge it. I noticed hansl was asking you to squash the commits into one, and I forgot to ask you that myself.

To keep the history tidy, may I suggest you name the single commit `feat(build): add desktop notifications` ?

**Comment by jkuri** [comment]
Done. Added name to commit as you suggested.

**Comment by filipesilva** [comment]
And it's in! Thanks @jkuri !

**Comment by jkuri** [comment]
np, thank you.

**Comment by hansl** [comment]
This PR will be reverted when we upgrade the broccoli files to the latest ones from angular/angular. If you want to add new features to the standard broccoli flow, do it in `angular-app.js` or do it in angular/angular.

**Pull request merged**
