### PR TITLE
refactor(@angular/cli): refactored the code and removed the code smells

### PR DESCRIPTION
**Pull request by alkavats1**
refactored the code and removed the code smells

### CODE REVIEW

**Review by alan-agius4 — CHANGES_REQUESTED** [review]
There are a couple of other occurrences, can you please update them?
Screenshot 2022-05-06 at 10 56 17

Since you will be touching files across multiple packages, you can you remove the commit scope?

`refactor(@angular/cli): ....` -> `refactor: .... `

**Comment by alan-agius4** [comment]
Nit: can you please avoid closing and opening new PRs for the same change, as contexts and comments are lost. Thanks.

**Comment by alkavats1** [comment]
Okay thanks @alan-agius4 
I've updated the other occurrences also 
Please review  now
Thanks

**Review by alan-agius4 — APPROVED** [review]
LGTM, thanks for the contribution.

**Pull request merged**
