### PR TITLE
docs: add SASS integration

### PR DESCRIPTION
**Pull request by eye0fra**
add SASS integration for font-awesome

### CODE REVIEW

**Comment by eye0fra** [comment]
Yes I know, they are instruction to how integrate font-awesome with sass in angular-cli, like they have done with bootstrap's wiki

**Comment by clydin** [comment]
Note that this works as well:
```
      "styles": [
        "../node_modules/font-awesome/scss/font-awesome.scss",
        "styles.scss"
      ],
```

**Comment by filipesilva** [comment]
@clydin it does, but showing this setup also helps in other cases where sass doesn't resolve paths. I think it's useful for that.

**Comment by clydin** [comment]
Understood and agree.  My only concern is that the impression may be given that the described method is the required method.

**Comment by filipesilva** [comment]
As far as usage goes though, there's absolutely no difference between using the .css and .scss in the assets array afaik. So a user that wanted to do something specific with FA, or use it as part of a single sass global style, is better off this way, no?

**Comment by eye0fra** [comment]
Agree :)

**Comment by clydin** [comment]
My concern is that someone reading this and wanting to use SCSS in their app may very well think that these steps **must** be followed to use font-awesome and SCSS in general in their app.

Also with the upcoming improvements to `url()` handling the need for the path variable will be eliminated.  But I suppose that can be eliminated later.

**Pull request closed without merging**
