### PR TITLE
docs(@angular/cli): correct e2e long description field

### PR DESCRIPTION
**Pull request by clydin**

### CODE REVIEW

**Comment by filipesilva** [comment]
Related to https://github.com/angular/angular-cli/pull/12554.

**Comment by clydin** [comment]
There's actually two of each format in there. so I picked the short form.

**Comment by filipesilva** [comment]
Oh you're right, I didn't notice the `add.md`. Nevermind my request then.

**Comment by clydin** [comment]
Too late :).  It makes more sense anyway since there could also be `e2e-usage.md` for usage notes.

**Pull request merged**
