### PR TITLE
fix(@schematics/angular): add validation for component and directive class name

### PR DESCRIPTION
**Pull request by harshlakhara**
fix(@schematics/angular): add validation for component and directive class name

class names for directives and components when they are created using `ng generate component <className>`
added tests for the changes made above

## PR Checklist

Please check to confirm your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular-cli/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #28548 

## What is the new behavior?

When a component or directive is created using an invalid character, such as a class name that begins with a number or a component or directive name that contains only a number, cli will throw an error.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by alan-agius4 — APPROVED** [review]
Thanks for your contribution. 

Can you please change the commit message scope from `@angular/cli` to `@schematics/angular` please?

**Comment by harshlakhara** [comment]
@alan-agius4 I have updated the scope to @schematics/angular

**Comment by alan-agius4** [comment]
> @alan-agius4 I have updated the scope to @schematics/angular

Please update the commit message and not the PR title, also one of the tests appear to be failing;

```
Failures:
1) Component Schematic standalone=false should error when class name contains invalid characters
  Message:
    Expected a promise to be rejected with Error: 'Class name "1Clazz" is invalid.' but it was rejected with Error: Selector "app-1-clazz" is invalid..
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (packages/schematics/angular/component/index_spec.ts:504:9)
        at <Jasmine>

```

**Comment by harshlakhara** [comment]
> > @alan-agius4 I have updated the scope to @schematics/angular
> 
> Please update the commit message and not the PR title, also one of the tests appear to be failing;
> 
> ```
> Failures:
> 1) Component Schematic standalone=false should error when class name contains invalid characters
>   Message:
>     Expected a promise to be rejected with Error: 'Class name "1Clazz" is invalid.' but it was rejected with Error: Selector "app-1-clazz" is invalid..
>   Stack:
>         at <Jasmine>
>         at UserContext.<anonymous> (packages/schematics/angular/component/index_spec.ts:504:9)
>         at <Jasmine>
> ```

working on it. Will update the PR with the changes.

**Comment by harshlakhara** [comment]
@alan-agius4 I have updated the PR

**Comment by harshlakhara** [comment]
@alan-agius4 husky is throwing error with module not found and its not able to lint the file.

**Comment by alan-agius4** [comment]
Can you try to run `yarn ng-dev format changed`?

**Comment by harshlakhara** [comment]
@alan-agius4  I have raised other PR #28566 for clean code as I messed git in this currenct PR. Sorry and Thanks.

**Pull request closed without merging**
