### PR TITLE
chore: remove format command

### LINKED ISSUE #765: Remove `ng format`
It doesn't follow the styleguide.

### PR DESCRIPTION
**Pull request by Brocco**
Formatting does not align with the style guide.
Fixes #765

### CODE REVIEW

**Comment by jkuri** [comment]
LGTM :)

**Comment by metric152** [comment]
This needs to be removed from the pdf reference
https://cli.angular.io/reference.pdf

**Comment by martinmcwhorter** [comment]
Probably should remove the copy about `Format` from cli.angular.io

**Comment by keradus** [comment]
could there be any formatter added/configured that would follow the guidelines?
not having any formatter is not great option

**Pull request merged**
