### PR TITLE
fix: move environment files to `config` directory

### LINKED ISSUE #1603: Move environments to the app directory
Right now it's in the app component directory, but it should be used and needed by the app module.

### PR DESCRIPTION
**Pull request by TheLarkInn**
Move environment configuration files from `environments` directory to `config` directory. Also bumped webpack beta to .20 (chore). 

This allows for free movement of app [or using multiple apps] without affecting/needing to change environment paths imports/exports. 
Fixes #1603

### CODE REVIEW

**Comment by tapas4java** [comment]
Why this change?? 
Are we fixing any particular issue by removing `environment` directory?

**Comment by TheLarkInn** [comment]
We are not removing it, but simply moving it from an `environments` folder to an `app` folder like the above comments mention. This fixes #1603

**Comment by tapas4java** [comment]
@TheLarkInn Thanks, I was asking why we are moving 3 environment files to app directory. I thought it was good inside `environment` directory as user can add few more environments later.

From #1603 it looks like this change is required for NgModule support which should be fine.

**Comment by TheLarkInn** [comment]
Yup! This is a 'forward-thinking' change for ngmodules.

**Comment by filipesilva** [comment]
Closed in favor of https://github.com/angular/angular-cli/pull/1633.

**Pull request closed without merging**
