### PR TITLE
feat(@angular/cli): add publicPath support via command for webpack-dev-server

### PR DESCRIPTION
**Pull request by scriste-sv**
This adds support for publicPath to webpack-dev-server via ng serve
The server would have to be started like ng serve --deploy-url /deploypath --base-href /deploypath.
The app will be served from http://localhost:4200/deploypath

Should fix #2727

### CODE REVIEW

**Comment by scriste-sv** [comment]
@filipesilva could you please review and let me know if this is eligible for to complete the fix on  #3285 and address the issues with ng serve?

Thank you.

**Comment by scriste-sv** [comment]
Great, thanks @filipesilva

**Comment by ledicjp** [comment]
Is it possible to let the port be the port that is specified inside the angular-cli.json? Like this the port 4200 is hard coded :(

**Comment by filipesilva** [comment]
@ledicjp yes, you can add it in the `defaults.serve` section. See https://github.com/angular/angular-cli/wiki/angular-cli for details.

**Pull request merged**
