### PR TITLE
fix(@angular/cli): Correct generate class filename

### LINKED ISSUE #7121: ng generate class hero model generates hero.ts instead of hero.model.ts
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.1.0 and up

### Repro steps.
```
ng generate class hero model
```
`hero.ts` is generated, but it should be `hero.model.ts` instead.

### The log given by the failure.

No log per se, 

### Desired functionality.
`hero.model.ts` should be generated, as this was the existing 1.0 functionality.

### Mention any other details that might be useful.

Followup from https://github.com/angular/angular-cli/issues/1283#issuecomment-309075311.

### PR DESCRIPTION
**Pull request by mallek**
fixes #7121

### CODE REVIEW

**Comment by filipesilva** [comment]
@Brocco can you review?

**Comment by mallek** [comment]
Is there something I need to fix on this?

**Comment by mallek** [comment]
@filipesilva @Brocco Can you please let me know if this PR works.  I am planing on working more on open items however this "urgent" item has been waiting on review for 20 days.  slightly discouraging

**Comment by Brocco** [comment]
@mallek thank you for the PR, however the functionality for specifying a type on a class is provided via an option on the class schematic.

I closed the related issue with this [comment](https://github.com/angular/angular-cli/issues/7121#issuecomment-350035046).

And you can see the type option for the schematic [here](https://github.com/angular/devkit/blob/0b9c700ccf3b9b3f2e7cdc2a662825598a8e850c/packages/schematics/angular/class/schema.json#L33-L36).

**Pull request closed without merging**
