### PR TITLE
closed link tag in index.html

### PR DESCRIPTION
**Pull request by sacgrover**
Fixes angular#16964

### CODE REVIEW

**Comment by sacgrover** [comment]
@dgp1130 Should I close this?

**Comment by dgp1130** [comment]
Sorry @sacgrover, looks like this PR fell through the cracks a bit.

@clydin, @alan-agius4, can one of you take a look at this? I'm thinking the fix should probably happen with how the styles are generated rather than a regex replacement afterwards. I'm not quite familiar enough to know exactly where this fix should happen though.

**Review by IgorMinar — CHANGES_REQUESTED** [review]
Hi @sacgrover, thanks for the pr. I think you are trying to fix a real issue but, can we please do this only as an option for xhtml deployments?

Doing this by default (for html) doesn't make sense, confuses people that don't know when the tags must be closed and when they don't have to be, and only bloats the payload very slightly but in the critical path.

I don't know how to implement the opt in, other cli folks should chime in on that, but it would not be too crazy to add --xhtml support to `ng new` and angular.json.

**Comment by dgp1130** [comment]
This PR is blocked on supporting XHTML in FW https://github.com/angular/angular/issues/37779. We'll want to support it there more completely before we add support to the CLI as well, or else we'll just be whack-a-mole-ing bugs filed by users for all the edge cases missed because FW doesn't fully support it.

**Comment by dgp1130** [comment]
Looking at old PRs, and this one seems to have been left in a weird state. It's awkwardly blocked on framework support and still has open questions as to how it would exactly work in tooling. There's also not much momentum or desire to make this happen on the Angular side right now, so leaving this PR hanging is just a disservice to the people who care about it. We're not quite at the right place to be able to accept PRs for XHTML right now.

We'll keep the discussion going at https://github.com/angular/angular-cli/issues/18044 and I'll bring this up in the relevant planning discussions to get a stronger direction and find the right priority for this work. For now, we think the best thing is to close this PR until we have a better idea of what a solution here will look like.

**Pull request closed without merging**
