### PR TITLE
chore(formatting): correction for package.json

### PR DESCRIPTION
**Pull request by zackarychapple**
chore(formatting): correction for package.json

realized a change snuck in on the package.json that disables the tests command from running tests

### CODE REVIEW

**Comment by filipesilva** [comment]
lgtm get this in :D

**Comment by hansl** [comment]
Oh shoot totally missed that. You should have a separate `lint` script instead, please.

**Comment by Brocco** [comment]
Definitely get this in, `npm test` should run tests 😇

**Comment by zackarychapple** [comment]
Updated to run tests and lint separately per @hansl

**Comment by filipesilva** [comment]
looks good

**Comment by hansl** [comment]
LGTM

**Pull request merged**
