### PR TITLE
feat(@angular/cli): bump blueprint dependencies

### PR DESCRIPTION
**Pull request by danielsogl**
Again I updated some deps. 
I already use them in production.

### CODE REVIEW

**Comment by filipesilva** [comment]
Heya, can you rebase? It took us a while to review it and some of these were also updated.

**Comment by danielsogl** [comment]
@filipesilva Done :)

**Comment by filipesilva** [comment]
I'm going to have to ask you to squash the commits.. We use commit messages to generate the changelog, and your PR has several commits of which a few have invalid commit messages. That causes the CI run to fail.

**Comment by hansl** [comment]
We just moved our blueprints to using Schematics. Could you submit a PR on https://github.com/angular/devkit instead? Thanks!

**Comment by danielsogl** [comment]
@hansl where can I find the right package.json file?

**Comment by filipesilva** [comment]
@danielsogl it's this one I believe: https://github.com/angular/devkit/blob/master/packages/schematics/angular/application/files/package.json

**Pull request closed without merging**
