### PR TITLE
docs: No more cache clean on NPM 5

### PR DESCRIPTION
**Pull request by code1line**
`npm cache verify` is possible, but not necessary.

### CODE REVIEW

**Comment by code1line** [comment]
Please also change the line in the README.md.

**Comment by hansl** [comment]
Hi @code1line, this PR looks good, but we have strict policy with the commit conventions (see CONTRIBUTING.md). Could you amend your commit (use `git commit --amend && git push -f`) to change the message to `docs: cache clean is not needed on NPM 5` (or similar)?  Thanks.

**Comment by code1line** [comment]
Done!

**Comment by hansl** [comment]
We're removing support for npm 3 so this is moot.

**Pull request closed without merging**
