### PR TITLE
broccoli bump and tools update

### PR DESCRIPTION
**Pull request by zackarychapple**
angular-cli throws multiple errors for Cannot read property with Angular2 Beta6.  Bumping broccoli version as well as updating tool compilations and maps.

### CODE REVIEW

**Comment by filipesilva** [comment]
Does this still happen with the latest master? It should be fixed there, we're late with releasing a new version though.

**Comment by zackarychapple** [comment]
It does, I was running off of 6db91e7 and was still getting the issue against beta6.

**Comment by filipesilva** [comment]
Ok, can you show me reproduction steps for these errors please?

I haven't seen them yet so I don't know how your PR fixes them.

**Comment by zackarychapple** [comment]
Working on replicating it again. I wiped and did a clean install again and was not able to replicate.  I noticed some odd behavior before when I went from beta3 to beta5 as well and had to wipe my node_modules directory.  Possibly this was an artifact of moving from beta5 to beta6 and was only "resolved" when I wiped my node module directory in testing the angular-cli updates.

**Comment by filipesilva** [comment]
Roger. We had loads of trouble with the upgrade last week so it scares me to think it might still be broken, and we just don't know. 

Needless to say, thanks a bunch for going ahead and fixing it. The upgrade was a hard one.

**Comment by zackarychapple** [comment]
I did some testing and it appears that I got my node_modules directories in a weird state in the process of bumping angular and angular-cli.  After wiping both it looks like Master does work (was not working Friday of last week) which confirms what you were saying. However I did notice that the perf stats appeared to be a little better on new versions of broccoli.  So might be a merge worth doing still.

**Comment by filipesilva** [comment]
I *think* the brocolli setup is supposed to be similar to the one found in the [angular repo](https://github.com/angular/angular/blob/master/package.json), but I might be wrong. If that is the case, it's better to not deviate much from those versions. @IgorMinar?

In either case, this PR as is changes more than (what I suppose to be) required for the version change, so in that sense there is a bit of an increased surface area for bugs. There is also a [new warning](https://travis-ci.org/angular/angular-cli/jobs/109334892#L500) about a missing file appearing on the travis tests.

It's probably best to wait for Igors input on this before putting more work into it.

**Comment by hansl** [comment]
The broccoli files are compiled version of the typescript files found in angular/angular. Did you compile the latest from over there?

**Comment by zackarychapple** [comment]
@hansl yes I did, pulled from the latest and compiled them and dropped them in.

**Comment by hansl** [comment]
LGTM, I will commit this on your behalf. Thanks a lot for the update.

**Comment by filipesilva** [comment]
Had to revert the use of `broccoli` beta version in https://github.com/angular/angular-cli/pull/227. It was breaking `ng serve`.

**Pull request closed without merging**
