### PR TITLE
fix(@schematics/angular): scroll issue on new app

### PR DESCRIPTION
**Pull request by mohuk**
Subtracting the top space from image vh(viewport height) to remove scroll

Closes: #15596

### CODE REVIEW

**Comment by mohuk** [comment]
cc: @vikerman @sjtrimble

**Comment by vikerman** [comment]
Thanks for PR! 

Can you share a screenshot on before and after so that it's easy to review? Thanks!

**Comment by mohuk** [comment]
Sure.

**Before**
Before

**After**
After

**Comment by vikerman** [comment]
Fixed the commit footer while squashing.

**Pull request merged**
