### PR TITLE
fix(@schematics/angular): exclusively list the files in tsconfigs

### PR DESCRIPTION
**Pull request by alan-agius4**
With the omission of `includes` or `files` in tsconfig files tsc will pick up all the files under the rootDir and make them as part of the compilation. In certain cases, redundant files will be picked up which will cause a slower compilations.

Related to: TOOL-949

### CODE REVIEW

**Comment by filipesilva** [comment]
Indeed they can, but it is deprecated. Ivy supports the string syntax as well currently. We decoupled the two things.

Maybe we should only do this in v9 then? Or perhaps we need to document in https://angular.io/guide/deprecations#loadchildren-string-syntax that if you want to use the string syntax you need to add the file to the files array.

**Comment by alan-agius4** [comment]
IMHO, I think an update to the docs should suffice.

**Comment by alan-agius4** [comment]
Make this for Ivy for the time being. And make this the default version 9.

**Comment by alan-agius4** [comment]
The VE, part might be needed if we go with https://github.com/angular/angular-cli/pull/15061#issuecomment-510871409

**Pull request merged**
