### PR TITLE
Compilation of .tsx files.

### PR DESCRIPTION
**Pull request by fragomeni**
Hello, this pull request enables the compilation of .tsx files along with the .ts files (default behavior of tsc). It is needed for integrating react components (like draft-js) into angular 2 applications.

### CODE REVIEW

**Comment by fragomeni** [comment]
I signed it!

**Comment by filipesilva** [comment]
@hansl can you have a look?

**Comment by hansl** [comment]
LGTM, I guess. This might be changed if/when we move towards webpack.

Is there a reason you need a React component and can't compile it separately outside of broccoli-typescript?

**Comment by fragomeni** [comment]
The component that I'm using, draft-js, is more a framework for rich text
editors than a finished component. I will be evolving my own rich text
editor altogether with my angular 2 application. Compiling it in the same
project would be more practical for me than managing two different projects.

Abraço do Frago

marcos.fragomeni@gmail.com
(061) 98165-4874

"A felicidade é o caminho!"

2016-06-16 21:21 GMT-03:00 Hans <notifications@github.com>:

**Comment by filipesilva** [comment]
Heya @fragomeni, we've just merged in the webpack changes. Can you rebase and update your PR?

**Comment by Brocco** [comment]
This is outdated and does not align with AoT

**Comment by tschaka1904** [comment]
Hi @fragomeni! We're you able to load tsx files?

**Comment by fragomeni** [comment]
@tschaka1904 , in fact, I've decided stop using the react component. So I haven't tried it anymore.

**Pull request closed without merging**
