### PR TITLE
fix(@angular/cli) - include "dom" lib in root tsconfig.json

### LINKED ISSUE #5046: TS2304: cannot find name "xxx"——after update to rc.0
> Please provide us with the following information:
> ---------------------------------------------------------------

Windows 10

@angular/cli: 1.0.0-rc.0
node: 6.9.1
os: win32 x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.8

follow update instruction from beta.32 to rc.0

webstrom failure:
image
image

Nothing change just cover the `src/app` folder.

1. remove global `cli` and `clean cache`.
2. install the `rc.0`
3. use `ng new upgrade-project --skip-install` to new a update project.
4. copy my `src/app` folder and paste it into update-project cover the old one.
5. run `ng serve` works well ,no errors output, but all my file with "confirm","document", etc, got a note.

### Mention any other details that might be useful.
If I cancel the settings in webstorm, it works fine.
image

Webstorm version:
2016.3.3

Anyone the same?

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

### PR DESCRIPTION
**Pull request by deebloo**
Add "dom" lib to root tsconfig.json. fixes #5046

### CODE REVIEW

**Comment by deebloo** [comment]
fixed

**Comment by Meligy** [comment]
Can we also add target as ES5 to this?

I was planning to open a discussion about it, tslint fails things like:

```
get someProperty() {
  return `some calculated value`;
}
```

Because it says you can only have getters when targeting ES5 or higher.

That's because it can only read the closest `tsconfig.json` file. `tsconfig.app.json` means nothing to it.

**Comment by deebloo** [comment]
@Meligy should the target be es5 or should we bump it straight to es2015?

**Comment by Meligy** [comment]
`target` is the output, which for the browser (non-node) stuff needs to be es5. We have `libs` and `polyfills` for many ES2015 features, but the syntax that cannot be polyfilled needs to be transpiled to ES5.

That's in theory. In reality it doesn't matter, because `tsconfig.spec.json` and `tsconfig.app.json` have their own `target` values (`es6` and `es5` respectively). This root file is more just for IDEs etc if I get it right.

So, I think we should set it to the minimum of both files, which is `es5`.

**Comment by Meligy** [comment]
To explain it a little further: TypeScript in theory supports targeting ES3 (outputting to ES3), but each feature in TypeScript is only supported in some targets. For example, property getters are not supported when targeting es3. `async`/`await` in TypeScript 1.x was only supported when targeting ES6.

If you don't specify anything, the lower value is assumed, which is `es3`. This is for backwards compatibility, just like when you don't specify `moduleResolution`, it's assumed `classic`, although evryons is (and should be) using `node`.

**Comment by deebloo** [comment]
Makes sense @filipesilva what do you think?

**Comment by filipesilva** [comment]
Makes sense to me as well.

**Comment by deebloo** [comment]
updated to add es5 to target

**Comment by cexbrayat** [comment]
I'm possibly mistaken, but doesn't that mean that we can remove the lib and target from `tsconfig.app.json`?

See #5111 for an attempt

**Comment by filipesilva** [comment]
@cexbrayat that's right, yes. I added a request for changes to your PR, the es5 bit still needs to stay for non-ng4 projects.

**Pull request merged**
