### PR TITLE
fix(@angular/cli): fix css url processing 

### LINKED ISSUE #4778: Module not found: Error: Can't resolve file
```
@angular/cli: 1.0.0-beta.32.3 [1.0.0-beta.28.3]
node: 7.5.0
os: darwin x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.7
```

After the update to beta.32.3 i started getting these errors in SCSS files:

```
ERROR in ./src/app/shared/header/header.component.scss
Module not found: Error: Can't resolve './assets/images/icon-search.png' in '/Users/hassan/Code/app/shared/header'
 @ ./src/app/shared/header/header.component.scss 6:1898-1940
 @ ./src/app/shared/header/header.component.ts
 @ ./src/app/shared/shared.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./src/app/shared/nav/nav.component.scss
Module not found: Error: Can't resolve './assets/fonts/portal.eot?' in '/Users/hassan/Code/src/app/shared/nav'
 @ ./src/app/shared/nav/nav.component.scss 6:295-332
 @ ./src/app/shared/nav/nav.component.ts
 @ ./src/app/shared/shared.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts
```

The error seems to appear in this line:
```
background-image: url('assets/images/icon-search.png');
```

P.S: It was working fine on beta.31

### LINKED ISSUE #4782: Assets not found in scss/css when using base-href
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Windows 10 x64

### Versions.
@angular/cli: 1.0.0-beta.32.3 [1.0.0-beta.28.3]
node: 7.2.0
os: win32 x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.7

### Repro steps.
create an app with ng-cli. create a build for a server (not ng serve) with base-href set to xxx. use url's in scss (like background-image: url('/assets/img/myimg'). the imagepath for the url will be set to server/assets/img/myimg instead of server/xxx/assets/img/myimg. If I try to use a relative path in the scss (ie url('./assets/img/myimg') ) i get a compileerror, that this is not resolveable. If i try to use url('assets/img/myimg') this is also not resolveable for the compiler.
my .angular-cli.json has this section: 
        "assets": [
            "assets",
            "favicon.ico"
        ],

### The log given by the failure.
There is only a compileerror that the path is not resolveable or a runtime 404 when the resource is not found without using the base-ref in the url.

### Mention any other details that might be useful.
There is a workaround for this issue: i set the style in my component directly and inject it like this: 
<span ... [style.background-image]="getLogo()"></span> 

  getLogo() {
    return this._domSanitizer.bypassSecurityTrustStyle(`url(${this.logosrc}`);
  }

where logosrc = "./assets/img/myimg"
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

### LINKED ISSUE #4806: CSS images with relative path not included in production build
> Please provide us with the following information:
> ---------------------------------------------------------------

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

### PR DESCRIPTION
**Pull request by filipesilva**
Fixing component css in #4667 uncovered errors in CSS url processing.

This PR correctly composes absolute urls when using `--base-href` and/or `--deploy-url`.

It also fixes asset output on `--aot` mode. Thanks to @clydin for finding out assets were being dropped in the child compiler.

Fix #4778
Fix #4782
Fix #4806

### CODE REVIEW

**Comment by filipesilva** [comment]
Still having some problems with the eject config, I need to ask @hansl for advice on it next week.

**Comment by omargon** [comment]
@filipesilva thanks for the fix. Do you know when it will be release and/or if there is a workaround in the meantime?

**Comment by filipesilva** [comment]
@omargon workaround would be to use absolute image paths. This will come out next release, which should be early next week *I think*.

**Comment by omargon** [comment]
@filipesilva thanks.

**Comment by es-lab** [comment]
I'm serving assets on a subdomain, and I need to set the deployUrl=http://sub.domain.com/, this worked on version beta26, but now with rc1 this is broken, and I think it is because of this fix you have done here.   
In the generated code I see everywhere my deployUrl written like this: `/http:/sub.domain.com/assets/...`

**Comment by clydin** [comment]
@es-lab, please open an issue so that we can properly assist you.

**Comment by es-lab** [comment]
@clydin I've opened the issue here #5254

**Comment by HelloPb** [comment]
background: url('assets/client/img.png')  is throwing compilation error for ng build -prod

**Pull request merged**
