### PR TITLE
docs: corrected spelling of Globally under Installation section

### PR DESCRIPTION
**Pull request by noopur-tiwari**

### CODE REVIEW

**Comment by noopur-tiwari** [comment]
@googlebot I signed it!

**Comment by alan-agius4** [comment]
@noopur-tiwari thanks for this, can you kindly fix the commit msg to `docs: corrected spelling of Globally under Installation section`

Thanks

**Comment by alan-agius4** [comment]
**Caretaker**: can you please reword the commit?

**Comment by noopur-tiwari** [comment]
> **Caretaker**: can you please reword the commit?

Sorry I couldn't get you. I have modified the Commit message based on your input
from 
**

> "Corrected spelling of Globally under Installation section."

**
to
**

> "docs: corrected spelling of Globally under Installation section"

**

Is anything else needed from my side?

**Comment by alan-agius4** [comment]
@noopur-tiwari, actually you didn’t rename the commit msg, but rather just the PR title.

Don’t worry, our caretaker will rename it when merging.

Thanks for your contribution.

**Pull request merged**
