### PR TITLE
refactor(@angular/cli): improved code quality 

### PR DESCRIPTION
**Pull request by alkavats1**
…calration

fix(common): improved the code quality and removed the unnecessary decalration in cli.ts file

### CODE REVIEW

**Review by alan-agius4 — APPROVED** [review]
LGTM

Can you please change the commit message to `refactor(@angular/cli): ....` and squash the commits?

Let me know if you need any help.

**Comment by alan-agius4** [comment]
@alkavats1, you need to drop the 5 commits and create a new single commit. 

You can use the below command to remove the current commits
```
git reset --soft HEAD~6
```


After committing, you than need to push with force

```
git push --force-with-lease
```

**Comment by alan-agius4** [comment]
This is not a breaking change, hence kindly remove the breaking change message as otherwise it will appear in the change log as such.

**Comment by alan-agius4** [comment]
This is not a breaking change, hence kindly remove the breaking change message as otherwise it will appear in the change log as such. 

You can use the same commands from above, this time just change `HEAD~6` to `HEAD~1`

**Review by alan-agius4 — APPROVED** [review]
Thanks for your contribution

**Comment by alkavats1** [comment]
@alan-agius4 Thank you so much for the help:)

**Pull request merged**
