### PR TITLE
feature(generate): provide options to default encapsulation & change detection

### LINKED ISSUE #2822: Add ability to configure default changeDetection and viewEncapsulation used by component generator
### Overview of the Requested Feature

Would like to have a way to set the global behavior of the component generator to handle writing the following component metadata properties:
- changeDetection
- viewEncapsulation

Something like the ability to set the default values to use for these from within the `angular-cli.json` file (or maybe some other generators config file) like so:

```
{

  . . .

  "defaults": {
    "changeDetection": "OnPush",
    "viewEncapsulation": "Native",
    . . .
  }
}
```

with the following potential string values:
- "OnPush" or "Default" for changeDetection
- "Emulated", "Native" or "None" for viewEncapsulation

If these properties are not in the `angular-cli.json` file then the metadata properties would not be included in the component generator template (same behavior it currently does).
#### Change Detection

If `"changeDetection" is set, the component metadata property would be included and set in the component generator template like so:

```
@Component({
  . . .
 changeDetection: ChangeDetectionStrategy.OnPush,
  . . .
})
```

with "OnPush" using `ChangeDetectionStrategy.OnPush` and "Default" using `ChangeDetectionStrategy.Default`.
#### View Encapsulation

If `"viewEncapsulation" is set, the component metadata property would be included and set in the component generator template like so:

```
@Component({
  . . .
 viewEncapsulation: ViewEncapsulation.Native,
  . . .
})
```

with "Native" using `ViewEncapsulation.Native`, "Emulated" using `ViewEncapsulation.Emulated` and "None" using `ViewEncapsulation.None`.
### Note

I think the ideal solution would be to have a way to create custom generator templates at a project level so users could control more than just the component metadata, but I am not sure if that is on the radar and if so, how far out it is.

### PR DESCRIPTION
**Pull request by Brocco**
Closes #2822

### CODE REVIEW

**Comment by filipesilva** [comment]
The changes themselves lgtm but can you have a look at the failing CI?

**Comment by Brocco** [comment]
@filipesilva the CI failures were a result of another issue. I rebased and CI is good now.

**Comment by Bielik20** [comment]
Hello, is there documentation or at least an example how to use it?
Also does it work for `ng library`? Do I need to configure it manually for every lib or just in the main app is ok?

**Comment by earshinov** [comment]
@Bielik20 , in case you haven't yet figured it out, here is example usage:

angular.json:
```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "frontend": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {
        "@schematics/angular:component": {
>>>       "changeDetection": "OnPush",
          "style": "sass"
        }
      },
```

Instead of relying on docs, check out the schema file referenced in the beginning of `angular.json`.

I'll leave the other questions to Angular maintainers. Not experienced enough myself.

**Comment by Bielik20** [comment]
Thank you for your help. Ok I misunderstood. I was hoping to set default change detection strategy, not make schematics set one during generation.

**Pull request closed without merging**
