### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Shivam7-1**

### CODE REVIEW

**Comment by Shivam7-1** [comment]
https://github.com/angular/angular-cli/pull/18239

**Comment by Shivam7-1** [comment]
How to run yarn admin templates

**Comment by alan-agius4** [comment]
> How to run yarn admin templates

You need to clone the repo locally see: https://github.com/angular/angular-cli and run the command in a terminal.

**Comment by alan-agius4** [comment]
Addressed in https://github.com/angular/angular-cli/pull/18440

**Pull request closed without merging**
