### PR TITLE
feat(@angular/cli): remove compileComponents()

### PR DESCRIPTION
**Pull request by filipesilva**
It is not needed in the CLI since we inline templates.

### CODE REVIEW

**Comment by filipesilva** [comment]
Closing as it's not a good time to make this change, some other changes might be needed soon.

**Comment by cexbrayat** [comment]
@filipesilva Can you briefly explain what would be these changes if you don't mind? You're talking about tests running with AoT or something else?

**Comment by filipesilva** [comment]
@cexbrayat yes, those will likely require additional changes and there's no point in changing stuff now only to change it again soon.

**Comment by cexbrayat** [comment]
@filipesilva Thank you for taking the time to answer. I was under the impression that it would not necessarily need changes in tests per se, but rather in `test.ts` according to the design docs. If I understood correctly the only thing we would have to changes in the tests is to remove the async part, which will be unneeded (even more than now :) ), so I thought your PR was a good first step.

**Comment by filipesilva** [comment]
We'll revisit this though, it's just that it shouldn't go in **right** now.

**Comment by cexbrayat** [comment]
@filipesilva Ok thx! 🙂

**Pull request closed without merging**
