### PR TITLE
docs(@angular/cli): Add Nightwatch schematics to e2e command

### PR DESCRIPTION
**Pull request by vaibhavsingh97**
**Overview**
Added Nightwatch Schematic to e2e command. Nightwatch schematics would add both schematics and custom builder to Angular Project.

Ref:
https://github.com/nightwatchjs/nightwatch-schematics
https://www.npmjs.com/package/@nightwatch/schematics

### CODE REVIEW

**Review by alan-agius4 — APPROVED** [review]
LGTM, since this appears to be a supported by nightwatch

https://github.com/nightwatchjs/nightwatch-schematics

That said, I'll going to mark this for further discussion just to make sure that everyone on the team is onboard with this.

**Comment by AutomatedTester** [comment]
Hi @alan-agius4 and @kyliau 

Is there anything else we(@vaibhavsingh97 or myself) can do here to get the update landed?

**Comment by alan-agius4** [comment]
@dgp1130 reached out to our devrels @twerske and @mgechev to see if there is any concern from their end about this change.

**Comment by mgechev** [comment]
No concerns on our end. Our general policy is to have a set of e2e tests running against the lasted build artifacts. You can keep up to date with renovatebot. Since the builder is already maintained by your team, we'd love to have it as an option.

**Comment by AutomatedTester** [comment]
@mgechev We have https://github.com/nightwatchjs/nightwatch-schematics/blob/main/src/schematics/nightwatch/index_spec.ts. Would you want us to add tests to this repo or are those good enough? We're happy to add in anything you suggest here.

**Review by mgechev — APPROVED** [review]

**Pull request merged**
