### PR TITLE
docs: cache clean is not needed on NPM 5

### PR DESCRIPTION
**Pull request by thehashrocket**

### CODE REVIEW

**Comment by filipesilva** [comment]
Heya, thanks for the contribution but https://github.com/angular/angular-cli/pull/7436 already has a fix for the same issue so I'll close this one in favor of it.

**Comment by thehashrocket** [comment]
@filipesilva can you show me where? I looked at the [diff](https://github.com/angular/angular-cli/pull/7436/files) and it's not included. That pull request has to do with `sass-test-variable`.

**Comment by devoto13** [comment]
It was probably inteneded to be https://github.com/angular/angular-cli/pull/7437.

**Comment by filipesilva** [comment]
Apologies, that is the PR I meant, yes.

**Pull request closed without merging**
