### PR TITLE
fix(@ngtools/webpack): fix compilation not working properly with webpack-dev-server

### LINKED ISSUE #3084: Modifying component template in AOT mode has no affect only after restart
### OS?
Linux Ubuntu 16.04

### Versions.
Node: 6.7.0
Angular 2: 2.1.2
@ngtools/webpack: 1.1.4

### Repro steps.
Using @ngtools/webpack with webpack-dev-server compiles the application right at startup, but when modifying a component template it still serves the old version after refresh.

Clone [this repository](https://github.com/blacksonic/angular2-aot-webpack) and start the application with ```npm run start-plugin``` and modify the ```HelloWorldComponent```.
If i stop the server and start it again, it shows the new version.

### PR DESCRIPTION
**Pull request by rynclark**
When using `@ngtools/webpack` with `webpack-dev-server`, the AoT compiler would use a program created from the last build, causing files not to compile unless the process was restarted or another build was triggered.

Creating a new program just before compilation from the old program to grab the latest source code fixes this.

Fixes #3084

### CODE REVIEW

**Comment by rynclark** [comment]
Also fixes #2576

**Comment by hansl** [comment]
@filipesilva please check this.  We need to be aware of performance impacting PRs such as this one. We already rebuild the program and re-rebuild it a second time might be a problem.

**Comment by filipesilva** [comment]
@hansl benchmark over master:
```
Angular-CLI Benchmark
Extra flags per benchmark: --aot
Iterations per benchmark: 5

=========================================
Base command: ng serve --no-progress
Comment: third rebuild time

Full command: ng serve --no-progress
Average time: 1396
Results: 1401,1385,1397,1392,1405

Full command: ng serve --no-progress --aot
Average time: 2895.6
Results: 2873,2935,2857,2963,2850

Benchmark execution time: 182722.018ms
```

Benchmark with these changes:
```
Angular-CLI Benchmark
Extra flags per benchmark: --aot
Iterations per benchmark: 5

=========================================
Base command: ng serve --no-progress
Comment: third rebuild time

Full command: ng serve --no-progress
Average time: 1456
Results: 1434,1579,1401,1417,1449

Full command: ng serve --no-progress --aot
Average time: 3484
Results: 3485,3451,3471,3469,3544

Benchmark execution time: 193738.856ms
```

So: 
- 4% increase on non-aot rebuilds
- 20% increase on aot rebuilds

I think the change on non-aot is just variance since the code change doesn't even run outside of aot.

As far as the the PR is concerned, I don't think speed should be a major concern for `--aot` rebuilds really.

**Comment by filipesilva** [comment]
@rynclark is this still a problem? `@ngtools/webpack` changed a lot in the last month so I wonder if this was fixed as well.

**Comment by randombk** [comment]
I can confirm that this issue still occurs in 1.2.11. Applying this patch fixes the issue.

**Comment by randombk** [comment]
In hopes of getting this merged asap, I updated this patch to the new codebase and added some observations from my own investigation into this issue at #5164.

**Comment by filipesilva** [comment]
Heya @rynclark @randombk, the original issue you were trying to solved seemed to be broken webpack configuration (https://github.com/angular/angular-cli/issues/3084#issuecomment-279519367).

I'm looking at this PR in relation to #5137 though, which seems to be exactly what you describe.

The changes in this PR break CI however, showing the following error:
```
ERROR in /tmp/angular-cli-e2e-11723-3750-1s602l2.d8uh0py14i/assets/webpack/test-app/app/main.aot.ts (3,34): Cannot find module './ngfactory/app/app.module.ngfactory'.)
```

This makes me think there's something missing in your solution.

**Comment by rynclark** [comment]
Not sure why it's breaking CI, it was working when created - haven't had the chance to update it to reflect any recent changes however.

This is why I created `@ultimate/aot-loader` - might be worth poking around there and seeing what we do differently from each other to get a solid solution.

**Comment by randombk** [comment]
@filipesilva The comment you linked does not help with this issue - I already had `@ngtools/webpack` in my config.

The issue continues to occur in `1.3.0`, with webpack `2.4.1`. Webpack no longer picks up changes in TypeScript code or angular templates. Multiple edits+saves are required before changes are registered.

My original PR (e2d8276) continues to work with the latest version, but after using it for a while, I noticed that only changes in TypeScript code are handled, while the issue persists with templates. This suggests that the real issue(s) is somewhere deeper in the codebase.

**Comment by clydin** [comment]
This should no longer be needed with the new Angular 5 compiler pipeline.

**Pull request closed without merging**
