### PR TITLE
Update README.md - mentioning angular-cli-ghpages addon

### PR DESCRIPTION
**Pull request by JohannesHoppe**
Say hello to [angular-cli-ghpages](https://github.com/Angular2Buch/angular-cli-ghpages)!

We created an addon on top of [tschaub/gh-pages](https://github.com/tschaub/gh-pages).
Compared to `github-pages:deploy` it gives us much more flexibility where and how to push the builds to.
In our case this plugin is the base for some smoke tests against a build matrix.

Many thanks for considering! :smile:

### CODE REVIEW

**Comment by filipesilva** [comment]
I can't merge this in, mostly because at the moment we're not really committed to the addon architecture.

But what I'd be happy to merge in is you adding this functionality to the existing one directly. If you want to try your hand at that, I'll ask you to keep all existing functionality and add tests for new one.

I did most of the code for the current one so feel free to ask me questions.

**Comment by JohannesHoppe** [comment]
@filipesilva Ok, so we got Webpack now. But `github-pages-deploy.ts` is still based on `ember-cli`. Will this stay as it is, our should we prepare for webpack plugins?

**Comment by filipesilva** [comment]
Oh wow, good catch! We didn't update `github-pages-deploy.ts` to use the new tasks. I'll put up a PR doing that.

It only really depends on the build task so the logic shouldn't be affected at all.

**Comment by filipesilva** [comment]
I updated https://github.com/angular/angular-cli/pull/1633 to also fix that, since I had to edit it in that PR as well.

**Comment by JohannesHoppe** [comment]
I also reported this here: https://github.com/angular/angular-cli/issues/1672
Going to close it, but will monitor that feature! ;-)

**Comment by filipesilva** [comment]
@JohannesHoppe now with `beta.14` the webpack surface should be stable.

**Pull request closed without merging**
