### PR TITLE
fix(template): remove /... from generated child routes

### LINKED ISSUE #861: When creating child route, CLI adds /...
v1 beta 5

The deprecated router uses `/...` to denote a child router. The CLI is not using the deprecated router. Yet when I create a route and a child route, I get this. There should not be a `/...`

```
  {path: '/foo/...', component: FooComponent}
```

to reproduce:

```
ng new myapp 
ng g r foo
ng g r foo/bar
```

### PR DESCRIPTION
**Pull request by deebloo**
fixes #861

### CODE REVIEW

**Comment by cironunes** [comment]
Could you please squash the commits into one?

**Comment by deebloo** [comment]
@cironunes I sure could

**Comment by deebloo** [comment]
yup got myself into some git trouble. give me a few 😄

**Comment by deebloo** [comment]
yeah. got myself into some rebase issues closing this PR and opening a clean one

**Pull request closed without merging**
