### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by mohitbhatia1994**
Update Angular 2.1.0

### CODE REVIEW

**Comment by mohitbhatia1994** [comment]
I signed it!

**Comment by grizzm0** [comment]
^2.0.0 is equal to >= 2.0.0 && < 3.0.0. There would be no need to up the dependency unless angular-cli uses some features that is not available in 2.0.0.

**Comment by grizzm0** [comment]
Also.. It it's the generated package.json in a new angular-cli project you want to update which currently is locked to ~2.0.0 (equals to >= 2.0.0 && < 2.1.0) then it's ./packages/angular-cli/blueprints/ng2/files/package.json you want to change.

**Comment by grizzm0** [comment]
Also a dupe of #2704

**Comment by filipesilva** [comment]
Superseded by https://github.com/angular/angular-cli/pull/2704

**Pull request closed without merging**
