### PR TITLE
feat: docker init

### PR DESCRIPTION
**Pull request by bbogdanov**
Introducing only the **init** action. 

Tested with a brand new application generated with the latest cli.

Also tested with angular-cli@1.6.5 generated app with the following required actions:
- rm -rf node_modules
- npm link @angular/cli
- ng update --all
- yarn

### CODE REVIEW

**Comment by bbogdanov** [comment]
Bot run

**Comment by bbogdanov** [comment]
Any thoughts on this one?

**Comment by hansl** [comment]
Hi @bbogdanov ,

As much as an `ng docker` command would be interesting, I don't think we're ready to maintain it and the code that comes with this PR. I think the Angular project and the Docker container should be separate commands.

May I suggest that you make a schematic to create new projects with a docker already configured, instead? This is definitely something we support.

Thanks. Unfortunately, I'm going to close this as it is not a feature we're interested in.

**Comment by bbogdanov** [comment]
@hansl Based on your answer maybe you also would like to remove https://github.com/angular/angular-cli/blob/master/docs/design/docker-deploy.md

**Pull request closed without merging**
