### PR TITLE
Update help command in README.md

### PR DESCRIPTION
**Pull request by miltador**
Help command is incorrect with the current version of angular-cli.

### CODE REVIEW

**Comment by miltador** [comment]
I signed it!

**Comment by grizzm0** [comment]
Dupe of #3159
Can be closed.

**Comment by miltador** [comment]
#3159 doesn't fix README.md template.

**Comment by grizzm0** [comment]
It has already been pointed out in the comments

**Comment by filipesilva** [comment]
Dupe of #3159 as @grizzm0 pointed out. I'll be merging that one soon.

**Pull request closed without merging**
