### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by estrellajm**
Swapped the npm cache verify around (line 130). Commented out the npm cache clean for npm version older than 5.

### CODE REVIEW

**Comment by estrellajm** [comment]
I signed it!

Kind Regards,
Jose Estrella
(978) 798-2677
estrellajosem@gmail.com

**Comment by estrellajm** [comment]
I cannot comment on why the Travis CI build failed. I only made a change on the README. Please advise.

**Comment by filipesilva** [comment]
@hansl was able to do that for you 👍

**Comment by estrellajm** [comment]
Makes sense. Will follow moving forward. Forgive the oversight.

**Pull request merged**
