### PR TITLE
fix(@angular/cli): Windows friendly tilde path resolution

### PR DESCRIPTION
**Pull request by douglasduteil**
Ensure that, on Windows, the path doesn't contain back slashes to be PostCSS friendly :)

Following #8791 
Closes #9077 #9061 #9080

### CODE REVIEW

**Comment by maa105** [comment]
this works thanks!

**Comment by clydin** [comment]
Thank you for the contribution.  However, please comment and/or review existing PRs before creating separate ones.  Fixes and improvements may be happening locally and not yet pushed.

**Comment by maa105** [comment]
`gulp.task('fix', function () {

  var line = 'url: ({ url }) => path.join(projectRoot, \'node_modules\', url.substr(1)),';

  var replacement = 'url: ({ url }, { file }) => { const relativePathToRoot = path.relative(file, projectRoot);return path.join(relativePathToRoot, \'node_modules\', url.substr(1)).replace(/\\\\/g, \'/\'); },';
  
  var fileName = '<project>\\node_modules\\@angular\\cli\\models\\webpack-configs\\styles.js';

  var fileContent = fs.readFileSync(fileName, { encoding: 'utf8' });

  var fileReplaced = fileContent.replace(line, replacement);

  fs.writeFileSync(fileName, fileReplaced, { encoding: 'utf8' });
});
`

this is a gulp task that does this fix until it becomes available, hope it helps

**Comment by douglasduteil** [comment]
@clydin > Sorry :confounded:

**Pull request closed without merging**
