### PR TITLE
feat(@angular/cli): support ES2015 target

### PR DESCRIPTION
**Pull request by filipesilva**

### CODE REVIEW

**Comment by jimmykane** [comment]
Thanks for this? Is there a plan for merging this soon ?

**Comment by jimmykane** [comment]
I bow!

**Comment by jimmykane** [comment]
I think a lot of issues on Angular repo should be closed by this, and even more on S.O.

**Comment by pgrm** [comment]
@filipesilva how can I make this work so that AOT builds use es2015, but `ng serve` during development uses es5?

**Comment by MoxxNull** [comment]
When I change target to es2015, ng serve builds without error, but the page won't load, error output is:

> Uncaught TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
    at getParentCtor (core.js:1729)
    at ReflectionCapabilities.parameters (core.js:1542)
    at JitReflector.parameters (compiler.js:26462)
    at CompileMetadataResolver._getDependenciesMetadata (compiler.js:15168)
    at CompileMetadataResolver._getFactoryMetadata (compiler.js:15107)
    at CompileMetadataResolver.getProviderMetadata (compiler.js:15377)
    at JitCompiler._compileModule (compiler.js:25904)
    at SyncAsync.then (compiler.js:25854)
    at Object.then (compiler.js:1629)

Any help on how to find out what's causing this?  Thanks :)

**Comment by MoxxNull** [comment]
@pgrm Good question, I am trying to figure out that aswell...

**Comment by misaunde** [comment]
You could try `ng serve --aot`

**Comment by pgrm** [comment]
@misaunde I do remember in the old and forever long *ng serve is slow* issue, that people got told, to not use `ng serve --aot` because it's slow. Also, I think you can't run unit tests in AOT. So I'm wondering what angular 5 will bring in this regard, because I'm reading everywhere, that AOT will be there by default. But an issue regarding AOT in unit tests is still opened. Maybe @filipesilva could shed some light on what is the best approach now, and how will that probably change with angular 5?

**Comment by filipesilva** [comment]
@pgrm AOT is now much faster with 1.5 and Angular 5 (at the same time), but we won't switch AOT to be the default in 1.5.

**Comment by filipesilva** [comment]
@pgrm https://github.com/angular/angular-cli/issues/7797 is still blocked on Angular itself  for now... I'll respond there with a workaround for now.

@misaunde `ng serve --aot` will also use es2015 if you have it set in your tsconfig.

**Comment by stevebread** [comment]
Does this config apply to global scripts referenced in `apps[0].scripts` in `angular-cli.json`? I am using CLI 1.5.4 with `"target": "es2015"` and still seeing the `Unexpected token` error with a prod build when the scripts use es2015 syntax

**Comment by gordlf11** [comment]
I've installed uglify-es and set my to "target": "es2015" but I am still experiencing an Unexpected token error with a prod build.

image

**Pull request merged**
