### PR TITLE
chore(lint): update tslint

### PR DESCRIPTION
**Pull request by filipesilva**
Update tslint config as per @johnpapa, @mgechev, @foxandxss suggestions.

### CODE REVIEW

**Comment by mgechev** [comment]
Style guide rules are missing. You can find some of them which are used by the docs [here](https://github.com/angular/angular.io/blob/master/tslint.json#L93-L105).

**Comment by Foxandxss** [comment]
Also, we could add the rules to force some kind of prefix. like "my-" and tell the users how to override it.

**Comment by filipesilva** [comment]
@mgechev @Foxandxss I updated the PR with all the rules in docs link. Please confirm this is what was intended.

**Comment by Foxandxss** [comment]
If those are the rules we have at angular.io yes. But I realized that some of them are _really_ strict. After we lint all our codebase I can't tell you that those rules are the best one we can put. In the meantime, sure, you can add those.

On the other hand, what do you think about the `my-` prefixes I said in my last comment?

**Comment by Brocco** [comment]
@Foxandxss you can define a prefix for selectors via `--prefix` in both the new and init commands. Also you can tweak that value in `angular-cli.json` or via `ng set defaults.prefix my`

**Comment by Foxandxss** [comment]
Good, that means that we can add those extra rules here and let the user tune it up.

Perhaps those commands could modify the lint rules too.

**Comment by filipesilva** [comment]
@Foxandxss I think that can be left to another PR though, as it's a bigger piece of functionality.

**Pull request merged**
