### PR TITLE
feat(@angular-devkit/build-angular): favor ESM over FESM bundles

### LINKED ISSUE #13635: [Build optimizer] fesm5 build breaks tree shaking
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] build
```

### Is this a regression?

 No

### Description
Hi, I've noticed that some packages ([ng-bootstrap](https://github.com/ng-bootstrap/ng-bootstrap/issues/2883)) which provide `fesm5` as a default package module doesn't take advandage of build optimizer, importing a single module will include the hole library

## 🔬 Minimal Reproduction

see https://github.com/ng-bootstrap/ng-bootstrap/issues/2883

### PR DESCRIPTION
**Pull request by filipesilva**
Fix #13635 

Blocked by https://github.com/angular/angular/issues/26743, https://github.com/angular/angular/pull/28656

### CODE REVIEW

**Comment by aitboudad** [comment]
using `esm` produce a slight increase in bundle size compared to `fesm` ones, especially `@angular/core` packages:
- ESM5: `~200kb`
- FESM5: `~110kb`

**Comment by filipesilva** [comment]
@aitboudad can you give me more details about how you tested that so I can take a look? 

There were some bugs with Build Optimizer and ESM bundles fixed in https://github.com/angular/angular-cli/pull/13474 that are important for bundle size. I'm mostly testing with `@angular-devkit/build-angular@next`.

**Comment by aitboudad** [comment]
@filipesilva just test any app which use a lazyload route, you may check this one https://github.com/aitboudad/cli-esm-build for example.

**Comment by filipesilva** [comment]
@aitboudad thank you, I can see it in that repro.

A normal `ng build --prod` creates these chunks:
```
chunk {0} runtime.08694c8c8efc22fa3f92.js, runtime.08694c8c8efc22fa3f92.js.map (runtime) 2.2 kB [entry] [rendered]
chunk {1} es2015-polyfills.d86fbce486db1797d2d9.js, es2015-polyfills.d86fbce486db1797d2d9.js.map (es2015-polyfills) 56.5 kB [initial] [rendered]
chunk {2} main.c117f4629509fae856f2.js, main.c117f4629509fae856f2.js.map (main) 252 kB [initial] [rendered]
chunk {3} polyfills.a1aacee915b46004ac1e.js, polyfills.a1aacee915b46004ac1e.js.map (polyfills) 41.1 kB [initial] [rendered]
chunk {4} styles.98be528fdcadb9fc4078.css, styles.98be528fdcadb9fc4078.css.map (styles) 59 bytes [initial] [rendered]
chunk {5} 5.8ef3afd4d758788a0ce7.js, 5.8ef3afd4d758788a0ce7.js.map () 904 bytes  [rendered]
```

If I go into `node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js` and add `esm5` to the top of the `mainFields` list, I get these chunks instead:
```
chunk {0} runtime.94c70a2719145181bc80.js, runtime.94c70a2719145181bc80.js.map (runtime) 2.2 kB [entry] [rendered]
chunk {1} es2015-polyfills.d86fbce486db1797d2d9.js, es2015-polyfills.d86fbce486db1797d2d9.js.map (es2015-polyfills) 56.5 kB [initial] [rendered]
chunk {2} main.e3d028f39954f2091c3b.js, main.e3d028f39954f2091c3b.js.map (main) 357 kB [initial] [rendered]
chunk {3} polyfills.a1aacee915b46004ac1e.js, polyfills.a1aacee915b46004ac1e.js.map (polyfills) 41.1 kB [initial] [rendered]
chunk {4} styles.98be528fdcadb9fc4078.css, styles.98be528fdcadb9fc4078.css.map (styles) 59 bytes [initial] [rendered]
chunk {5} 5.acb78234e382d3d3a3e9.js, 5.acb78234e382d3d3a3e9.js.map () 1.02 kB  [rendered]
```

The main bundle goes from 252kb to 357kb.

**Comment by aitboudad** [comment]
each approach has some side effects, the real fix I think should be landed either in Webpack or Terser.

**Comment by filipesilva** [comment]
I looked at this a bit today and took a bunch of samples at https://github.com/filipesilva/cli-esm-build. 

I think what's happening is that FESM "forces" the single big module to stay together even while other modules are concatenated by webpack (via https://webpack.js.org/plugins/module-concatenation-plugin/). The bigger module makes it easier for Terser to optimize.

The lazy route forces a number of modules to out of concatenated modules. Without FESM, there are many smaller modules that aren't guaranteed to stick together, so Terser can do less. I need to look further into this.

**Comment by alan-agius4** [comment]
Relates to https://github.com/angular/angular-cli/issues/10754

**Comment by filipesilva** [comment]
We've been working on this general problem and we don't think we can switch over to ESM while module concatenation in webpack has so many bailout scenarios, especially around lazy chunks. I'll close this PR for now.

**Pull request closed without merging**
