### PR TITLE
chore(e2e): update to e2e-spec

### PR DESCRIPTION
**Pull request by Shyam-Chen**

### CODE REVIEW

**Comment by hansl** [comment]
Could you point me the issue or the styleguide chapter this is solving?

**Comment by filipesilva** [comment]
@hansl I believe it's this one: https://github.com/angular/angular-cli/issues/835

**Comment by filipesilva** [comment]
And here is the style recommendation: https://angular.io/docs/ts/latest/guide/style-guide.html#!#style-02-11

**Comment by filipesilva** [comment]
Thanks @Shyam-Chen!

**Pull request merged**
