### PR TITLE
feat(module): component optional when generating module

### PR DESCRIPTION
**Pull request by baruchvlz**
As mentioned in #3365 

~~Usage: `ng g m foo --component`~~

### CODE REVIEW

**Comment by baruchvlz** [comment]
Noob me forgot about e2e tests. I will fix and update tomorrow.

**Comment by baruchvlz** [comment]
@filipesilva  Sorry if this is out of line, but I was just wondering if there's a way to trigger the Travis build without having to commit anything. It seems the build cancelled when I pushed the last commit.

**Comment by hansl** [comment]
We're discussing this internally to see if that's the way we want to move forward. The other solution would be to have components generated by default and have a `--no-component` flag (or `--component=false`).

**Comment by baruchvlz** [comment]
If you guys choose to go for the second option I can change the code to fit the need.

**Comment by hansl** [comment]
Okay we're going with this PR as is.

**Comment by hansl** [comment]
Could you add a simple e2e test that actually call your flag? I want to make sure we avoid regressions.

**Comment by hansl** [comment]
Other than adding a test, this LGTM.

**Comment by baruchvlz** [comment]
@hansl Correct me if I'm wrong, but the `--routing` has a e2e test [here](https://github.com/baruchvlz/angular-cli/blob/c97a322ba4d97618b60db6ad297b308683d879e4/tests/e2e/tests/generate/module/module-routing.ts) with it's new functionality. Also, the module default behavior is being tested [here)(https://github.com/baruchvlz/angular-cli/blob/c97a322ba4d97618b60db6ad297b308683d879e4/tests/e2e/tests/generate/module/module-basic.ts), also with the new behavior.

**Comment by hansl** [comment]
@baruchvlz yes, but I want a test that actually uses `--component`. There's no testing on using the flag itself, which is the regression I want to avoid (say we get rid of the flag entirely later on).

**Comment by baruchvlz** [comment]
The `--component` flag itself doesn't exist in the current code base, so I don't think there's any regression. I added the `--component` flag based on the suggestion in the issue and then removed it when it was decided to go a different direction, but the flag was never introduced into the code. 

Sorry if I'm misunderstanding, I don't have experience working with such large projects.

**Comment by hansl** [comment]
No it's okay. We'll add a `--component` flag if/when people request it. LGTM.

**Comment by Meligy** [comment]
I think this default is a bit confusing.

Example: https://github.com/angular/angular-cli/issues/3255#issuecomment-270818087

**Pull request merged**
