### PR TITLE
fix(@angular-devkit/schematics): running external schematics with yarn pnp

### PR DESCRIPTION
**Pull request by michaelfaith**
This change addresses an issue encountered when running external schematics from a yarn pnp workspace.  The function used to resolve a collection json using node used recursion in a way that it effectively walked itself into an exception. Then if the exception is the type it expected, it would keep going.  This was flawed in that yarn with pnp throws a different type of error when it failed to load the mis-constructed collection path (e.g. `/node_modules/@schematics/angular/collection.json/package.json`).  `ENOTDIR` instead of `MODULE_NOT_FOUND`.

This process of intentionally / knowingly walking into an exception seems problematic in
general.  So, I addressed it by first checking if the `schematics` entry in the package
is a relative path.  If it is, then don't construct the collection path from that.  
If entry is not relative, then assume it's pointing at another package and we need
to recurse to get to the actual collection path.

I've tested this in both yarn pnp and non-pnp environments.

## PR Checklist

Please check to confirm your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular-cli/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #25648

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

Fixes: #25648

### CODE REVIEW

**Comment by clydin** [comment]
Thank you for the contribution.
The recursion is used to facilitate the use of package references within the `schematics` field of which the referenced package name could then contain a `schematics` field in its `package.json` that then needs to be resolved. This scenario unfortunately is lacking test coverage currently.
The relative path case appears well covered within this change but the package reference case with `schematics` fields look s like it would fail here. This may lead to breakage of some schematics packages.

**Comment by michaelfaith** [comment]
@clydin thanks for the feedback.  Do you happen to have an example of a package that has their collection declared in that way?  Just so I understand the use case correctly.  Or just as snipped of what that `package.json` entry might look like?

**Comment by michaelfaith** [comment]
I went ahead and added the recursion back in, but after the check for relative path.  Let me know if you feel this addresses the package use-case.

**Review by clydin — APPROVED** [review]
LGTM.

Thank you for taking the time to improve this area of the code.

**Pull request merged**
