### PR TITLE
WIP: webpack 5 support status

### PR DESCRIPTION
**Pull request by valorkin**
This PR is not meant to be merged, but is able to run unit tests with webpack@5
When all green - we have support for webpack@5 :D

### CODE REVIEW

**Comment by valorkin** [comment]
issues top:
- watch mode doesn't work, `this.watcher.close is not a function` 34 errors
- 580 DeprecationWarnings:
  - 229 `[DEP_WEBPACK_COMPILATION_AFTER_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: afterOptimizeChunkAssets is deprecated (use Compilation.hook.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)`
  - 225 `[DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API`
  - 83 `[DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hook.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)`
  - 5 ```[DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
	Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.```
  - 18 `[DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET_PUSH] DeprecationWarning: chunk.files was changed from Array to Set (using Array method 'push' is deprecated)`
  - 20 `[DEP_WEBPACK_MAIN_TEMPLATE_ASSET_PATH] DeprecationWarning: MainTemplate.hooks.assetPath is deprecated (use Compilation.hooks.assetPath instead)`

**Comment by valorkin** [comment]
webpack-source@2 typings in PR already https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47817

**Comment by valorkin** [comment]
// TODO_WEBPACK_5
        // the proper typing is available only in tapable, but importing of it leads to
        // Module 'tapable' is not listed as dependency in package.json
        // (_compilation.hooks as unknown as { processAssets: AsyncSeriesHook<[Record<string, Source>]>; })

**Comment by valorkin** [comment]
fix 3rd party licences
```Running `ng "build" "--prod" "--extract-licenses" "--output-hashing=none"` [silent]...
CWD: /mnt/ramdisk/test-project
ENV: undefined
Last step took 36.33s...

Error: File dist/test-project/3rdpartylicenses.txt was expected to exist but not found...
    at /home/circleci/ng/tests/legacy-cli/e2e/utils/fs.ts:163:24
    at suppressedCallback (fs.js:215:5)
    at FSReqCallback.oncomplete (fs.js:156:23)


Test "tests/build/extract-licenses" failed...
File dist/test-project/3rdpartylicenses.txt was expected to exist but not found...
Error: File dist/test-project/3rdpartylicenses.txt was expected to exist but not found...
    at /home/circleci/ng/tests/legacy-cli/e2e/utils/fs.ts:163:24
    at suppressedCallback (fs.js:215:5)
    at FSReqCallback.oncomplete (fs.js:156:23)```

**Comment by alan-agius4** [comment]
@valorkin, I am assuming we can close this correct?

**Comment by valorkin** [comment]
@alan-agius4 do you have other tracking issue?
Lately had to switch to other activities, but most likely will have to jump back on.

**Comment by alan-agius4** [comment]
There a couple of issues in the issue tracker.

I think it would be best to create small PRs anyways.

**Comment by alan-agius4** [comment]
Closing as per our convo on slack.

**Pull request closed without merging**
