### PR TITLE
chore(docs): fix ng completion command syntax

### PR DESCRIPTION
**Pull request by ejkj**
Unbreak by using single angle bracket for redirecting sderr to stdout

### CODE REVIEW

**Comment by filipesilva** [comment]
@catull you originally wrote this change, can you weigh in?

**Comment by catull** [comment]
@ejkj The fix is interesting.  What do you mean with "Unbreak" ?  Please elaborate.
Are you stating that perhaps it is safer to redirect stderr rather than appending it to stdout ?

**Comment by catull** [comment]
I found a bug in the completion, easily fixable.

The completion falsely suggests that `ng h` is the same as `ng help`; turns out, `ng h` is is invalid.
I missed that one previously.

Expect a new chore(completion) PR.

**Comment by catull** [comment]
As far as the single redirect is concerned, it works the way @ejkj suggests.
So, that fix LGTM, include it and give credit to @ejkj.

**Comment by catull** [comment]
I don't have that branch anymore, will create a new one instead.

**Comment by filipesilva** [comment]
Closing as outdated, the completion command has been vastly improved by @catull meanwhile.

**Pull request closed without merging**
