### PR TITLE
Support xliff2

### PR DESCRIPTION
**Pull request by EvanCarroll**
* Added support for xliff2
* Set xliff2 as default

### CODE REVIEW

**Comment by EvanCarroll** [comment]
CORE already supports xliff2. The CLI should too, and it should default to using it. https://github.com/angular/angular/issues/11735

**Comment by intellix** [comment]
Think it's nice to move forward with xliff2 by default, but it's not the same default as provided by Angular: https://angular.io/guide/i18n#create-a-translation-source-file-with-the-ng-xi18n-tool

> By default, the tool generates a translation file named messages.xlf in the XML Localization Interchange File Format (XLIFF, version 1.2).

**Comment by EvanCarroll** [comment]
@intellix would it get committed if I made the appropriate changes  in @angular/angular first?

**Comment by hansl** [comment]
@EvanCarroll thanks a lot for the PR. Unfortunately, as we follow semver, we won't be able to change the default value until we do a major release (2.0 is the next one).

Supporting the xliff2 format is definitely something we want, so if you remove changing the default from this PR I'll approve it.

Of course, if you change the default in Angular it would be more of a motivation for us. Let us know. You can also file an issue so we can remember to do it when we start a 2.0 branch.

Thanks!

**Comment by EvanCarroll** [comment]
@hansl done, I can patch @Angular/angular and docs to use xliff2, but they have translations in there written in xliff1 and I can't find a tool that works with the ng output in xliff2.

**Pull request merged**
