### PR TITLE
Fix audit vulnerability warnings for 8.3.x

### LINKED ISSUE #16414: Cross-Site Scripting dependency of serialize-javascript
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Hi all, 

Looks like there's an npm audit issue dependant on serialize-javascript.  Currently the dependency is set to v 1.9.1, seems to be resolved in >=2.1.1  

Any eta on if we can update the dependency?

RE: https://npmjs.com/advisories/1426

 Moderate        Cross-Site Scripting
  Package         serialize-javascript
  Patched in      >=2.1.1
  Dependency of   @angular-devkit/build-angular [dev]
  Path            @angular-devkit/build-angular > copy-webpack-plugin > serialize-javascript

  More info       https://npmjs.com/advisories/1426

Please read https://angular.io/guide/security#report-issues on how to disclose security related issues.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

### PR DESCRIPTION
**Pull request by clydin**
Closes #16414

NOTE TO CARETAKER: pending status of `ci/angular: merge status` is incorrect and can be ignored.  The two _missing_ status checks do not exist on this branch.

### CODE REVIEW

**Comment by bbortt** [comment]
Maybe use `terser-webpack-plugin@1.4.3` in order to stay on the minor patch..
anyways +1

**Comment by Nikhilkapoor20** [comment]
any update on this guys ?

**Comment by paprende** [comment]
which release is this fix in?

**Comment by bbortt** [comment]
Unreleased. Would be `0.803.21`..

**Pull request merged**
