### PR TITLE
fix(@ngtools/webpack): Race condition between invalidate & populateWebpackResolver

### PR DESCRIPTION
**Pull request by scott-phillips-sp**

### CODE REVIEW

**Comment by hansl** [comment]
Hey @scott-phillips-sp, could you rebase your changes on top of master?  We reworked the way our travis tests are run and it might help.

I don't see a problem with this PR.

**Comment by dneeleman** [comment]
Can this be picked up? This is really annoying while using webpack --watch.

**Comment by dneeleman** [comment]
Please?

**Comment by dneeleman** [comment]
Anyone?

**Comment by dneeleman** [comment]
Are we waiting for the next eclipse to finish this PR?

**Comment by clydin** [comment]
Since `populateWebpackResolver` no longer exists, this should no longer be necessary.

**Pull request closed without merging**
