### PR TITLE
Update jasmine

### PR DESCRIPTION
**Pull request by alan-agius4**
feat(@schematics/schematics): update jasmine to 3.3.1+

feat(@schematics/angular): update workspace jasmine to 3.3.1+
 
build: update jasmine to 3.3.1+

test: fix chunk in entry test

### CODE REVIEW

**Comment by hansl** [comment]
We don't use Jasmine 3 internally yet, so this PR should be blocked until it's supported inside Google.

**Comment by alan-agius4** [comment]
Odd as Angular/Angular are using Jasmine 3
https://github.com/angular/angular/blob/master/package.json

**Comment by hansl** [comment]
It seems that's the case, but internally we still have Jasmine 2.9.

**Comment by hansl** [comment]
Closing this. Once we support Jasmine 3 internally we can reopen. Until then, there's no advantage from moving the deps.

**Comment by alexeagle** [comment]
Igor told me we need to update externally first so that John Barton can finish the internal update. I think this can land first?

**Comment by alan-agius4** [comment]
@alexeagle, I just rebased, if this needs to go in. It should be all good once it's green.

**Pull request merged**
