### PR TITLE
feat: adds client dir between src and app

### PR DESCRIPTION
**Pull request by Brocco**
Adds a directory layer in preparation for following the style guide in the blueprints
Updates to templates, tests and build process
Related to #316

### CODE REVIEW

**Comment by hansl** [comment]
From appveyor:

>     √ ng generate component test\..\my-comp (313ms)
>     ERR:  { [Error: ENOENT: no such file or directory, uv_chdir] errno: -4058, code: 'ENOENT', syscall: 'uv_chdir' }

Legit?

**Comment by Brocco** [comment]
Yes, AppVeyor failed because the full test run times out after an hour. The check mark means the test passed. I don't know how to rerun that test, thoughts?

**Comment by hansl** [comment]
Just restarted it.

**Comment by hansl** [comment]
Seems like everything is green. LGTM! Please rebase and submit.

**Comment by filipesilva** [comment]
Ran `npm test` manually, since appveyor got stuck.

`78 passing (5m)`

**Pull request merged**
