### PR TITLE
chore(docs): add documentation showing how to include bootstrap

### PR DESCRIPTION
**Pull request by Brocco**
Applies to #2711

### CODE REVIEW

**Comment by Meet91** [comment]
Following this updated doc to integrate Bootstrap with angular-cli results into following module conflicts:
- jquery.js
- tether.js

Details errors are as below:

**ERROR in multi scripts
Module not found: Error: Can't resolve 'C:\word\angular-demo\node_modules\jquery\dist\jquery.js' in 'C:\word\angular-demo\node_modules\angular-cli\models'
 @ multi scripts

ERROR in multi scripts
Module not found: Error: Can't resolve 'C:\word\angular-demo\node_modules\tether\dist\js\tether.js' in 'C:\word\angular-demo\node_modules\angular-cli\models'
 @ multi scripts**

I'm using below configuration:
angular-cli: 1.0.0-beta.20-4
node: 7.1.0(npm-4.0.3)
os: win32 x64
bootstrap : 3.3.7

Any help in this matter would be really appreciated!

Thanks,
Mitesh

**Comment by filipesilva** [comment]
@Meet91 that is because this document shows how to install the current bootstrap version, which is Bootstrap 3, while the readme shows how to install Bootstrap 4.

**Comment by hansl** [comment]
Could you make sure the version is mentionned in the doc?

**Comment by Brocco** [comment]
Updated to include information for both version 3 and version 4

**Comment by hansl** [comment]
LGTM. Let's see Filipe's review.

**Comment by Brocco** [comment]
@filipesilva can you re-review this for me?

**Comment by filipesilva** [comment]
@Brocco bootstrap4 also needs a couple of scripts as listed in https://github.com/angular/angular-cli#global-library-installation:

```
"scripts": [
  "../node_modules/jquery/dist/jquery.js",
  "../node_modules/tether/dist/js/tether.js",
  "../node_modules/bootstrap/dist/js/bootstrap.js"
],
```

I think bootstrap3 also needs `jquery` and `bootstrap.js` (but not tether).

**Comment by Brocco** [comment]
To me,  there are different levels of how to utilize bootstrap.

I was just showing how to reference the CSS and not any of the component JS code. There are different ways to handle that from within angular applications. A lot of people don't want to include jQuery or any other libraries and instead do things the "angular way". Because if we show including those scripts then we should also show how to install both [ng bootstrap](https://github.com/ng-bootstrap/ng-bootstrap) and [ng2 bootstrap](https://github.com/valor-software/ng2-bootstrap) which I think would be overkill.

**Comment by beeman** [comment]
I agree with @Brocco that this guide should not include any 3rd-party JS libs. With that being said, it might be good to emphasize that this guide just includes the style, and refer to the various Angular Bootstrap implementations.

**Comment by Splaktar** [comment]
For the latest Bootstrap 4 w/ SCSS, I use the following to get things working:

In styles.scss (other in a file imported into it):
```
@import '../node_modules/bootstrap/scss/bootstrap';
@import '../node_modules/bootstrap/scss/bootstrap-grid';
```

This way the SASS loader can do its thing properly and I get good IDE support. Not sure if it's the best way, but thought it might be helpful for those using SCSS.

**Pull request merged**
