### PR TITLE
feat:@angular/cli add support for tsx syntax

### LINKED ISSUE #8046: Cli build should support loading modules with *.tsx extension.
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Versions.
```
Angular CLI: 1.5.0-rc.0
Node: 6.11.0
OS: win32 x64
Angular: 5.0.0-rc.2
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cli: 1.5.0-rc.0
@angular-devkit/build-optimizer: 0.0.27
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.33
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0-rc.0
@schematics/angular: 0.0.45
typescript: 2.5.3
webpack: 3.7.1
```

### Repro steps.
1. call `ng new testproject`
2. cd testproject
3. rename src\app\app.component.ts to src\app\app.component.tsx
4. add to tsconfig.json compilerOptions
    "jsx": "react",
    "jsxFactory": "h"
5. call `ng build`

### The log given by the failure.
```
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve './app.component' in 'c:\temp\testproject\src\app'
resolve './app.component' in 'c:\temp\testproject\src\app'
  using description file: c:\temp\testproject\package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: c:\temp\testproject\package.json (relative path: ./src/app)
    using description file: c:\temp\testproject\package.json (relative path: ./src/app/app.component)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        c:\temp\testproject\src\app\app.component doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        c:\temp\testproject\src\app\app.component.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        c:\temp\testproject\src\app\app.component.js doesn't exist
      as directory
        c:\temp\testproject\src\app\app.component doesn't exist
[c:\temp\testproject\src\app\app.component]
[c:\temp\testproject\src\app\app.component.ts]
[c:\temp\testproject\src\app\app.component.js]
[c:\temp\testproject\src\app\app.component]
 @ ./src/app/app.module.ts 9:0-47
 @ ./src/main.ts
 @ multi ./src/main.ts
```

### Desired functionality.
The tsx is providing just extended syntax sugar, which can be used for different porpoises. In my case I'm using mono-repo approach and I'm delivering part of components as web-components where I'm using jsx/tsx.  
For compiler there should not be difference in extension of module. 

Ropen of https://github.com/angular/angular/issues/19691#issuecomment-336222081

### PR DESCRIPTION
**Pull request by wholysz**
Add support for tsx syntax in component files
Closes #8046

### CODE REVIEW

**Comment by wholysz** [comment]
Hello, I tried to reflect needed changes in all files that were relevant, although I'm not sure if I covered all of the edge cases. Especially in `packages/@ngtools/webpack/src/lazy_routes.ts#53`. In my opinion we don't need to ensure that the module will be resolved into `.tsx`, as angular modules are always written in "plain" `.ts`. If you could, please double check that I'm not wrong 😄

**Comment by filipesilva** [comment]
Heya, some tests still seem to be failing. It looks like it's the path resolver.

**Comment by filipesilva** [comment]
@hansl could you have a look?

**Comment by trotyl** [comment]
I guess this is depending on https://github.com/angular/angular/pull/20556, currently Angular compiler/compiler-cli itself is incompatible with `.tsx` file suffix.

**Comment by wholysz** [comment]
@trotyl Thanks! Perhaps you're right. Any ETA for your PR merge? Would love to have it in place :)

@hansl do you find something missing in above changes? The build is failing due to the tests. Can we sync up on gitter regarding this?

**Comment by rsxdalv** [comment]
@wholysz @trotyl The upstream PR has been merged

**Comment by hansl** [comment]
Although we should support TSX files, this PR really needs  to be updated and cleaned up.  Closing this but if you submit a new PR we'll take a look at it. Thanks

**Comment by rsxdalv** [comment]
For anyone stumbling upon this, here's the current workaround: https://gist.github.com/majo44/4862b8e7db6254975669e0a3f9d67a2a
.

**Pull request closed without merging**
