### PR TITLE
refactor(@angular/cli): remove compression plugin

### PR DESCRIPTION
**Pull request by filipesilva**
Followup from #4618

### CODE REVIEW

**Comment by wulfsberg** [comment]
I am a little surprised by this change. One thing I like about Angular-CLI is the way it handles all the steps needed to produce a production-ready deployment output.
I can see why gzipping may not always be appropriate, and as such may not strictly be a core feature of Angular CLI, but it is a step which requires some build tool on top of just naive copying between deployment folders.
This means that we'll have to add yet another build tool to the chain on top of Angular CLI to provide this step; something I am really not fond of.
Are there any plans for re-introducing this as an easy plugin?

**Comment by filipesilva** [comment]
@wulfsberg the reasoning for this change can be found https://github.com/angular/angular-cli/pull/4618#issuecomment-279175818

No plans of re-introducing it ourselves. Sounds perfectly possible with the upcoming plugin architecture.

**Comment by sebastiannm** [comment]
Would not be better then to remove this feature once it's easy to do with the new plugin architecture?

**Comment by rkrzewski** [comment]
https://github.com/angular/angular-cli/pull/4618#issuecomment-279175818 says that there is an easy workaround and asks for documenting how it can be enabled by end users. Where can I find such information? This PR removed the feature, but did not add any docs AFAICT.
Also, https://github.com/angular/angular-cli/pull/4702#issuecomment-280623583 mentions "upcoming plugin architecture" does this mean that the mentioned workaround is not possible until that feature lands?

**Comment by chouclee** [comment]
At least give us a flag to enable it ╮(╯▽╰)╭

**Comment by abcfy2** [comment]
Is there any other ways to compress text files?

**Comment by Anufriev** [comment]
Hello guys!

I'm using workaround with gulp.

`npm install --save-dev gulp`
`npm install --save-dev gulp-gzip`

I changed script section of package.json
`"scripts": {
    "ng": "ng",
    "start": "ng serve",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "build-prod": "ng build -t production -e prod && gulp compress"
  },`

And I added gulpfile.js in the root directory (next to the package.json)
`var gulp = require('gulp');
var gzip = require('gulp-gzip');
 
gulp.task('compress', function() {
    gulp.src(['./dist/*.js', './dist/*.css'])
    .pipe(gzip())
    .pipe(gulp.dest('./dist'));
});`

I run building via `npm run build-prod`

**Comment by sebastiannm** [comment]
Hi @Anufriev,

that didn't worked perfectly. But changing to this works:

```
gulp.src(['./dist/*.js', './dist/*.css'])
```

**Comment by tibbus** [comment]
oh man, so sad to hear, I loved the gzip feature 😞

**Comment by h4b00** [comment]
You should guys leave it as special option with additional flag.

**Comment by kambbado** [comment]
@Anufriev, did you have to modify the index.html file or the lazy load?  I tried your suggestion and I was not able to get it to work.

**Comment by steve-todorov** [comment]
@filipesilva I wasn't able to find any documentation on the new plugin architecture for angular-cli. Is it still in development and if so will it be released soon? So far using `ng eject` does the job for me but I'm interested in what could be achieved with the plugin architecture :)

**Comment by riddla** [comment]
So, what is the "easy workaround" then? https://github.com/angular/angular-cli/pull/4618#issuecomment-279175818 talks about it but does not explain it ...

**Pull request merged**
