### PR TITLE
docs: fix typo in ng update --next description

### PR DESCRIPTION
**Pull request by vltansky**
`--next` arg description probably should be 
Use the **latest** version, including beta and RCs and not **largest**

### CODE REVIEW

**Comment by vltansky** [comment]
@googlebot I signed it!

**Comment by alan-agius4** [comment]
@vltansky, I think this was not a mistake, as latest, might get confused with latest tag.

Maybe a better word would be `prerelease.`

**Comment by vltansky** [comment]
@alan-agius4 updated to `prerelease`

**Comment by alan-agius4** [comment]
@vltansky thanks.

**Comment by alan-agius4** [comment]
**Caretaker note**: please squash commits when merging.

**Pull request merged**
