### PR TITLE
fix(e2e): return exit codes on failure of e2e tests

### LINKED ISSUE #1017: ng e2e
Hi all! Thanks for your hard work on angular-cli. It seems that `ng e2e` returns a status code of `0` even when it fails. This makes continuous integration painful. I have purposefully demonstrated a scenario below where my tests fail, and I expected angular-cli to be returning `1`.

```
$ ng e2e

> myproject@0.0.0 pree2e /code/myproject/web
> webdriver-manager update

selenium standalone is up to date.
chromedriver is up to date.

> myproject@0.0.0 e2e /code/myproject/web
> protractor "config/protractor.conf.js"

[18:30:07] I/direct - Using ChromeDriver directly...
[18:30:07] I/launcher - Running 1 instances of WebDriver
Spec started

myproject-web App
    ✗ should display message saying app works
      - Failed: Angular could not be found on the page http://localhost:4200/ : retries looking for angular exceeded

**************************************************
*                    Failures                    *
**************************************************

1) myproject-web App should display message saying app works
  - Failed: Angular could not be found on the page http://localhost:4200/ : retries looking for angular exceeded

Executed 1 of 1 spec (1 FAILED) in 10 secs.
[18:30:19] I/launcher - 0 instance(s) of WebDriver still running
[18:30:19] I/launcher - chrome #01 failed 1 test(s)
[18:30:19] I/launcher - overall: 1 failed spec(s)
[18:30:19] E/launcher - Process exited with error code 1

Some end-to-end tests failed, see above.

$ echo $?
0
```

If I run the underlying protractor configuration, I get the result I expected:

```
$ protractor config/protractor.conf.js
Using ChromeDriver directly...
[launcher] Running 1 instances of WebDriver
Spec started

  myproject-web App
    ✗ should display message saying app works
      - Failed: Angular could not be found on the page http://localhost:4200/ : retries looking for angular exceeded

**************************************************
*                    Failures                    *
**************************************************

1) robotic-audit-web App should display message saying app works
  - Failed: Angular could not be found on the page http://localhost:4200/ : retries looking for angular exceeded

Executed 1 of 1 spec (1 FAILED) in 10 secs.
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1

$ echo $?
1
```

Issue checklist:

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
OS X Yosemite (10.10.5)

2. Versions. Please run `ng --version`
```
$ ng --version
angular-cli: 1.0.0-beta.5
node: 5.4.1
os: darwin x64
```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
No changes. Generated using CLI.

4. The log given by the failure. Normally this include a stack trace and some
   more information.
See above.

### PR DESCRIPTION
**Pull request by marc-sensenich**
If there is an error, returns the exit code associated with the error in the promise, else returns 0.

Fixes #1017

### CODE REVIEW

**Comment by filipesilva** [comment]
Thanks for the contribution! Overall it looks good, but seems to be failing on OSX. I restarted it but it's still failing. Can you have a look?

**Comment by marc-sensenich** [comment]
I'll look into that issue and try to replicate it locally. I haven't been able to replicate on my MacBook.

**Comment by filipesilva** [comment]
It seems to fail not on your new tests, but rather on our e2e suite. 

That might be because since you fixed the `ng e2e` error codes, that is uncovering an existing error. It might also be because there is some issue in running it in sequence.

It might be helpful to print stdout and stderr in https://github.com/angular/angular-cli/blob/master/tests/e2e/e2e_workflow.spec.js#L130 to see what's wrong when running on the CI.

**Comment by marc-sensenich** [comment]
I matched the change you made on .travis.yml and it ran successfully on my Travis instance https://travis-ci.org/marc-sensenich/angular-cli/builds/136321458. It seems to be failing on the projects instance

**Comment by filipesilva** [comment]
@marc-sensenich the new failures were due to a recent change in master. The old failures where because it turns out that `ng e2e` never worked on travis OSX, because of the chrome versions. I merged your code in, but moved the acceptance test into the e2e workflow.

I did this because I ran into a situation where the acceptance test was accepting failures in the `ng e2e` command while debugging. This has happened before and it's the reason why most tests that deal with the generated project are ran in `e2e_workflow.spec.js`.

Thanks for picking this issue up by the way, it was leading to some hard to detect silent fails!

**Pull request closed without merging**
