### PR TITLE
fix(@angular/cli): show errors after warnings

### PR DESCRIPTION
**Pull request by Taha-Di-Nero**

### CODE REVIEW

**Comment by Taha-Di-Nero** [comment]
Of course

**Comment by Taha-Di-Nero** [comment]
@filipesilva why merging is blocked ??

**Comment by filipesilva** [comment]
Sorry it took awhile for me to come back to this PR. I've re-reviewed it and it should be ready. Thanks!

**Comment by clydin** [comment]
It looks like this is moving the warnings before the output stats.  I'm not sure this is a good idea as this can cause any warnings to be easily missed.  Warnings and errors are both diagnostic messages and I think it would make more sense to group them together as such.  Also, errors are already shown after warnings.  So the current order is information, warnings, errors.  This represents an increasing level of severity and therefore shows the most urgent message last; which could be considered the order of most utility.

In regards to the actual underlying concern of too much text being displayed in a small console window, PR #8875 should provide partial relief.  In addition, further work on reducing the verbosity of warnings and errors would also be a fruitful effort in this regard.

**Comment by filipesilva** [comment]
To be honest I misunderstood the original issue (#8292). I thought warnings were actually showing after errors. 

I agree with @clydin here: the warnings are already being shown before the errors so I don't think there's any need to change.

Apologies for that... I should have read read the issue and PR with more attention.

**Pull request closed without merging**
