### PR TITLE
fix(@angular/cli): fix empty 3rdpartylicenses.txt

### LINKED ISSUE #6921: 3rdpartylicenses.txt is empty
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.2.0
node: 8.1.3
os: linux x64
@angular/animations: 4.2.5
@angular/common: 4.2.5
@angular/compiler: 4.2.5
@angular/core: 4.2.5
@angular/forms: 4.2.5
@angular/http: 4.2.5
@angular/platform-browser: 4.2.5
@angular/platform-browser-dynamic: 4.2.5
@angular/router: 4.2.5
@angular/cli: 1.2.0
@angular/compiler-cli: 4.2.5
@angular/language-service: 4.2.5
```

### Repro steps.
`ng new myproject`
`cd myproject`
`ng build --target=production`
The file `dist/3rdpartylicenses.txt` will be empty.

### The log given by the failure.

No log 

### Desired functionality.

3rdpartylicenses.txt should contain the licenses of all modules loaded from node_modules

### Mention any other details that might be useful.

* I am the author of the webpack plugin that outputs the licenses. I have already pushed a fix in version 0.5.1 of license-webpack-plugin. Upgrading the version of license-webpack-plugin should resolve the issue.
* https://github.com/xz64/license-webpack-plugin/issues/12

### PR DESCRIPTION
**Pull request by xz64**
Upgrades license-webpack-plugin from 0.4.x to 0.5.x.

Closes #6921

### CODE REVIEW

**Comment by xz64** [comment]
Hi @filipesilva, I have rebased the branch.

**Comment by filipesilva** [comment]
@xz64 I'm so sorry, yesterday we made the move from yarn to npm5 (https://github.com/angular/angular-cli/pull/7060) and all PRs that changed dependencies became invalidated. Can you rebase again, and not commit the yarn lock please?

**Comment by xz64** [comment]
It is rebased now, without a yarn.lock file.

**Comment by filipesilva** [comment]
It's in now, thanks again for your work @xz64 👍

**Pull request merged**
