### PR TITLE
fix(@ngtools/webpack): Bump loader-utils and use getOptions

### PR DESCRIPTION
**Pull request by ryani33**
fix deprecated warning
deprecated-warning

link: webpack/loader-utils#56

### CODE REVIEW

**Comment by filipesilva** [comment]
There's a CI error but it's unrelated to your PR. If you rebase it the error should go away.

**Comment by ryani33** [comment]
All set~ @filipesilva

**Comment by ryani33** [comment]
If there is something I need to do, please let me know~

**Comment by filipesilva** [comment]
@ryani33 no, there wasn't anything else you needed to do. Sometimes a bunch of commits are merged together at the same time, that's all.

Thanks for fixing this!

**Pull request merged**
