### PR TITLE
feat(@angular/cli): support 5.0.0+ builds of @angular/service-worker

### PR DESCRIPTION
**Pull request by alxhub**

### CODE REVIEW

**Comment by alxhub** [comment]
This will likely have issues on Windows until Angular 5.0.0-rc.3 is released, due to https://github.com/angular/angular/commit/621f87b2bde074d5317689f544f90714876dbbdc.

**Comment by StephenFluin** [comment]
It throws an error when I don't have an ngsw.json file in `src`, is that intentional or am I doing something wrong? Perhaps it could warn the user and link them to an example file?

```
return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
               ^
Error: ENOENT: no such file or directory, open '/usr/local/google/home/stephenfluin/workspace/devfest/src/ngsw.json'
```

**Comment by alxhub** [comment]
I added an explicit error if the file is not found, @StephenFluin :)

**Comment by ivancamilov** [comment]
we're on 5.0.0-rc.5, so this should work on Windows now. Hopefully this can be merged soon.

**Comment by Taha-Di-Nero** [comment]
@alxhub  Why version 5.1.0-beta.2 is not supported ?? I used master build.

> The installed version of @angular/service-worker is 5.1.0-beta.2. This version of the CLI
> requires the @angular/service-worker version to satisfy >= 1.0.0-beta.5 < 2.0.0. Please upgrade
> your service worker version.

**Pull request merged**
