### PR TITLE
feat(@angular/cli): show more version information

### PR DESCRIPTION
**Pull request by hansl**
Group all Angular packages that have the same version as @angular/core, and
also show information for schematics, devkit and others that might not be
in the package.json but still installed. Those versions are important.

### CODE REVIEW

**Comment by hansl** [comment]
The new `ng version` looks like this:

```
 ng version

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: local (v1.5.0-beta.4, branch: master)
Node: 8.3.0
OS: darwin x64
Angular: 4.4.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, tsc-wrapped

@angular/cli: 1.5.0-beta.4
@angular-devkit/build-optimizer: 0.0.26
@angular-devkit/core: 0.0.19
@angular-devkit/schematics: 0.0.32
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.7.2
@schematics/angular: 0.0.44```

**Comment by Toxicable** [comment]
@hansl The current one show the `typescript` version but i don't see it in your output above. Is this intended?

**Comment by hansl** [comment]
It should be there. Let me double check.

**Comment by hansl** [comment]
@Toxicable Fixed, and added webpack version too.

**Pull request merged**
