### PR TITLE
feat(@angular/cli): support inlining SVG within stylesheets

### PR DESCRIPTION
**Pull request by clydin**
Leverages postcss-url to handle inlining which provides support for SVG inlining.
This has several advantages:
* Increased performance -- inlining is performed in-place
* SVG URLs with fragment identifiers are maintained (future work will allow for fragment extraction)
* Inlined SVGs are automatically optimized when targeting production.

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Have you considered altering the webpack config to use url-loader? That should be more consistent.

**Comment by hansl** [comment]
Any reason this failed on Appveyor? I can't seem to figure any error out from the logs.

**Comment by filipesilva** [comment]
Fluke I guess, restarted it.

**Comment by filipesilva** [comment]
Blocked on the release of cssnano 4.0.

**Pull request merged**
