### PR TITLE
docs(@ngtools/webpack): remove `sourcemap` from loader settings

### PR DESCRIPTION
**Pull request by alan-agius4**
Related to #8301

### CODE REVIEW

**Comment by alan-agius4** [comment]
updated

**Comment by alan-agius4** [comment]
updated & fixed CLA issue, as I pushed from another account.

**Comment by filipesilva** [comment]
The changes themselves LGTM, but the CLA bot got stuck I believe. Can you add a comment directed at the google bot saying you are ok with your commit being used please? That should be all that's needed.

**Comment by alan-agius4** [comment]
@googlebot I am okay with the commit

**Comment by alan-agius4** [comment]
@googlebot I am okay with the commit ad3f449124b432554053b181f03e6f0f897a6b9c

**Comment by alan-agius4** [comment]
it looks like the google bot is still stuck :(

**Comment by filipesilva** [comment]
I think at this point it's up to the current caretaker to merge despite the cla bot.

**Comment by hansl** [comment]
I confirm that @alan-agius4 has signed the CLA.

**Pull request merged**
