### PR TITLE
Extract messages libs

### LINKED ISSUE #18871: Bug: ng xi18n --ivy does not extract i18n tokens from libraries
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [x] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

This works with `ng xi18n`

### Description

`ng xi18n --ivy` does not extract i18n tokens from libraries, whereas `ng xi18n` is able to extract it from libraries compiled with ViewEngine.

## 🔬 Minimal Reproduction

https://github.com/kyubisation/xi18n-ivy-library-viewengine
Run `npm ci && npm test` (which build the ViewEngine and Ivy libraries and runs xi18n) and check messages.xlf

## 🌍 Your Environment
<pre><code>

Angular CLI: 10.1.3
Node: 12.9.1
OS: win32 x64

Angular: 10.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.3
@angular-devkit/build-angular   0.1001.3
@angular-devkit/core            10.1.3
@angular-devkit/schematics      10.1.3
@schematics/angular             10.1.3
@schematics/update              0.1001.3
ng-packagr                      10.1.0
rxjs                            6.6.3
typescript                      4.0.3

</code></pre>

**Anything else relevant?**

### LINKED ISSUE #18885: Exclude directories from "ng xi18n"
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [x] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
The tool parses imported third party modules in node_modules folder too and there is no way to exclude directories from parsing. For example:

create an new app
`ng new repro-app`

install a third party module
`npm @ng-bootstrap/ng-bootstrap`

import this module in the app.module.ts

```
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
...
imports: [
    ...
      NgbModule
  ]
...

```
run xi18n
`ng xi18n --output-path src/locale --i18n-locale=de`

look in the generated messages.xlf

```
<trans-unit id="ngb.alert.close" datatype="html">
	<source>Close</source>
	<context-group purpose="location">
		<context context-type="sourcefile">node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.d.ts</context>
		<context context-type="linenumber">3</context>
	</context-group>
</trans-unit>
```

As you cas see the file contains translation units from a third party module although we don,t use it in our templates.

### Describe the solution you'd like

A command line parameter --exclude=path/one,path/two will solve my problem. Alternatively (or at once) the parameter --include=path/one, path/two will be helpful. 

### Describe alternatives you've considered

I could postprocess the messages.xlf with a custom tool to remove unwanted translation units.

### PR DESCRIPTION
**Pull request by alan-agius4**
**feat(@angular-devkit/build-angular): extract i18n messages from libraries**

Closes #18871

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
LGTM! SImple and neat solution.

**Comment by kyubisation** [comment]
Thank you very much for your work on this issue. 👍 
To avoid any misunderstandings; Our primary use case from #18871 is extraction of i18n tokens from libraries in node_modules and not from "local" libraries.
Due to my limited understanding of the extractor, I cannot discern if this would be handled with this solution.

**Comment by alan-agius4** [comment]
> To avoid any misunderstandings; Our primary use case from #18871 is extraction of i18n tokens from libraries in node_modules and not from "local" libraries.
> Due to my limited understanding of the extractor, I cannot discern if this would be handled with this solution.

This works for both local and node_modules libraries.

**Comment by kyubisation** [comment]
Thank you very much for the clarification and again for your work on this! ❤️

**Review by clydin — APPROVED** [review]

**Comment by santam85** [comment]
@petebacondarwin @alan-agius4 are you planning to merge this for a 10.1.x patch too?

**Comment by alan-agius4** [comment]
@santam85, No this feature will not be back ported to v10.

**Pull request merged**
