### PR TITLE
docs(serve): fix webpack links

### PR DESCRIPTION
**Pull request by fasfsfgs**
Fix some links to old webpack’s website that doesn’t work anymore.

### CODE REVIEW

**Comment by fasfsfgs** [comment]
Actually #9055 was about other files. I separated `.md`files and `.ts` files in different PRs.

But I just did all changes in this one and changed the commit message to something you suggested, but with a broader sense since I'm changing more than just the `serve.ts` file now.

Thanks for reviewing it. =)

**Comment by filipesilva** [comment]
Oh I'm sorry for closing the other one then! I thought they were the same but you were using the github web UI to make a new commit message (that happens a lot). Sorry!

**Comment by fasfsfgs** [comment]
That's no problem.
Is there anyway to rerun travis-ci? It threw an error on `npm install` with network issues.

**Comment by filipesilva** [comment]
I'll re-run it, npm seems to have have some problems today.

**Comment by fasfsfgs** [comment]
Thanks! Ok it passed. I guess it has to manually start the remaining steps there?

**Comment by filipesilva** [comment]
All done now, thanks!

**Pull request merged**
