### PR TITLE
fix(@ngtools/webpack): fix lazy loading new Error emit after webpack …

### PR DESCRIPTION
**Pull request by rayros**
…detect lazy module file change

https://github.com/angular/angular-cli/issues/4326#issuecomment-276794698

### CODE REVIEW

**Comment by hansl** [comment]
@rayros Could you explain how this relates to the issue you pointed at?  That issue is from February and has been fixed.

**Comment by rayros** [comment]
Ok, I create angular 2 project and use lazy loading for some module, when i change something in this module webpack throw the same error which i pointed at description. This error not occurs on the first build.

**Comment by rayros** [comment]
Do you want a example repository?

**Comment by JaSpr** [comment]
bump

**Comment by JaSpr** [comment]
bump

**Comment by JaSpr** [comment]
@rayros Have you been able to rebase your changes, so that the changes can be merged in?

**Pull request closed without merging**
