### PR TITLE
build: set up ts-circular-deps check to prevent new circular deps

### PR DESCRIPTION
**Pull request by josephperrott**
The repo current has zero circular typescript dependencies, this check will ensure no circular dependencies are added.

### CODE REVIEW

**Comment by clydin** [comment]
There's a tslint rule in place that checks for circular imports: https://github.com/angular/angular-cli/blob/master/tslint.json#L6
https://www.npmjs.com/package/tslint-no-circular-imports

**Comment by alan-agius4** [comment]
@josephperrott should this be closed? Since we are handling circular deps with tslint?

**Comment by josephperrott** [comment]
@alan-agius4 and I spoke offline, and I believe its still an open question of if this should be added/included.

My main concern is that we prevent circular deps, which is already being done in this repository.  The argument for merging this in is to have the same method for circular deps discovery/enforcement used across our org.

**Comment by alan-agius4** [comment]
Closing in favor of https://github.com/angular/angular-cli/pull/20655

**Pull request closed without merging**
