### PR TITLE
build: use npm5 instead of yarn

### PR DESCRIPTION
**Pull request by filipesilva**

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
npm5 is not faster than yarn, and I have heard that it can be buggy in some cases. I would recommend staying with yarn.

**Comment by filipesilva** [comment]
I agree with you that it's not faster, and that there are bugs. But the reason for moving isn't so much the speed, but the interop.

Right now it's pretty painful to develop with a linked cli and npm5. You need to `npm link && rm -rf node_modules/ && yarn` on the CLI dir. And then on the linked project, linking and then installing something else will break the modules as well. This is very frustrating as a CLI dev.

Another factor is that even though the CLI itself uses yarn, when in our e2e tests we use `npm` to ensure compatibility with most users. So using npm everywhere also has benefits.

It also helps that `package-lock.json` is pretty decent, and that it doesn't depend on the package manager version like yarn does.

Overall I do expect `package-lock.json` to become the standard.

**Comment by diagramatics** [comment]
So bringing this topic back up again, I noticed Angular's now switched to Yarn with https://github.com/angular/angular/pull/19328. Is the team's stance changing again?

**Comment by filipesilva** [comment]
No plan to change at the moment, no.

**Pull request merged**
