### PR TITLE
feat(@angular/cli): Add postcss plugins

### PR DESCRIPTION
**Pull request by mikkeldamm**
Makes it possible to define postcss plugins that should be used with the postcss-loader. It is done be defining the plugins in the cli config as so:

```
"environments": { ... },
"postCssPlugins": [
    "postcss-cssnext",
    "postcss-nested",
    "postcss-mixins",
    ...
]
```

### CODE REVIEW

**Comment by dominikg** [comment]
given that bootstrap4 uses postcss-flexbugs-fixes[1] to generate its css this PR would enable angular-cli users to do the same and avoid issues[2] when integrating bootstrap4 source scss instead of dist css.

[1] https://github.com/twbs/bootstrap/pull/19109
[2] https://github.com/twbs/bootstrap/issues/20760

**Comment by mikkeldamm** [comment]
@hansl @filipesilva can anyone of you look at this? 😺

**Comment by filipesilva** [comment]
I'm sorry, but this sort of costumization is not something we're looking at adding right now. It's not as simple as just adding the names, some plugins also need args and they need to be installed. 

Can you instead open an issue where this can be discussed?

**Comment by cedvdb** [comment]
@filipesilva similar to OP https://github.com/angular/angular-cli/issues/7514

**Pull request closed without merging**
