### PR TITLE
initial support for support jade/pug templates

### PR DESCRIPTION
**Pull request by tycho01**
This is an attempt to continue the existing PR 2205 in the absence of its creator, ShadowManu. The scope of the original PR has been left intact here, though I've attempted to add some rudimentary documentation/tests as had been requested of the original PR.

### CODE REVIEW

**Comment by tycho01** [comment]
Note: comments after my first post until the googlebot post appear to be from my own repo from a few months ago. Feel free to ignore them.
The original PR by @ShadowManu for this could be found [here](https://github.com/angular/angular-cli/pull/2205), where he stated he was having trouble incorporating the requested changes as he was on travel. Given he signed the CLA there as well, I hope that addresses the GoogleBot concern that part of the commits here were his.

Edit: I can reproduce the CI failure at `run test:deps`, though not using its underlying command `node scripts/publish/validate_dependencies.js`. Hm.

**Comment by ShadowManu** [comment]
Just to confirm. I do accept my commits to be contributed to Angular CLI ;) 

@tycho01 I'll try to get active, just that I work until night and I'm left too exhausted for the weekends. But I'll try to help wrap this up.

**Comment by tycho01** [comment]
Sure, that works for me :), I suppose I've been sufficiently excited about getting initial support in I wouldn't mind helping out where possible.

**Comment by ShadowManu** [comment]
We run pug-cli alongside ng start, so it has been low on priority for our team.

**Comment by filipesilva** [comment]
Closing, please see https://github.com/angular/angular-cli/issues/1886#issuecomment-281332399 for context.

**Pull request closed without merging**
