### PR TITLE
fix: using local npm 2 from ember-cli dependency while ng init

### LINKED ISSUE #2179: Init error (npm 2 dependency)
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Ubuntu 14.04

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
```
angular-cli: 1.0.0-beta.14
node: 6.6.0
os: linux x6
```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

`ng init`

4. The log given by the failure. Normally this include a stack trace and some
   more information.

```
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
installing ng2
  identical .editorconfig
  create README.md
  create src/app/app.component.css
  create src/app/app.component.html
  create src/app/app.component.spec.ts
  create src/app/app.component.ts
  create src/app/app.module.ts
  create src/app/index.ts
  create src/app/shared/index.ts
  create src/assets/.gitkeep
  create src/assets/.npmignore
  create src/environments/environment.prod.ts
  create src/environments/environment.ts
  create src/favicon.ico
  create src/index.html
  create src/main.ts
  create src/polyfills.ts
  create src/styles.css
  create src/test.ts
  create src/tsconfig.json
  create src/typings.d.ts
  create angular-cli.json
  create e2e/app.e2e-spec.ts
  create e2e/app.po.ts
  create e2e/tsconfig.json
  identical .gitignore
  create karma.conf.js
  create package.json
  create protractor.conf.js
  create tslint.json
Installing packages for tooling via npm.
npm WARN prefer global marked@0.3.6 should be installed with -g
npm WARN prefer global node-gyp@3.4.0 should be installed with -g
npm WARN prefer global npm@2.14.21 should be installed with -g
npm WARN unmet dependency /home/valeryvs/Git/angular-cli-test-4/node_modules/angular-cli requires protractor@'^3.3.0' but will load
npm WARN unmet dependency /home/valeryvs/Git/angular-cli-test-4/node_modules/protractor,
npm WARN unmet dependency which is version 4.0.5
npm WARN unmet dependency /home/valeryvs/Git/angular-cli-test-4/node_modules/angular-cli requires tslint@'^3.15.1' but will load
npm WARN unmet dependency /home/valeryvs/Git/angular-cli-test-4/node_modules/tslint,
npm WARN unmet dependency which is version 3.13.0
npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/home/valeryvs/Git/angular-cli-test-4/node_modules/.bin/npm" "install"
npm ERR! node v6.6.0
npm ERR! npm  v2.14.21
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package webpack@2.1.0-beta.22 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer html-webpack-plugin@2.22.0 wants webpack@*
npm ERR! peerinvalid Peer karma-webpack@1.8.0 wants webpack@^1.1.0 || ^2 || ^2.1.0-beta
npm ERR! peerinvalid Peer sass-loader@3.2.3 wants webpack@^1.12.6 || ^2.1.0-beta
npm ERR! peerinvalid Peer string-replace-loader@1.0.3 wants webpack@1.x.x || 2.x.x
npm ERR! peerinvalid Peer webpack-dev-server@2.1.0-beta.4 wants webpack@^2.1.0-beta

npm ERR! Please include the following file with any support request:
npm ERR!     /home/valeryvs/Git/angular-cli-test-4/npm-debug.log

Package install failed, see above.

```

5. Mention any other details that might be useful.

Package
 ember-cli@2.5.0
depends on
 npm@2.14.21

"Installing packages for tooling via npm." use this npm@2

But `npm 2` can not install new webpack.
https://github.com/Hashnode/mern-cli/issues/12
https://github.com/kentcdodds/es6-todomvc/issues/4

### PR DESCRIPTION
**Pull request by ValeryVS**
fix #2179 
look for `my/path/to/project/node_modules/.bin` and exclude it from path for `npm install` command

### CODE REVIEW

**Comment by ValeryVS** [comment]
The best solution, of course - do not use npm 2 as local dependency. But, pobably, it is not smple task yet.
Also we can beware developers of using `node_modules/.bin` in path.
Modifying path probably looks hacky, but it works.

**Comment by ValeryVS** [comment]
Actually, we shouldn't use RegExp like this.
Just exclude

- npm bin output
- node_modules/.bin
- node_modules\.bin

should be enough.

And, we can check npm -v before install.

I fix PR tomorrow.

**Comment by ValeryVS** [comment]
It is done.

- runs `npm bin`
- exclude from path:
- - `npm bin`'s output
- - `node_modules/.bin`
- - `node_modules\.bin`
- runs `npm install`

**Comment by ValeryVS** [comment]
Rebased to master

**Comment by filipesilva** [comment]
Closed, reasoning in https://github.com/angular/angular-cli/issues/2179#issuecomment-251251820.

**Pull request closed without merging**
