### PR TITLE
feat(generate): Enable route generation for @angular/router v3

### PR DESCRIPTION
**Pull request by delasteve**
Eventually will fix https://github.com/angular/angular-cli/issues/1093

Route generation checklist:
- [x] Recreate `ng generate route`
- [x] Create `ng generate guard` and spec file
- [x] Create `app.routes.ts` boilerplate
- [x] Export `./app.routes` in app barrel
- [x] Import and bootstrap `APP_ROUTER_PROVIDERS`
- [x] Create blueprint for routes file
- [x] Allow `--lazy` to be set
- [ ] Allow custom `--path` to be set
- [ ] Modify parent `{component}.routes.ts`

If I am missing anything, please let me know and I will add it to the list.

### CODE REVIEW

**Comment by webia1** [comment]
thank you, it works for me:

```
$ ng generate route test
installing route
installing component
  create src\app\+test\test.component.css
  create src\app\+test\test.component.html
  create src\app\+test\test.component.spec.ts
  create src\app\+test\test.component.ts
  create src\app\+test\index.ts
  create src\app\+test\shared\index.ts
```
would you update the main repository, would be great,..

**Comment by jasonswett** [comment]
Dumb question, but how do I try out this new version? I tried doing `npm install -g git+ssh://git@github.com:delasteve/angular-cli.git\#feature/router-v3` but it didn't seem to work.

**Comment by webia1** [comment]
the changes are not merged yet, I've edited the source codes manually,..

**Comment by filipesilva** [comment]
I'd like to add a caveat to this PR: we're still waiting on some initial style guide recommendations about how routes should look like with the new router, and that will eventually determine how generation ends up working/looking like.

**Comment by delasteve** [comment]
Totally agree and understood. See the conundrum I got myself into. 😝

**Comment by hansl** [comment]
We already have someone internally working on making `ng generate route` works properly again. The project is limited to route configuration, and does not include guards. I'm going to put this PR on hold until we re-enable route generation and then we can discuss more about adding guards to the project as a new feature.

Cheers!

**Comment by Brocco** [comment]
Routes have changed drastically and currently there are no plans to generate specific routes, only routing module files.

**Pull request closed without merging**
