### PR TITLE
(feature proposal) Add universal option to ng-new

### PR DESCRIPTION
**Pull request by Fufuxx**
(feature proposal) Add universal option to ng new #14963 

Hope I am doing this right. This is my first ever contribution -> Please let me know if anything needs to be amended / modified.

### CODE REVIEW

**Comment by mgechev** [comment]
@Fufuxx before opening a PR with a large feature, I'd strongly recommend to first open an issue where we can discuss the impact and whether it aligns with the scope of the project.

I added the PR for further discussion. We'll talk about the implementation and come back to you next week.

**Comment by Fufuxx** [comment]
@mgechev Thanks for looking into this.
There is a related issue that has been opened up -> #14963

**Comment by alan-agius4** [comment]
I am going to remove the needs further discussion from the PR, as the original issue has a `need: further discussion`  already.

**Comment by alan-agius4** [comment]
Closing as per https://github.com/angular/angular-cli/issues/14963#issuecomment-510783321

**Comment by alan-agius4** [comment]
Thanks for your this anyway :) hope to see you around with another contribution :)

**Pull request closed without merging**
