### PR TITLE
feat(@angular/cli): adds --animation flag to ng new

### PR DESCRIPTION
**Pull request by dave11mj**
Fixes https://github.com/angular/angular-cli/issues/6243

### CODE REVIEW

**Comment by filipesilva** [comment]
@Brocco can you review is this is functionality we want, since you were more involved in https://github.com/angular/angular-cli/pull/6144?

**Comment by intellix** [comment]
Any reason why you're not using `NoopAnimationsModule` within `app.module.spec.ts`?

**Comment by dave11mj** [comment]
@intellix the main reason is because because I didn't know the difference between the two. Although, after a quick search I completely agree `NoopAnimationsModule` (No Operation meant for testing) should be used in `app.component.spec.ts` (I couldn't find the file you mentioned) instead of `BrowserAnimationsModule`. I tested it and updated the commit. Thanks for the feedback !  :D

PS: Sorry about closing the PR while trying to comment xD..

**Comment by dave11mj** [comment]
@Brocco to pick up from your feedback on https://github.com/angular/angular-cli/pull/5786 I included both `BrowserAnimationsModule` and `BrowserModule` since thats how is [officially documented](https://angular.io/docs/ts/latest/guide/animations.html) and when including only `BrowserAnimationsModule` causes the error below. ^^

image

**Comment by hansl** [comment]
Closing every Blueprints related issue and PR.

**Pull request closed without merging**
