### PR TITLE
chore(routes): remove lazy route prefix

### PR DESCRIPTION
**Pull request by Brocco**

### CODE REVIEW

**Comment by johnpapa** [comment]
LGTM

**Comment by elvirdolic** [comment]
@Brocco what are the reasons for this Pull Request? Are there any instructions/migration steps for us who have already routes with (+) prefix?

**Comment by intellix** [comment]
@elvirdolic You need to migrate to NgModule first :) The old router lazy loaded components by expecting a + folder prefix. New router just lazy-loads modules at the specified location.

**Comment by Brocco** [comment]
@elvirdolic the `+` prefix for lazy routes was a convention devised for a previous version of the router and before the concept of `NgModules` was introduced.

The idea of that indicator no longer makes sense. Lazy routes are now associated to lazy modules and the need for this indicator is no longer necessary.

**Comment by Meligy** [comment]
Don't you think a naming convention for lazy loading would be useful?

This is probably a styleguide question though, which I'm not sure where will be best to discuss.

**Comment by bobrosoft** [comment]
I think naming convention for that kind of stuff was a bad idea, so I completely agree with that PR.

**Pull request merged**
