### PR TITLE
fix(webpack): Added ContextReplacementPlugin to remove ng test warning

### LINKED ISSUE #2359: Critical dependency: the request of a dependency is an expression
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
macOS El Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
   ```
   angular-cli: 1.0.0-beta.15
   node: 6.4.0
   os: darwin x64
   ```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
`ng new testapp`
`cd testapp`
`ng test`

4. The log given by the failure. Normally this include a stack trace and some
   more information.
   ```
   WARNING in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
   45:15 Critical dependency: the request of a dependency is an expression

   WARNING in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
   57:15 Critical dependency: the request of a dependency is an expression
   ```

5. Mention any other details that might be useful.
I believe this is the fix for it. https://github.com/angular/angular/issues/11580#issuecomment-246880731
The warning only happens while running `ng test` but not when doing `ng build` or `ng serve`

### PR DESCRIPTION
**Pull request by delasteve**
Fixes #2359

@TheLarkInn: This is my first time working with webpack. Please let me know if there is anything else I need to do. It appears to have fixed the issue I was seeing with my project.

### CODE REVIEW

**Comment by JohannesRudolph** [comment]
Looks like the appveyor build failed for an unrelated reason. Can anyone investigate/confirm?

**Comment by JohannesRudolph** [comment]
I can confirm this fixes #2359 but it does not fix #2364

**Comment by delasteve** [comment]
@TheLarkInn / @hansl - It appears it was just a flaky test. I rebased last night and now all tests pass.

Let me know if there is anything else you would like me to do.

**Comment by TheLarkInn** [comment]
Branch is out of date, this looks good so far, but I'd like to make sure with the most recent changes that this still passes.

**Pull request closed without merging**
