### PR TITLE
feat(generate): support component --suffix=Route

### PR DESCRIPTION
**Pull request by leon**
Allow the user to choose the component suffix at generation time.
#3913

supports all kinds of casings such as:
```
--suffix=route
--suffix=Route
--suffix=smart-component
--suffix=SmartComponent
```

### CODE REVIEW

**Comment by filipesilva** [comment]
@Brocco can you review?

**Comment by cacogr** [comment]
https://angular.io/docs/ts/latest/guide/style-guide.html#02-03

> **Do** append the symbol name with the conventional suffix for a thing of that type (e.g., Component, Directive, Module, Pipe, Service).

I don't know how strict is angular-cli about the official style guide.

**Comment by leon** [comment]
@cacogr 
It also says

> Why? Provides a consistent way to quickly identify and reference assets.

I've got into the habit of naming all my route files .route.ts since it makes it easy to find routes.

I can see that the style guide has a couple too get started with .component, .pipe and so on.
But I don't see why we shouldn't evolve this to include more over time.

Say we have a lot of modals in our app. naming all modal components .modal.ts is a good way to just by looking at the filename know that this is a modal.

```
remove-user-modal.component.ts
or
remove-user.modal.ts
```

Almost all UI stuff is going to be components so I would say naming everything as .component.ts is an antipattern.

**Comment by delasteve** [comment]
The styleguide does allow for new types.

https://angular.io/styleguide#!#02-02

> **Do** use conventional type names including `.service`, `.component`, `.pipe`, `.module`, `.directive`. Invent additional type names if you must but take care not to create too many.

**Comment by Brocco** [comment]
Closing per this [comment](https://github.com/angular/angular-cli/issues/3913#issuecomment-273162548)

**Pull request closed without merging**
