### PR TITLE
test: removed empty methods

### PR DESCRIPTION
**Pull request by aanchal88**
## PR Checklist

Please check to confirm your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular-cli/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by aanchal88** [comment]
Hii @alan-agius4 , please review

**Review by alan-agius4 — APPROVED** [review]
Thanks

**Comment by aanchal88** [comment]
Hii @alan-agius4 , please merge the PR. Thnks

**Comment by alan-agius4** [comment]
@aanchal88, currently we are on merge freeze for the holidays. The PR will be merged in January when the caretaker rotation is back.

**Pull request merged**
