### PR TITLE
fix(@angular-devkit/build-angular): add missing declaration types …

### PR DESCRIPTION
**Pull request by opulisDynamics**
…in build_angular schemas.

Fixes issue #13388

### CODE REVIEW

**Comment by opulisDynamics** [comment]
Hi,

I made this pull request to specifically address issue #13388.
I get that this issue has been closed by @hansl as "working as intended", but I kindly disagree with this as this breaks the ability to cleanly compile custom builders deriving or using the `BrowserBuilder`. I even wonder how transpilation worked on your side since 7.2.0 given these broken types declarations links.

This PR fixes this, and allow fellow devs to continue working with their own builders setup while waiting for v8.

To break circular dependencies, I had to move two declarations `NormalizedSourceMaps` and `NormalizedOptimization` away from `utils`. I chose to declare them in `browser/schema` as imports from this file were already present for every other files that needed these declarations. This is not ideal, but I thought that putting these right between `NormalizedBrowserBuilderSchema` and it's above `TODO` comment would be the best compromise. Please, do tell if you disagree.

Sincerely sorry for the little mess with commits:
- First one didn't have the right author information and did not pass linting
- Second one corrected lint issues, I marked it "refactor" rather than "style" as some code needed to be moved to avoid circular dependencies. Hope I did well there.
- Subsequent ones were needed to fix the first commit's authorship issue.

Finally, I'm not sure why two items of **test-large** failed on CI when it worked locally:

```
20 Browser Builder rebuilds

    √ rebuilds on TS file changes (10 secs)

    √ rebuilds on CSS changes (8 secs)

    √ type checks on rebuilds (12 secs)

    √ rebuilds on type changes (9 secs)
```

Thank you for your amazing work, I hope this edit can help.

**Comment by opulisDynamics** [comment]
Well I just learned about squashing. I hope it's all good, Bot seems okay with this.
Thanks, learning everyday 👍 !

**Comment by alan-agius4** [comment]
@opulisDynamics I don't see the need for that.

**Comment by imzachwolf** [comment]
My build was fixed with "@angular-devkit/build-angular": "0.13.9". Thanks folks.

**Pull request merged**
