### PR TITLE
fix(@angular/cli): Generating an Angular component with no name should…

### LINKED ISSUE #9175: Generating an Angular component with no name should throw proper error message
### Versions
```
@angular/cli: 1.4.1
node: 8.9.1
os: win32 x64
@angular/animations: 4.4.6                                                                                              @angular/common: 4.4.6                                                                                                  @angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6                                                                                @angular/router: 4.4.6
@angular/cli: 1.4.1
@angular/compiler-cli: 4.4.6                                                                                            @angular/language-service: 4.4.6
typescript: 2.3.4 
```

### Repro steps

* create a new project with the angular-cli
> ``` ng new test-sample ``` 
> ``` cd test-sample```
* try creating any angular component without providing any (proper) name
>``` ng g component ```

### Observed behavior
```
Cannot read property 'split' of undefined                                                                      
TypeError: Cannot read property 'split' of undefined
        at Class.run (C:\Users\cran-cg\test-sample\test-sample\node_modules\@angular\cli\commands\generate.js:109:64)           	
	at resolve (C:\Users\cran-cg\test-sample\test-sample\node_modules\@angular\cli\ember-cli\lib\models\command.js:273:20)
	at new Promise (<anonymous>)                                                                                  
        at Class.validateAndRun (C:\Users\cran-cg\test-sample\test-sample\node_modules\@angular\cli\ember-cli\lib\models\command.js:251:12)                                                                                         
        at Promise.resolve.then.then (C:\Users\cran-cg\test-sample\test-sample\node_modules\@angular\cli\ember-cli\lib\cli\cli.js:154:24)                                                                                      
        at <anonymous>
```

### Desired behavior
* A proper,valid error message should have been printed out to the user

### PR DESCRIPTION
**Pull request by cRAN-cg**
Fixes #9175

### CODE REVIEW

**Comment by cRAN-cg** [comment]
@Brocco could you please review.

**Comment by cRAN-cg** [comment]
@Brocco I need some hint, as to how should I detect that. Could you please help

**Comment by cRAN-cg** [comment]
@Brocco I guess we need to validate if `name` is among one of the elements in the `required` property in the `schema.json` of the given schematic. Could you please help me verify and if I am correct needed some hints for implementation.

**Comment by Brocco** [comment]
This has already been addressed... you can see the fix [here](https://github.com/angular/angular-cli/blob/master/packages/@angular/cli/commands/generate.ts#L150).

**Pull request closed without merging**
