### PR TITLE
refactor(@angular/cli): remove ng init & ng update

### PR DESCRIPTION
**Pull request by Brocco**
BREAKING CHANGE: Removing the ng init & ng update commands because their current implementation causes more problems than it solves. Update functionality will return to the CLI, until then manual updates of applications will need done.

### CODE REVIEW

**Comment by hansl** [comment]
At least a BREAKING CHANGE section on this one please :)

**Comment by Brocco** [comment]
Thank you, breaking change text has been added to the PR.

**Comment by kuncevic** [comment]
Before without CLI globally installed I was being able to create CLI app just like that:

- npm init -y
- npm install @antular/cli --save
- alter package.json by adding "ng":"ng" script section (https://github.com/angular/angular-cli/commit/761e86f2224c718f62dcc100059096d5752c0726)
- npm run ng -- init

Now it is seams to be that it is not longer possible.

**Comment by AlainD-** [comment]
Hi,
just for information, as of today, the main [README.md](https://github.com/angular/angular-cli/blob/master/README.md) has not been updated accordingly to the realase of the 1.0.0-beta.32, and still suggest to run ng update after an update of @angular/cli.

**Comment by filipesilva** [comment]
@AlainD- you're absolutely right, thanks for the heads up!

**Comment by filipesilva** [comment]
Here's a PR that'll fix it.

**Comment by fvilers** [comment]
I'm missing the `init` command. How can I create an application in an existing git repository?

**Comment by Equinox** [comment]
@fvilers You could `ng new appname --skip-git` (optionally --skip-install also to skip yarn/npm install to save moving the node_modules over also) a new application in another directory then move the files over manually.

**Comment by fvilers** [comment]
@Equinox This is what I did, but this is not the behavior I expect from a cli. I hope the maintainers will restore the command soon.

**Comment by kuncevic** [comment]
@fvilers you are not alone https://github.com/angular/angular-cli/issues/4768 
It might came or might not.

**Comment by ctilley83** [comment]
So what's the solution for upgrading an existing app guys? Manually change the package.json file?

**Comment by AlainD-** [comment]
I don't know the recommendations but what I usually do, I create a new project in a temporary folder, and then compare the differences between that new project and mine. I manually modify my project accordingly then.

**Pull request merged**
