### PR TITLE
feat(@angular/cli): platform-electron-renderer

### PR DESCRIPTION
**Pull request by ashkandaie**
Allows targeting electron renderer using the new platform property in .angular-cli.json.

Happy to add wiki story for the use case.

This resolves issue #5767

### CODE REVIEW

**Comment by ashkandaie** [comment]
@hansl, I created a new PR. Same CLA block error. My GH primary email is the same as my google account w/ signed CLA. Thoughts?

**Comment by devoto13** [comment]
@ashkandaie That's because in your commits you use different email address. See:

```
$ git log
commit c9a818655274cbe75b86ec76db2f098e28c9213e (HEAD -> master, origin/support-platform-electron-renderer, origin/master, origin/HEAD)
Merge: db4c9351 e746369c
Author: Ashkan Daie <ashkan@ashkan-mbp.lan>
```

You'll need to set it to the email you signed CLA with and re-create/edit your commits. See [here](https://help.github.com/articles/setting-your-commit-email-address-in-git/) how to do it. Also check [commit message guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#commit). You'll need to fix it as well for build to pass.

**Comment by markfknight** [comment]
@ashkandaie This is an awesome addition thanks. 

Quick question does 'ng serve' need to be blocked, I currently use and ejected webpack config with "target": "electron-renderer" and serve to localhost:4200 via 'webpack-dev-server' with no issues, would be good to retain this functionality if possible.

**Comment by filipesilva** [comment]
I appreciate the time you took to make a PR for this, but we aren't ready yet to add new platforms and support them. We're tentatively adding `platform-server` as experimental but will need more time to properly design and add more platform support. So for now I will close this PR.

**Pull request closed without merging**
