### PR TITLE
docs(readme): add a reminder to read the prerequisites before installing

### PR DESCRIPTION
**Pull request by shairez**

### CODE REVIEW

**Comment by cironunes** [comment]
As per https://github.com/angular/angular-cli/issues/190, can you also add a note about this in the [known issues section](https://github.com/angular/angular-cli#known-issues)?

**Comment by hansl** [comment]
Could you stash your 2 commits please? We try to keep 1 commit per PR.

**Comment by filipesilva** [comment]
You mean squash?

**Comment by hansl** [comment]
Yes, stupid auto correct.

**Comment by filipesilva** [comment]
I squashed the commits and rebased myself, so the PR wouldn't continue to be held up by it.

**Comment by shairez** [comment]
thanks @filipesilva 
was planning on doing it tonight after work

**Pull request closed without merging**
