### PR TITLE
fix(@angular-devkit/core): transform path using getSystemPath for NodeJsAsyncHost's `exists` method

### PR DESCRIPTION
**Pull request by why520crazy**

### CODE REVIEW

**Review by alan-agius4 — APPROVED** [review]
Thanks for your contribution.

LGTM, can you please fix the commit message to the below?

```
fix(@angular-devkit/core): transform path using getSystemPath for NodeJsAsyncHost's `exists` method
```

**Comment by SirJosh1987** [comment]
Getting therw

**Comment by why520crazy** [comment]
> Thanks for your contribution.
> 
> LGTM, can you please fix the commit message to the below?
> 
> ```
> fix(@angular-devkit/core): transform path using getSystemPath for NodeJsAsyncHost's `exists` method
> ```

resubmitted！

**Review by alan-agius4 — APPROVED** [review]
LGTM. thanks

**Comment by why520crazy** [comment]
Did CI run `@angular-devkit/core` 's unit tests? I added a problematic test case, but it passed.
I don't know how to run the test locally for `@angular-devkit/core`, have any related documents？

**Comment by why520crazy** [comment]
Did CI run unit tests for `@angular-devkit/core` , I added a problematic test case, but is passed.
I don't know how to run the test locally only for `@angular-devkit/core`, have any related documents?

**Comment by why520crazy** [comment]
Before, `write` operation did not succeed.
```
 it('should get correct result for exists', async () => {
    let isExists = await host.exists(normalize('not-found')).toPromise();
    expect(isExists).toBe(false);
    host.write(normalize('not-found'), virtualFs.stringToFileBuffer('content'));
    isExists = await host.exists(normalize('not-found')).toPromise();
    expect(isExists).toBe(true);
  });
```
After
```
 it('should get correct result for exists', async () => {
    let isExists = await host.exists(normalize('not-found')).toPromise();
    expect(isExists).toBe(false);
    await host.write(normalize('not-found'), virtualFs.stringToFileBuffer('content')).toPromise();
    isExists = await host.exists(normalize('not-found')).toPromise();
    expect(isExists).toBe(true);
  });
```

**Comment by why520crazy** [comment]
I resubmit a PR use a feature branch replace with this, see https://github.com/angular/angular-cli/pull/21005

Closed this PR.

**Pull request closed without merging**
