### PR TITLE
Remove solutions tsconfig

### LINKED ISSUE #18040: New "Solution Style" tsconfig.json file breaks the unused files in most Editors
If we have an unused service, we will run into some Typescript errors in Editors since the unused file isn't really a part of any TypeScript compilation.
**VS code**
image
**Webstorm**
image

Shall we revert the changes for tsconfig.file?

### LINKED ISSUE #18130: tsconfig.base.json does not exist after upgrade to Angular 10 (no error)
### Description
Hello guys, I am working on  on upgrading a couple of projects to Angular 10 from Angular 9 and I am going through the steps in the update.angular.io guide, however I am having an issue with one of the projects. (I am using **ng update**)

The first project was upgraded successfully by upgrading to the latest Angular 8 version first, then upgrading to Angular 9 and then to Angular 10.
The upgrade of the second project however seemed incomplete, because not all of the same migrations were executed as for the first one.

I am aware of this https://github.com/angular/angular-cli/issues/18027, however I have not received any errors and I updated the project step by step without skipping major versions.

### Update log

After executing ng update @angular/core @angular/cli, the following output was present:
```
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Using package manager: 'npm'
Collecting installed dependencies...
Found 44 dependencies.
Fetching dependency metadata from registry...
                      Package "@angular-devkit/build-ng-packagr" has an incompatible peer dependency to "tsickle" (requires "~0.38.0", would install "0.39.0")
                       Package "@angular/cdk" has an incompatible peer dependency to "tslib" (requires "^1.9.0", would install "2.0.0").
                       Package "tsickle" has an incompatible peer dependency to "typescript" (requires "~3.8.2", would install "3.9.6")
```

Since tsickle does not have typescript 3.9.x as a peer dependency yet (should be resolved by this issue I guess: https://github.com/angular/tsickle/pull/1161 ), I ignored that warning. I ignored the angular/cdk warning as well, because upgrading the angular/material package (after the core and cli packages) should update the cdk to version 10 as well. Eventually I executed the ng update with the **--force** flag.

This is the final output, in which you will notice that only the package.json file is updated and the additional migrations to the tsconfig.json, tsconfig.lib.prod.json and the creation of the tsconfig.base.json are missing, but no error is thrown.

```
ng update @angular/core @angular/cli --force
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Using package manager: 'npm'
Collecting installed dependencies...
Found 44 dependencies.
Fetching dependency metadata from registry...
                      Package "@angular-devkit/build-ng-packagr" has an incompatible peer dependency to "tsickle" (requires "~0.38.0", would install "0.39.0")
                       Package "@angular/cdk" has an incompatible peer dependency to "tslib" (requires "^1.9.0", would install "2.0.0").
                       Package "tsickle" has an incompatible peer dependency to "typescript" (requires "~3.8.2", would install "3.9.6")
    Updating package.json with dependency @angular/cli @ "10.0.1" (was "9.1.10")...
    Updating package.json with dependency @angular/core @ "10.0.2" (was "9.1.11")...
    Updating package.json with dependency @angular-devkit/build-ng-packagr @ "0.1000.1" (was "0.901.10")...
    Updating package.json with dependency ng-packagr @ "10.0.0" (was "9.1.5")...
    Updating package.json with dependency @angular/language-service @ "10.0.2" (was "9.1.11")...
    Updating package.json with dependency @angular/compiler-cli @ "10.0.2" (was "9.1.11")...
    Updating package.json with dependency @angular/common @ "10.0.2" (was "9.1.11")...
    Updating package.json with dependency @angular/animations @ "10.0.2" (was "9.1.11")...
    Updating package.json with dependency @angular/elements @ "10.0.2" (was "9.1.11")...
    Updating package.json with dependency @angular/platform-browser @ "10.0.2" (was "9.1.11")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "10.0.2" (was "9.1.11")...
    Updating package.json with dependency @angular/compiler @ "10.0.2" (was "9.1.11")...
    Updating package.json with dependency @angular/forms @ "10.0.2" (was "9.1.11")...
    Updating package.json with dependency tslib @ "2.0.0" (was "1.10.0")...
    Updating package.json with dependency @angular/router @ "10.0.2" (was "9.1.11")...
    Updating package.json with dependency @angular-devkit/build-angular @ "0.1000.1" (was "0.901.10")...
    Updating package.json with dependency typescript @ "3.9.6" (was "3.8.3")...
UPDATE package.json (2870 bytes)
✔ Packages installed successfully.
** Executing migrations of package '@angular/core' **

❯ Missing @Injectable and incomplete provider definition migration.
  As of Angular 9, enforcement of @Injectable decorators for DI is a bit stricter and incomplete provider definitions behave differently.
  Read more about this here: https://v9.angular.io/guide/migration-injectable
  Migration completed.

❯ ModuleWithProviders migration.
  As of Angular 10, the ModuleWithProviders type requires a generic.
  This migration adds the generic where it is missing.
  Read more about this here: https://v10.angular.io/guide/migration-module-with-providers
  Migration completed.

❯ Undecorated classes with Angular features migration.
  In version 10, classes that use Angular features and do not have an Angular decorator are no longer supported.
```

### Issue
The end result is a very short upgrade log and it seems not everything was migrated, which includes the missing tsconfig.base.json. What could be the reason for that and is it essential for all Angular 10+ projects to have the new structure, that these tsconfig migrations provide? **The project builds and runs successfully though.**

### LINKED ISSUE #18170: Issues with importing interfaces created with export interface in Angular and TypeScript 3.9.6
### Description

Recently I switched from Angular 9 to 10. On a new project I have issues to import interfaces automatically. For example I want to import this interface to my app.component.ts:
<pre><code>
export interface TestInterface {
    string: name;
}
</code></pre>
It is located in src/app/testInterface.ts. When i try to import it in my app.component.ts:
<pre><code>
test: testInterface;
</code></pre>
I am using VSC and IntelliSense is not showing me the option to autoimport/import the interface anymore. When i press Ctrl+. for Quick Fix I receive the message: No code actions available. In Angular 9 with Typescript 3.8.3 everything works fine, IntelliSense shows me the autoimport option or I can import the interface with Ctrl+. Key Binding. If I manually add the import it works:
<pre><code>
import { testInterface } from 'src/app/testInterface';
</code></pre>

## 🔬 Reproduction
To reproduce this issue try to install the latest angular/cli (at the moment of writing v10.0.1):
<pre><code>
npm i @angular/cli@10.0.1 -g
</code></pre>

Then create a new project:
<pre><code>
ng new
</code></pre>
Name it as you wish, I have enabled routing and choosen CSS for stylesheets.

When you install Angular 9 and create an project:
<pre><code>
npm i @angular/cli@9.1.10 -g
</code></pre>
<pre><code>
ng new
</code></pre>

Everything works as it should

## 🌍 Environment
My Environment is:
<pre><code>
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.1
Node: 12.18.0
OS: win32 x64

Angular: 10.0.2
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.1
@angular-devkit/build-angular     0.1000.1
@angular-devkit/build-optimizer   0.1000.1
@angular-devkit/build-webpack     0.1000.1
@angular-devkit/core              10.0.1
@angular-devkit/schematics        10.0.1
@angular/cdk                      10.0.1
@angular/cli                      10.0.1
@angular/material                 10.0.1
@ngtools/webpack                  10.0.1
@schematics/angular               10.0.1
@schematics/update                0.1000.1
rxjs                              6.5.5
typescript                        3.9.6
webpack                           4.43.0

Visual Studio Code Version 1.46.1
</code></pre>

### PR DESCRIPTION
**Pull request by alan-agius4**
Following the issues highlighted in https://docs.google.com/document/d/1eB6cGCG_2ircfS5GzpDC9dBgikeYYcMxghVH5sDESHw/edit?usp=sharing and discussions held with the TypeScript team. Together with the TypeScript team it was decided that the best course of action is to rollback this feature.

In future, it is not excluded that solution style tsconfigs are re-introduced.

Closes #18040, closes #18130 and closes #18170

### CODE REVIEW

**Comment by LayZeeDK** [comment]
Isn't this considered a breaking change? In which version will this land?

**Comment by alan-agius4** [comment]
@LayZeeDK, why is this a breaking change? We’ll be running migrations to revert back the changes from existing projects.

It’s scheduled to land in 10.1

**Comment by LayZeeDK** [comment]
1. Do you consider introducing them a breaking change?
2. Do automated migrations negate breaking changes?

**Comment by alan-agius4** [comment]
> Do you consider introducing solution-style configs a breaking change?
No, solutions style tsconfig only effects the IDE’s. it’s not used by any compilation.

> Do automated migrations negate breaking changes?
Certainly not.

**Comment by mhosman** [comment]
When you are gonna release this fix??

**Comment by alan-agius4** [comment]
This will be available in 10.1.0.

Today we’ll be releasing the pre-release version and you can try it out using `ng update @angular/cli -—next`

**Comment by LayZeeDK** [comment]
> > Do you consider introducing solution-style configs a breaking change?
> 
> No, solutions style tsconfig only effects the IDE’s. it’s not used by any compilation.
> 

Fair point.

> > Do automated migrations negate breaking changes?
> 
> Certainly not.

Thanks, that's also my impression.

**Pull request merged**
