### PR TITLE
docs: add docs about how to change the build directory

### PR DESCRIPTION
**Pull request by bellingson**
It's often helpful to change the build directory from dist/ to another location.
For example, if you are integrating angular within an existing web application an easy
deployment method is to just change the dist/ folder to a build directory within the
parent application.

### CODE REVIEW

**Comment by filipesilva** [comment]
Closed as this PR was made obsolete by https://github.com/angular/angular-cli/pull/1455.

**Comment by filipesilva** [comment]
Actually, I misread your commit. Latest master commits made this obsolete, but I think there's value in documenting the new functionality. Can you update your PR?

**Comment by bellingson** [comment]
Sure.. I'm about to go on vacation.  When I get back, I will take a look at the new functionality and update the PR.

**Comment by filipesilva** [comment]
We're doing a big docs sweep soon that will cover this as well in #2711, so closing it for now.

**Pull request closed without merging**
