### PR TITLE
Add Circle CI

### PR DESCRIPTION
**Pull request by filipesilva**
Add Circle CI

---
This PR used to read:

The new `--ci` flag enables CI integration mode for build/test/e2e commands. It sets progress logging to false and for test/e2e also uses chrome with `--no-sandbox` flags, required when running chrome in CI like Travis or Circle CI.

### CODE REVIEW

**Comment by Chris1308** [comment]
Do you think it is a good idea to add the chrome headless flag too?

**Comment by filipesilva** [comment]
I thought about it, but it needs chrome 60 on Windows and that's not out yet so adding it would break some platforms. Some CI providers also only have older versions of Chrome by default.

When it's out I'd like to add a `--headless` flag to test/e2e and have `-ci` also toggle it. That way it can be disabled via `--ci --no-headless`.

**Comment by filipesilva** [comment]
Blocked for discussion.

**Comment by ishitatsuyuki** [comment]
I would like to mention that headless is quite convenient for local testing too because it doesn't open a redundant window. What's more, a selenium grid is often used for continuous integration, long before Chrome headless born.

**Comment by ishitatsuyuki** [comment]
I'm against this. Disabling sandbox is up to the user's configuration, as local testing and CI testing is a lot different. We should not patch the Karma configuration on the fly, too.

By the way, I know Chrome is popular, but it isn't the only browser. I feel this is too subjective. `ChromeHeadless` exists in `karma-chrome-launcher`, so it could make sense to add it to the default blueprint, as an alternative.

**Comment by filipesilva** [comment]
@ishitatsuyuki headless is a separate discussion that still requires `--no-sandbox` configuration AFAIK.

Removed the `--ci` flag that was included in this PR, instead added some documentation on how users can configure their projects for travis/circleci in https://github.com/angular/angular-cli/pull/6947.

**Comment by filipesilva** [comment]
Closing temporarily while I run some tests on circleci in my fork.

**Pull request closed without merging**
