### PR TITLE
Update Autoprefixer and PostCSS

### PR DESCRIPTION
**Pull request by ai**
Hi from PostCSS community. I updated Autoprefixer, PostCSS and PostCSS loader/imports.

Autoprefixer 9 and PostCSS 7 didn’t have any breaking changes. Just drop Node.js 4 support.

@vikerman this update will bring to Angular users many fixes and reduce meanless issue reports in Autoprefixer repo (like [this](https://github.com/postcss/autoprefixer/issues/1137))

### CODE REVIEW

**Comment by ai** [comment]
@vikerman do you know the reason for this issue in CI?

```
The package "@ngtools/webpack" does not have a BUILD file associated to it. You must either set an exception or make sure it can be built using Bazel.
```

**Comment by ai** [comment]
@alan-agius4 thanks. Fixed.

**Comment by alan-agius4** [comment]
@ai, the commit is still invalid.

Please use: 
`feat(@angular-devkit/build-angular): update Autoprefixer and PostCSS`

Thanks

**Comment by ai** [comment]
Could it be 7.0.1? There is no API changes, only bugfixes.

**Comment by ai** [comment]
Also, we need a way to prevent it in the feature. Autoprefixer 9 was released from month ago. Maybe we should add checklist “what to do before release” and add “Update dependencies” in that list? (I do it before releasing any of my project)

**Pull request merged**
