### PR TITLE
refactor(@angular/cli): refactored the code and removed the code smells

### PR DESCRIPTION
**Pull request by alkavats1**
refactored the code and removed the code smells from the test.ts files

### CODE REVIEW

**Comment by alkavats1** [comment]
Hi @devversion / @alan-agius4 
Could you please review my PR?

**Review by alan-agius4 — CHANGES_REQUESTED** [review]
There are a couple of other occurrences can you please update them?

Since you will be touching files across multiple packages, you can you remove the commit scope?

**Comment by alkavats1** [comment]
HI @alan-agius4 
I've checked in the codebase. I found no more occurrences.

**Comment by alkavats1** [comment]
Closing, will raise new PR

**Pull request closed without merging**
