### PR TITLE
feat(@schematics/angular): use isolatedModules in generated project

### PR DESCRIPTION
**Pull request by cexbrayat**
## PR Checklist

Please check to confirm your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular-cli/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the new behavior?

As 3acb7768317bb05a9cd73fa64e081b5ca0326189 introduced an optimization for projects that use `isolatedModules`, this commit makes projects generated with `ng new` use this option by default.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by cexbrayat** [comment]
It looks like only one i18n test is failing (extract-ivy-library) but only when running with `esbuild` enabled:

It seems that in that case the messages from `app.component.html` are referenced as `src/app/app.component.ts`

```
Test Process error Error: File "messages.xlf" did not contain "src/app/app.component.html"...
Content:
<?xml version="1.0" encoding="UTF-8" ?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file source-language="en-US" datatype="plaintext" original="ng2.template">
    <body>
      <trans-unit id="5640424602650517303" datatype="html">
        <source> i18n-lib-test works! </source>
        <context-group purpose="location">
          <context context-type="sourcefile">projects/i18n-lib-test/src/lib/i18n-lib-test.component.ts</context>
          <context context-type="linenumber">9,10</context>
        </context-group>
      </trans-unit>
      <trans-unit id="2023484548631819319" datatype="html">
        <source>Hello world</source>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/app.component.ts</context>
          <context context-type="linenumber">16</context>
        </context-group>
      </trans-unit>
    </body>
  </file>
</xliff>
```

**Comment by clydin** [comment]
Yes. I re-ran it so it's not a flake.
It appears this will need further investigation.

**Comment by cexbrayat** [comment]
Yeah, I confirm that this is an issue: I just ran `ng extract-i18n` on a project of mine with `isolatedModules: true`, and the extracted messages only reference the TS files instead of the HTML files, line numbers are off, and equiv-text is broken.

**Comment by cexbrayat** [comment]
@clydin I rebased on your fix, and the PR is now green 👍

**Review by clydin — APPROVED** [review]

**Pull request merged**
