### PR TITLE
fix(@schematics/angular): add missing express `REQUEST` and `RESPONSE` tokens

### LINKED ISSUE #26110: New `@angular/ssr` is missing `REQUEST` and `RESPONSE` tokens
### Which @angular/* package(s) are the source of the bug?

platform-server, Don't known / other

### Is this a regression?

No

### Description

Angular Universal exposed two injection tokens `REQUEST` and `RESPONSE` from `@nguniversal/express-engine/tokens`. Also mentioned [here](https://github.com/angular/universal/blob/main/modules/express-engine/README.md#using-the-request-and-response) in the `ngExpressEngine` documentation. `

Unfortunately the new SSR solution with `@angular/ssr` does not expose these anymore. Can you add them back or how should I handle use cases where I need access to the raw request object to read headers and/or cookies? 

### Please provide a link to a minimal reproduction of the bug

_No response_

### Please provide the exception or error you saw

_No response_

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.0-rc.0
Node: 18.17.1
Package Manager: npm 9.6.7
OS: win32 x64

Angular: 17.0.0-rc.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... platform-server, router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-rc.0
@angular-devkit/build-angular   17.0.0-rc.0
@angular-devkit/core            17.0.0-rc.0
@angular-devkit/schematics      17.0.0-rc.0
@schematics/angular             17.0.0-rc.0
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.0
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by alan-agius4**
This commit updates the nguniversal migration to add `REQUEST` and `RESPONSE` tokens.

Closes #26110

### CODE REVIEW

**Review by clydin — APPROVED** [review]

**Comment by pavankjadda** [comment]
@alan-agius4 Whats the new package that exports these? I just ran the `ng update @angular/core @angular/cli --next --force` and it didn't update imports.

**Comment by pavankjadda** [comment]
@alan-agius4 did you get a chance to look at this?

**Comment by alan-agius4** [comment]
The tokens are no longer exporting from a package. Instead the migration will create them in the project when encountering imports to `@nguniversal/express-engine/tokens`.

**Comment by pavankjadda** [comment]
> The tokens are no longer exporting from a package. Instead the migration will create them in the project when encountering imports to `@nguniversal/express-engine/tokens`.

Thanks. I was expecting that after looking at PR. 
1. But it's not creating them during migration
2. When I create them manually, I see error 

```
 error TS2742: The inferred type of 'REQUEST' cannot be named without a reference to '.pnpm/@types+express-serve-static-core@4.17.35/node_modules/@types/express-serve-static-core'. This is likely not portable. A type annotation is necessary.

export const REQUEST = new InjectionToken<Request>('REQUEST');
```

You can run the migration on here https://github.com/stevermeister/ngx-cookie-service and reproduce the issue

**Comment by alan-agius4** [comment]
Are you importing the `Request` from the right place?

```ts
import { InjectionToken } from '@angular/core';
import { Request, Response } from 'express';

export const REQUEST = new InjectionToken<Request>('REQUEST');
export const RESPONSE = new InjectionToken<Response>('RESPONSE');
```

**Comment by pavankjadda** [comment]
> Are you importing the `Request` from the right place?
> 
> ```ts
> import { InjectionToken } from '@angular/core';
> import { Request, Response } from 'express';
> 
> export const REQUEST = new InjectionToken<Request>('REQUEST');
> export const RESPONSE = new InjectionToken<Response>('RESPONSE');
> ```

I think so. You can see them here https://github.com/stevermeister/ngx-cookie-service/blob/test/projects/ngx-cookie-service-ssr/src/lib/tokens.ts

**Comment by pavankjadda** [comment]
> > Are you importing the `Request` from the right place?
> > ```ts
> > import { InjectionToken } from '@angular/core';
> > import { Request, Response } from 'express';
> > 
> > export const REQUEST = new InjectionToken<Request>('REQUEST');
> > export const RESPONSE = new InjectionToken<Response>('RESPONSE');
> > ```
> 
> I think so. You can see them here https://github.com/stevermeister/ngx-cookie-service/blob/test/projects/ngx-cookie-service-ssr/src/lib/tokens.ts

It seems like an issue with PNPM. When I tried with NPM I don't see an issue. But PNPM gives that error. Any idea why?

**Pull request merged**
