### PR TITLE
chore(template): clean up templates

### PR DESCRIPTION
**Pull request by delasteve**

### CODE REVIEW

**Comment by filipesilva** [comment]
I have somewhat of a nit regarding this. I understand that it's not in alphabetically order, but at the moment none of the other blueprints are. Accepting this PR makes the component blueprint the outlier.

Can I ask you to change the other ones as well?

**Comment by delasteve** [comment]
Sure can. It did more, I believe (it's been a while), but they were fixed in various rebasings.

**Comment by delasteve** [comment]
Removed `ddescribe` and `iit` because https://github.com/karma-runner/karma-jasmine/issues/73

According to @Brocco's comment (https://github.com/angular/angular-cli/pull/918#issuecomment-223588543) class curly braces should be on separate lines, I extended this to `constructor` functions since `ngOnInit` was already doing it. I can move the braces for the `constructor` and `ngOnInit` back to one line depending on how you would like it, @filipesilva.

I wasn't sure what to do with https://github.com/angular/angular-cli/pull/741/files#diff-8360312d36bd87696ebdad9888e6dec5R13 - It looks ugly either way I put it. One breaks the character line limit in tslint, one just looks ugly.

I was thinking of doing something like 

```
it('should ...', 
  inject([<%= classifiedModuleName %>Service], 
  (service: <%= classifiedModuleName %>Service) => {
    expect(service).toBeTruthy();
  }));
```

Thoughts?

**Comment by Brocco** [comment]
To be clear re: curly braces, I believe that if there is nothing going inside then they should be on the same line, but in the case you referenced, it was for a class definition, which will always have code inside.

For your specific example, I think the line breaks you have are fine, just update the indenting....

```
it('should ...', 
  inject([<%= classifiedModuleName %>Service], 
    (service: <%= classifiedModuleName %>Service) => {
    expect(service).toBeTruthy();
  }));
```

**Comment by delasteve** [comment]
@Brocco correct. It was only for classes. So, in the case of `constructor` and `ngOnInit` for the various Components, Services, etc, braces on the same line or not?

Also, the formatting you pointed out, are you sure about services being indented one more level? It feels wrong that it is indented again with the expect on the same indentation level.

**Comment by Brocco** [comment]
I like that extra indentation because it's a carry over of the parameters to the function.

To sum up my thoughts on curly braces. If you are going to put stuff in there, then put the closing one on a new line, if not then the same line is fine. So class definitions new line, constructor same line, ngOnInit I could go either way but lean towards new line.

**Comment by delasteve** [comment]
Ah, I missed that in the inject. Woops...

Okay then, what about this? I just hate that it's becoming a pyramid o' doom, though. Bah. It calls out the callback function better though, imo.

```
it('should ...', 
  inject([<%= classifiedModuleName %>Service], 
    (service: <%= classifiedModuleName %>Service) => {
      expect(service).toBeTruthy();
    }));
```

**Comment by delasteve** [comment]
@filipesilva - @Brocco, I believe everything has been fixed. 😄 

Let me know if there is anything else you would like done.

I included https://github.com/angular/angular-cli/pull/1023 along with other new line fixes.

**Comment by delasteve** [comment]
Just updated the PR that included @Brocco's changes to the spec files and anything else released in beta6.

**Comment by johnpapa** [comment]
Why add a space between the curlies ? `constructor() { }` vs `constructor() {}` ?

**Comment by delasteve** [comment]
@johnpapa: VSCode formats it that way (afaik, I don't think I changed anything to make it do so), therefore I changed it since most of the community seems to be using VSCode.

**Comment by delasteve** [comment]
Hmm, I just rebased and caused a timeout. Could someone restart this?

Also, is there anything else that someone has a question about or something else that the team would like me to do?

**Comment by delasteve** [comment]
Since this isn't getting merged in, I updated the spec templates to follow the new testbed for `rc.4` found here https://github.com/angular/angular/pull/9564. This PR will fail until it's released.

That said, would it be preferable to import the testing exports as seen here: https://github.com/angular/angular/pull/9564/files#diff-7603ee1fd936988af932c5804ceba9e4R9? @Brocco I believe it was you who imported all the jasmine exports last time. Thoughts?

**Comment by delasteve** [comment]
Updated to include `rc.4` and the `beta.2` router.

Let me know if there are any other questions so that I can fix them. 😄

**Comment by Brocco** [comment]
@delasteve Please leave the extra imports in the spec files. They are the common ones which most devs will use and we want them there for convenience.

After that please rebase and I'll merge this in.

**Comment by delasteve** [comment]
@Brocco, the angular team deprecated those as of rc.4. Would you still like those in?

https://github.com/angular/angular/pull/9564

**Pull request merged**
