### PR TITLE
Fix for noImplicitAny: make them explicit any refs

### PR DESCRIPTION
**Pull request by catull**
Some references in packages/base-href-webpack-plugin.spec.ts have implicit type any.
This is not allowed in the config of TypeScript compiler.
Thus all these references must be made explicit any types.

Similarly to issue #1876, this time the build fails with:

```log
npm run build

> angular-cli@1.0.0-beta.11-webpack.8 build /Users/carlo/workspace/javascript/ng/angular-cli.git
> npm-run-all -c build:main build:packages


> angular-cli@1.0.0-beta.11-webpack.8 build:main /Users/carlo/workspace/javascript/ng/angular-cli.git
> tsc -p addon/ng2


> angular-cli@1.0.0-beta.11-webpack.8 build:packages /Users/carlo/workspace/javascript/ng/angular-cli.git
> for PKG in packages/*; do echo Building $PKG...; tsc -P $PKG; done

Building packages/ast-tools...
Building packages/base-href-webpack...
packages/base-href-webpack/src/base-href-webpack-plugin.spec.ts(5,23): error TS7006: Parameter 'indexHtml' implicitly has an 'any' type.
packages/base-href-webpack/src/base-href-webpack-plugin.spec.ts(5,34): error TS7006: Parameter 'callback' implicitly has an 'any' type.
packages/base-href-webpack/src/base-href-webpack-plugin.spec.ts(7,23): error TS7006: Parameter 'event' implicitly has an 'any' type.
packages/base-href-webpack/src/base-href-webpack-plugin.spec.ts(7,30): error TS7006: Parameter 'compilerCallback' implicitly has an 'any' type.
packages/base-href-webpack/src/base-href-webpack-plugin.spec.ts(9,27): error TS7006: Parameter 'hook' implicitly has an 'any' type.
packages/base-href-webpack/src/base-href-webpack-plugin.spec.ts(9,33): error TS7006: Parameter 'compilationCallback' implicitly has an 'any' type.
packages/base-href-webpack/src/base-href-webpack-plugin.spec.ts(32,42): error TS7006: Parameter 'x' implicitly has an 'any' type.
packages/base-href-webpack/src/base-href-webpack-plugin.spec.ts(32,45): error TS7006: Parameter 'htmlPluginData' implicitly has an 'any' type.
packages/base-href-webpack/src/base-href-webpack-plugin.spec.ts(40,42): error TS7006: Parameter 'x' implicitly has an 'any' type.
packages/base-href-webpack/src/base-href-webpack-plugin.spec.ts(40,45): error TS7006: Parameter 'htmlPluginData' implicitly has an 'any' type.
packages/base-href-webpack/src/base-href-webpack-plugin.spec.ts(58,13): error TS7006: Parameter 'x' implicitly has an 'any' type.
packages/base-href-webpack/src/base-href-webpack-plugin.spec.ts(58,16): error TS7006: Parameter 'htmlPluginData' implicitly has an 'any' type.
```

This PR fixes the compilation errors.

### CODE REVIEW

**Comment by catull** [comment]
Indeed, I authored these changes.

When I check the log, commit 71670ae32afec93e13ebf344c803e696f4544b97 clearly states the origin.

**Comment by catull** [comment]
Merges from Pull Requests do not always show the exact origins, I noticed in this particular project.

However small the contribution may be, it is also possible that someone other than me, came up with the same fix in a possibly larger Pull Request.

**Comment by catull** [comment]
At any rate, the change is in, that's all the counts.

**Comment by hansl** [comment]
This PR seems out of date now with the latest changes. Also, we do not want to force `noImplicitAny` on generated apps, just on the CLI itself.

**I'm going to close this PR** as most of its content is already in master.

As for the CLA bot, it gets confused sometimes. I can still merge without its accord, so just comment that you agree with the terms and I will ignore it.

Cheers!

**Comment by catull** [comment]
No problem, close it.

**Pull request closed without merging**
