### PR TITLE
chore(blueprints): update codelyzer

### PR DESCRIPTION
**Pull request by mgechev**
This version includes template support and is compatible with the latest changes in the `TemplateParser` introduced by Angular 2.0.2.

The following new rules are introduced:

```
// Does not allow access to private & protected
// in inline templates
"templates-use-public": true,

// Makes sure `@Injectable()` is invoked and not
// used as `@Injectable`.
"invoke-injectable": true
```

There's one more rule which verifies if all members accessed in templates are defined in the component's controller but doesn't check the inheritance chain so I'll open a PR for it once we have the entire functionality implemented.

### CODE REVIEW

**Comment by filipesilva** [comment]
Good stuff, thanks!

**Comment by mgechev** [comment]
A final change that I need to introduce as part of this PR are a few templete related rules. I will do that in a few hours today.

**Comment by filipesilva** [comment]
Ok, labelling it as WiP. Let me know when finished.

**Comment by mgechev** [comment]
@filipesilva it's ready, I only had to update `tslint.json`.

**Pull request closed without merging**
