### PR TITLE
refactor(@angular/cli): Use EnvironmentPlugin instead of DefinePlugin

### PR DESCRIPTION
**Pull request by ishitatsuyuki**

### CODE REVIEW

**Comment by clydin** [comment]
Thank you for the contribution.
For this use case, the EnvironmentPlugin appears to be a less flexible version of the DefinePlugin.  Could you provide some background on the reasoning for the change?

**Comment by ishitatsuyuki** [comment]
This doesn't solve or break anything. However, I found it looks more appropriate for the usecase.

Basically, this is for code clarity, since the plugin internally wraps DefinePlugin.

**Comment by clydin** [comment]
Ok. Understood.
In that case, the change should be a refactor instead of a fix.
Also please remove the white space changes.

**Comment by hansl** [comment]
What problem does this fix? Point to an issue please. Otherwise, this looks more like a `refactor` than a `fix`

**Comment by hansl** [comment]
@clydin tells me the commit message changed. We just need to evaluate the impact because this seems like it could affect other parts of the code.

**Pull request merged**
