### PR TITLE
refactor(init): run `link-cli` before `npm-install`

### PR DESCRIPTION
**Pull request by monojack**

### CODE REVIEW

**Comment by kylecordes** [comment]
Excellent... Great improvement in first use experience, looking forward to this.

**Comment by hansl** [comment]
@filipesilva: we moved it to after in #2086 because Ember-CLI was using the wrong dependency, but was this only for our e2e tests? We later updated e2e to use `node tests/e2e_runner.js` instead of using `npm run e2e`, so maybe this is working now.

Could you check it out?

if it doesn't work, I think we should just kill the `--link-cli` functionality altogether.

**Comment by monojack** [comment]
This was intended to reduce the time it takes to scaffold a new project by skipping re-installing the `angular-cli` package inside the project's `node_modules`. It links to the `angular-cli` global package and when `npm install` runs, it finds the symlink and skips over. Reduces the time with more than 60-70%

**Comment by Meligy** [comment]
Except, the problem with this behavior (as documented in #2086), is that it makes everyone hit by the `node_modules` inside the angular-cli repo folder being deleted, due to https://github.com/npm/npm/issues/10343, which is why #2086 changed it as I understand.

**Comment by aecz** [comment]
It looks like it only affects developers who have angular-cli repo locally and npm linked it.
For developers that just install angular-cli globally, it works and saves a lot of time and space.
```
npm i -g angular-cli
ng new myproject --link-cli
```
=> Global installation of angular-cli is not affected. So as @hansl said, the issue could be with angular-cli e2e tests but the build in appveyor went well for Node 5 so please keep this functionality.

And here are some metrics:

Project size:
- without link: 218MB
- with link: 60MB

=> 72% smaller

Command time:
- without link: 5 min 40s
- with link: 1 min 23 s

=> 76% faster

**Comment by kylecordes** [comment]
My timing ratios are similar to those from @aecz - although it sounds like there is a remaining issue here (--link-cli works with an ordinary global install of CLI, but with a local dev repo who linked that one globally? I didn't try it on the same machine with my source checkout), it seems worth fixing as the user experience is so much better. In particular it is much better for developers on Windows machines - for historical technical reasons I have forgotten, the file system implementation in Windows performs well reading and writing huge files but not so well reading and writing a large number of small files.

Is it possible that this link option could be polished sufficiently to be made the default?

**Comment by Meligy** [comment]
A proper test as I imagine would be to skip NPM installation and try all the steps manually like:

```
npm rm -g angular-cli
npm cache clear
npm i -g angular-cli
ng new myproject --sn
cd myproject
npm link angular-cli
npm i
```

If this doesn't affect the folder of the globally installed `angular-cli`, then this means that https://github.com/npm/npm/issues/10343 affects developers who have angular-cli repo locally as mentioned above (which will still need to be warned in docs or something).

**Comment by filipesilva** [comment]
As mentioned in https://github.com/angular/angular-cli/pull/2250#issuecomment-248537631, this change was introduced in https://github.com/angular/angular-cli/pull/2086 to address https://github.com/npm/npm/issues/10343. 

https://github.com/npm/npm/issues/10343 is very well summarized in its title: 
> `npm install` after `npm link` will "steal" dependencies from linked packages

It currently has the `big-bug` label in https://github.com/npm/npm. This means that it is a big bug and hence a big problem. For some reason or another it might not be affecting you in particular, but it's still an outstanding problem in `npm3`.

It's not very relevant that switching the order of `npm link` and `npm install` would make it faster if it potential breaks your install.

The `--link-cli` option is solely meant for working on the CLI while also testing changes on a project. The difference in install times is irrelevant for users because this is only used for development. It doesn't make any sense at all to make it the default because that completely sidesteps the point of having a local version.

If you want to use the `--link-cli` option for anything but CLI development, you do so at your own risk. Please don't open issues regarding alternative uses of this options.

**Comment by aecz** [comment]
I think the flag --link-cli for originally intented to link to the global version of angular-cli as stated in #778 .

For those who wants this behavior and do not have angular-cli repo linked locally. You can use these commands:
```
npm i -g angular-cli (unless it is already installed)
ng new --link-cli --skip-npm myproject
cd myproject
npm install
```
Much faster and lighter. Perfect when you make a demo of how great is angular-cli.

**Comment by filipesilva** [comment]
@aecz it's true that initially that was the purpose of `--link-cli`, but as it stands at the moment there are several reasons why this is a bad idea:
- the CLI started having a build step
- the CLI started having subpackages
- doing `npm install` after `npm link` can steal dependencies

Thus we cannot neither recommend nor support that usage.

**Comment by kylecordes** [comment]
Since it turns out that the NPM bug gets in the way of this efficiency/speed initial purpose, would be wise to park the link feature out of the way somehow? Here are a couple of ideas come to mind:

* Remove --link-cli, and people developing type an extra command to link manually?
* Rename it something like --link-for-cli-development or some other name that tries to clarify its more narrow purpose?
* When executed, make it notice it has been linked to a global installation, and print out a warning?

Offhand it seems that one of these could save some trouble for people who make their way into this feature somehow, are enthused at the apparent initial project-setup speed improvement (dramatic on Windows) without realizing the problems.

**Pull request closed without merging**
