### PR TITLE
docs: Fix typo in multiple files

### PR DESCRIPTION
**Pull request by thapasusheel**
## PR Checklist

Please check to confirm your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular-cli/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [X] Other... Please describe: Fix typo in multiple files

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

```pseudo
descrption > description
redudant > redundant
targetting > targeting
suppport > support
Specfication > Specification
peform > perform
```

### CODE REVIEW

**Review by alan-agius4 — COMMENTED** [review]
Thanks for this. 

Can you please update the commit type to `docs: `

**Comment by thapasusheel** [comment]
> Thanks for this. 
> 
> Can you please update the commit type to `docs: ` 

Sure, I have updated commit type to `docs:`.

**Comment by alan-agius4** [comment]
@thapasusheel, looks like you only updated the PR title not the commit https://github.com/angular/angular-cli/pull/26078/commits

**Comment by thapasusheel** [comment]
> @thapasusheel, looks like you only updated the PR title not the commit https://github.com/angular/angular-cli/pull/26078/commits

I am sorry for my inconvience. @alan-agius4  Can you review it again?

**Review by alan-agius4 — APPROVED** [review]

**Comment by alan-agius4** [comment]
Thanks for your contribution.

**Pull request merged**
