### PR TITLE
Fix: Changed file angular-ecosystem-logos.png. Cause of missing trans…

### PR DESCRIPTION
**Pull request by b1tw0rker**
…parency in bakground.

## PR Checklist

Please check to confirm your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular-cli/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by b1tw0rker** [comment]
Fix: Changed file docs/images/angular-ecosystem-logos.png. Cause of missing transparency in bakground.

**Review by alan-agius4 — CHANGES_REQUESTED** [review]
Thanks for your contribution. 

Can you please change the commit message to something like the below as per our commit message guidelines mention in https://github.com/angular/angular-cli/blob/main/CONTRIBUTING.md#commit?

```
docs: update angular-ecosystem-logos.png to transparent background.

This change update the mentioned file to have a transparent backgrounda
```

**Comment by alan-agius4** [comment]
@b1tw0rker are you willing to address the pending comment?

**Comment by alan-agius4** [comment]
Closing since comments have not been actioned. Please feel free to re-open when addressing the comments.

**Pull request closed without merging**
