### PR TITLE
fix(@angular-devkit/build-angular): update webpack-subresource-integr…

### PR DESCRIPTION
**Pull request by matdryz**
Related to [angular/angular-cli#9338](https://github.com/angular/angular-cli/issues/9338)

### CODE REVIEW

**Comment by alan-agius4** [comment]
The reason why this is blocked is because this version has a peer dependency of html-webpack-plugin. Which is not used in the CLI.

**Comment by matdryz** [comment]
Isn't it OK since it is an optional peer dependency?

**Comment by clydin** [comment]
Optional peer dependencies functionally don't exist since they are not standardized nor supported by npm.

**Comment by fabioemoutinho** [comment]
would be great to get rid of the following error:

`WARNING in webpack-subresource-integrity: Cannot determine asset for chunk scripts, computed="undefined", available=scripts.95488a83006a892d75cd.js. Please report this full error message along with your Webpack configuration at https://github.com/waysact/webpack-subresource-integrity/issues/new`

**Comment by alan-agius4** [comment]
Superseded by https://github.com/angular/angular-cli/pull/15592

**Pull request closed without merging**
