### PR TITLE
fix production build - issue #1644

### PR DESCRIPTION
**Pull request by abner**
changed mangle configuration to mangle: { screw_ie8 : true, keep_fnames: true } to fix production builds issue - see #1644

### CODE REVIEW

**Comment by abner** [comment]
as we can see in this pull request, this is even the way on angular own build. [https://github.com/angular/angular/pull/7988/files](https://github.com/angular/angular/pull/7988/files)

**Comment by TheLarkInn** [comment]
@hansl This is technically the change we were talking about yesterday.

@abner will you sync your branch with master.

**Comment by hansl** [comment]
Yes this is what's needed to fix the issue. We can revert it once we support offline compiler

**Comment by abner** [comment]
ok @TheLarkInn. just did it.

**Comment by TheLarkInn** [comment]
@abner still looks like this branch is out of date with latest master.

**Comment by filipesilva** [comment]
@TheLarkInn @abner I'm updating it myself, no worries.

**Pull request closed without merging**
