### PR TITLE
fix(@angular/cli): fix import path for component when importing into …

### LINKED ISSUE #7135: Angular cli Generates Wrong Directory Path in app.module.ts
### Bug Report or Feature Request (mark with an `x`)
- [x] bug report
- [ ] feature request

### Versions.

node -v : v6.10.0
npm -v : 5.3.0
ng -v : 
```
@angular/cli: 1.2.4
node: 6.10.0
os: darwin x64
```

### Repro steps.

- install the latest angular-cli (version : 1.2.4)
- go in the desired repository
- run the command `ng new myProject`
- go in the created project
- go in myProject/src/app and create a folder "common"
- go in "common" folder 
- run `ng g c myComponent`

### The log given by the failure.
- the component is created at the right location : 
```
installing component
  create src/app/common/my-component/my-component.component.css
  create src/app/common/my-component/my-component.component.html
  create src/app/common/my-component/my-component.component.spec.ts
  create src/app/common/my-component/my-component.component.ts
  update src/app/app.module.ts
```
- but the path written in "app.module.ts" is wrong
```
ERROR in /Users/u.name/myProject/src/app/app.module.ts (5,38): Cannot find module './common/src/app/common/my-component/my-component.component'.

ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve './common/src/app/common/my-component/my-component.component' in '/Users/u.name/myPoject/src/app'
 @ ./src/app/app.module.ts 10:0-99
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
```

### Desired functionality.
The path written is constantly adding "src/app" part whereas older version of the cli did not have this behavior
The correct import statement should be : 
`import { MyComponentComponent } from './common/my-component/my-component.component';`

### Mention any other details that might be useful.
This issue has also been reported on StackOverflow by another user : 
https://stackoverflow.com/questions/45293787/angular-cli-generates-wrong-directory-path-in-app-module-ts

### PR DESCRIPTION
**Pull request by andrewkww**
…a module

This is similar to 86021a0910495e61ec8bc539001b3755e928173d.

Fix #7135

### CODE REVIEW

**Comment by hansl** [comment]
Hi @andrewkww,

Could you add a test so we prevent readding issue #7135 in the future? Thanks!

**Comment by andrewkww** [comment]
@hansl Yup, added tests for other blueprints too.

**Comment by exequiel09** [comment]
Been waiting for this. I hope this PR will be merged soon. Thanks for the awesome work.

**Comment by hansl** [comment]
We're in the process of moving all our blueprints to Schematics. @Brocco is doing that work in #7090. Let's see if the issue happens still after that PR (some pathing problems were fixed because of the nature of Schematics which is stricter WRT paths).

I'm keeping this PR open but know that it will be obsolete. If the issue still happens, I'll check in with you that you make the change in the proper place on the Schematics repo.

Thakns!

**Comment by cyrilletuzi** [comment]
@hansl Why not include this PR in 1.3 ? I suppose schematics will have to wait for 1.4, meaning we will stay a more few weeks with this regression (and very annoying) issue.

**Comment by andrewkww** [comment]
Given the number of people running into the issue, it seems like a good idea to at least merge the change into 1.3.x.

**Comment by andrewkww** [comment]
Looks like the issue is now fixed in master. It'd still be good to include the tests that I have, since they test for the issue.

Also, the issue still exists in 1.3.x and 1.4.x. I think it's still a good idea to have the fix applied there. Let me know if you want the fix in those branches, and I can submit a pull request to those branches.

**Comment by hansl** [comment]
@andrewkww Master is not what's being released in 1.3.0, so this PR might actually skip master and be merged in 1.3.x directly.

**Comment by andrewkww** [comment]
Yes, but since this PR is set to merge into master, I've removed the patch so that the commits only contains the tests. This should be good to merge into master. If you want the fix for blueprint that I had previously, I can create a separate pull requests, one for 1.3.x and one for 1.4.x.

**Comment by hansl** [comment]
Please create one for `1.3.x`. We will only have the tests for 1.4.x.

**Comment by hansl** [comment]
@andrewkww I went ahead and did a PR for your 1.3.x branch and merged it. It's going to be out today. Thanks!

**Pull request merged**
