### PR TITLE
fix(@angular/cli): blueprint for polyfill.ts has redundant information

### LINKED ISSUE #5080: Blueprint for polyfill.ts has redundant information
### OS?
Windows 10.

### Versions.
@angular/cli: 1.0.0-rc.0
node: 7.6.0
os: win32 x64

### Repro steps.
The lines [39](https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/blueprints/ng/files/__path__/polyfills.ts#L39) and [40](https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/blueprints/ng/files/__path__/polyfills.ts#L40) can be joined with the line [48](https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/blueprints/ng/files/__path__/polyfills.ts#L48) and [49](https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/blueprints/ng/files/__path__/polyfills.ts#L49).

[Lines 39 e 40](https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/blueprints/ng/files/__path__/polyfills.ts#L39-L40):
```
/** IE10 and IE11 requires the following to support `@angular/animation`. */
import 'web-animations-js';  // Run `npm install --save web-animations-js`.
```
[Lines 48 and 49](https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/blueprints/ng/files/__path__/polyfills.ts#L48-L49):
```
/** ALL Firefox browsers require the following to support `@angular/animation`. **/
// import 'web-animations-js';  // Run `npm install --save web-animations-js`.
```
### Mention any other details that might be useful.
Lines 39 e 40 can be like this:
```
/** IE10, IE11 and all Firefox requires the following to support `@angular/animation`. */
// import 'web-animations-js';  // Run `npm install --save web-animations-js`.
```

### PR DESCRIPTION
**Pull request by rodrigopandini**
Fixes #5080

### CODE REVIEW

**Comment by rodrigopandini** [comment]
I signed it!

**Comment by grizzm0** [comment]
Can be closed along with the issue as @hansl answered why it is that way.

**Comment by Meligy** [comment]
The issue is still open.

**Comment by filipesilva** [comment]
I flagged the issue properly as awaiting further info from @hansl.

**Pull request closed without merging**
