### PR TITLE
feat(@angular/cli): allow comments in .angular-cli.json

### LINKED ISSUE #5610: Allow comments in .angular-cli.json
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x ] feature request
```

### Versions.
v1.0.0

### Repro steps.
ng s

### The log given by the failure.
InvalidConfigError: Parsing .angular-cli.json failed. Please make sure your .angular-cli.json is valid JSON. Error:
SyntaxError: Unexpected token / in JSON at position 533

### Desired functionality.
Would be really great to be able to put comments to that file. :)

### PR DESCRIPTION
**Pull request by thorn0**
Also allow trailing commas and unquoted object keys.

Closes #5610

### CODE REVIEW

**Comment by hansl** [comment]
We already have our own Json parser that supports those (basically Json5 support, and has AST with positioning): https://github.com/angular/devkit/tree/master/packages/angular_devkit/core/src/json

**Comment by thorn0** [comment]
@hansl Okay, I used it. 
Unfortunately, it doesn't support trailing commas, but I guess I'll open a separate issue or a PR for that.

**Comment by thorn0** [comment]
It doesn't look like my changes have anything to do with the test failing on Travis.

**Comment by thorn0** [comment]
Updated devkit to 0.4.0 to get support for trailing commas.

**Comment by thorn0** [comment]
Okay, I'm not sure how to update devkit properly. Seems like it's not that simple and shouldn't be part of this PR. So I'm leaving this PR as is.

**Comment by thorn0** [comment]
Rebased it onto `master`. @hansl Please have a look.

**Comment by clydin** [comment]
Closing as 6.0 has a new configuration system which brings support for comments.

**Pull request closed without merging**
