### PR TITLE
feat: update to angular2@2.0.0-beta.7

### PR DESCRIPTION
**Pull request by tapas4java**
Updated to angular2@2.0.0-beta.7

### CODE REVIEW

**Comment by filipesilva** [comment]
Lgtm

**Comment by Brocco** [comment]
@tapas4java Can you please also update the version of TypeScript? I added issue #240

**Comment by tapas4java** [comment]
Sure, will do it today

**Comment by tapas4java** [comment]
Closes #240

**Comment by Brocco** [comment]
Nice work, this lgtm, will merge later if not already merged

**Comment by Meligy** [comment]
Is this merged after version `0.0.24`? I have updated angular-cli (`npm update angular-cli -g`), and I still get Angular v2.6.

**Comment by Brocco** [comment]
This was definitely in prior to 0.0.24, can you verify the version you have installed globally with `npm ls -g --depth 0` if it shows `0.0.24` can you please create a separate issue with the details?

**Comment by Meligy** [comment]
Actually it shows 0.0.23, with a bunch of weird errors like:

```
npm ERR! extraneous: cardinal /usr/local/lib/node_modules/angular-cli/node_modules/bower/node_modules/cardinal
npm ERR! error in /usr/local/lib/node_modules/angular-cli/node_modules/bower/node_modules/cardinal: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/angular-cli/node_modules/bower/node_modules/cardinal/package.json'
npm ERR! extraneous: configstore /usr/local/lib/node_modules/angular-cli/node_modules/bower/node_modules/configstore
npm ERR! error in /usr/local/lib/node_modules/angular-cli/node_modules/bower/node_modules/configstore: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/angular-cli/node_modules/bower/node_modules/configstore/package.json'
npm ERR! extraneous: decompress-zip /usr/local/lib/node_modules/angular-cli/node_modules/bower/node_modules/decompress-zip
npm ERR! error in /usr/local/lib/node_modules/angular-cli/node_modules/bower/node_modules/decompress-zip: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/angular-cli/node_modules/bower/node_modules/decompress-zip/package.json'
npm ERR! extraneous: github /usr/local/lib/node_modules/angular-cli/node_modules/bower/node_modules/github
npm ERR! error in /usr/local/lib/node_modules/angular-cli/node_modules/bower/node_modules/github: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/angular-cli/node_modules/bower/node_modules/github/package.json'
npm ERR! extraneous: handlebars /usr/local/lib/node_modules/angular-cli/node_modules/bower/node_modules/handlebars
npm ERR! error in /usr/local/lib/node_modules/angular-cli/node_modules/bower/node_modules/handlebars: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/angular-cli/node_modules/bower/node_modules/handlebars/package.json'
npm ERR! extraneous: insight /usr/local/lib/node_modules/angular-cli/node_modules/bower/node_modules/insight
npm ERR! error in /usr/local/lib/node_modules/angular-cli/node_modules/bower/node_modules/insight: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/angular-cli/node_modules/bower/node_modules/insight/package.json'
npm ERR! extraneous: request /usr/local/lib/node_modules/angular-cli/node_modules/bower/node_modules/request
npm ERR! error in /usr/local/lib/node_modules/angular-cli/node_modules/bower/node_modules/request: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/angular-cli/node_modules/bower/node_modules/request/package.json'
npm ERR! extraneous: update-notifier /usr/local/lib/node_modules/angular-cli/node_modules/bower/node_modules/update-notifier
npm ERR! error in /usr/local/lib/node_modules/angular-cli/node_modules/bower/node_modules/update-notifier: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/angular-cli/node_modules/bower/node_modules/update-notifier/package.json'
npm ERR! extraneous: dateformat@1.0.12 /usr/local/lib/node_modules/gulp/node_modules/dateformat
npm ERR! error in /usr/local/lib/node_modules/gulp/node_modules/gulp-util/node_modules/dateformat: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/gulp/node_modules/gulp-util/node_modules/dateformat/package.json'
npm ERR! invalid: dateformat /usr/local/lib/node_modules/gulp/node_modules/gulp-util/node_modules/dateformat
npm ERR! extraneous: meow /usr/local/lib/node_modules/gulp/node_modules/gulp-util/node_modules/dateformat/node_modules/meow
npm ERR! error in /usr/local/lib/node_modules/gulp/node_modules/gulp-util/node_modules/dateformat/node_modules/meow: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/gulp/node_modules/gulp-util/node_modules/dateformat/node_modules/meow/package.json'
npm ERR! extraneous: defs /usr/local/lib/node_modules/typings/node_modules/defs
npm ERR! error in /usr/local/lib/node_modules/typings/node_modules/defs: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/typings/node_modules/defs/package.json'
npm ERR! extraneous: escodegen /usr/local/lib/node_modules/typings/node_modules/escodegen
npm ERR! error in /usr/local/lib/node_modules/typings/node_modules/escodegen: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/typings/node_modules/escodegen/package.json'
npm ERR! extraneous: recast /usr/local/lib/node_modules/typings/node_modules/recast
npm ERR! error in /usr/local/lib/node_modules/typings/node_modules/recast: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/typings/node_modules/recast/package.json'
npm ERR! extraneous: regenerator /usr/local/lib/node_modules/typings/node_modules/regenerator
npm ERR! error in /usr/local/lib/node_modules/typings/node_modules/regenerator: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/typings/node_modules/regenerator/package.json'
```

Looks like a machine-specific problem. I thought the upgrade command would have got the latest version, but it didn't. I'll uninstall and install again, but as for as this project is concerned, it's all cool.

Thanks for replying :)

**Pull request merged**
