### PR TITLE
fix(@angular/cli): normalize yarnrc/npmrc options

### LINKED ISSUE #16615: noproxy config is not respected when running ng update
# 🐞 Bug report

### Command

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes. This would not have been a problem prior to https://github.com/angular/devkit/pull/692 assuming a private registry was accessible without proxy. It is also relevant to #13166 .

### Description

NPM natively supports a `noproxy` setting in the `.npmrc` file that will prevent the proxy settings from being used for some specific URLs. This is incredibly useful when you have a private repository that is within your corporate network, but some packages, like `node-sass` will still need to reach to the internet to download binary files through the proxy.

Assuming that your private registry is at `registry.company.com`, you can add either the full sub-domain, or even just `company.com` to the `noproxy` setting and NPM will go to the registry directly, but all calls to other URLs done by NPM will still go through the proxy.

When using `ng update`, all calls using `npm-registry-client` will go through the proxy, even though they should be blacklisted by the `noproxy` list. This will cause calls to fail when using an enterprise proxy and a private registry that cannot be reached through the proxy.

## 🔬 Minimal Reproduction

- Setup a private npm repository that forwards calls to the official repository
- Setup a proxy so that it is required to go through the proxy to reach the broad internet, but that the private npm repository MUST be reached directly.
- Configure your `.npmrc` file like so:

```
proxy: myproxy.company.com
https-proxy: myproxy.company.com
noproxy: company.com
```

- Attempt to update an angular project from angular@^6 to angular@^7 using `ng update`.

## 🔥 Exception or Error
At this point, `ng update` will fail trying to parse the json file that is expected from the registry and print the html error page returned by the proxy instead. Something on the lines of:

```
Failed to parse JSON at column 1, unexpected token < in :
<doctype HTML........
  Cannot reach <insert package url here>. Timeout.
</html>
```

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.3.9
Node: 13.2.0
OS: win32 x64
Angular: 7.2.16
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.5
@angular-devkit/build-angular     0.8.5
@angular-devkit/build-optimizer   0.8.5
@angular-devkit/build-webpack     0.8.5
@angular-devkit/core              0.8.5
@angular-devkit/schematics        7.3.9
@angular/cli                      7.3.9
@ngtools/webpack                  6.2.5
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.5.4
typescript                        3.2.4
webpack                           4.21.0
</code></pre>

**Anything else relevant?**
Requires a private repository and proxy that cannot reach the repository.

## Workaround
Since `ng-update` will run NPM install scripts after doing the `npm-registry-client` calls, it is possible to remove the proxy setting before running `ng update`, and add it back as npm starts the install process using a second console. This will work as long as the first few packages getting installed does not do any network calls in their install script. It is also an incredibly risky workaround and I would recommend anyone attempting this to delete their `node_modules` folders after the update process, set their proxy settings correctly and re-run `npm install` before moving on.

### LINKED ISSUE #17314: ng update failes to latest version 9.1.0: unable to get local issuer certificate
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: 9.0.7

### Description

Error fetching metadata for '@angular/cli': request to https://proget.mydomain.de/npm/FEED/@angular%2fcli failed, reason: unable to get local issuer certificate

image

## 🔬 Minimal Reproduction

* Install and configure a local npm repository, e.g. ProGet
* npm set strict-ssl false
* npm set cafile C:\YourCARoot.cer
* npm set registry https://my-registry.internal-proget.de/npm/FEED
* ng update @angular/cli @angular/core

## 🌍 Your Environment

**Attention: This is the projects local version**
<pre><code>
C:\lvs\git\ng-viewer [master ↑1]> ng --version                                                                                                                                                        Your global Angular CLI version (9.1.0) is greater than your local
version (8.3.25). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.3.25
Node: 12.16.1
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.25
@angular-devkit/build-angular     0.803.25
@angular-devkit/build-optimizer   0.803.25
@angular-devkit/build-webpack     0.803.25
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      8.2.3
@angular/cli                      8.3.25
@ngtools/webpack                  8.3.25
@schematics/angular               8.3.25
@schematics/update                0.803.25
rxjs                              6.5.4
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

Well i'am very disappointed to have this error over and over again, since Angular 5 on any version this appears again and again. Why this cannot be fixed forever!!!

## Possible Fixes

* Researched from @bridzius 
> A quick fix from the cli perspective would be the downgrade of pacote back to `@<10`.
* The CLI could convert the strict-ssl setting to strictSSL

### PR DESCRIPTION
**Pull request by alan-agius4**
Closes #17314 and closes #16615

### CODE REVIEW

**Comment by kyliau** [comment]
merged label removed since PR hasn't got LGTM

**Comment by alan-agius4** [comment]
Superseded by https://github.com/angular/angular-cli/pull/17358

**Comment by devoto13** [comment]
@alan-agius4 Is there a particular reason why this was closed?

Judging from [this file](https://github.com/npm/cli/blob/release/v7.0.0-beta/lib/config/flat-options.js#L36) conversion is hard-coded in NPM CLI and moving forward there is no better way than repeating it for relevant options in Angular CLI.

**Comment by alan-agius4** [comment]
@devoto13, the reason why this has been closed is because we rolled back Pacote to version 9, which is used in npm version 6 and this PR was no longer relevant. Pacote 10+ is a complete rewrite for npm 7.0

Unfortunately, the file mentioned is for npm, but in the case of the CLI we need to support other package managers.

**Comment by devoto13** [comment]
@alan-agius4 Thanks for the explanation. I saw the rollback to version 9, but thought it was more of a quick fix.

> Unfortunately, the file mentioned is for npm, but in the case of the CLI we need to support other package managers.

This was actually my point. Given that code in the linked file is not something Angular CLI can re-use and that other package managers should be supported, is there any reason to delay an upgrade to newer Pacote versions? I mean NPM@7 release will not make this process any easier. The logic to normalise property names needs to be re-implemented in Angular CLI as was started by this PR.

My main reasoning for the update is that older `pacote` pulls plenty of older dependencies/polyfills and updating will allow to shrink some MBs from the CLI installation size.

**Comment by devoto13** [comment]
Actually never mind. Just looked through the new dependency tree and it managed to grow 2 times in size despite removing obsolete dependencies.

**Pull request closed without merging**
