### PR TITLE
Add package.json so that custom typeroots location is present and can resolve the types

### PR DESCRIPTION
**Pull request by sheetalkamat**
## PR Checklist

Please check to confirm your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular-cli/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

Per https://github.com/microsoft/TypeScript/issues/53122#issuecomment-1458855201 there are errors when building angular cli with typescript@next and this fixes this.
More info on typeRoots changed behavior per https://github.com/microsoft/TypeScript/pull/51715

### CODE REVIEW

**Review by Stoniboo — APPROVED** [review]

**Review by SpySioutis — APPROVED** [review]

**Review by Stoniboo — APPROVED** [review]

**Review by Stoniboo — APPROVED** [review]
✨

**Comment by alan-agius4** [comment]
@sheetalkamat is this change still needed?

**Comment by Stoniboo** [comment]
Yes

**Comment by alan-agius4** [comment]
Closing as this PR is stalled. If you wish to land these changes, please re-open.

**Review by Stoniboo — COMMENTED** [review]
I want to add these changes

**Pull request closed without merging**
