### PR TITLE
Replace deprecated camel-case argument

### PR DESCRIPTION
**Pull request by cgrevil**

### CODE REVIEW

**Review by alan-agius4 — CHANGES_REQUESTED** [review]
Can you please sign the CLA and update the commit message to 

```
docs: replace deprecated camel-case argument

`--createApplication` is deprecated in favor of `--create-application`
```

**Comment by cgrevil** [comment]
@googlebot I signed it!

**Comment by alan-agius4** [comment]
@cgrevil, you need to update the commit message and not the PR title.

**Comment by cgrevil** [comment]
@googlebot I fixed it.

**Comment by cgrevil** [comment]
@googlebot I signed it!

**Comment by alan-agius4** [comment]
Closing since issues has not been addressed.

**Pull request closed without merging**
