### PR TITLE
Fix for #3875

### PR DESCRIPTION
**Pull request by sterfpaul**
The problem: duplication of symlinked source files (npm linked sources) in CompilerHost's stats.
The solution: resolve these paths before of all
Gift of jdavidls

Exact same as: #3877 but with a new master.

(I remade this because Travis CI build was failing see: #4354)

### CODE REVIEW

**Comment by sterfpaul** [comment]
I signed it!

**Comment by sterfpaul** [comment]
I signed it!

**Comment by sterfpaul** [comment]
@googlebot I signed it!

**Comment by sterfpaul** [comment]
@googlebot why won't you verify me?

**Comment by Equinox** [comment]
@sterfpaul Because it's after confirmation from the person that committed the first two commits, not your confirmation of signing the CLA.

**Comment by sterfpaul** [comment]
@Equinox I am the commiter of all these commits and i signed the cla and i linked the email addresses from the commits to the cla. So i don't get why it's still not verifying me.

**Comment by sterfpaul** [comment]
I signed it!

**Comment by prowe214** [comment]
@sterfpaul Are you reopening this somewhere else?  Just making sure I follow along since this one has changed PRs a couple times.  This is a fix we're looking for.

**Comment by prowe214** [comment]
Ours is an issue with using `npm link` to locally consume a package that we're developing, cli's webpack doesn't seem to like symlinks, I was hoping this would fix it.

Hadn't tested this solution locally yet though, we were waiting on it getting merged.

**Comment by sterfpaul** [comment]
Yeah I was waiting on that too. Then I cloned it myself and tested it but it doesn't work.

I did find a workaround that might work for you.

Partial workaround for the problem in my repo is to add the following paths configuration to tsconfig.json:

```
paths": {
     "@angular/core": ["../node_modules/@angular/core"]
   }
```
Doesn't seem to work for everything. Not for Observable from rxjs for example.

**Pull request closed without merging**
