### PR TITLE
fix(@angular/cli): allow TS 2.5 for Angular >= 5.1

### LINKED ISSUE #8768: Angular cli 1.6 and Typescript 2.5.3 warning
I've recently updated to Angular 5.1.0 and Angular CLI 1.6.0 which is supposed to be typescript 2.5  friendly however I'm receiving the following warning

> @angular/compiler-cli@5.1.0 requires typescript@'>=2.4.2 <2.5.0' but 2.5.3 was found instead.

### Versions
```
Angular CLI: 1.6.0
Node: 7.9.0
OS: win32 x64
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cli: 1.6.0
@angular-devkit/build-optimizer: 0.0.35
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.41
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0
@schematics/angular: 0.1.10
@schematics/schematics: 0.0.10
typescript: 2.5.3
webpack: 3.10.0
```

```
  "dependencies": {
    "@angular/animations": "^5.1.0",
    "@angular/common": "^5.1.0",
    "@angular/compiler": "^5.1.0",
    "@angular/core": "^5.1.0",
    "@angular/forms": "^5.1.0",
    "@angular/http": "^5.1.0",
    "@angular/platform-browser": "^5.1.0",
    "@angular/platform-browser-dynamic": "^5.1.0",
    "@angular/platform-server": "^5.1.0",
    "@angular/router": "^5.1.0",
    "core-js": "^2.5.1",
    "rxjs": "^5.5.5",
    "zone.js": "^0.8.18"
  },
  "devDependencies": {
    "@angular/cli": "^1.6.0",
    "@angular/compiler-cli": "^5.1.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.92",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "^1.7.1",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "^1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.5.0"
  }
```

### Repro steps

* ng serve --aot

### PR DESCRIPTION
**Pull request by cyrilletuzi**
@filipesilva @Brocco 

Fixes #8768

### CODE REVIEW

**Comment by e-cloud** [comment]
hope this can be merged and release A.S.A.P :smile:

**Comment by jtsom** [comment]
Apparently not in the 1.6.1 release of the CLI...

**Comment by cyrilletuzi** [comment]
@filipesilva @Brocco why is this not part of 1.6.1 release ?

**Comment by SpeedHighway** [comment]
How do I install 2.6.0 since trying to do so installs the current 2.6.2 of typescript which isn't supported, even after this?

**Comment by clydin** [comment]
< 2.6 is officially supported which means 2.5.x is the highest allowed.

**Comment by rhino5oh** [comment]
@SpeedHighway you don't lol.  The latest version of angular only supports typescript 2.5.x so use 2.5

**Comment by yyjazsf** [comment]
tips:use "@angular/compiler-cli": "^5.2.0-beta.0" is not warning, but @angular/compiler-cli@^5.1.1 also

**Pull request merged**
