### PR TITLE
feat(@angular/cli): support TypeScript 2.4

### LINKED ISSUE #6827: typescript 2.4 support
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
1.1.3

### Desired functionality.
Angular-cli should support typescript 2.4 (just released yesterday). Right now angular-cli is locked down to max v2.3

### PR DESCRIPTION
**Pull request by filipesilva**
This PR doesn't change new projects to use 2.4 since I have seen some reports of possible problems in `@angular/*`. 

Instead, it:
- removes the dependency restrictions on <2.3
- bumps related dependencies (`rxjs@^5.4.2`, `ts-node@~3.2.0`) to the minimum that supports 2.4
- builds the CLI itself using 2.4

So if you want to install ts 2.4 in your new project, the CLI itself won't stop you.

Fix #6827

### CODE REVIEW

**Comment by filipesilva** [comment]
Followup from https://github.com/angular/angular-cli/pull/6891, had to close it because the CLA check bugged.

**Comment by filipesilva** [comment]
Fiddled around with the `const mkdir = denodeify(fs.mkdir);` problem, couldn't get to a solution. 

Following @clydin's recommendation I tried using [`denodeify` as a generic](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/denodeify/denodeify-tests.ts#L8-L9), and doing `const mkdir = denodeify<string, void>(fs.mkdir);`. But this doesn't seem to be enough, the types of the callbacks don't seem to match. 

I'll leave it as is for now and try to fix the typings later on.

**Comment by kuncevic** [comment]
interesting, angular cli supports typescript 2.4 but angular is not, yet https://github.com/angular/angular/issues/18454

**Comment by filipesilva** [comment]
Not so much 'supports' as 'doesn't stop you from trying to use it' :p

**Comment by kuncevic** [comment]
@filipesilva haha :)

**Pull request merged**
