### PR TITLE
turn off uglify warnings in production

### PR DESCRIPTION
**Pull request by mhamel06**
Fix https://github.com/angular/angular-cli/issues/1836

### CODE REVIEW

**Comment by clydin** [comment]
Could the warnings be hidden behind a `verbose` command line option?  They could be useful to some.

**Comment by filipesilva** [comment]
@TheLarkInn, what do you think?

**Comment by ciesielskico** [comment]
+1, warnings in production should be opt-in

**Comment by Brocco** [comment]
This needs to be configurable based upon a flag on the build command. And it will need corresponding tests.

**Comment by ciesielskico** [comment]
Actually I would rather have these warnings in development mode with actual line numbers so I can fix those warnings then.

**Comment by clydin** [comment]
They are not actually warnings. They are a list of uglifyjs optimization actions.

On Oct 14, 2016, at 4:31 PM, Alexander Ciesielski <notifications@github.com<mailto:notifications@github.com>> wrote:


Actually I would rather have these warnings in development mode with actual line numbers so I can fix those warnings then.

-

**Comment by hansl** [comment]
This was made obsolete by the latest changes to logging.

**Pull request closed without merging**
