### PR TITLE
feat(@schematics/angular): update karma to v3.0

### PR DESCRIPTION
**Pull request by Sibiraj-S**
Update Karma to v3.0.0 which resolves several vulnerable dependencies

### CODE REVIEW

**Comment by clydin** [comment]
This will need to be a `feat` since it changes the generated project.

**Comment by Sibiraj-S** [comment]
@clydin updated the change.

**Comment by sarunint** [comment]
@Sibiraj-S please also mention "Close #10963" in the commit message so that the issue is automatically closed when the PR is merged.

**Comment by Sibiraj-S** [comment]
@clydin . Updated the commit scope

**Comment by hansl** [comment]
@Sibiraj-S Additional (sorry for just piling on); could you also change the version in the root `package.json`? It will be installed for our tests.

**Comment by Sibiraj-S** [comment]
@hansl For. NP. Also karma-cli is redundant. Is it okay to remove that to.

**Comment by hansl** [comment]
Then please do :) . We don't use the CLI, not sure why it's there.

**Comment by Sibiraj-S** [comment]
What will be scope. I was thinking of `feat(@schematics/angular)`.

**Comment by Sibiraj-S** [comment]
@hansl . Done 😄

**Comment by hansl** [comment]
Looks good. Seems like your change might have some merging issue. Rebase and we'll merge it in as soon as caretaker is around (Monday at the latest).

**Comment by Sibiraj-S** [comment]
@hansl That is some sort off err I guess. Even though It shows some conflicts here, it merges cleanly without any err in my local.

**Comment by Sibiraj-S** [comment]
@hansl @clydin All Changes are made I guess.

**Comment by Sibiraj-S** [comment]
Can we expect this changes in next release, The vulnerabilities is kind of bothering/unpleasant in work envs.

**Pull request merged**
