### PR TITLE
fix(serve): Removes logic looking for `config/environment.js` in the project root

### LINKED ISSUE #3531: ERROR when using 'ng serve' with a ./config/environment.js path
> Please provide us with the following information:
> ---------------------------------------------------------------

Windows 10

angular-cli: 1.0.0-beta.22-1
node: 7.2.0
os: win32 x64

No. This app was created using the CLI.
I added a 'config' directory to the root of my application with an 'environment.js' file inside. I use this file from 'server.js' to set env variable in my express app.

C:\Users\brand\Desktop\projects\ng2-skeleton-node>ng serve
app.set is not a function
TypeError: app.set is not a function
    at module.exports.app (C:\Users\brand\Desktop\projects\ng2-skeleton-node\config\environment.js:2:7)
    at Project.config (C:\Users\brand\Desktop\projects\ng2-skeleton-node\node_modules\angular-cli\angular-cli\lib\models\project.js:198:52)
    at C:\Users\brand\Desktop\projects\ng2-skeleton-node\node_modules\angular-cli\commands\serve.js:95:40
    at process._tickCallback (internal/process/next_tick.js:103:7)

### Mention any other details that might be useful.

I renamed folder to 'configuration' and updated my references; this corrected the issue.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

### PR DESCRIPTION
**Pull request by gelliott181**
This removes the logic for ember-cli config files in the project root. Previously the CLI package would break when this file was present and `ng serve` was performed. It would remain unusable until the `config/environment.js` file is removed and `npm install` is performed again.

This allows the project to be served with the `config/environment.js` file in place. Fixes #3531

### CODE REVIEW

**Comment by gelliott181** [comment]
I signed it!

**Comment by gelliott181** [comment]
I signed it!

**Comment by gelliott181** [comment]
I signed it!

**Comment by gelliott181** [comment]
I signed It!

**Comment by hansl** [comment]
LGTM, thanks. Could you rebase?

**Comment by gelliott181** [comment]
Did you get the rebased commit? I did it late one night and wasn't sure if I pushed my master.

**Pull request closed without merging**
