### PR TITLE
chore(libs): completely removed current install/uninstall tasks

### PR DESCRIPTION
**Pull request by jkuri**
As it was agreed I removed this two tasks.

### CODE REVIEW

**Comment by filipesilva** [comment]
Can you also check `package.json` for any dependency you might have added for this feature? I know `glob` had to go from dev dep to normal dep in https://github.com/angular/angular-cli/commit/ef96ef20bb1c7841b65518a8ac7a58e42e824f79, but I don't know if there was anything else you added initially.

**Comment by jkuri** [comment]
If I remember correctly I didn't added any new dependency for this tasks, but I can check if `glob` is used somewhere else and if not, remove it.

**Comment by filipesilva** [comment]
It had to be moved to `dependencies` on account of https://github.com/angular/angular-cli/issues/233, but you're right, something else might need it now.

If nothing does need it though, it should go back to `devDependencies`.

**Comment by jkuri** [comment]
`/tests/runner.js' and `/tests/acceptance/init.spec.js` also uses `glob`..

**Comment by filipesilva** [comment]
That might be why it was a devDep I guess... I don't think those tests run outside of the dev environment.

**Comment by jkuri** [comment]
Moved `glob` to devDependencies.

**Comment by hansl** [comment]
LGTM :+1:

**Pull request merged**
