### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mithun-daa**
Fix grammar.

### CODE REVIEW

**Comment by filipesilva** [comment]
The grammar here is correct though - ran is the past of run.

**Comment by chrisoverzero** [comment]
Past tense is not correct grammar here. The sentence is in the passive voice, so it requires the past participle. Using a different kind of "test", "Tests are taken at the end of the semester" and not "Tests are took at the end of the semester."

**Comment by filipesilva** [comment]
Huh, I learn something new every day. Thank you for the explanation @chrisoverzero.

**Comment by filipesilva** [comment]
Closed via https://github.com/angular/angular-cli/commit/b28c098fd0835741e0ed2bcb89e125ae35d734b5

**Pull request closed without merging**
