### PR TITLE
chore(webpack): enable xhtml tags in ng build

### PR DESCRIPTION
**Pull request by CarreraPHP**
enable xhtml self closing tags in html files generated through ng build

### CODE REVIEW

**Comment by CarreraPHP** [comment]
PR request for #3217 to enable self closing tags in webpack generated html files.

**Comment by grizzm0** [comment]
You need to update the tests for index.html aswell.

**Comment by CarreraPHP** [comment]
@grizzm0, Updated tests as well.

**Comment by hansl** [comment]
LGTM, thanks!

**Pull request merged**
