### PR TITLE
add support for publicPath option in webpack

### LINKED ISSUE #2276: No publicPath option in configuration file
I´ve searched in the source but there´s no way of setting the "publicPath" of my application 

It should be inside the webpack output configurations but looking at angualr-cli source it´s not available.

For me it is crucial because I prepend /static/dist/ to load javascript and assets on my app.

I´m using NG version 1.0.0-beta.15

I´m using Django as Server and only doing watch on ng build and Django puts it´s static files in /static/ folder and maps the base URL to a template index.html file so the hrefs in the index files are not relative to the static folder and gets a 404 error.

All of this gets solved if I could add the publicPath configuration in angular-cli.json or environment files

### PR DESCRIPTION
**Pull request by Mischi**
Hi all,

this PR tries to add the publicPath option for webpack. 
I have not figured out how to test this feature yet? Would be happy for any suggestions though 😃 

Personally i would like to use this feature to easily integrate angular-cli based projects into ASP.NET MVC applications but there are many other valid use cases for publicPath option. See [BROCKHAUS-AG/AspNetAngular2IntegrationDemo](https://github.com/BROCKHAUS-AG/AspNetAngular2IntegrationDemo) for a simple demo ...

This should also fix #2276.

Cheers,
Fabian

### CODE REVIEW

**Comment by clydin** [comment]
Changing the base href doesn't do what you need?

**Comment by Mischi** [comment]
Hi,

using base href works kind of. The problem with using base href is that it will also affect ajax calls which in my case is not what i want ...

**Comment by clydin** [comment]
You can either use root relative urls or provide an app wide config object with a url _api_ base which can be prefixed to all ajax calls (good practice anyway in case the static content is split from the API in the future).

The nice thing about setting the base href is that it handles index.html, webpack, and angular routing all in one place.

**Comment by Mischi** [comment]
> You can either use root relative urls or provide an app wide config object with an api base url which can be prefixed to all ajax calls (good practice anyway in case the static content is split from the API in the future).

Yes, that works. Thanks!

But it doesn't feel correct to me though since  my `index.html` is served on `http://localhost:8080/` and all assets are below  `http://localhost:8080/Content/`. Using base href would feel more correct if my index.html would be served from `http://localhost:8080/Content/` too. But maybe that's just my lack of understanding as it seems to work with base href ....

Btw, my application structure looks like this:

* ClientApp (angular-cli project)
  - angular-cli.json
* Controllers
  -  HomeController (serves `../Content/index.html` on `http://localhost:8080/`)
* Content (`outDir`)
  - index.html
  - main.bundle.js
  - ...

**Comment by Mischi** [comment]
After playing a little bit more with `--base-href` i am pretty sure that `--base-href` is NOT what i want in my case.

I prepared two demos which demonstrate the difference between `--basic-href` and `publicPath` as i propose in this PR.

The `--basic-href` demo (http://ngcli-basehref.azurewebsites.net/) will use the --base-href "/Content" for routing too as you noticed which is not what i want.

If you compare this with the `publicPath` demo (http://ngcli-publicpath.azurewebsites.net/) you will notice, that /Content is only used for assets and not for routing.

@clydin, do you know a way i can archive this without `publicPath`?

Thanks in advance,
Fabian

**Comment by clydin** [comment]
Add this to your app module:
```
providers: [{provide: APP_BASE_HREF, useValue: '/'}]
```

As to the PR, I think that two options that perform similar functions but with slightly different outcomes  could lead to confusion.  Some guides on different hosting strategies would probably be useful regardless.

**Comment by Mischi** [comment]
Thanks again!

**Comment by jbellmann** [comment]
@Mischi 
Why did you close this PR? You don't want it merged anymore? I have seen lots of issues about this "publicPath"-config option.

**Comment by andyg3** [comment]
APP_BASE_HREF does exactly what I needed too. In my case, my index file is in the appname/ folder and my angular files are in a separate appname/dist/ folder. So I set my outDir to appname/dist and APP_BASE_HREF to "/appname/dist/". My BASE HREF is set to /appname/ and it calls the js files like "./dist/main.bundle.js"

**Comment by Mischi** [comment]
Hi @jbellmann, the solution @clydin proposed works for my current project but if you care i can reopen it.

**Comment by andyg3** [comment]
The solution from @clydin doesn't work in my case. I definitely need publicPath supported.

**Comment by jbellmann** [comment]
@Mischi 

please notice [my PR into your feature-branch](https://github.com/BROCKHAUS-AG/angular-cli/pull/1). Contains only the missing test.

**Comment by clydin** [comment]
@andyg3 feel free to open an issue to discuss your use case

**Comment by jbellmann** [comment]
@here I signed the CLA, but somehow the @googlebot is not checking again.

**Comment by andyg3** [comment]
Is there a way to kick the @googlebot into re-checking this?

**Comment by changLiuUNSW** [comment]
Is there any update with this? I really need publicPath supported.

**Comment by jbellmann** [comment]
@Mischi 

I merged latest changes from master and created a PR for your feature-branch.

Is there an easier way to handle this?

Regards,
Jörg

**Comment by rsnj** [comment]
I really need publicPath support as well. Will be great to get this merged in.

**Comment by changLiuUNSW** [comment]
https://github.com/angular/angular-cli/pull/3285

**Comment by filipesilva** [comment]
Superseded by https://github.com/angular/angular-cli/pull/3285, as it is more complete.

**Pull request closed without merging**
