### PR TITLE
fix(@schematics/angular): add migration to remove `skipTests` from `@schematics/angular:module`

### LINKED ISSUE #20848: Schematic input does not validate against the Schema
# 🐞 Bug report

### Command (mark with an `x`)

- [x] generate

### Is this a regression?

Yes, it works on Angular 11

## 🔬 Minimal Reproduction

Into _angular.json_ set `skipTests` at `true` to module schematic:

```
{
  ...
  "projects": {
    "frontend": {
     ...
      "schematics": {
        ...
        "@schematics/angular:module": {
          "skipTests": true
        },
        ...
      },
   },
}, 
```

run the command for generate new module:

`ng g m foo`

output

```
Schematic input does not validate against the Schema: {"skipTests":true,"name":"test","project":"frontend"}
Errors:

  Data path "" must NOT have additional properties(skipTests).
```

## 🔥 Exception or Error

<pre><code>
Schematic input does not validate against the Schema: {"skipTests":true,"name":"foo","project":"frontend"}
Errors:

  Data path "" must NOT have additional properties(skipTests).
</code></pre>

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.0
Node: 12.22.1
Package Manager: npm 6.14.12
OS: win32 x64

Angular: <error>
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0 (cli-only)
@angular-devkit/build-angular   12.0.0 (cli-only)
@angular-devkit/core            12.0.0 (cli-only)
@angular-devkit/schematics      12.0.0 (cli-only)
@angular/cli                    12.0.0 (cli-only)
@schematics/angular             12.0.0 (cli-only)
rxjs                            6.6.7 (cli-only)
typescript                      4.0.5 (cli-only)

</code></pre>

### PR DESCRIPTION
**Pull request by alan-agius4**
Migration for #20842

Closes #20848

### CODE REVIEW

**Review by clydin — APPROVED** [review]

**Comment by jacekkoziol** [comment]
It seems like the issue still exists, I'm using:

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    
Angular CLI: 12.0.2
Node: 14.15.5
Package Manager: npm 6.14.11
OS: darwin x64

Angular: 12.0.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.2
@angular-devkit/build-angular   12.0.2
@angular-devkit/core            12.0.2
@angular-devkit/schematics      12.0.2
@schematics/angular             12.0.2
rxjs                            6.6.7
typescript                      4.2.4
```
And still get an error:

```
ng g module public

Schematic input does not validate against the Schema: {"skipTests":true,"path":"src/app","name":"public","project":"my-project-name"}
Errors:

  Data path "" must NOT have additional properties(skipTests).
```

**Comment by alan-agius4** [comment]
Have you updated using `ng update`?

You can run the migration by running the below command
```
ng update @angular/cli --migration-only schematic-options-12
```

**Comment by jacekkoziol** [comment]
Yes, I've updated with `ng update`.
I've tried to use command:
`ng update @angular/cli --migration-only schematic-options-12`
and I'm getting the info: 
`Package '--migration-only' is not a dependency.`

**Comment by alan-agius4** [comment]
Oops wrong command argument, fixed!

**Comment by jacekkoziol** [comment]
@alan-agius4 Thank you for your help! The command `ng update @angular/cli --migrate-only schematic-options-12` solved the problem 😄

**Pull request merged**
