### PR TITLE
fix (#4199): let postcss pass-through sourcemap

### PR DESCRIPTION
**Pull request by asnowwolf**
resolve issue #4199 CSS Sourcemap is empty.

### CODE REVIEW

**Comment by filipesilva** [comment]
@asnowwolf I think this was fixed in https://github.com/angular/angular-cli/pull/4222. If that's incorrect, let me know.

**Comment by asnowwolf** [comment]
@filipesilva I think the root cause is post-css-loader eat the sourcemap which generated by sass-loader. I'm not sure that PR is resolved the issue. I'll test it later.

**Comment by asnowwolf** [comment]
@filipesilva 
I just tested the latest master branch and it still lost the sourcemap (I turned on the sourcemap and extractCss options)

**Comment by filipesilva** [comment]
Can you give me some repro steps to see that? I added a few tests in #4222 and they verify mappings are being generated.

**Comment by asnowwolf** [comment]
see <https://github.com/asnowwolf/t1>

the step is:

1. pull the latest master branch of angular-cli
2. `npm link` it as global package
3. `ng new t1 --style=scss --extract-css`
4. `npm i --save bootstrap@4.0.0-alpha.6`
5. add `@import '~bootstrap/scss/bootstrap';` to style.scss
6. `ng serve`
7. in chrome, I can't see the sourcemap correctly.

**Comment by asnowwolf** [comment]
Sorry, I've test it again, It's right now. I think there are some mistakes on my first test.

**Comment by filipesilva** [comment]
I was just testing myself and your demo seemed to give me the sourcemaps. I think you didn't `npm link angular-cli` to have the master version in the project.

Anyway, glad it's working for you!

**Comment by asnowwolf** [comment]
Sure, I think that's the mistake. thank you.

**Pull request closed without merging**
