### PR TITLE
protractor::getText now returns a Promise, so updated app.e2e-spec.ts.

### PR DESCRIPTION
**Pull request by SamuelMarks**
https://github.com/angular/protractor/blob/master/CHANGELOG.md#breaking-changes-4

I think. Double check from one of you required. My IDE was complaining so I traced the error all the way down the pipeline.

### CODE REVIEW

**Comment by sumitarora** [comment]
@SamuelMarks Please fix the commit message https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#commit

**Comment by Brocco** [comment]
This was merged into master reference: https://github.com/angular/angular-cli/commit/ba15605fc3ef2e9a117b25b8fbc05b6817b3d27d

**Comment by cexbrayat** [comment]
To be honest, I don't understand this change. Protractor has returned promises for a very long time (the breaking change mentioned is from Protractor 2.0.0 !).

I think the problem encountered by @SamuelMarks is probably something like https://github.com/angular/protractor/issues/4176. The cause is @types/jasmine 2.5.46. Try to pin your version to 2.5.45 and you should be fine?

Anyway I think this PR is introducing code that is not really the way Protractor should be used IMHO.

**Comment by cexbrayat** [comment]
I think the proper fix to the problem encountered is something like https://github.com/angular/angular-cli/pull/6799 : 
- use last `@types/jasmine`
- add `@types/jasminewd2`
- add `jasminewd2` to the tsconfig for e2e tests

**Pull request closed without merging**
