### PR TITLE
Fix GitHub typo Git'h'ub to Git'H'ub.

### PR DESCRIPTION
**Pull request by potato4d**

### CODE REVIEW

**Comment by potato4d** [comment]
I signed it.

**Comment by Equinox** [comment]
It's [here](https://github.com/angular/angular-cli/pull/3935/files#diff-47671671e7f3a5bbd35326f4efc1b03eL27), also. Throughout the different READMEs there are "github", "Github" etc might be worth making them all "GitHub" in the one pr at some point

**Comment by potato4d** [comment]
OK, I'm try it.

**Comment by potato4d** [comment]
I have completed fix it.
Changes are document only, source code is not done because it may be destructive(e.g. /packages/angular-cli/commands/github-pages-deploy.ts)

**Comment by hansl** [comment]
Ignoring the CLA bot because the original author signed it (see comments above), and I'm a Google employee.

**Comment by hansl** [comment]
LGTM, thanks!

**Pull request merged**
