### PR TITLE
feat(config): add template option to app config

### LINKED ISSUE #3338: Add customization options for HtmlWebpackPlugin
Currently app configuration doesn't allow to configure `HtmlWebpackPlugin` to use it's templating features.

It might be useful to have separate option in app config to specify different value for template option,
e.g. `index.ejs` to use ejs templates and allow `HtmlWebpackPlugin` to process it and generate `index.html`.

Also it would be useful to know the current environment inside the template to conditionally add things to resulting `index.html`.

### PR DESCRIPTION
**Pull request by miltador**
Currently app configuration doesn't allow to configure
HtmlWebpackPlugin to use it's templating features.

This PR allows to specify different value for template option,
e.g. 'index.ejs' to use ejs templates and allow HtmlWebpackPlugin
to process it and generate 'index.html'.

Also added environment value to the default set of options, very
useful for using inside template to conditionally add things.

Fixes #3338

### CODE REVIEW

**Comment by clydin** [comment]
HtmlWebpackPlugin pretty heavily leaks the underlying webpack implementation.  A templating solution that nicely abstracts the necessary information would probably be a better option.
Once something like this is implemented, it's hard to change it moving forward.  If webpack is ever replaced this would be _problematic_.

**Comment by miltador** [comment]
@clydin, agree with the point when webpack will ever be replaced. But if it will then there will be still needed a solution for placing links\scripts in index.html instead of HtmlWebpackPlugin.

If there will be another templating solution in the future then probably the template itself will have different extension or name, so something like `template` option will still be needed.

**Comment by clydin** [comment]
I agree that templating is a useful feature (especially exposing the environment).  However, once templating is "supported", changing the public API surface within the templates will be difficult and will likely cause a large amount of breakage in user's projects.

Also, there's an increasing amount of PR's that are adding direct webpack config options to a `angular-cli.json`.  Without careful thought, the file will eventually just be a webpack config in disguise.  Ideally, at least in my opinion, options should be abstracted from the underlying implementation, grouped logically, and the overall quantity should be minimized where possible.

**Comment by miltador** [comment]
@clydin, yes, we should be really careful with adding webpack or other build system specific options.
I do not see a big problem with adding `template` option if templating will be a feature of `angular-cli`. We'll definitely want to specify template and output (index) filenames.

As a workaround of not polluting `angular-cli.json` I can use `index` option instead for specifying template file name and use some predefined value for output filename, e.g. `index.html`. Or even go further and set output filename same as template name but change the file extension to `.html`.

Anyway, things will break down if user uses templates when the underlying webpack or `HtmlWebpackPlugin` will be changed to something else.

**Comment by filipesilva** [comment]
Closing as I also closed the issue itself, see https://github.com/angular/angular-cli/issues/3338#issuecomment-265736505

**Pull request closed without merging**
