### PR TITLE
chore(deps): remove addon code from ember.

### PR DESCRIPTION
**Pull request by hansl**

### CODE REVIEW

**Comment by CarreraPHP** [comment]
@hansl, with the removal of addon code from ember what is the roadmap for addon support in angular-cli? When implemented, will it be a separate ecosystem, there will be default support to ember-cli addons or there will be a migration tool or guide from ember-cli to angular-cli.

**Comment by hansl** [comment]
Separate ecosystem. We have a great design that's coming up after 1.0.

**Comment by JohannesHoppe** [comment]
This makes me really sad, because I actually made several angular-cli addons.
For God's sake, why didn't you decided to keep the old code until you have that alternative  addon-system??

**Comment by filipesilva** [comment]
@JohannesHoppe I'm sorry this broke the addons you had, although to be fair last time the issue was brought up I believe I mentioned that there was no warranty Ember-CLI addon system would be there in the future for Angular-CLI.

We had to remove it because it was slowing down `ng` command initialization and in some cases also had some bugs. 

Personally I think your work in https://github.com/angular-buch/angular-cli-ghpages is great and wanted to replace the current command in the CLI with it (or a similar version based on https://github.com/tschaub/gh-pages). I haven't done it yet because it's low prio compared to other things.

**Comment by piotrtomiak** [comment]
@filipesilva @hansl this breaks integration of Angular CLI with our Angular IDE as well. I know this is all in beta stages, but I think you shouldn't make such drastic changes without providing any alternatives. Speaking of which, how can we help to get some basic add-on mechanism pretty quickly into Angular CLI ?

**Pull request merged**
