### PR TITLE
E2e osx

### PR DESCRIPTION
**Pull request by jkuri**
https://github.com/angular/angular-cli/issues/90 https://github.com/angular/angular-cli/issues/91

### CODE REVIEW

**Comment by cironunes** [comment]
Great! LGTM

**Comment by jkuri** [comment]
Thanks for helping man. 
Now tests are taking much longer since travis needs to install nvm before running any tests.

**Comment by filipesilva** [comment]
lgtm as well, merging.

**Comment by filipesilva** [comment]
Eh wait, can't do it without a rebase atm. Can you rebase on top of master @jkuri ?

**Comment by jkuri** [comment]
Sure, rebased.

**Pull request merged**
