### PR TITLE
fix(@angular-devkit/build-angular): use process TTY as progress default

### LINKED ISSUE #11195: Regression: Don't print progress in a non-TTY context
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions

```
$ node --version
v8.11.2
$ yarn --version
1.7.0
```
macOS High Sierra 10.13.5 (17F77)

### Repro steps

See #8148.

### The log given by the failure

See #8148.

### Desired functionality

See #8148.

### Mention any other details that might be useful

This is a regression as it worked fine in CLI 1.7.4 and no longer does in 6.0.8.

### PR DESCRIPTION
**Pull request by filipesilva**
Fix #11195

### CODE REVIEW

**Comment by hansl** [comment]
This PR was a feature, as it changed the default behavior. It's been released in 6.1.3.

**Comment by alexeagle** [comment]
@hansl what do you suggest we do? Cut a 6.1.4 that removes this change?

**Comment by hansl** [comment]
Actually probably the most semver option, yes. Revert it in the patch (6.1.4 is due today anyway) and leave it alone in master.

**Comment by filipesilva** [comment]
This isn't a feature but rather a fix for a regression. See https://github.com/angular/angular-cli/issues/11195, https://github.com/angular/angular-cli/issues/8148 and https://github.com/angular/angular-cli/pull/8501.

**Pull request merged**
