### PR TITLE
fix(@schematics/angular): remove IE9/10 from browserslist for new projects

### PR DESCRIPTION
**Pull request by clydin**
BREAKING CHANGE:
Deprecated support for IE 9-10 has been removed in Angular 11.
Only IE 9-10 support has been removed. IE 11 is officially supported in Angular 11.
Additional information can be found here: https://v10.angular.io/guide/deprecations#ie-9-10-and-mobile

### CODE REVIEW

**Review by alan-agius4 — APPROVED** [review]

**Comment by alan-agius4** [comment]
Should we do a migration to remove these from existing project?

**Comment by clydin** [comment]
I think leaving existing projects is acceptable.  IE9/10 while not officially supported may still work for a given project and users may wish to keep that behavior.
I do think some form of warning and/or future health check audit may be prudent to help users optimally configure their projects.

**Review by kyliau — CHANGES_REQUESTED** [review]
Please add this link to the commit message: https://angular.io/guide/deprecations#ie-9-10-and-mobile

**Review by kyliau — APPROVED** [review]
We should either do a migration or print out a warning when users upgrade to v11.
Could you please do this as a follow up? Thank you.

**Pull request merged**
