### PR TITLE
fix(@angular/cli): updates module.id subsequent variable typing

### PR DESCRIPTION
**Pull request by dave11mj**
Fixes: https://github.com/angular/angular-cli/issues/5499

Related PR: https://github.com/angular/angular-cli/pull/5193

### CODE REVIEW

**Comment by filipesilva** [comment]
Blocking for now until we find the right approach.

**Comment by JemiloII** [comment]
Is this still necessary since the cli is using webpack now?

**Comment by filipesilva** [comment]
It's still useful for people migrating projects.

**Comment by JemiloII** [comment]
ahh makes sense then

**Pull request merged**
