### PR TITLE
feat: make part of the brocolli funnel config external

### PR DESCRIPTION
**Pull request by yannickadam**
Allows users to modify/update cli-config.json to add additional dependencies.

### CODE REVIEW

**Comment by yannickadam** [comment]
Maybe this should be included in ember-cli-build.js instead?

**Comment by doczoidberg** [comment]
What do I have to do to add additional packages from node or jspm?

**Comment by yannickadam** [comment]
Install your packages using npm, bower, ... inside your project directory.
Then, modify cli-config.json and add your own funnel:
```javascript
    {
      "funnels": [
        {"from":"node_modules", "to":"vendor", "files": [
          "angular2/bundles/angular2.dev.js",
          "angular2/bundles/router.dev.js",
          "angular2/bundles/http.dev.js",
          "systemjs/dist/system.src.js"
        ]},
        {"from":"[YOUR_DIRECTORY_HERE]", "to":"[DEST_DIR_UNDER_/DIST]", "files": [
          "[FILES_TO_INCLUDE]"
        ]}
      ]
    }
```

**Comment by doczoidberg** [comment]
I have no cli-config.json?

**Comment by yannickadam** [comment]
You need to generate your project using your own build of this pull-request. Then, cli-config.json will be at the root of your newly generated project.

**Comment by xmlking** [comment]
proposing: `angular-cl`i may adopt JSPM for dependency management and bundler tasks. 
it will manage all dependencies in `src/jspm.config.js`   and keep `index.html` clean.

**Comment by IgorMinar** [comment]
@xmlking unfortunately I don't currently feel comfortable building on top of jspm. it's too fragile and unstable.

**Comment by IgorMinar** [comment]
@yannickadam thanks for the PR. This looks like a good temporary solution, but definitely not a long term solution. ideally all you'd need to do is to specify your dependencies in `package.json` and we'd know what's the right thing to do (similar to jspm but without the downsides of jspm). I also don't think that these files should appear outside of the `vendor` directory, so your current setup is too flexible.

**Comment by hansl** [comment]
Is this PR still looked at?  The last message is 2 months old and and the owner of the PR hasn't answered.

**Comment by cironunes** [comment]
Closing it due to the lack of activity, feel free to reopen if you want to continue working on it.

**Pull request closed without merging**
