### PR TITLE
chore: update rxjs to rc.1

### PR DESCRIPTION
**Pull request by dzonatan**
Related to #2866

### CODE REVIEW

**Comment by filipesilva** [comment]
I don't think we can do this at the moment. `@angular/*` packages explicitely list `5.0.0-beta.12` as the peerDep, so if we change it everyone will get it peerDep warnings.
```
$ npm info @angular/core peerDependencies
{ rxjs: '5.0.0-beta.12', 'zone.js': '^0.6.21' }
```

**Comment by hansl** [comment]
I agree with @filipesilva.  Unfortunately we won't be updating until the core team does.

**Comment by dzonatan** [comment]
Then maybe #2866 is worth reopening for now?
I'm really upset with the size of angular-cli.. 🤔

**Comment by filipesilva** [comment]
@dzonatan you're right, reopening #2866.

**Comment by nkwood** [comment]
FWIW, the PR for 5.0.0-rc.1 in core (https://github.com/angular/angular/pull/12476) is now tagged for merge, but it probably doesn't make sense to re-open this until they cut a release.

**Comment by filipesilva** [comment]
@nkwood fair enough, didn't know it was already that close. I'll keep this open but on hold.

**Comment by e-cloud** [comment]
@dzonatan , it's better to support rc4

**Comment by filipesilva** [comment]
Closing as we'll  do this update when moving to angular 2.3.

**Comment by e-cloud** [comment]
so when will you moving to angular 2.3?

**Pull request closed without merging**
