### PR TITLE
fix(@schematics/angular): consecutive blank lines in routing.module.ts

### PR DESCRIPTION
**Pull request by sacgrover**
Fixes: #18220

### CODE REVIEW

**Comment by sacgrover** [comment]
@alan-agius4 Ok, I will do that.. Actually, I made the same earlier but to make it consistent with other I modified. Because there are a blank line between module import and component import in other places.

**Comment by alan-agius4** [comment]
@sacgrover, I see, in that case there should be a blank line in the logical statement and before the constant declaration.

```ts
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';<% if (lazyRoute) { %>

import { <%= classify(name) %>Component } from './<%= dasherize(name) %>.component';<% } %>

const routes: Routes = [<% if (lazyRoute) { %>{ path: '', component: <%= classify(name) %>Component }<% } %>];
```

**Comment by sacgrover** [comment]
Changes done as per asked.

**Comment by sacgrover** [comment]
> LGTM, thanks

Could You please rerun it as i don't have permissions for it?

**Pull request merged**
