### PR TITLE
refactor: remove `flatModuleId` and `flatModuleOutFile` from library …

### PR DESCRIPTION
**Pull request by alan-agius4**
remove `flatModuleId` and `flatModuleOutFile` from library tsconfig

The autogenerated fiellds are no longer required following this PR https://github.com/dherges/ng-packagr/pull/1024

This has been released in `ng-packagr` `v4.1.0`

//cc @filipesilva

### CODE REVIEW

**Comment by alan-agius4** [comment]
@filipesilva, rebase done, need to re-approved.
Thanks

**Comment by alan-agius4** [comment]
Both tests failures look like flakes

**Comment by filipesilva** [comment]
Restarted the flaked CI check.

**Comment by hansl** [comment]
@alan-agius4 could you rebase on top of master?

**Comment by alan-agius4** [comment]
@hansl rebase done.

**Comment by hansl** [comment]
Merging this as Filipe already reviewed.

**Pull request merged**
