### PR TITLE
feat(@angular/cli): add styles/scripts prefix

### PR DESCRIPTION
**Pull request by avshenuk**
Just for consideration. Add styles/scripts prefix in order to generate styles/scripts into different folders etc.

### CODE REVIEW

**Comment by hansl** [comment]
What's the use case for this that you're trying to fix?

**Comment by avshenuk** [comment]
Currently all the generated files will go into the root. Having styles/scripts placed into their own folders is better from multiple perspectives where one of them is Security of the application. Following the principle: secure everything and ignore specific it would be inconvenient to ignore every generated style/script but instead a singe folder containing all these styles/scripts. Saturday, 08 April 2017, 01:16AM +03:00 from Hans  notifications@github.com :

**Comment by changLiuUNSW** [comment]
@avshenuk  Be careful, this change will break CSS assets url path if user adds ```publicPath``` via ```deployUrl```.
We override ```publichPath:''``` for ```extractTextPlugin ``` which will only work if CSS and assets are under the same folder and your change will make the CSS and assets under different folder.
https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/models/webpack-configs/styles.ts#L181

**Comment by filipesilva** [comment]
thank you for the work you put into this Pr, but I don't think this change provides enough benefit vs the risk. There's also some overlap with `--deploy-url` in regards to functionality.

**Pull request closed without merging**
