### PR TITLE
refactor(@schematics/angular): remove copyright header from universal schematic files

### PR DESCRIPTION
**Pull request by brandonroberts**
## PR Checklist

Please check to confirm your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular-cli/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Angular copyright headers are included in scaffolded files when adding Angular Universal support.

Issue Number: N/A

## What is the new behavior?

The Angular copyright headers are no longer included in scaffolded files when adding Angular Universal support.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by alan-agius4 — APPROVED** [review]

**Comment by alan-agius4** [comment]
@brandonroberts, thanks for this

**Comment by dgp1130** [comment]
@brandonroberts there was a CI issue with a recent update to `lru-cache` which should now be fixed. I think if you rebase CI should pass?

**Comment by dgp1130** [comment]
Thanks @brandonroberts, merged it in!

**Comment by brandonroberts** [comment]
Thanks @dgp1130!

**Pull request merged**
