### PR TITLE
Add Validator generation

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
I'm trying to address: https://github.com/angular/angular-cli/issues/8170

I need help to figure out how to complete this PR. First of all, how can I execute the code that I added to check if it's really working?

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
any help with this?

**Comment by okeefem2** [comment]
@FrancescoBorzi One thing you can do (someone from the team may have better advice) is to build the project `npm run build`, then run npm link in the package that you made changes in, for you this would be `dist/schematics/angular` this links this built package to your global npm. Then in any angular project on your machine, run `npm link @schematics/angular` to create a symlink between your global and local (project) packages. Then you can use the code you wrote. Another thing I messed up at first is that you need to adhere to strict commit message guidelines, please [refer to the documentation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#commit).

**Comment by FrancescoBorzi** [comment]
@okeefem2 thanks a lot for your suggestion, that helped. About the commit message I guess we can deal with it later since the commits can be squashed and renamed when merging, right?

**Comment by okeefem2** [comment]
@FrancescoBorzi Happy to help! I look forward to being able to generate Validators!

**Comment by alexeagle** [comment]
Hi there,

Thanks for your proposal. We thought about this a fair amount.

One thing to observe is that angular-cli contains schematics for angular packages. This makes our ownership model more complex within our team. If someone who owns the `@angular/forms` package understands validators the best, then it seems like the `@angular/forms` schematic ought to be included in that package and owned by the same person.

Another observation is that creating a validator function is not difficult for users. But maintaining this code is an extra burden for us. So it doesn't meet our (current) bar for how much functionality we want to own.

You're free to publish a third-party schematic package that provides this, of course. We're happy to have your work be part of the angular community, we just don't want to merge it to this location.

**Comment by FrancescoBorzi** [comment]
@alexeagle thanks for your answer, I understand. Any suggestions about how could that be included into a third-party schematic package that can be easily used by users?

**Pull request closed without merging**
