### PR TITLE
Add missing semicolon to e2e template

### PR DESCRIPTION
**Pull request by bschlosser**
Very small change to add a missing semicolon after the beforeEach() call in app.e2e.ts

### CODE REVIEW

**Comment by hansl** [comment]
Weird that the linter didn't catch it in our tests... Thanks! LGTM

**Comment by hansl** [comment]
Could you rebase on master please? @bschlosser

**Comment by bschlosser** [comment]
Rebased.

Yeah, I was surprised that the linter didn't catch it as well. I'll look into that.

**Comment by bschlosser** [comment]
I signed it! Corporate - BP3 Global Inc

**Pull request closed without merging**
