### PR TITLE
feat(config): use of webpack externals

### LINKED ISSUE #2141: Proposal: Provide a way to add externals to webpack config
The issue is that if I use global script via app[0].scripts I cannot use it again in my .ts files.

Example: if I have:

```
      "scripts": [
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/moment/moment.js",
        "../node_modules/fullcalendar/dist/fullcalendar.min.js"
      ],
```

I cannot do: `import * as moment from 'moment';`. If I do so, moment will become an empty object. Of course, I can use it without importing it since it is global BUT other libs that depends on moment (angular2-moment in my case) will do `import * as moment from 'moment';`, they will get an empty object and their code will break. 
Then I cannot use this libs. (I think https://github.com/angular/angular-cli/issues/1974 is related)

I cannot remove moment from scripts since I have other global scripts that depend on it (fullcalendar). Maybe there is a way to make all this scripts work without apps[0].scripts but I have not found it.

My solution is to use webpack externals https://webpack.github.io/docs/library-and-externals.html

If I add 

```
externals: {
      'moment': 'moment'
    },
```

to `webpack-build-common.ts` it is working.

I can provide a PR adding externals from `apps[0].externals` to the webpack config. Is it the right solution?

### PR DESCRIPTION
**Pull request by MrChoclate**
fix #2141

### CODE REVIEW

**Comment by filipesilva** [comment]
Putting this PR on hold until I can better investigate #2141

**Comment by gregvis** [comment]
This feature is essential for using the angular cli with electron. 

In order for electron to find node modules, it cannot be bundled in webpack, it must be referenced externally.  

For example, i'm using npm package 'drivelist' to get a list of drives in my system. This library uses a node 'child_process' which cannot be webpacked. 

I'm using drivelist in an angular service, so to use it, I do the following:

'typings.d.ts'
`declare var drivelist: any`

webpack config:
`externals: {'drivelist':'require("drivelist")'}`

**Comment by gregvis** [comment]
I require externals for using Angular 2 with Electron. 

For example, i'm using an npm library called 'drivelist' which calls a node 'child_process'. The only way I could get this to work with ng-serve is to make 'drivelist' external and have Electron load the module. 

For ng serve, i included the external like this to work:
```
 externals: {
            'drivelist': 'commonjs '+ path.resolve(projectRoot, 'node_modules', 'drivelist'),
           'electron': 'commonjs electron'
         
        }
```

Then in Electron, i'm just loading the ng serve url:
```
win = new BrowserWindow({width: 800, height: 600})
win.loadURL('http://localhost:4200');
```

**Comment by filipesilva** [comment]
Closing in favor of https://github.com/angular/angular-cli/pull/3814

**Comment by epieddy** [comment]
@filipesilva The stuff in #3814 is not related to being able to use the externals configuration of webpack.

We need the options provided in this PR.

**Pull request closed without merging**
