### PR TITLE
feat(@angular/cli): add type-checking flag to BuildOptions

### PR DESCRIPTION
**Pull request by rahuljayaraman**
To turn off type checking
```
ng build --type-checking=false
ng build -tc=false
ng serve -tc=false
```
Ref: https://github.com/angular/angular-cli/issues/5675

### CODE REVIEW

**Comment by filipesilva** [comment]
@hansl can you weight in? Is this something you want to be supported?

**Comment by rahuljayaraman** [comment]
@hansl do you have feedback for me on this one?

**Comment by hansl** [comment]
Sorry for the slow answer, going through my inbox one by one.

If you're not using type checking, why use typescript at all? Also, the Typescript compiler (and `ngc`) doesn't support disabling type checking, so this is not something we will support.

Closing this as this is not a feature we want. Sorry.

**Comment by rahuljayaraman** [comment]
@hansl Does angular-cli emit on error though? If I'm not mistaken, tsc does that.

**Pull request closed without merging**
