### PR TITLE
chore(): add typings files to assist devs

### PR DESCRIPTION
**Pull request by Brocco**
Some editors/IDEs will utilized TypeScript definition files
Adding some useful definitions to assist developers

### CODE REVIEW

**Comment by filipesilva** [comment]
What do you think of using (tsd)[https://github.com/DefinitelyTyped/tsd] to install and manage these?

A `postinstall` script in `package.json` could then install them automatically after the project dependencies are installed.

**Comment by cironunes** [comment]
+1 for using tsd

**Comment by Brocco** [comment]
I have no problem switching to using a tool. But I just heard of a new typings manager yesterday, take a look at https://github.com/typings/typings and I can switch to either this or tsd with a post install script

**Comment by filipesilva** [comment]
I checked that repo and `typings` seems nice. 

It's own registry is kinda empty but I guess it doesn't make much of a difference since it can install stuff from a lot of places. 

I can't find much information about it on the Internet though. 

I'm OK either way really, what do you prefer @brocco?

**Comment by Brocco** [comment]
I think `typings` looks interesting as a future goal, but with the state and current direction of the CLI, I think I'll just stick with `tsd` I'll clean up this PR and re-push it

**Comment by filipesilva** [comment]
Can't think of any others right now, no.

**Comment by Brocco** [comment]
I ended up going with typings over tsd as tsd has been deprecated in favor of typings (npm install message when upgrading tsd).

type info is now kept in `typings.json` and will be installed via an npm post install script

**Comment by filipesilva** [comment]
It's in!

Also, for the record, some info on the deprecation can be found in this issue https://github.com/DefinitelyTyped/tsd/issues/269

**Pull request merged**
