### PR TITLE
feat: allowOutsideReadDir configuration

### PR DESCRIPTION
**Pull request by eromano**
Load file from an external folder now fails because of this check :
An asset cannot be read from a location outside the project
Introduced by the PR:
64c6031#diff-9eb0a75e499bdadd44d6dc62218812b8
With allowOutsideOutDir property asset configuration the user can decide to allow this kind of behaviour:

```json
"assets": [
  {
    "glob": "**/*",
    "input": "/temp-folder/outside-allowed/of/project",
    "output": "../not-dist/some/folder/",
    "allowOutsideReadDir": true
  },
]

```
it is false by default and be enabled by the user only when he knows the security risk behind this kind of decision.

See issue: https://github.com/angular/angular-cli/issues/8783

### CODE REVIEW

**Comment by eromano** [comment]
Hi guys this PR is needed to our project https://github.com/Alfresco/alfresco-ng2-components in order to update the angular cli. If you want I am happy to illustrate a possible scenario

**Comment by tleveque23** [comment]
Any news on this one? Seems that only some reviews are missing. This bug is really annoying for our project....

**Comment by bjornharvold** [comment]
Interested in how this will get resolved as well. Wouldn't having a mono repo with common assets in an external directory be a good use case for this feature? In my case, I have Ethereum contracts in one project that needs to be compiled and then used by an admin app and a consumer app. All 3 projects are in the same mono repo at the same level.

**Comment by hansl** [comment]
@eromano Could you add a warning on compilation when the configuration option is present (and error out if it's not)?

The reason this check is there is so that people cannot `ng build && deploy` and end up with files they don't want (or aren't aware of) from, e.g., their home directory. There's a way to copy all your SSH keys for example to the assets directory, and someone who doesn't know better will end up with their CD keys available publicly.

This will be all removed in the soon future (next major), but we can make that fix in 1.7.0.

**Comment by prashu2705** [comment]
Hi,

When will this be merged? I'm in need of this change as well.

Thanks.

**Comment by eromano** [comment]
@hansl I have added the warning. I don't know if this PR still make sense or not.
Sorry for the late response but I didn't notice the mention

**Comment by SpellChucker** [comment]
+1 on this one too, we use a shared folder for assets outside of the project and pull them in through `.angular-cli.json`.

**Comment by eromano** [comment]
@hansl should I rebase it another time? or there are no intention to merge it?

**Comment by Dumpen** [comment]
This would be a greatly appreciated feature. We have a lot of shared assets that will benefit from this.

**Comment by kafumanto** [comment]
We are using sibling shared modules and this missing feature is a problem.

**Comment by agustintarifa** [comment]
Any news about this?

**Comment by alexeagle** [comment]
Sorry this got stale @eromano 
Sounds like this change is still needed? Will discuss with @hansl

**Comment by alexeagle** [comment]
We are okay with accepting a PR to read assets from outside the project. But this needs some work to re-base first (likely just make the change again fresh).

**Comment by alan-agius4** [comment]
Thanks for your PR. Though I'll be closing as per @alexeagle comment. Please re-open the PR when the issues are fixed and is in a mergeable state.

**Pull request closed without merging**
