### PR TITLE
fix(aot-tools): add missing tsc-wrapped dep

### LINKED ISSUE #2498: Missing dependency in @angular-cli/ast-tools
OS: Windows 7
angular-cli: 1.0.0-beta.16
node: 6.5.0
os: win32 x64

@angular-cli/ast-tools imports @angular/tsc-wrapped but does not declare it in its package.json as a dependency.
https://github.com/angular/angular-cli/blob/master/packages/ast-tools/src/ast-utils.ts#L3

### PR DESCRIPTION
**Pull request by filipesilva**
Fix #2498

### CODE REVIEW

**Comment by clydin** [comment]
Should the typescript version be bumped as well?  Looks like tsc-wrapped has a peer dep of ^2.0.2

**Comment by filipesilva** [comment]
@clydin good catch, will update.

**Comment by Brocco** [comment]
All looks good, only thing is that now TypeScript is at version 2.0.3

**Comment by filipesilva** [comment]
@Brocco I'll update that separately, we have 2.0.2 everywhere atm and I just wanted parity on this package.

**Comment by filipesilva** [comment]
Here it is: https://github.com/angular/angular-cli/pull/2738

**Pull request closed without merging**
