### PR TITLE
support source mapping for component styles. add html-loader.

### PR DESCRIPTION
**Pull request by asnowwolf**
feat add css-with-mapping-loader to enable source mapping for component style
feat: add html-loader
feat: inline small SVG files referenced by HTML/CSS as dataURLs

NOTICE: Currently, angular will lost source mapping of component style, see my another PR: https://github.com/angular/angular/pull/14175 . To experiment, please manually patch it first.

### CODE REVIEW

**Comment by hansl** [comment]
This PR does not seem to have a focused fix or feature, fails all the tests in the list, and does not have an issue attached to it. I'm going to close this.

**Comment by asnowwolf** [comment]
The problems it solves are:
1. For the Component Styles file, you can not see the correct SourceMap information when debugging.
2. When packing all the picture files are not given the correct "cache-hash"

Should I first commit the issues before submit PR?

**Comment by asnowwolf** [comment]
And also, the testing fail is because:

error An unexpected error occurred: "https://registry.yarnpkg.com/requires-port/-/requires-port-1.0.0.tgz: Request failed \"502 Bad Gateway\"".

But I will remove all node_modules and re-run `npm test` on my mac.

**Comment by asnowwolf** [comment]
Does we don't allow to add new dependencies? or need approval first?

```
2 excessive dependencies in package.json:
    css-with-mapping-loader
    html-loader
```

**Comment by asnowwolf** [comment]
e2e testing is ok now.

**Pull request closed without merging**
