### PR TITLE
Add documentation on how to use a custom domain

### PR DESCRIPTION
**Pull request by dhcdata**

### CODE REVIEW

**Comment by hansl** [comment]
That is not our documentation format at all. If you're interested in doing the right change, you should add the argument documentation to the `/docs/wiki` folder in the project, which contains all our documentation.

**Comment by dhcdata** [comment]
I would gladly put it where ever it belongs in the correct format if you could point to any documentation on formatting.  

There is no `/docs/wiki` folder in the project.  There is a `/docs/documentation` and a `/docs/design`.  

I didn't think to put it in either of those places since `github-pages:deploy` command isn't documented there at all.  This command is also not document to the wiki attached to the project  This command is however documented on the `/README.md` page.

**Comment by hansl** [comment]
`/docs/documentation` is what I meant. `github-pages:deploy` should be documented in there since we officially support it.

**Comment by austin94** [comment]
@dhcdata my pull-request #3392 introduces a `--custom-domain` flag which handles the base-href manipulation and CNAME file creation.  Your additions look good, but I would suggest using that new flag. Thanks!

**Pull request closed without merging**
