### PR TITLE
fix(webpack): remove usage of fallbackLoader and loader

### LINKED ISSUE #4434: fallbackLoader option has been deprecated - replace with "fallback" loader option has been deprecated - replace with "use"
> Please provide us with the following information:
> ---------------------------------------------------------------

- macOS Sierra
- Ubuntu 16.04.1 LTS (clean machine)

```
@angular/cli: 1.0.0-beta.30
node: 7.5.0
os: darwin x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.6
@angular/cli: 1.0.0-beta.30
@angular/compiler-cli: 2.4.6
```

```
$ ng new fallbackloader
$ cd fallbackloader
$ ng serve
```

```
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
** NG Live Development Server is running on http://localhost:4200. **
```
### Mention any other details that might be useful.

The project seems to work correctly. 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

### PR DESCRIPTION
**Pull request by beeman**
Fixes #4434

### CODE REVIEW

**Comment by hansl** [comment]
Just to clarify; this is to fix a warning, correct? There's no need for an emergency release, right?

**Comment by beeman** [comment]
That's right @hansl, the apps work fine and the warning only appears once

**Comment by HauntedSmores** [comment]
Im still getting this issue and I deleted node_modules and redid npm install. Is this not on a release branch or something?

**Comment by beeman** [comment]
@HauntedSmores it's been merged into master, it will be available in the next release.

**Comment by HauntedSmores** [comment]
@beeman Thanks for the response!

**Comment by beeman** [comment]
@HauntedSmores this file is part of Angular CLI itself, it's not inside your app. 

If you want to manually get rid of this error, the file should be located in `node_modules/@angular/cli/models/webpack-configs/styles.ts`

**Comment by TwanoO67** [comment]
This is not only a warning, this error appears 4 times during compilation, and it makes webpack compilation fail...

**Comment by dags** [comment]
any ETA to get this new release. Currently, my build is broken ..

**Comment by HauntedSmores** [comment]
@Beeman I know it is, I checked the path from your repo but I don't have styles.ts in the directory you just gave

**Comment by dags** [comment]
I think CLI doesn't install individual ts files .. I can't find it either ...

**Comment by dags** [comment]
It is also in the project :

./node_modules/@angular/cli/models/webpack-configs/styles.js

**Comment by darrenbrett** [comment]
I get this error too when running "ng serve" - although my app still compiles and boots up. (see below). So it's more of an annoyance than something critical. But curious, is there a current resolution or do we just need to wait for the next update?

> bash-3.2$ ng s
> fallbackLoader option has been deprecated - replace with "fallback"
> loader option has been deprecated - replace with "use"
> fallbackLoader option has been deprecated - replace with "fallback"
> loader option has been deprecated - replace with "use"
> fallbackLoader option has been deprecated - replace with "fallback"
> loader option has been deprecated - replace with "use"
> fallbackLoader option has been deprecated - replace with "fallback"
> loader option has been deprecated - replace with "use"
> ** NG Live Development Server is running on http://localhost:4200. **
> Hash: 86877c66b943cc1f9090
> Time: 37200ms
> chunk    {0} main.bundle.js, main.bundle.map (main) 754 kB {3} [initial] [rendered]
> chunk    {1} polyfills.bundle.js, polyfills.bundle.map (polyfills) 222 kB {4} [initial] [rendered]
> chunk    {2} styles.bundle.js, styles.bundle.map (styles) 27 kB {4} [initial] [rendered]
> chunk    {3} vendor.bundle.js, vendor.bundle.map (vendor) 5.05 MB [initial] [rendered]
> chunk    {4} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]
> webpack: Compiled successfully.

**Comment by G-Pandey** [comment]
When will the next update be released? I also couldn't find `style.ts` in the suggested directory. Project does compile successfully but it would be nice to have it resolved asap.

**Comment by michaelcm** [comment]
Also looking for a release promptly with this fix. Thanks in advance!

**Comment by elnobun** [comment]
For those who cannot find it in Angular CLI, the correct path is

```
node_modules/angular-cli/models/webpack-configs/styles.js
```

You should see this:

```
// load global css as css files
    if (globalStylePaths.length > 0) {
        rules.push.apply(rules, baseRules.map(function (_a) {
            var test = _a.test, loaders = _a.loaders;
            return ({
                include: globalStylePaths, test: test, loaders: ExtractTextPlugin.extract({
                    loader: [
                        // css-loader doesn't support webpack.LoaderOptionsPlugin properly,
                        // so we need to add options in its query
                        ("css-loader?" + JSON.stringify({ sourceMap: cssSourceMap }))
                    ].concat(commonLoaders, loaders),
                    fallbackLoader: 'style-loader',
                    // publicPath needed as a workaround https://github.com/angular/angular-cli/issues/4035
                    publicPath: ''
                })
            });
        }));
    }

```

Change the `loader` to `use`, and the `fallbackLoader` to `fallback`

**Comment by JanStureNielsen** [comment]
See http://stackoverflow.com/questions/42076879/fallbackloader-option-has-been-deprecated-replace-with-fallback

**Comment by beeman** [comment]
@JanStureNielsen this has been fixed in the last release

**Comment by michaelcm** [comment]
The last release v1.0.0-beta.30 was released 10 days ago, and the patch was pushed 7 days ago... doesn't seem to be included in the last release.
https://github.com/MRHarrison/angular-cli/commit/f5624ab588a101fc3396aeb34962a8cb4761c7aa

**Comment by beeman** [comment]
The last release is beta 31 and has the fix. See the readme for the upgrading instructions.

**Pull request merged**
