### PR TITLE
feat: Implementation of flag to install Angular Material on `new` or `init`

### LINKED ISSUE #884: Smooth integration of angular2-material
Hi,

I think it would be interesting to have a smooth integration between angular2 and angular2-material.
Angular2 is now called a platform and not a framework because of all this ecosystem around it and having all of that merged within angular-cli would be awesome.

It's just my opinion, but having something like that would be nice : 
`ng new my-project --material` or `ng new my-project --mobile --material`

Behind the hood it would 
`npm install --save @angular2-material/core`

And initialize those files (so devs just have to add the components they need) :

**angular-cli-build.js**
```javascript
/* global require, module */

var Angular2App = require('angular-cli/lib/broccoli/angular2-app');

module.exports = function(defaults) {
  return new Angular2App(defaults, {
    vendorNpmFiles: [
      'systemjs/dist/system-polyfills.js',
      'systemjs/dist/system.src.js',
      'zone.js/dist/**/*.+(js|js.map)',
      'es6-shim/es6-shim.js',
      'reflect-metadata/**/*.+(js|js.map)',
      'rxjs/**/*.+(js|js.map)',
      '@angular/**/*.+(js|js.map)',
      '@angular2-material/**/*.+(js|js.map)'
    ]
  });
};
```

**system-config.ts**
```javascript
/***********************************************************************************************
 * User Configuration.
 **********************************************************************************************/
/** Map relative paths to URLs. */
const map: any = {
  '@angular2-material': 'vendor/@angular2-material'
};


/** User packages configuration. */
const packages: any = {
  '@angular2-material/core': {
    format: 'cjs',
    defaultExtension: 'js',
    main: 'core.js'
  }
};

////////////////////////////////////////////////////////////////////////////////////////////////
/***********************************************************************************************
 * Everything underneath this line is managed by the CLI.
  **********************************************************************************************/
....
```

This way it would be much easier to start a project with material-design and we wouldn't have to type as fast as Kara :fire: !

### PR DESCRIPTION
**Pull request by marc-sensenich**
Added --material flag onto the new and init features for the core setup of Angular Material

fixes #884

### CODE REVIEW

**Comment by metric152** [comment]
this is pretty cool. nice feature add.

**Comment by filipesilva** [comment]
@hansl can you have a look?

**Comment by JohannesHoppe** [comment]
Great idea. :+1: 
But I tried this out and I don't see a big benefit (for now).

According to the "Getting Started Guide" (https://github.com/angular/material2/blob/master/GETTING_STARTED.md) only step 1 to 3 are done.

There are more steps to do:
* I still need to install the componentes by hand (eg. `npm install --save @angular2-material/{button,card}`
* vendorNpmFiles copies only *.js files, it should copy everything
* Main file for the packages are not configured. 
```materialPkgs.forEach((pkg) => {
  packages[`@angular2-material/${pkg}`] = {main: `${pkg}.js`};
});```

For the sake of simplicity I would install all components by default...

**Comment by JohannesHoppe** [comment]
All my suggestions as a diff:
https://github.com/Angular2Buch/angular-cli-material-flag/commit/a53de8f45fee20db78cfb2786f1deb44792d2454

... works like a charm! Thanks @marc-sensenich :smile:

**Comment by filipesilva** [comment]
Closed as this PR was made obsolete by https://github.com/angular/angular-cli/pull/1455.

**Pull request closed without merging**
