### PR TITLE
fix(sass): don't compile partials

### PR DESCRIPTION
**Pull request by Madd**

### CODE REVIEW

**Comment by Madd** [comment]
Signed

2016-06-20 22:59 GMT+02:00 googlebot <notifications@github.com>:

**Comment by filipesilva** [comment]
Thanks for working on this @Madd ! I'm working on getting it merged now.

**Comment by filipesilva** [comment]
Closed via https://github.com/angular/angular-cli/commit/af9a4f98b5a6f5b7370a30138d11eeb79d4aad81

**Comment by hieutranagi47** [comment]
I don't know why the issue was close while we can not import a partial scss file without underscode and scss extension similar:
/utilities/_fonts.scss
=> @import 'utilities/fonts'
http://sass-lang.com/documentation/file.SASS_REFERENCE.html#partials

**Pull request closed without merging**
