### PR TITLE
fix(@angular/build-angular): add deployUrl to project icon href path

### LINKED ISSUE #13201: favicon href would work with deploy-url option
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
```

### Versions
On Ubuntu, Angular CLI version is 7.1.2

I have this shell script:

```bash
#!/usr/bin/env bash
set -e;
deploy_url="localhost:9080/"
cd "$(dirname $(dirname "$0"))"
cd apps/api-app
ng build --watch --output-hashing none --deploy-url "$deploy_url"
```

It generates an index.html like so:

```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>ApiApp</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.js"></script>

</head>
<body>

<app-root></app-root>
<script type="text/javascript" src="localhost:9080/runtime.js"></script>
<script type="text/javascript" src="localhost:9080/polyfills.js"></script>
<script type="text/javascript" src="localhost:9080/styles.js"></script>
<script type="text/javascript" src="localhost:9080/vendor.js"></script>
<script type="text/javascript" src="localhost:9080/main.js"></script>
</body>
</html>


```

But what about the href for favicon?

```html
 <link rel="icon" type="image/x-icon" href="favicon.ico">
```

how can I get that to reference localhost:9080?

in other words, I would like it to have generated:

```html
  <link rel="icon" type="image/x-icon" href="localhost:9080/favicon.ico">
```

### PR DESCRIPTION
**Pull request by daaashley**
--deploy-url on cli prepends icon href path with the indicated url

Closes #13201

### CODE REVIEW

**Comment by mgechev** [comment]
@daaashley looks like the linting is failing. Also, please add a test which verifies the behavior.

**Comment by daaashley** [comment]
> @daaashley looks like the linting is failing. Also, please add a test which verifies the behavior.

@mgechev  Would this be part of the build-angular tests or the main e2e? Sorry, first time working in this repo.

**Comment by alan-agius4** [comment]
I am going to mark this as needs further discussion to see if we'd like to have this landed. Since we'd like to avoid adding addition features which are related to `deployUrl` since using `baseHref` is preferred.

Eventually, if the team decides to that this should go in, tests should be added in https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/test/browser/deploy-url_spec_large.ts

**Comment by alan-agius4** [comment]
@daaashley, it also looks like you haven't yet signed the CLA agreement.

**Comment by daaashley** [comment]
I signed CLA, should update.

**Comment by daaashley** [comment]
Added possible test and I think it passed, let me know if that looks like what you were looking for. I wasn't able to figure out what types headElement and treeAdapter needed to be in my function in index-html-webpack-plugin.ts so lint still fails with type "any"--any advice?  Also, not sure why CLA isn't updating, I did sign it.

**Comment by clydin** [comment]
Thank you for taking the time to put together this contribution and help close an issue.  However, as explained in the referenced issue, this is not a capability that the CLI is considering for inclusion at this time.

**Pull request closed without merging**
