### PR TITLE
fix(@angular/cli): prevent unicode character compression

### LINKED ISSUE #3544: ng build --prod does not preserve escaped '\x1B' sequence.
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Windows 7

### Versions.
angular-cli: 1.0.0-beta.21
node: 6.9.2
os: win32 x64

### Repro steps.
- ng new test11
- cd test11
- edit src/app/app.component.ts with
title = 'app works!' + '\x1B';
- ng build
image
**'\x1B' sequence is preserved.**
- ng build --prod
image
**becomes raw 0x1B character.**

Above steps are just to demo the issue I am facing now. But, my real problem is with angular's 
[browser_adapter.ts line 30](https://github.com/angular/angular/blob/7295a5e7f208af0cc3503f33403979f7898c8ba2/modules/%40angular/platform-browser/src/browser/browser_adapter.ts)

the Escape sequence on line 30 becomes invalid character (raw 0x1B) while building for prod by the cli command. 

Is there any way in CLI to fix this erroneous behavior of bundling?

### LINKED ISSUE #6155: ng build --aot --prod generates ESC character in vendor
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 6.10.2
os: win32 x64
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/core: 4.1.0
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.1.0

### Repro steps.
Create a new project with the cli
run `ng build --aot --prod`
check the vendor file. 
Easiest way is to open the file in notepad++. Press ALT + 027 to insert the ESC char. Ctrl + C to copy and Ctrl + F to find it. 

### The log given by the failure.
No angular crashlog. Crashlog from IBM WebSphere.
Illegal character [0x001b] found at offset [some hex value] in file [vendor.**.bundle.js]

### Desired functionality.
Don't generate the ESC char but ESC as string. 

### Mention any other details that might be useful.
Also happend with cli 1.0.1
I added my generated vendor. Check line 529 col 10548.
https://www.dropbox.com/s/d80zz1fpxy8xho4/vendor.8b1206c372ceef779894.bundle.js?dl=0

### LINKED ISSUE #7243: UglifyJs changes ascii characters to unicode for trim polyfill
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.2.0
node: 6.9.0
os: win32 x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6

### Repro steps.
Uncomment import 'core-js/es6/string'; polyfill.
Run ng build --prod
Search in polyfills for "\u2028"

### The log given by the failure.
"?A?".trim() returns "A"

### Desired functionality.
trim polyfill should escape:

module.exports = '\x09\x0A\x0B\x0C\x0D\x20\xA0\u1680\u180E\u2000\u2001\u2002\u2003' +
  '\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u202F\u205F\u3000\u2028\u2029\uFEFF';

But this is replaced by:

exports="\t\n\v\f\r   ᠎             　\u2028\u2029\ufeff"

In some env, some unicode characters are replaced by ?, so now trim will remove ? from string.

### Mention any other details that might be useful.
This can be avoid setting this for Uglify plugin:
output: {
    ascii_only: true
},

Could you have a look at this bug?

I can't modify the environement use to run production build, and I don't know it. But adding ascii_only would fix that.

Thanks!

Pierre

### PR DESCRIPTION
**Pull request by robindijkhof**
Fixes #3544
Fixes #6155 
Fixes #7243

### CODE REVIEW

**Comment by clydin** [comment]
All unicode characters will be escaped with this change and could potentially cause a significant size increase for unicode heavy applications.
An option would probably be more appropriate; especially considering this is appears to be needed only for specific backend server frameworks (at least from reading through the referenced issue).

**Comment by filipesilva** [comment]
Thanks for taking the time to put up this PR. I used it to asses the situation in #6155 and have responded there. Please see https://github.com/angular/angular-cli/pull/6951 for my reasoning to not accept this fix.

**Comment by filipesilva** [comment]
I also updated your PR description to reflect all the issues this addresses.

**Comment by robindijkhof** [comment]
@filipesilva I think I did so.

**Comment by filipesilva** [comment]
Thanks for the quick response @robindijkhof 👍

**Pull request merged**
