### PR TITLE
fix(Versions): fix builds from master branch

### PR DESCRIPTION
**Pull request by BernhardRode**
Current master branch cannot create new projects.

It fails with: npm ERR! notarget No compatible version found: angular-cli@1.0.0-beta.19

This PR adds the current version to the files and reenables creating new projects.

### CODE REVIEW

**Comment by BernhardRode** [comment]
I have already signed the CLA in 2013 ....
Google Individual CLA	Bernhard Rode	Nov 08, 2013 00:24 PST

**Comment by hansl** [comment]
I can let that in if you sign the CLA. Otherwise it's part of my PR that fixes a bunch of tests, so no worried.

**Comment by BernhardRode** [comment]
So let's close it. 
I signed the CLI, but @googlebot does not seem to get my secondary e-mail adresses (which are entered on github and google)

**Comment by BernhardRode** [comment]
No he found it ^^

**Pull request closed without merging**
