### PR TITLE
fix(@angular/cli): update regex to validate the project-name

### LINKED ISSUE #25704: Mismatch in schema name validation
### Command

new

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

There is a possibility to create an application with the `ng new` command with the name which makes it impossible to configure it through the `ng config` command.

### Minimal Reproduction

1. generate new application with `ng new my.application`
2. run any `ng config` command in generated application (e.g. `ng config schematics.@schematics/angular:component.style scss`)
3. Observe command output

ER: Command executed correctly
AR: Error:
`Error: Schema validation failed with the following errors:
  Data path "/projects" must NOT have additional properties(my.application).`

### Exception or Error

```text
Error: Schema validation failed with the following errors:
  Data path "/projects" must NOT have additional properties(my.application)
```

### Your Environment

```text
Angular CLI: 16.2.0
Node: 18.16.0
Package Manager: npm 9.5.1
OS: win32 x64

Angular: undefined
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1602.0
@angular-devkit/core         16.2.0
@angular-devkit/schematics   16.2.0
@angular/cli                 16.2.0
@schematics/angular          16.2.0
```

### Anything else relevant?

Application name is validated by: https://github.com/angular/angular-cli/blob/main/packages/schematics/angular/application/schema.json#L16
Project name is validated by: https://github.com/angular/angular-cli/blob/main/packages/angular/cli/lib/config/workspace-schema.json#L26C9-L26C47

### PR DESCRIPTION
**Pull request by harshlakhara**
fix(@angular/cli): update regex to validate the project-name

Ensure that the regex used for validating the project-name is updated to address any issues and enhance accuracy.

the existing regex for project-name validation was not validating the name with the dot(.) in application name.

Fixes #25704 

## PR Checklist

Please check to confirm your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular-cli/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #25704  

## What is the new behavior?

Project name can include the dot(.) in the name while creating the project but while validating the dot(.) was missing. I updated the pattern to accept dot(.) in projectName.

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

### CODE REVIEW

**Review by alan-agius4 — CHANGES_REQUESTED** [review]
Can you please update the commit message as per guideline https://github.com/angular/angular-cli/blob/main/CONTRIBUTING.md#-commit-message-guidelines? 

Thanks

**Comment by harshlakhara** [comment]
Sure I will update it.

**Comment by harshlakhara** [comment]
@alan-agius4 I have updated the commit message. Can you please review it?

**Comment by harshlakhara** [comment]
> Looks like you updated the PR description and not the commit message. Also, the scope should be `@angular/cli` and not `@angular-cli`.

I have updated the commit fixing the typo.

**Comment by alan-agius4** [comment]
The commit message has not been updated.
Screenshot 2024-01-22 at 17 43 35

**Comment by harshlakhara** [comment]
@alan-agius4 I have updated the commit as well please check.

**Comment by alan-agius4** [comment]
Can you please squash into a single commit? Otherwise it should be good.

**Comment by harshlakhara** [comment]
I think it is done now.

**Comment by harshlakhara** [comment]
Can it be merged now?

**Comment by harshlakhara** [comment]
@alan-agius4 i closing this PR and have raised a new PR #26924. Please check and review it.

**Pull request closed without merging**
